- lib/graphql/relay/relation_connection.rb
This is a followup from:
https://github.com/rmosolgo/graphql-ruby/pull/2513
Resolve:
https://github.com/rmosolgo/graphql-ruby/issues/2332
In this PR:
I use ```exists?``` if the nodes are a ```ActiveRecord::Relation```. Keep the original logic for ```Sequel::Dataset```.
> Use exists? optimize RelationConnection.has_next_page for ActiveRecord relations

- lib/graphql/schema/member/has_fields.rb
Fixes #2199 
I've bumped into [this](https://stackoverflow.com/questions/27771439/programmatic-way-to-obtain-ruby-keywords) hacky way to get the list of Ruby keywords. On the one hand – it should properly handle different ruby versions, on the other – it's a private API and might stop working in future. Please let me know if you prefer a hard-coded list of keywords or if I should change the wording in the warning.
> Warn user when field name is a ruby keyword

- lib/graphql/schema/field.rb
- spec/graphql/schema/field_spec.rb
This way, you can customize how connections are set up in your schema, for example, if you want a custom behavior as shown in #2534  
Fixes #2534 
Fixes #2283
> Support custom .connection_extension

- guides/fields/resolvers.md
- lib/graphql/schema/resolver.rb
- spec/graphql/schema/resolver_spec.rb
I think it might be useful to have the ability to define field extensions inside resolvers for cases when some logic is shared between resolvers and types:
```ruby
class GreetingExtension < GraphQL::Schema::FieldExtension
def resolve(object:, arguments:, **rest)
name = yield(object, arguments)
"#{options[:greeting]}, #{name}!"
end
end
class ResolverWithExtension < BaseResolver
type String, null: false
extension GreetingExtension, greeting: "Hi"
def resolve
"Robert"
end
end
```
Please let me know if it sounds worthless 🙂
> Allow resolvers to define field extensions

- lib/graphql/language/lexer.rb
- lib/graphql/language/lexer.rl
- lib/graphql/language/nodes.rb
- lib/graphql/language/parser.rb
- lib/graphql/language/parser.y
- lib/graphql/language/token.rb
I saw that @DmitryTsepelev  gave a really good talk about graphql-ruby's internals, and it included some detailed benchmarks. I decided to see if I could improve them 😈 
They're here: https://gist.github.com/DmitryTsepelev/36e290cf64b4ec0b18294d0a57fb26ff
Specifically, I looked at the parsing benchmark. I was able to reduce the memory by about half, but the time is about the same. 
```
~/code/graphql-ruby $ ruby benchmark.rb
user     system      total        real
8 fields, 0 nested levels (   122 bytes):   0.000366   0.000017   0.000383 (  0.000382)
8 fields, 2 nested levels ( 10706 bytes):   0.022603   0.000751   0.023354 (  0.024115)
8 fields, 4 nested levels (853970 bytes):   0.948247   0.013408   0.961655 (  0.974112)
Total allocated: 77147304 bytes (664744 objects)
Total retained:  0 …
```
> Tune parser for query with lots of nested fields

- lib/graphql/schema/argument.rb
- spec/graphql/authorization_spec.rb
Reverts rmosolgo/graphql-ruby#2519
It caused cyclical loops. 1.10-dev has a better behavior here.
Fixes #2554
> Revert "Authorize arguments of input objects, too"

- lib/generators/graphql/templates/base_field.erb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
I don't know why this code was ever in there, but it's breaking things. See https://github.com/rmosolgo/graphql-ruby/issues/2575 and https://github.com/rmosolgo/graphql-ruby/issues/2569
> Fix the base field generator

- guides/mutations/mutation_classes.md
- guides/schema/generators.md
- lib/generators/graphql/core.rb
- lib/generators/graphql/install_generator.rb
- lib/generators/graphql/templates/base_mutation.erb
- lib/generators/graphql/templates/mutation.erb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
- spec/integration/rails/generators/graphql/mutation_generator_spec.rb
I noticed that a few places in the guides reference a `BaseMutation`, including the [Mutation Classes guide](https://graphql-ruby.org/mutations/mutation_classes.html#example-mutation-class). I though it would be a good idea to have the generator create that BaseMutation, referencing the type classes that are generated.
Let me know what you think! Happy to tweak things if this is an appropriate addition to the project.
> Generate a base mutation class referencing the base type classes

- guides/development.md
:wave: Noticed this while running through the setup. Mongo has its own tap now -- see https://github.com/Homebrew/homebrew-core/pull/43770.
> fix(website) new mongo install instructions

- guides/type_definitions/lists.md
There was a small issue with the valid/invalid table for "Non-null lists with nullable items". 
An example that should have been _invalid_ was showing up as _valid_.
> [Docs] Fixing small mistake in table for "List" docs

- lib/graphql/language/block_string.rb
- spec/graphql/language/block_string_spec.rb
This fixes a bug when a block string contains only newlines.
> Block Strings: Fix bug calling empty? on nil

- lib/graphql/tracing/skylight_tracing.rb
This is a follow-up to #2583.
Ensures that we warn whenever the `GraphQL::Tracing::SkylightTracing` class is initialized*, and suggest enabling Skylight's GraphQL probe instead.
*I guessed that warning in the `initialize` made the most sense, but definitely let me know if this warning should live somewhere else! :)
> Deprecate GraphQL::Tracing::SkylightTracing

- lib/graphql/pagination/array_connection.rb
- lib/graphql/pagination/connection.rb
- lib/graphql/pagination/connections.rb
- lib/graphql/pagination/relation_connection.rb
- lib/graphql/schema/field/connection_extension.rb
- spec/support/connection_assertions.rb
Improve capping by max_page_size, now subclasses can "just" use `first` and `last`. Max_page_size will be applied as `first` if no `first` or `last` is given. 
The advantage there is we get `has_next_page`/`has_previous_page` correctly implemented for free, and it's harder to forget to use max_page_size. Fixes #1109
> Fixes for new pagination 

- guides/mutations/mutation_errors.md
ActiveRecord errors keys are symbols, so they would need to be converted to string first. The [`camelize`](https://api.rubyonrails.org/classes/String.html#method-i-camelize) method will also default to `PascalCase` unless the `:lower` argument is passed.
I though that it would help people implementing that pattern of errors.
> Update conversion from ActiveRecord error

- lib/generators/graphql/mutation_generator.rb
- spec/integration/rails/generators/graphql/mutation_generator_spec.rb
Currently the mutation generator are generating camel case field names.
I think since this https://github.com/rmosolgo/graphql-ruby/pull/1126
and the class based API were introduced, the standard seems to have changed to ruby underscore
syntax names. See https://github.com/rmosolgo/graphql-ruby/pull/1126/files#diff-161608206c9ba9bc29a59e613e2bdbfdR307  
Before
```
field :updateName, mutation: Mutations::UpdateName
```
After
```
field :update_name, mutation: Mutations::UpdateName
```
Let me know if this is the expected behaviour
cc @rmosolgo
> updates mutation_generator to use underscored field names

- guides/queries/multiplex.md
I'm pretty sure this is the right way to configure the JSON rendering to not include a
root node (which breaks the multiplex spec and confuses clients).
@rmosolgo I'm doing this a tad blind since I don't know the impetus behind the original multiple recommendations, but this works for us and AFAIK the pure `render json: result` should never work, so...
cc @rrangith
> Recommend the right thing up front for multiplex

- guides/queries/ast_analysis.md
- lib/graphql/analysis/ast.rb
- lib/graphql/analysis/ast/analyzer.rb
- lib/graphql/analysis/ast/max_query_complexity.rb
- lib/graphql/analysis/ast/max_query_depth.rb
- lib/graphql/analysis/ast/query_complexity.rb
- spec/graphql/analysis/ast/max_query_depth_spec.rb
- spec/graphql/analysis/ast/query_complexity_spec.rb
Fixes #2388 
Alternative to #2394 
We were already using "query" analyzers to analyze multiplexes, but in some cases it didn't actually work. 
I want to update it to, yknow, _actually_ work, and also: 
- Update the analyzer API to clarify what kind of thing it's analyzing (while maintaining a use-agnostic access to `subject`) 
- Reflect this dual usage in the docs 
Thanks especially to @patvice who wrote up this issue in detail, provided the appropriate tests, and explored an alternative solution.
> Fix multiplex max depth

- lib/graphql/schema/timeout_middleware.rb
The call to `Time.now` can be affected by changes to system time such as
NTP updating the OS' time. This can be avoided by using a monotonically
increasing time source.
For more information see:
https://blog.dnsimple.com/2018/03/elapsed-time-with-ruby-the-right-way/
> TimeoutMiddleware: switch to monotonic time

- guides/queries/multiplex.md
- spec/graphql/execution/multiplex_spec.rb
@rmosolgo 
We were worried that since `Multiplex` processes requests concurrently, that it wouldn't be able to maintain order in our responses. 
This PR is to confirm to users that results will always be kept in the same order that their respective requests were sent in. 
This way users can do something like the following without worrying about whether or not the order of the responses was maintained:
```
payload = [
ComponentA.required_graphql_query,
ComponentB.required_graphql_query
]
responses = GraphQLClient.batch_request(payload: payload)
ComponentA.handle_response(responses[0])
ComponentB.handle_response(response[1])
```
I could optionally remove the test case I made, but the doc change should be made so people don't get confused in the future
> Add clarification to Multiplex about ordering of responses

- lib/graphql/execution/errors.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/query.rb
- lib/graphql/query/variables.rb
- lib/graphql/schema.rb
- lib/graphql/schema/object.rb
- spec/graphql/execution/errors_spec.rb
Implementing as a tracer was ok, but there's some error-raising stuff that can happen _outside_ of those events, for example: 
- Loading objects from ID in query variables 
- `.authorized?` hooks (and initializing object instances)
There might be others; this will put us in a good place to "just" slap error handling on when needed.
Fixes #2629 
Fixes #2627
> rework Execution::Errors to manually wrap significant bits of code

- lib/graphql/introspection/entry_points.rb
- lib/graphql/introspection/schema_type.rb
- lib/graphql/schema/warden.rb
- spec/graphql/introspection/entry_points_spec.rb
- spec/graphql/introspection/schema_type_spec.rb
- spec/graphql/schema/warden_spec.rb
This PR takes a crack at fixing the heart of issue #1333 by hiding any types in introspection queries that become unreachable due to visibility checks. The algorithm does a depth first traversal of the schema's "graph" starting at the roots and only recursing into nodes that pass visibility checks. It punts on pushing this logic into Warden since that's a much trickier problem to solve and doesn't appear to provide much value.
I ran the introspection query benchmark and it doesn't seem to add any noticeable performance impact although this could be different for large schemas:
Branch:
```
query     2.000  i/100ms
query     23.533  (± 4.2%) i/s -    118.000  in   5.020621s
```
Master:
``` …
```
> Introspection shouldn't return types that are unreachable due to visibility checks

- lib/graphql/schema/member/has_fields.rb
Some time ago I've [added](https://github.com/rmosolgo/graphql-ruby/pull/2559) a check to make sure user not defines a field with a name that matches one of Ruby keywords. In order to do that I've used a `RubyToken` module, which was [removed](https://github.com/ruby/ruby/commit/45bb6f28db04a1f267f5b8d79392cb35087510d8) from Ruby a couple of weeks ago, so that hack doesn't work with ruby 2.7.0-preview3 (thanks @ahlucas for pointing that out!).
After a short research I found out that `irb/ruby-token` was not used for a long time (so removing it was a matter of time). Also, I could not find a new way to list all the Ruby keywords in the runtime (I guess because neither ruby nor [parser](https://github.com/whitequark/parser) need to check _if_ a token is a keyword, they need to know _the …
> Explicitly list RUBY_KEYWORDS in GraphQL::Schema::Member::HasFields

- lib/graphql/schema/base_64_bp.rb
We backport Base64.urlsafe_encode64 method for old Rubies. And the method has been updated in Ruby master branch with a performance patch.
So this pull request applies the patch to graphql-ruby also.
ref
https://github.com/ruby/ruby/commit/1bdabaa6b13344c195698ca5b0ced323cb93e2e1
https://github.com/ruby/ruby/pull/1676
Thanks!
> Backport original Base64.urlsafe_encode64 performance improvement

- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/query/context.rb
- spec/graphql/query/context_spec.rb
Resolves https://github.com/rmosolgo/graphql-ruby/issues/2602.
This PR adds a "scoped context" to the existing context. This is useful for propagating values which are specific to a field and its children, as opposed to for the entirety of the query.
This is achieved with very little overhead on the interpreter runtime by simply reinitializing the scoped context at various points where new resolvers would run within a possibly new context as the query is being executed.
> Adds scoped context for propagating values specific to a field and its children

- lib/graphql/language/document_from_schema_definition.rb
This change ensures that visibility checks during SDL generation receive an instance of the context class set on the schema.  Related change: https://github.com/rmosolgo/graphql-ruby/pull/2637
> fix: Use schema context class for SDL generation

- lib/graphql/argument.rb
- lib/graphql/define/assign_object_field.rb
- lib/graphql/execution/execute.rb
- lib/graphql/execution/multiplex.rb
- lib/graphql/language/nodes.rb
- lib/graphql/relay/node.rb
- lib/graphql/schema/mutation.rb
- lib/graphql/schema/relay_classic_mutation.rb
- lib/graphql/schema/resolver.rb
- lib/graphql/schema/type_membership.rb
- lib/graphql/schema/union.rb
- lib/graphql/subscriptions.rb
- lib/graphql/union_type.rb
- spec/graphql/query/context_spec.rb
- spec/graphql/schema/resolver_spec.rb
Fixes part of #2650. This fixes all the deprecations that I had when running graphql-ruby with my Rails app, and removes almost 1000 deprecation warnings from my test suite. Looking at the travis logs for ruby-head there are some deprecation warnings my changes don't seem to fix. A lot of the deprecations from ruby-head in travis are external libraries that can be fixed by just updating them, e.g. rake, rails, and rubocop.
> Fix some Ruby 2.7 deprecation warnings.

- guides/schema/introspection.md
- lib/graphql/schema.rb
- lib/graphql/schema/introspection_system.rb
- spec/graphql/schema/introspection_system_spec.rb
- spec/support/jazz.rb
A question was asked in issue GH-2546 asking whether it was possible to
disable a single introspection entry point considering that #2327 had
implemented then functionality to disable introspection as a whole using
`disable_introspection_entry_points`. In the issue, an option was laid
out to implement the functionality for individual
`disable_schema_introspection_entry_point` and
`disable_type_introspection_entry_point` options. This commit implements
these methods.
These new methods are used in an identical manner to
`disable_introspection_entry_points`:
```ruby
disable_type_introspection_entry_point
end
```
With the above, attempting to execute a query with `__type`
introspection will return the following error message:
```
Field '__type' doesn't exist …
```
> Implement `__type`/`__schema` introspection disabling

- lib/graphql/schema/directive.rb
- spec/graphql/schema/directive_spec.rb
Oops, it was downcasing the whole name. This broke when I tried to migrate to `Schema::Directive`, so now I'm upstreaming the fix.
> Fix directive graphql_name

- lib/generators/graphql/templates/schema.erb
- lib/graphql/directive.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/schema.rb
- lib/graphql/schema/enum_value.rb
- lib/graphql/schema/object.rb
- lib/graphql/tracing.rb
- lib/graphql/tracing/active_support_notifications_tracing.rb
- lib/graphql/tracing/appsignal_tracing.rb
- lib/graphql/tracing/data_dog_tracing.rb
- lib/graphql/tracing/new_relic_tracing.rb
- lib/graphql/tracing/platform_tracing.rb
- lib/graphql/tracing/prometheus_tracing.rb
- lib/graphql/tracing/scout_tracing.rb
- lib/graphql/tracing/skylight_tracing.rb
- spec/graphql/execution/execute_spec.rb
- spec/graphql/execution_error_spec.rb
- spec/graphql/tracing/platform_tracing_spec.rb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
- spec/integration/rails/graphql/tracing/active_support_notifications_tracing_spec.rb
- spec/support/dummy/schema.rb
We noticed some unaccounted-for time in our internal perf tools, and I think it's because these aren't covered. 
Before the interpreter, `authorized_new` was included with the field that returned the value. But the interpreter ran it without any tracing. 
Also, wrapping `resolve_type` is brand new.
> Add tracing events for authorized and resolve_type calls

- lib/graphql/execution/lookahead.rb
- lib/graphql/schema/directive.rb
- lib/graphql/schema/directive/include.rb
- lib/graphql/schema/directive/skip.rb
- spec/graphql/execution/lookahead_spec.rb
GraphQL::Execution::Lookahead is primarily for determining what fields will need to be loaded for the query, so that they can be used to optimize database access.  However, it doesn't take into consideration whether or not fields are excluded by `@skip` or `@include` directives.
I wasn't able to use `GraphQL::Schema::Directive.include?` directly, because it is given the parent object, which we won't know when looking ahead more than one level deep.  As a result, I added a `GraphQL::Schema::Directive.static_include?` method that directive classes can override so that `GraphQL::Execution::Lookahead` will use it to determine if the field will be included.
While looking at the code in lib/graphql/execution/lookahead.rb, I noticed that there was a reference to directives in a comment that …
> Consider fields not selected in lookahead if skipped by a directive

- lib/graphql/schema/field.rb
In commit https://github.com/rmosolgo/graphql-ruby/commit/2eb84f0c8bdf41912517f96fb71e89a63f0c04b2#diff-19915f765769f8f600fa85498d1ea515 was changed @extensions default value to [], one condition was not changed.
> Fix field extensions after change default value to [] from nil

- lib/graphql.rb
- lib/graphql/define/defined_object_proxy.rb
- lib/graphql/define/instance_definable.rb
- spec/graphql/input_object_type_spec.rb
- spec/graphql/schema/input_object_spec.rb
- spec/support/jazz.rb
Oops, passing `.call(arg, :default_value, [{}])` was causing the empty hash to be dropped. I think the built-in compat method will help here, and GraphQL-Ruby 2.0 will eventually drop this code anyways.
I will backport to 1.9.x
Fixes #2691
> Fix argument default_value: {} on Ruby 2.7

- lib/graphql/schema.rb
- spec/graphql/interface_type_spec.rb
- spec/support/dummy/schema.rb
Fixes #2694 
(cc @liang3404814 -- I saw this commit on your repo and I'm getting ready to cut 1.10.1, so I grabbed it!)
> Use Interface.orphan_types in schema construction

- .travis.yml
- lib/graphql.rb
- lib/graphql/define/defined_object_proxy.rb
- lib/graphql/define/instance_definable.rb
- spec/graphql/input_object_type_spec.rb
- spec/graphql/schema/input_object_spec.rb
- spec/support/jazz.rb
Also fixes #2691 , same as #2703
> [1.9.x] Fix argument default_value: {} on Ruby 2.7

- lib/graphql/analysis/ast/query_complexity.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/schema/input_object.rb
- spec/graphql/analysis/ast/query_complexity_spec.rb
- spec/graphql/execution/errors_spec.rb
- spec/graphql/schema/input_object_spec.rb
- spec/integration/rails/graphql/query/variables_spec.rb
Oops, the interpreter was leaving these as Hashes instead of wrapping them in input object instances.
> Properly wrap nested objects coming in variables

- lib/generators/graphql/core.rb
Hi,
Module#parent_name is deprecated in Rails 6.0 and will be removed in Rails 6.1.
Ref: https://github.com/rails/rails/pull/34051
To suppress a deprecation warning, use Module#module_parent_name instead.
> Use Module#module_parent_name instead of Module#parent_name

- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/query/null_context.rb
- lib/graphql/query/variables.rb
- lib/graphql/schema/input_object.rb
- lib/graphql/schema/member/has_arguments.rb
- spec/graphql/execution/errors_spec.rb
- spec/graphql/schema/input_object_spec.rb
I've added all the coercion behavior to type classes, but `runtime.rb` was still doing a lot of it itself. I've refactored it to use the type classes, instead.
> Unify input coercion

- lib/graphql/schema/build_from_definition.rb
- spec/graphql/schema/build_from_definition_spec.rb
If an SDL document contained a built-in type definition `build_from_definition` would raise an error due to type conflicts.
This defers merging in the `BUILT_IN_TYPES` and reverse merges them to keep any previously defined ones in the provided document.
> Fix build_from_definition for built-in types

- lib/generators/graphql/templates/schema.erb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
Oops, the default schema used interpreter, but not the also-required Analysis::AST plugin. 
Fix #2718
> Include new analysis in default schema

- lib/graphql/schema/warden.rb
- spec/graphql/language/document_from_schema_definition_spec.rb
Types referenced from directive arguments were previously excluded by the warden because they weren't in `reachable_types`. Fixes #2677
> Include directive argument types as reachable

- lib/graphql/schema/input_object.rb
- spec/graphql/query/executor_spec.rb
InputObject's have input fields according to the spec and not arguments.
This updates the error message to use the term `Field` instead of `Argument`. This also makes the error message consistent with the legacy ones.
> Update InputObject undefined field error message

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/execution/errors_spec.rb
This PR illustrates an issue we encountered with `GraphQL::Execution::Interpreter` where it did not return the error when it saw a non-nullable array field returning nulls. The expected behavior is shown with a simple schema that does not use `GraphQL::Execution::Interpreter`.
I'd be happy to work on a fix if I knew where to look.
> New interpreter not reporting certain type of errors

- lib/graphql/schema/field.rb
- lib/graphql/schema/input_object.rb
- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/schema/resolver.rb
- spec/graphql/execution/errors_spec.rb
- spec/graphql/schema/argument_spec.rb
Hi! Thank you for the great gem.
`loads:` with plain field arguments does not work now.
ref #2544
I think it is more convenient to add this.
I may have made the wrong fix or have some missing tests. If so please point.
best regards.
> loads: with plain field arguments

- lib/graphql/execution/interpreter.rb
- lib/graphql/execution/interpreter/handles_raw_value.rb
- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/execution/interpreter_spec.rb
This PR allows to return _raw values_ from resolvers. When Interpreter gets such a value, it should write it directly to the response, instead of visiting all the child nodes. This is how it could look like:
```ruby
field :expansion_raw, Expansion, null: false
def expansion_raw
raw_value(sym: "RAW", name: "Raw expansion")
end
end
```
This change is a first step of implementing partial response caching (current solutions are very limited and skip various built-in checks). Here is an example [gist](https://gist.github.com/palkan/faad9f6ff1db16fcdb1c071ec50e4190) by @palkan, which contains the same change (using metaprogramming) as well as caching implementation.
What do you think? Do you have suggestions on the API design?
> Allow return raw values from resolvers

- .travis.yml
- lib/graphql/define/defined_object_proxy.rb
- lib/graphql/define/instance_definable.rb
- lib/graphql/subscriptions.rb
- spec/graphql/subscriptions_spec.rb
It's possible for reads and writes to happen _between_ `each_subscription_id` and `read_subscription`, this allows `read_subscription` to signal to the caller that there's no such subscription anymore. The caller handles it by calling `delete_subscription`, which is an opportunity to clean up any dangling state. (There may not _be_ any state, since it wasn't found by `read_subscription` -- depends on the backend.)
Fixes #2061
> Unsubscribe when read_subscription returns nil

- lib/graphql/subscriptions.rb
- lib/graphql/subscriptions/subscription_root.rb
- spec/graphql/subscriptions_spec.rb
I'm not sure if I can actually _fix_ this or not, but I want to keep an eye on this behavior 
Closes #2721 
TODO: 
- Yes -- when I changed the default value, it :boom:ed because the prepared value wasn't a member of the Enum.
> Subscriptions, prepare: and interpreter 

- lib/graphql/pagination/connections.rb
- lib/graphql/schema.rb
- lib/graphql/schema/field/connection_extension.rb
- spec/graphql/pagination/connections_spec.rb
- spec/support/connection_assertions.rb
Fixes #2743 -- `schema.connections` was not inheritance-aware.
> Fix connection wrapper inheritance

- lib/graphql/language/nodes.rb
- spec/graphql/language/visitor_spec.rb
Using `GraphQL::Language::Visitor` to replace a variable definition currently results in the following exception:
```
NoMethodError: undefined method `variable_definitions' for #<GraphQL::Language::Nodes::OperationDefinition:0x00007fa76b0c0c78>
/Users/jturkel/salsify/jturkel-graphql-ruby/lib/graphql/language/nodes.rb:96:in `public_send'
/Users/jturkel/salsify/jturkel-graphql-ruby/lib/graphql/language/nodes.rb:96:in `replace_child'
/Users/jturkel/salsify/jturkel-graphql-ruby/lib/graphql/language/visitor.rb:180:in `on_node_with_modifications'
/Users/jturkel/salsify/jturkel-graphql-ruby/lib/graphql/language/visitor.rb:102:in `block in on_abstract_node'
/Users/jturkel/salsify/jturkel-graphql-ruby/lib/graphql/language/visitor.rb:101:in `each' …
```
> Fix visitor replacement of variable definitions

- lib/graphql/schema.rb
- lib/graphql/schema/build_from_definition.rb
- lib/graphql/schema/field.rb
- spec/graphql/schema/build_from_definition_spec.rb
There are a handful of issues about whether or not this library will provide Relay-like behaviors to schemas built from IDL. 
I think the best answer is no -- it will be complicated to implement, and in `.from_definition`, you're already providing the implementation, so better to put the schema's behavior there. 
Fixes #2731 
Fixes #1043
Fixes #1077
If you were previously _depending_ on the halfway support, I recommend taking inspiration from the ConnectionExtension, and adding the relevant wrapping code to your resolver implementation. 
Here's the generalized code for applying wrappers: 
https://github.com/rmosolgo/graphql-ruby/blob/4cae8b41479cc4348a8627c65f1399269b441aa0/lib/graphql/schema/field/connection_extension.rb#L40-L56
But, if you're writing resolvers by hand, you can probably …
> Don't add half-way connection handling to schemas from definition

- lib/graphql/execution/interpreter.rb
- lib/graphql/execution/interpreter/arguments_cache.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/query.rb
- spec/graphql/query_spec.rb
Fixes #2778 
Also, this moves the interpreter's runtime code to use `query.arguments_for`, which makes me pretty confident of the test coverage 🍻
> Fix query.arguments_for with Interpreter and variables

- lib/graphql/language.rb
- lib/graphql/language/printer.rb
- lib/graphql/language/sanitized_printer.rb
- lib/graphql/query.rb
- spec/graphql/language/sanitized_printer_spec.rb
The goal here is to add something that's safe for logging. All strings, except for IDs, are replaced with `"<REDACTED>"`. 
Variables are inlined and redacted the same way.
- Fixes #2334 
- Fixes #1106  
- Fixes #2333
> Add Query#sanitized_query_string

- lib/graphql/schema/argument.rb
- spec/graphql/schema/input_object_spec.rb
- spec/support/dummy/schema.rb
- spec/support/star_wars/schema.rb
Currently, GraphQL-Ruby _doesn't_ use the provided symbol to build keyword arguments, which is confusing. 
So instead, if `argument(...)` is configured with a symbol, use the given symbol for the method's keyword arguments. 
This can break existing configurations if they configured arguments with camelized symbols, but expected underscored arguments in their methods (see the change in the test suite, for example).
Fixes #2611 
Fixes #2665 (this approach maintains current behavior)
Fixes #2706
Fixes #1839
> Use Argument names as configured (fix args with numbers)

- lib/graphql/schema.rb
- spec/graphql/pagination/active_record_relation_connection_spec.rb
- spec/support/connection_assertions.rb
Oops, if a class was configured with the new connection system, it wasn't properly passed to that class's instance, which was used by the old runtime. Pass it along as needed.
Fixes #2793
> Support new connection system on old runtime

- lib/graphql/pagination/active_record_relation_connection.rb
- lib/graphql/pagination/array_connection.rb
- lib/graphql/pagination/relation_connection.rb
- spec/integration/rails/graphql/relay/array_connection_spec.rb
- spec/integration/rails/graphql/relay/connection_resolve_spec.rb
- spec/integration/rails/graphql/relay/connection_type_spec.rb
- spec/integration/rails/graphql/relay/page_info_spec.rb
- spec/integration/rails/graphql/relay/relation_connection_spec.rb
- spec/support/star_wars/schema.rb
#2805 Mentioned a previously-fixed bug that showed up in the new connection system. This adds a build that runs _new_ connections with the _old_ tests. There are some differences, which are now explicitly called out in the suite. 
Along the way, I fixed #2349 _again_. But this didn't fix the bug reported in #2805.
> Test new connections system with existing tests for previous system

- lib/graphql/analysis/ast/query_complexity.rb
- spec/graphql/analysis/ast/query_complexity_spec.rb
The AST `QueryComplexity` analyzer is designed to return a single `max_possible_complexity` value in its `result` right now. Unfortunately there's currently no way to capture individual field level complexity details.
This adds a `field_complexity` method which acts as a hook. It gets called once for every field with its calculated complexity values. The default hook implementation is a no-op and can be overridden for custom behaviour.
Example:
```ruby
class CustomComplexityAnalyzer < GraphQL::Analysis::AST::QueryComplexity
private
def field_complexity(scoped_type_complexity, max_complexity:, child_complexity:)
Rails.logger.info("Field complexity: #{scoped_type_complexity.response_path} => #{max_complexity}")
end
end
```
> Add field complexity hooks in QueryComplexity

- lib/graphql/schema/build_from_definition.rb
- spec/graphql/language/document_from_schema_definition_spec.rb
- spec/graphql/schema/build_from_definition_spec.rb
- spec/graphql/schema/warden_spec.rb
Putting _every type_ in orphan types means you can't really use `warden.reachable_types` when a schema is parsed from IDL. 
Instead, let's empty that array _out_ after the schema is loaded. 
The downside is, somehow, something might possibly break, because truly-orphaned types are lost completely. 
However, I don't think those types would have ever been valid in queries, so I don't expect this to break query behavior.
> Prune unreachable types when parsing schema from IDL

- lib/graphql/schema.rb
- spec/graphql/analysis/analyze_query_spec.rb
- spec/graphql/schema_spec.rb
Fix #2717 
I've confirmed this patch solves the problem described in the issue, but I got an error with an existence test.
```bash
Error:
GraphQL::Analysis::.visit_analyzers#test_0001_groups all errors together:
NoMethodError: undefined method `new' for #<IdCatcher:0x0000563352e005c0>
/home/pocke/ghq/github.com/rmosolgo/graphql-ruby/lib/graphql/analysis/ast.rb:58:in `block (2 levels) in analyze_query'
/home/pocke/ghq/github.com/rmosolgo/graphql-ruby/lib/graphql/analysis/ast.rb:58:in `map'
/home/pocke/ghq/github.com/rmosolgo/graphql-ruby/lib/graphql/analysis/ast.rb:58:in `block in analyze_query'
/home/pocke/ghq/github.com/rmosolgo/graphql-ruby/lib/graphql/tracing.rb:67:in `block in trace'
/home/pocke/ghq/github.com/rmosolgo/graphql-ruby/lib/graphql/tracing.rb:81:in `call_tracers' …
```
> Enable to work AST Analyzer

- lib/graphql/pagination/array_connection.rb
- lib/graphql/pagination/connection.rb
- lib/graphql/pagination/relation_connection.rb
- spec/support/connection_assertions.rb
- Ignore cursors given as `""`
- Use `nonce: true` when generating cursors 
Fixes #2819
> New connections fixes

- lib/graphql/define/instance_definable.rb
Follow up: https://github.com/rmosolgo/graphql-ruby/pull/2704
This is another subtle change in 2.7 handling of keyword arguments.
It wouldn't be a problem if the target method was set as `ruby2_keywords`, but in this case it isn't.
I wish I could produce a test case for this, but my understanding of the library is too limited. 
I figured that one out, because lots of our tests were failing, and all Argument with `default_value = {}` ended up with `default_value = nil`.
> Fix default_value: {} on Ruby 2.7

- lib/graphql/types/big_int.rb
- spec/graphql/types/big_int_spec.rb
`Integer(nil)` raises TypeError which is not handled by the BigInt class.
This will return `nil` for `nil` input.
> Fix TypeError in BigInt for nil input

- lib/generators/graphql/templates/graphql_controller.erb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
Hi, thanks really really a lot for your labor to maintain this awesome gem!
We just encountered a strange situation where the error message in graphql-ruby is delivered in wired manner in development environment.
After digging it a while, I noticed that the development error handler, which was auto-generated by this gem's template, uses slightly different key compared with [the error handling system in graphql-ruby](https://github.com/rmosolgo/graphql-ruby/blob/564b9219435950a764afbff30a4327ee4ee842ab/guides/errors/execution_errors.md).
```ruby
def handle_error_in_development(e)
logger.error e.message
logger.error e.backtrace.join("\n")
render json: { error: { message: e.message, backtrace: e.backtrace }, data: {} }, status: 500
end
```
This PR is a little chore to fix this template. Hope …
> align error json format in development with production's

- guides/pagination/using_connections.md
For the "whole schema" it seems the method is `default_max_page_size` and not `max_page_size` which is what is specified in the documentation
Trying to use `max_page_size` will throw an unknown method error
```
undefined method `max_page_size' for MySchema:Class
```
> Fix `default_max_page_size` in documentation

- javascript_client/src/subscriptions/ActionCableLink.ts
- javascript_client/src/subscriptions/__tests__/ActionCableLinkTest.ts
fixes #2838 
A few notes:
- I refactored the ActionCableLinkTest tests mainly to have the cable mock object more accurately reflect what actioncable returns. I'm also getting reference to the underlying subscription through the Observable subscriptions `_cleanup` object. Setting the reference within the mock (old line 13) doesn't give you the object after ActionCableLink has transformed it.
- I removed `this.unsubscribe()` on line 50 because I discovered that `observer.complete()` also calls unsubscribe, and the call is redundant.
- The actual fix involves using `Object.assign` instead of the spread operator for two reasons:
- The spread operator doesn't carry over prototype methods
- Creating a clone of the object breaks an equality check in actioncable when removing/unsubscribing a …
> Fix actioncable unsubscribe

- lib/graphql/pagination/relation_connection.rb
- spec/integration/rails/graphql/relay/page_info_spec.rb
- spec/integration/rails/graphql/relay/relation_connection_spec.rb
In `relation_connection` when `hasNextPage` and `hasPreviousPage` are being resolved before `nodes` or `edges` they don't return correct values because they're depending on `@before_offset` and `@after_offset` variables. These variables are initialised inside `sliced_nodes` method.
As a result when this method has not been called before resolving these fields, they return wrong values.
This PR tries to fix that issue by moving the `@before_offset` and `@after_offset` in their own private methods to work independently of `slices_nodes` method been called in advance or not.
> Fix has_previous and has_next page values when sliced_nodes has not been called

- guides/schema/generators.md
- lib/generators/graphql/install_generator.rb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
While `Graphiql` is great for testing GraphQL APIs, `GraphQL Playground` contains some features that `Graphiql` is missing such as http headers and is many developers preferred choice for testing their APIs. It can also be added to a rails project with the [`graphql_playground-rails`](https://rubygems.org/gems/graphql_playground-rails) gem. This PR adds an option to the install generator to set up `GraphQL Playground` upon installation in your project, by installing the gem and mounting it at the `/playground` route. Note that this does not prevent `Graphiql` from being installed as well (should it?) which can be done by including the `--skip-graphiql` option and also unlike `Graphiql` works for API only apps as well. Would love to hear thoughts and/or feedback on this addition!
> Add `--playground` option to install generator

- guides/queries/ast_analysis.md
Make it clear how to work with arguments in this API. 
Fixes #2574
Fixes #2573
> Document query.arguments_for in AST analysis

- lib/graphql/execution/interpreter.rb
- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/pagination/array_connection_spec.rb
- spec/graphql/pagination/connections_spec.rb
Improve the error message when the returned value doesn't satisfy GraphQL's expectation. 
Fixes #2588 
new message:
```
Failed to build a GraphQL list result for field `Query.things` at path `things`.
Expected `#<GraphQL::Pagination::ArrayConnection:0x00007fe77f3d2020 @items=[{:name=>"thing1"}, {:name=>"thing2"}], @context=#<Query::Context ...>, @first_value=nil, @after_value=nil, @last_value=nil, @before_value=nil, @has_max_page_size_override=true, @max_page_size=nil>` to implement `.each` to satisfy the GraphQL return type `[ThingConnection!]!`.
This field was treated as a Relay-style connection; add `connection: false` to the `field(...)` to disable this behavior.
```
> Improve error message for failed list result

- lib/graphql/language/nodes.rb
- spec/graphql/language/equality_spec.rb
`eql?` is the hash equality operator. Objects which implement `eql?` must also implement a matching `hash`, otherwise using these objects as hash keys or calling uniq with them will behave unpredictably.
The implementation was also not a good match for `eql`'s hash semantics. It checked that scalars and children were equal, but not filename, line, or col.  Additionally, subclasses like `Field` and `FragmentDefinition` also had additional attributes which were not tested (EDIT: maybe this is wrong).
This commit changes `eql?` to `==` so that we have an easy way to do tree comparison (as needed for comparing children) but we don't mess up hashing semantics.
> Change `eql?` to `==`

- lib/graphql/query.rb
- lib/graphql/query/fingerprint.rb
- spec/graphql/query/fingerprint_spec.rb
We use something like this at GitHub to connect query runs over time. You can use these identifiers to trace query performance over the long run.
__TODO:__
- Make the string a bit more human-friendly:
cc @swalkinshaw I'd love to know, do y'all at shopify have something like this? (Any advice in this area?)
> Add Query#fingerprint for grouping queries in logs

- javascript_client/package.json
- javascript_client/src/subscriptions/__tests__/createAblyHandlerTest.ts
- javascript_client/src/subscriptions/createAblyHandler.ts
Hi Robert, as far as I can tell this is necessary for making the [initial response](https://github.com/rmosolgo/graphql-ruby/blob/master/guides/subscriptions/subscription_classes.md#adding-an-initial-response) work, or am I missing something?
This should probably also be done for ActionCable etc., but I'll leave that up to you.
There is a slight semantic change here in that a message with an empty (or otherwise malformed) payload would previously have triggered a call to `onNext({ data: undefined })` and now doesn't trigger one at all. This seems the most consistent and straightforward to me. Could do this a few different ways as well -- feel free to change.
Prettier made some formatting changes, and I've added a small bit of config to match your style. Feel free to undo/remove.
> Dispatch initial response in Ably handler

- javascript_client/src/subscriptions/__tests__/createAblyHandlerTest.ts
- javascript_client/src/subscriptions/createAblyHandler.ts
Hi Robert, here is another one where any errors in the original request (such as a 500) weren't being passed on to the subscription error handler.
> Pass request errors to observer in Ably handler

- lib/graphql/schema/object.rb
- spec/graphql/schema/object_spec.rb
- spec/support/jazz.rb
In the situation of:
```
module MyInterface
end
class MyClass
include MyInterface
end
class MySubClass < MyClass
end
```
`MySubClass.to_graphql` was not correctly passing down its superclass interfaces. This because of a small bug in a recent PR in which the wrong method was used to pass down these interfaces:
https://github.com/rmosolgo/graphql-ruby/pull/2791/files#diff-bb60261811b3e1117b450eedea63f7fcR165
We used `own_interface_type_memberships` but previously we were using `interfaces` which also read from the superclass's interfaces.
cc @otereshin-shopify who found the bug
----- 
Fixes #2873
> Inherit superclass interfaces to children in to_graphql

- lib/graphql/language/document_from_schema_definition.rb
- lib/graphql/schema/printer.rb
- spec/graphql/schema/printer_spec.rb
Now, any directive in an IDL-based schema is printed verbatim. 
This makes parse-then-dump work as expected, eg: 
```ruby 
GraphQL::Schema.from_definition(idl_string).to_definition
```
> Reprint all directives when schema is built from IDL

- lib/graphql/types/iso_8601_date.rb
- lib/graphql/types/iso_8601_date_time.rb
- spec/graphql/types/iso_8601_date_spec.rb
- spec/graphql/types/iso_8601_date_time_spec.rb
It can be easy to unintentionally resolve a Date object for a DateTime scalar field and vice versa. The intent of this PR is to make `ISO8601Date` and `ISO8601DateTime` more flexible, by allowing them to be resolved with either a `Date` object, a `DateTime` object, or a well-formatted string.
- Updates `ISO8601Date.coerce_result` to parse the resolved value and coerce to a `Date` object
- Updates `ISO8601DateTime.coerce_result` to parse the resolved value and coerce to a `DateTime` object while retaining precision if the resolved value is already a `DateTime` object
- Updates the exception text for `ISO8601DateTime` to reflect the extended input options
- Adds test cases for all combinations of scalars + resolve options
- Each `coerce_result` could perform explicit logic for each …
> feat: Date scalars accept Date, DateTime, and well-formatted Strings

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/pagination/connections_spec.rb
This `rescue` was catching _other_ NoMethodErrors, derp! 
Fixes https://github.com/rmosolgo/graphql-ruby/pull/2854#discussion_r409771169
cc @dewski -- thanks for reporting it!
> Only rescue NoMethodErrors relating to the .each call

- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/schema/input_object.rb
- lib/graphql/schema/member/has_arguments.rb
- spec/graphql/schema/input_object_spec.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/2671 (?)
Example adapted from the app I'm working on:
```rb
def object_from_id(id)
BatchLoader::GraphQL.for(id).batch { ... }
end
end
class UpdateThingInput < BaseInputObject
argument :id, ID, required: true, loads: Types::Thing, as: :thing
...
end
class UpdateThing < BaseMutation # < RelayClassicMutation
input_type UpdateThingInput
def resolve(thing:, **args)
...
end
end
```
Without the fix from this PR, attempting to use that mutation results in:
```
NoMethodError:
undefined method `key?' for #<GraphQL::Execution::Lazy:0x0000565081e580f8>
...
```
> Fix loads: on nested input objects

- lib/graphql/schema.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/member/has_arguments.rb
- spec/graphql/schema/argument_spec.rb
If `object_from_id` returns a lazy value, and a field has an auto-loaded list argument, the resolved list values are `GraphQL::Execution::Lazy` objects rather than the underlying application objects.
> Fix lazy loads: with list args

- lib/graphql/compatibility/execution_specification/specification_schema.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/internal_representation/scope.rb
- lib/graphql/internal_representation/visit.rb
- lib/graphql/schema.rb
- lib/graphql/schema/object.rb
- lib/graphql/tracing.rb
graphql-ruby tends to end up with very large stacks of things happening recursively. This PR attempts to, wherever possible, avoid pushing extra stack frames from blocks.
Move of these changes follow the pattern of instead doing:
``` ruby
def each
@array.each { |i| yield(i) }
```
We capture the block and pass it through.
``` ruby
def each(&block)
@array.each(&block)
end
```
Which avoids re-visiting our `each` in the stack.
> Reduce stack depths of deeply nested blocks

- lib/graphql/relay/base_connection.rb
- lib/graphql/schema/base_64_encoder.rb
- spec/graphql/schema/base_64_encoder_spec.rb
The new pagination system crashes when it's using the default cursor encoder and receives an invalid cursor. This was already fixed in #1855 for the relay connections. I just moved the error handling introduced there to the encoder. Now it can be used by both connection types.
I would say that it probably also makes more sense to be there because the encoder is configurable and different encoders can throw different errors. Handling all possible errors in the connections could become messy.
> Handle base64 argument errors in the encoder

- lib/graphql/schema.rb
In Ruby 2.7, `Schema.to_json` prints the following warning when called
with keyword arguments.
```
graphql-ruby/lib/graphql/schema.rb:874: warning: Using the last argument
as keyword parameters is deprecated; maybe ** should be added to the
call
```
I added `**` to args to fix the deprecation.
> Fix deprecation on Schema.to_json parameters

- guides/mutations/mutation_authorization.md
Closes #2916 
Update in the documentation to make it clear that any `falsey` return from `authorized?` will stop the execution of the mutation. Also, fixes a code example that would never run the mutation's `resolve` method.
> Update mutation_authorization documentation for authorized? 

- lib/graphql/object_type.rb
Fixes the following warning:
```
/Users/hasghari/github/graphql-ruby/lib/graphql/object_type.rb:91: warning: Using the last argument as keyword parameters is deprecated; maybe ** should be added to the call
/Users/hasghari/github/graphql-ruby/lib/graphql/schema/type_membership.rb:22: warning: The called method `initialize' is defined here
```
> Fix keyword parameters warning in Ruby 2.7

- lib/graphql/schema/loader.rb
- spec/graphql/schema/loader_spec.rb
When loading schemas, disable method name access to prevent any warnings
that occur when method names already exist.
Re-applies 3e75532 after cf70a75 reverted the change.
The existing spec has been updated to trigger the warning which is
emitted only when the GraphQL classes are built.
Fixes #2933
> Disable method access when loading schema to prevent warnings

- lib/graphql/execution/multiplex.rb
- lib/graphql/query.rb
- lib/graphql/tracing.rb
This has been deprecated since 1.7.4 (Oct 2017)
> Remove global tracers support

- lib/graphql/schema/loader.rb
- spec/graphql/schema/build_from_definition_spec.rb
- spec/graphql/schema/loader_spec.rb
Oops, I refactored `Schema::Loader` to build class-based schemas, but I broke underscored fields that are loaded.
Fixes #2939
Fixes #2940
> Fix underscored names in introspection loader

- javascript_client/package.json
- javascript_client/src/subscriptions/__tests__/createAblyHandlerTest.ts
- javascript_client/src/subscriptions/createAblyHandler.ts
Hi Robert,
We've noticed that Ably sometimes raises [error 90010](https://help.ably.io/error/90010). I've investigated and found two related issues:
1. Subscriptions don't get cleaned up properly, causing this error which, afaict, effectively means that only the first 200 subscriptions work as expected.
2. Errors raised by Ably don't get propagated to the observer meaning they might go unnoticed.
See the two commit messages for more details.
Assuming you agree with these changes, could I ask you to roll a release with this ASAP?
> Fix unsubscribing and error handling for Ably

- lib/graphql/execution/instrumentation.rb
Small performance optimization on instrumentation.rb
Below are the benchmark results
```
ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin19]
MacBook Pro 2015, 16GB Ram, i7 2.8 GHz
```
Although the performance increase might not be that significant, we get a memory improvement by calling `reverse_each` since it saves us the allocation of the array that happens with `reverse`
(https://github.com/rails/rails/pull/17244)
```
validate - introspection 
56.000  i/100ms
validate - abstract fragments
474.000  i/100ms
validate - abstract fragments 2
371.000  i/100ms
validate - big query     4.000  i/100ms
validate - introspection 
567.398  (± 2.6%) i/s -      2.856k in   5.037012s
validate - …
```
> Replace reverse.each with reverse_each

- lib/graphql/introspection/schema_type.rb
- lib/graphql/schema/field.rb
- spec/graphql/execution/interpreter_spec.rb
- spec/graphql/schema/field_spec.rb
- spec/integration/mongoid/star_trek/schema.rb
- spec/support/dummy/schema.rb
- spec/support/jazz.rb
- spec/support/lazy_helpers.rb
- spec/support/star_wars/schema.rb
This is a bit of a breaking change. If a field is defined in camel case (`field :doStuff`), but the method is underscored (`def do_stuff`), then it will stop working. But altogether, I think defaulting to matching Ruby values is an improvement. 
Fixes #2906
> Use field name as defined for hash key or method name

- lib/graphql/schema/warden.rb
- spec/graphql/schema/introspection_system_spec.rb
- spec/graphql/schema/object_spec.rb
- spec/support/jazz.rb
Oops, long story short, we have some code that took advantage of the previously-broken behavior with hidden interfaces. (Fields on hidden interfaces _were_ added to object types.) I need an option to add fields to objects even when the interface is hidden.
> Show fields when they override inherited ones

- lib/graphql/schema/field.rb
- lib/graphql/schema/list.rb
- spec/graphql/schema/input_object_spec.rb
If:
1. `object_from_id` returns a lazy value
2. An input object `A` has a `loads:` argument
3. An input object `B` has an argument of type `[A]`
Then in the resolver, `B`'s argument will be an array of `GraphQL::Execution::Lazy` objects rather than `A` objects.
This PR makes it so that lists of lazy input objects are properly synced before being passed to resolvers.
> Fix lazy loads: in lists of inputs

- lib/graphql/execution/interpreter/arguments.rb
- spec/graphql/query_spec.rb
`GraphQL::Execution::Interpreter::Arguments#each_value` currently yields `[<argument_keyword>, ArgumentValue]` arrays but I believe it was meant to yield `ArgumentValue`s to be consistent with `GraphQL::Query::Arguments#each_value`.
> Arguments#each_value should yield ArgumentValues

- lib/graphql/schema/member/has_fields.rb
All object types have the method `raw_value` via `GraphQL::Schema::Object.include(HandlesRawValue)` so this should be
considered reserved too.
> Add raw_value to GRAPHQL_RUBY_KEYWORDS

- lib/generators/graphql/object_generator.rb
- spec/integration/rails/generators/graphql/object_generator_spec.rb
Resolves #2951
Added support for existing Models in object generator. If a ActiveRecord's class exists the generator will fetch columns info based on Model's schema.
Example usage:
`rails generate graphql:object User`
You can also add custom fields which don't exist in your schema, example:
`rails generate graphql:object User custom_field:String`
Also added support for "datetime" and "date" field types.
> Improve object generator

- lib/graphql/pagination/connection.rb
- lib/graphql/pagination/connections.rb
- lib/graphql/schema/field/connection_extension.rb
- spec/graphql/pagination/connections_spec.rb
- spec/support/connection_assertions.rb
Fixes #2960 
I'm rolling this out in a larger release than usual because it changes the API of `.wrap(...)`. It requires a new input, `parent`.
TODO:
> Add Edge#parent to new connections

- lib/graphql/schema.rb
- spec/graphql/schema_spec.rb
Currently, subclassing a `Schema` doesn't inherit the base class's error handler. This means that configuration like `use use GraphQL::Execution::Errors` isn't passed down to subclasses. This PR is an attempt to fix that.
> fix: Inherit Schema.error_handler configuration from base class

- lib/graphql/types/iso_8601_date.rb
- lib/graphql/types/iso_8601_date_time.rb
- spec/graphql/types/iso_8601_date_time_spec.rb
As [documented by Ruby](https://ruby-doc.org/stdlib-2.3.0/libdoc/date/rdoc/DateTime.html): "Almost certainly you'll want to use Time since your app is probably dealing with current dates and times."
The tests conflated timezones with UTC offsets - the difference is subtle but important. There's plenty of sources (e.g. [Stack Overflow](https://stackoverflow.com/tags/timezone/info)) on the internet explaining this.
Also added a small speedup by using `to_time` to coerce a Date object instead of writing out and parsing a string.
> Use Time objects instead of DateTime for ISO8601DateTime scalar

- lib/graphql/subscriptions/subscription_root.rb
- spec/graphql/schema/subscription_spec.rb
This resolves #2982 by filtering out the arguments before creating the event
If we want to be explicit with the tests, I can create a new field with extras in the subscription and duplicate one test for subscribe and another one for update using that new field
> Fixed NoMethodError when using extras in a subscription field 

- guides/type_definitions/interfaces.md
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/schema.rb
- spec/graphql/schema/union_spec.rb
Often abstract types in GraphQL are be backed by "wrapped" domain objects such as unions, ADTs, etc. Currently `resolve_type` must return a GraphQL type only even though the wrapped domain object ideally should be unwrapped at this point as well instead of passing through to the next resolver.
This allows abstract type's `resolve_type` to return an optional "resolved"/unwrapped object in addition the resolved type. To optionally return a new object value, an array can be returned as `[type, object]`.
This is backwards compatible as well and the existing validation still applies to verify the first item in the array is a GraphQL type.
@rmosolgo this is a proposal right now to see what you think. If you think it's useful, I need to update documentation.
Also I'm not 100% sure how this works …
> Allow resolve_type to optionally return resolved object

- lib/graphql/tracing/new_relic_tracing.rb
- lib/graphql/tracing/platform_tracing.rb
- lib/graphql/tracing/scout_tracing.rb
- spec/graphql/tracing/scout_tracing_spec.rb
- spec/support/scout_apm.rb
This adds code to `GraphQL::Tracing::ScoutTracing` to write the transaction name for single query execution.
Fixes #2968 
---
This seems like an opportunity to refactor a bit since the 16 line method is identical to `GraphQL::Tracing::NewRelicTracing` except for one line. I didn't want to make this change without checking first, though.
It seems like a simple improvement would be to move the code that determines the transaction name into `PlatformTracing` as `transaction_name`, like:
```ruby
def transaction_name
query = data[:query]
selected_op = query.selected_operation
if selected_op
op_type = selected_op.operation_type
op_name = selected_op.name || "anonymous"
else
op_type = "query"
op_name = "anonymous"
end
"GraphQL/#{op_type}.#{op_name}"
end
```
And then in Scout/NewRelic it can do …
> Add Scout transaction naming

- guides/subscriptions/broadcast.md
- guides/subscriptions/implementation.md
- guides/subscriptions/overview.md
- guides/subscriptions/subscription_classes.md
- guides/subscriptions/subscription_type.md
- guides/subscriptions/triggers.md
- lib/graphql/schema/field.rb
- lib/graphql/schema/resolver.rb
- lib/graphql/schema/subscription.rb
- lib/graphql/schema/warden.rb
- lib/graphql/subscriptions.rb
- lib/graphql/subscriptions/action_cable_subscriptions.rb
- lib/graphql/subscriptions/broadcast_analyzer.rb
- lib/graphql/subscriptions/event.rb
- spec/dummy/Gemfile
- spec/dummy/app/assets/javascripts/application.js
- spec/dummy/app/channels/graphql_channel.rb
- spec/dummy/app/views/pages/show.html
- spec/dummy/test/system/action_cable_subscription_test.rb
- spec/graphql/subscriptions/broadcast_analyzer_spec.rb
- spec/graphql/subscriptions_spec.rb
If lots of people are subscribed to the same event with the same query string, and you can be sure that they should _all receive the same data_, then we should be able to calculate the payload _once_ and distribute it to all subscribers. 
I thought I would need a new API, but I think it's possible using: 
- `Query#fingerprint`, which returns a unique string for each query string + variables 
- `Event#topic`, which includes field name, args, and subscription scope
__TODO__: 
Fixes #2851
Part of #2846
> Add subscription broadcasts

- lib/graphql/schema/input_object.rb
I was doing some code spelunking and noticed that the `@arguments_by_keyword` instance variable in `GraphQL::Schema::InputObject` was unused.
> Remove unused instance variable in GraphQL::Schema::InputObject

- javascript_client/package.json
- javascript_client/src/subscriptions/__tests__/createAblyHandlerTest.ts
- javascript_client/src/subscriptions/createAblyHandler.ts
- Refactor to use async/await
- Fix `unsubscribe` call (cf. ably/ably-js#667)
- Report missing `X-Subscription-ID` header
- Report errors when entering or leaving presence, and when detaching
- Wait for leave and detach to complete before releasing channel
The last item is the main reason for this PR. Currently, the ack messages that Ably sends back especially for detach won't be processed correctly because by the time they arrive, the channel has already been released and Ably can't find it in its mapping. I _think_ this should be harmless but there is a chance this is causing problems.
The code could be a lot nicer if we could use `Ably.Promise`, but that would be a breaking change so I left it for another day.
> Ably robustness improvements

- javascript_client/src/subscriptions/__tests__/createAblyHandlerTest.ts
- javascript_client/src/subscriptions/createAblyHandler.ts
1. In certain circumstances, the initial response can cause `dispose` to be called before the subscription has finished setting up. In this situation, the channel is never detached.
2. Likewise, if the subscription is disposed while the Ably channel is still attaching, detaching the channel doesn't do anything.
This PR fixes both of those issues. I've also simplified cleanup based on feedback from Ably.
> Fix issues around early disposal

- lib/graphql/schema/input_object.rb
- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/schema/warden.rb
- spec/graphql/query/executor_spec.rb
This line:
`visible_arguments_map = warden.arguments(self).reduce({}) { |m, f| m[f.name] = f; m}`
Was straightforward, but was also making visibility calls to arguments that we did not need to check.
I have sacrificed a small bit of readability here in order to reduce the number of `visible?` calls being made in warden.
There are three steps to this process to make sure it remained the same and didn't break tests:
1. Inject all required arguments as `nil` that were missing from input. This is to satisfy this test:
https://github.com/rmosolgo/graphql-ruby/blob/39b78e5e46b654d5fc9b170025e3b690e463b9e8/spec/graphql/query/executor_spec.rb#L293
2. Check to see if the input/required args are visible on the object. Satisfies this test:
https://github.com/rmosolgo/graphql-ruby/blob/39b78e5e46b654d …
> Only check used input arguments visibility

- lib/graphql/execution/interpreter/runtime.rb
Previously this only checked for field extras but field extensions should be checked as well since they can mutate arguments.
@jturkel does this makes sense to you as well? I guess you didn't have any instances of field extensions mutating args?
> Fix arguments caching - check for field extensions

- lib/graphql/directive.rb
- lib/graphql/field.rb
- lib/graphql/input_object_type.rb
- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/static_validation/literal_validator.rb
- lib/graphql/static_validation/rules/arguments_are_defined.rb
- lib/graphql/static_validation/rules/required_arguments_are_present.rb
- lib/graphql/static_validation/rules/required_input_object_attributes_are_present.rb
Replaces more usages of `warden.arguments` during static validation (since they trigger `visible?` calls for all arguments on a type regardless if they are specified or not) with more selective `warden.get_argument`.
https://github.com/rmosolgo/graphql-ruby/pull/2985 which fixed some of these occurrences, but not all of them.
This also required additional backwards compatible work to port `get_argument` to the legacy types.
cc @eapache @grcooper @chrisbutcher
> Remove more visible? calls to unused arguments

- lib/graphql/execution/interpreter/runtime.rb
Previously this only checked for field extras but field extensions
should be checked as well since they can mutate arguments.
> Fix arguments caching - checking for extensions

- lib/graphql/schema/loader.rb
- spec/graphql/schema/loader_spec.rb
This PR updates `GraphQL::Schema.from_introspection` to load field and enum value deprecation reasons from introspection results. I converted `spec/graphql/schema/loader_spec.rb` to use the not so new anymore class based API while I was adding test coverage.
> Load deprecation reason from introspection results

- lib/graphql/schema.rb
- lib/graphql/schema/loader.rb
- spec/graphql/schema/loader_spec.rb
This PR updates `GraphQL::Schema.from_introspection` to load directives from introspection results. While I was in here I made a few related changes:
* Updated `GraphQL::Schema.directives` to accept an array or varargs to be consistent with `orphan_types` and make the DSL a bit more ergonomic
* Updated `loader_spec.rb` `assert_deep_equal` to check that collection element names match before doing recursive equality checking for better error messages. This was previously done for some collections but not all.
> Load directives from introspection results

- guides/pagination/using_connections.md
These code blocks were displayed inline before and looked broken.
Looks like this right now:
> [Docs] Improve code formatting in Connections

- guides/queries/multiplex.md
I was implementing multiplexing for my server, and in the documentation it was mentioned that Apollo sends the batched queries in a `_json` field. However when I inspected the request from the client, there was no `_json` field.
I dug deeper, and found that Apollo client sends the queries in a JSON array, and that Rails' ActionDispatch is the one who populates the "_json" field when the parsed data is not a Hash ([source](https://github.com/rails/rails/blob/e82c10b49ad9cb949f77297e6a814fd8f09d3c8f/actionpack/lib/action_dispatch/http/parameters.rb#L13)).
I also fixed some dead links.
> Correct multiplex documentation regarding the _json field in the params variable

- lib/generators/graphql/templates/graphql_controller.erb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
One possible solution to #3028.
The variables_fingerprint calls size on the variables.  When variables are an instance of ActionController::Parameters, then this will raise an error as size in not defined. Converting ActionController::Parameters to a hash resolves the issue.
> Update controller generator so that provided_variables has .size

- lib/graphql/pagination/connection.rb
- lib/graphql/pagination/connections.rb
- lib/graphql/schema/field/connection_extension.rb
- spec/graphql/pagination/connections_spec.rb
- spec/support/connection_assertions.rb
The new connection module didn't properly use `edge_class:` configurations.
Fixes #3005 
Fixes https://github.com/rmosolgo/graphql-ruby/issues/3017
> Use edge_class: with new pagination implementation

- lib/graphql/schema/argument.rb
- spec/graphql/schema/argument_spec.rb
> Add validation to prevent arguments with both required and default_value

- lib/graphql/static_validation/rules/variables_are_used_and_defined.rb
- spec/graphql/static_validation/rules/variables_are_used_and_defined_spec.rb
- spec/graphql/static_validation/validator_spec.rb
* This provides a default behavior for anonymous operation types in `GraphQL::StaticValidation::Rules::VariablesAreUsedAndDefined` when `usage.used_by.name` or `usaged.declared_by.name` is `nil`
* fixes #3047
> GraphQL::StaticValidation::Rules::VariablesAreUsedAndDefined - show "anonymous <operation_type>" in error message

- lib/graphql/language/visitor.rb
This is a not code path and was previously calling `AbstractNode#==`, which is slower since it implements some imprecise matching. We should be treating `DELETE_NODE` as a singleton, so `.equal?` should be sufficient here.
> Use equal? to check for DELETE_NODE

- guides/related_projects.md
Some time ago, I needed to retrieve statistical information (e.g. counts, sums...) about a set of data using a GraphQL API. To make it easier to retrieve such information (while at the same time providing a clear and flexible query interface) I created [graphql-groups](https://github.com/hschne/graphql-groups). 
While the gem is still in early development I would be happy to add it to the list of related projects. If you have any reservations I'd gladly address them :blush:
> Add graphql-groups to the list of related projects

- lib/graphql/schema/enum_value.rb
- spec/graphql/schema/enum_spec.rb
Fixes #3008 -- This used to be covered by `#to_graphql`, but since 1.11, the main codepath doesn't use that method!
> Validate enum values up front

- lib/graphql/subscriptions/serialize.rb
- spec/graphql/subscriptions/serialize_spec.rb
`Subscription::Serialize` is what graphql-ruby uses when `.trigger` objects have to be persisted before being passed to execution.  This adds support to timestamps and openstructs, so that can be properly used with `.trigger` (fixes https://github.com/rmosolgo/graphql-ruby/issues/2326)
> Support Date, Time, and OpenStruct in Subscription::Serialize

- lib/graphql/schema/member/has_fields.rb
- spec/support/jazz.rb
Naming your fields after Object instance methods will cause the resolver to call them on the resolver instance. This is normally not intentional, and confusing. This MR adds `Object.instance_methods` to the `CONFLICT_FIELD_NAMES` so a warning is generated.
There already was a test for the field name :method in spec/graphql/schema/object_spec.rb:341 . I have removed `:method` from the existing GRAPHQL_RUBY_KEYWORDS to ensure the test tests that it comes from Object.instance_methods instead. 
There is an example of the confusion between resolver instance resolution and actual object resolution in the jazz.rb test code, where `object_id` is exposed intentionally but this method is called on the resolver instance instead of the actual object instance. 
I am unsure if the intent of that test …
> Add `Object.instance_methods` to `CONFLICT_FIELD_NAMES` for warnings

- lib/graphql/schema/argument.rb
- spec/graphql/schema/argument_spec.rb
Reverts rmosolgo/graphql-ruby#3011 because that behavior is _actually allowed_ by the spec, see https://github.com/rmosolgo/graphql-ruby/pull/2416 and https://github.com/graphql/graphql-spec/pull/418 and https://github.com/rmosolgo/graphql-ruby/issues/3001#issuecomment-670274075
> Revert "Add validation to prevent arguments with both required and default_value"

- lib/graphql/schema/member/has_fields.rb
- lib/graphql/schema/mutation.rb
- lib/graphql/schema/resolver/has_payload_type.rb
- spec/graphql/schema/mutation_spec.rb
- spec/graphql/schema/object_spec.rb
Improve the method warnings in two ways: 
- A given `method:` value bypasses this warning since it will be called on the application object, not the graphql type definition 
- Mutations provide more specific warnings about conflicting fields (and don't warn a second time when generating payload types)
Fixes #2775 
Fixes #2723
> Improve method conflict warnings

- lib/graphql/schema/resolver.rb
- spec/graphql/schema/resolver_spec.rb
This way `mutation.arguments` will return the arguments during authorization. (This is especially helpful for the CanCan integration.)
> Store prepared arguments on resolver instance when they're ready

- lib/graphql/schema/subscription.rb
- lib/graphql/subscriptions.rb
- spec/graphql/schema/subscription_spec.rb
Oops, using errors for control flow (🙈 I know, I know) was interfering with catch-all error handlers (`rescue_from(StandardError)`). So, use `throw` instead (🙈 I know, I know. I just don't know how else to reliably propagate that information from deep in the query runtime to the subscription update call. `ctx.skip` could work for `no_update`, but I don't know how that could work for `unsubscribe`.) 
Fixes #3044 
cc @hattmarris this should also fix https://github.com/rmosolgo/graphql-ruby/issues/3035#issuecomment-662098266
> Use throw instead of raise to halt subscriptions early

- lib/graphql/query/context.rb
Profiling one of our key queries revealed we were spending 17%  of the CPU time in `GraphQL::Query::Context#fetch`. The underlying problem was that this calls `GraphQL::Query::Context#to_h` which allocates a new hash when merging`@scoped_context` and `@provided_values`. This optimization avoids the allocation and merging of hashes with some conditional logic. `GraphQL::Query::Context#dig` has a similar performance issue but handling that properly is a little trickier so I'm going to leave it for another day.
> Optimize GraphQL::Query::Context#fetch

- lib/graphql/schema/warden.rb
This pull request contains two documentation fixes.
* `Warden#initialize` doesn't receive `deep_check` argument.
* `Warden#types` actually returns a Hash, but the documentation said "it returns a Array".
> Fix incorrect documentations

- lib/graphql/types/iso_8601_date_time.rb
frozen_string_literal comment only works if the comment is at the first line of the file.
But `iso_8601_date_time.rb` had a frozen_string_literal comment after `require`. So this pull request swaps the require and frozen-string_literal comment.
We can confirm this problem with `-w` option of ruby.
```bash
$ ruby -cw lib/graphql/types/iso_8601_date_time.rb
lib/graphql/types/iso_8601_date_time.rb:3: warning: `frozen_string_literal' is ignored after any tokens
Syntax OK
```
> Put frozen_string_literal at the first line

- lib/graphql/query/fingerprint.rb
It raises a NameError when `digest/sha2` library isn't loaded by another place.
For example:
```ruby
require 'bundler/inline'
gemfile do
source 'https://rubygems.org'
gem 'graphql', path: '.'
end
class QueryType < GraphQL::Schema::Object
field :foo, String, null: false, resolve: -> (_, _, _) do
'foo'
end
end
class T
def self.trace(key, data, &block)
p data[:query].fingerprint if data[:query]
block.call
end
end
tracer T
query QueryType
end
doc = GraphQL.parse(<<~Q)
query {
foo
}
Q
Schema.execute(
document: doc,
variables: {},
context: {},
)
```
```
/path/to/lib/graphql/query/fingerprint.rb:19:in `generate': uninitialized constant GraphQL::Query::Fingerprint::Digest (NameError)
from /path/to/lib/graphql/query.rb:286:in `operation_fingerprint'
from …
```
> Add `require 'digest/sha2'` for fingerprint

- lib/generators/graphql/core.rb
- lib/generators/graphql/templates/base_argument.erb
- lib/generators/graphql/templates/base_enum.erb
- lib/generators/graphql/templates/base_field.erb
- lib/generators/graphql/templates/base_input_object.erb
- lib/generators/graphql/templates/base_interface.erb
- lib/generators/graphql/templates/base_mutation.erb
- lib/generators/graphql/templates/base_object.erb
- lib/generators/graphql/templates/base_scalar.erb
- lib/generators/graphql/templates/base_union.erb
- lib/generators/graphql/templates/enum.erb
- lib/generators/graphql/templates/graphql_controller.erb
- lib/generators/graphql/templates/interface.erb
- lib/generators/graphql/templates/loader.erb
- lib/generators/graphql/templates/mutation.erb
- lib/generators/graphql/templates/mutation_type.erb
- lib/generators/graphql/templates/object.erb
- lib/generators/graphql/templates/query_type.erb
- lib/generators/graphql/templates/scalar.erb
- lib/generators/graphql/templates/schema.erb
- lib/generators/graphql/templates/union.erb
Currently, running the generators from within an engine produces files that are not namespaced properly.
For example, if you run `rails g graphql:scalar Date` in the engine `blorgh`, you'll end up with a new ruby file that looks like:
```ruby
module Types
class Date < Types::BaseScalar
end
end
```
It should look like this:
```ruby
module Blorgh
module Types
class Date < Types::BaseScalar
end
end
end
```
Wrapping the template contents in [#module_namespacing](https://github.com/rails/rails/blob/master/railties/lib/rails/generators/base.rb#L288-L292) provides the correct namespace in a generator is called from within an engine.
🎩  Results:
> Use module_namespacing for graphql templates

- lib/graphql/query/validation_pipeline.rb
- lib/graphql/schema.rb
- spec/graphql/analysis/ast/max_query_depth_spec.rb
Even with `max_depth ...`, if a query is too big, it will raise a stack error. 
This is the easiest, most catch-all fix. (It covers all of validation, regardless of `max_depth ...`.) 
The handling of this error can be customized in your schema definition, eg: 
```ruby 
def self.query_stack_error(query, err)
raise err # to raise the original Ruby error 
end 
end 
```
Although I think this fix is appropriate in any case, more subtle changes might be possible: 
- Change `MaxQueryDepth` to _halt_ analysis when the max depth is exceeded. We'd have to change the error message, which currently contains the actual query depth. We could also add a hard cap to MaxQueryDepth (configurable, default 500?). TODO: would validation still raise a stack error?
- Refactor …
> Rescue SystemStackErrors during validation

- guides/related_projects.md
Authentication is a common feature in most applications and Devise does great work providing this set of functionalities in full stack ruby world. When it comes to API's there are a number of of gems that modify Devise to work with REST endpoints, like devise Token Authentication for example, but with @mcelicalderon we couldn't find a gem that provides a graphql interface for devise and fit our needs so we created [graphql_devise](https://github.com/graphql-devise/graphql_devise) and have been working on it for almost a year now.
The gem has around 30 releases at the moment and we would love if it can be added to this gem related projects. If you have any reservations we would be glad to address them, just let us know!
> Add gql devise to related_projects.md

- guides/subscriptions/ably_implementation.md
Adding some clarification since this tripped me up. The "Channel Lifecycle"  source option is disabled until you set the request mode to "Batch request"
> Update instructions for Ably Webhook configuration

- lib/graphql/pagination/connections.rb
- spec/graphql/pagination/connections_spec.rb
This is a followup to PR #2699, that allows returning `raw_value` from connection resolvers. In this case interpreter should stop any further processing and use the provided value (right now the value wrapped into `RawValue` will reasonably raise `Couldn't find a connection wrapper for RawValue ...`).
Example:
```ruby
class QueryType < Types::BaseObject
field :feed, Types::Event.connection_type, null: false
def feed
return raw_value(value) if (value = read_cache)
write_cache do
Event.where(language_id: language_id, category_id: category_id)
end
end
end
```
> Do not wrap connections when RawValue is returned from resolver

- lib/graphql/static_validation/validator.rb
Currently, rules attribute has fallback value which is ALL_RULES and this array contains 27 modules (latest version). None of them is Class and has `validate` method. So for this case, loop through this Module array was a complete waste of time and resources.
To deal with legacy rules which come from GraphQL pro. We should compare `rule_to_use` and ALL_RULES array before we decide to start the loop
> Avoid redundant loop through rules_to_use in Validator#validate

- lib/graphql/schema.rb
- lib/graphql/schema/interface.rb
- spec/graphql/schema_spec.rb
To fix: https://github.com/rmosolgo/graphql-ruby/issues/3123
Fixed up the `possible_types` method on the `Schema` class object. Previously this was not taking into account the `context` which meant that some interfaces could be shown when they shouldn't be.
> Update possible types on schema class for interfaces

- gemfiles/rails_4.2.gemfile
- lib/graphql/subscriptions.rb
- lib/graphql/subscriptions/action_cable_subscriptions.rb
- spec/graphql/subscriptions/action_cable_subscriptions_spec.rb
```ruby
class FooSchema < GraphQL::Schema
use GraphQL::Subscriptions::ActionCableSubscriptions
subscription(Foo::Types::SubscriptionType)
end
module Foo
class SubscriptionType < ::Types::BaseObject
field :foo_subscription, subscription: Foo::FooSubscription
end
end
class BarSchema < GraphQL::Schema
use GraphQL::Subscriptions::ActionCableSubscriptions
subscription(Bar::Types::SubscriptionType)
end
module Foo
class SubscriptionType < ::Types::BaseObject
field :foo_subscription, subscription: Bar::FooSubscription
end
end
#
FooSchema.subscriptions.trigger(:foo_subscription, {}, {}, scope: nil) # => transmitting graphql-event:XXX
BarSchema.subscriptions.trigger(:foo_subscription, {}, {}, scope: nil) # => transmitting graphql-event:XXX
```
Multiple schemas will generate the same event stream …
> customize ActionCable subscriptions

- lib/graphql/schema/argument.rb
- spec/graphql/schema/argument_spec.rb
Following up on the discussion in #3133, this adds validation to prevent deprecating required arguments in the class based API. The validation added in #3015 only covered the legacy API.
> Validate that deprecated requirements aren't required

- lib/graphql/execution/interpreter/arguments.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/schema/input_object.rb
- spec/graphql/execution/interpreter/arguments_spec.rb
- spec/graphql/schema/field_extension_spec.rb
Fixes #3004 , addresses issues described in #3003 
TL;DR: it's possible to make mistakes where objects from the arguments cache are reused, even after they're modified in field-specific ways. This will make that impossible, since arguments objects can't be modified.
It could well be a breaking change, because arguments hashes won't play nicely with `.delete` anymore (as shown in updated test here, same goes for other destructive Hash methods).
> Freeze Interpreter::Arguments instances

- lib/graphql/execution/interpreter/arguments.rb
- spec/graphql/query_spec.rb
`GraphQL::Execution::Interpreter::Arguments` is a hash-like class so this PR adds the `fetch` method.
> Implement GraphQL::Execution::Interpreter::Arguments#fetch

- guides/queries/timeout.md
- lib/graphql/schema/timeout.rb
- spec/graphql/schema/timeout_spec.rb
This would allow dynamically determining `max_seconds` on a query-by-query basis. You'd use a custom subclass of `GraphQL::Schema::Timeout` to do that. 
Fixes #3162
> Per-query timeout duration

- lib/graphql/language/sanitized_printer.rb
- spec/graphql/language/sanitized_printer_spec.rb
This PR fixes a few problems with `GraphQL::Language::SanitizedPrinter`:
1. Variables with lists of enum values rendered as strings
1. Queries with argument values that needed to be coerced to lists raised `NoMethodError: undefined method `arguments' for #<GraphQL::Schema::List:0x00007fc4819dd508>` errors
1. Queries with JSON scalars raised `NoMethodError: undefined method `arguments' for GraphQL::Types::JSON:Class` errors
> SanitizedPrinter fixes for lists and JSON scalars

- lib/graphql/language/sanitized_printer.rb
- lib/graphql/query.rb
- spec/graphql/language/sanitized_printer_spec.rb
We (Salsify) are implementing logging of GraphQL queries and variables but our approach is slightly different than the default behavior of `GraphQL::Language::SanitizedPrinter`:
* We log queries and variables separately to get a more faithful representation of the requests we're getting from clients
* We extended our `GraphQL::Schema::Argument` subclass to support a `redact` option rather than just redacting all strings
We were able to implement this by subclassing `GraphQL::Language::SanitizedPrinter` but it involved some unfortunate copying of code from `GraphQL::Language::Printer` to restore overridden behavior and copying of code from `GraphQL::Language::SanitizedPrinter` where we need to inject logic in the middle of a method. Alternatively we could directly subclass …
> Make query sanitization more extensible

- lib/graphql/schema/field.rb
- lib/graphql/schema/field/connection_extension.rb
- spec/graphql/schema/field_extension_spec.rb
This is a follow-up after https://github.com/rmosolgo/graphql-ruby/pull/3138 which had breaking changes for our application without a real way to work around it. This proposes a solution to make extensions dealing with extended arguments more flexible.
Field Extensions let you extend (modify) the resolver object and arguments in the `resolve` hook. Previously the `after_resolve` hook would receive the *original* object and arguments and not the extended ones. This was a lossy process with no way for `after_resolve` to access the extended values.
This changes `after_resolve` to receive the extended values instead. If you need access to the original non-extended values, the `memo` argument can be used.
Example:
```ruby
class MyExtension < GraphQL::Schema::FieldExtension
def apply(field) …
```
> FieldExtension: pass extended values instead of originals to after_resolve

- CHANGELOG.md
- lib/graphql/unauthorized_error.rb
This PR is a fix for #3174 
It uses `graphql_name` which is both more appropriate and fixes a potential performance issue with calling `name` in the constructor.
> Use graphql_name in UnauthorizedError constructor when constructing default message

- lib/graphql/schema/build_from_definition.rb
- spec/graphql/schema/build_from_definition_spec.rb
Fixes #3181 
The only difference in retained memory was the procs for these methods, which was 0.02% in my own case :+1:
> Fix .valid_isolated_input? on parsed schemas

- guides/subscriptions/subscription_classes.md
The documentation on subscriptions page show `Room` and `Message` as mandatory in the client side, but the ruby class show them as `null: true`. This change makes them not nullable in the ruby gql class to have consistency
```javascript
type MessageWasPostedPayload {
room: Room!
message: Message!
}
```
> Fix fields nullability in subscriptions documentation

- lib/graphql/define/assign_global_id_field.rb
- lib/graphql/schema/member/has_fields.rb
- spec/graphql/schema/interface_spec.rb
Accept options in `global_id_field` macro and pass them to as field definition options. This would be extremely useful with https://github.com/Gusto/apollo-federation-ruby/ turning:
```
global_id_field :id
field :id, ID, null: false, external: true
```
into:
```
global_id_field :id, external: true
```
> Accept additional options in global_id_field macro

- lib/graphql/pagination/connections.rb
- lib/graphql/relay/range_add.rb
- spec/integration/rails/graphql/relay/range_add_spec.rb
Oops, this had a hardcoded reference to `Relay::BaseConnection`, so it always returned legacy connections.
Fixes #3191
> Update RangeAdd to use new connections when available

- guides/type_definitions/extensions.md
While spending some time extending the graphql-ruby type system in a project of mine I noticed that the documentation that describes how the `field` DSL generates a `GraphQL::Schema::Field` object wasn't using the correct method signature. It looks like the method signature changed in 82d95dd, but this documentation was never updated.
The method signature is quite complex with a large number of keyword arguments, but hopefully only using the required arguments is sufficient for this particular documentation example.
> Update method signature example in extension docs

- javascript_client/src/subscriptions/__tests__/createAblyHandlerTest.ts
- javascript_client/src/subscriptions/createAblyHandler.ts
Specify the [`rewind`](https://www.ably.io/blog/channel-rewind/) parameter for each channel so that early messages don't get lost.
Without this change, any messages sent during a specific time window are lost. This time window begins when the subscription is established server-side and ends when the client-side call to `subscribe` takes effect, i.e. once the subscription request has been received and processed by Ably servers.  I've observed this window to be up to three seconds long,  although obviously it can be of arbitrary length depending on network latency etc.
Note that Ably promises to keep messages (with the default channel configuration) for two minutes, which should be enough even for pathological cases.  However, technically messages can still get lost when establishment of …
> Fix race conditions with Ably subscriptions

- lib/graphql/static_validation/all_rules.rb
- lib/graphql/static_validation/rules/input_object_names_are_unique.rb
- lib/graphql/static_validation/rules/input_object_names_are_unique_error.rb
- spec/graphql/query_spec.rb
- spec/graphql/static_validation/rules/input_object_names_are_unique_spec.rb
From the GraphQL spec: 
> Input objects must not contain more than one field of the same name, otherwise an ambiguity would exist which includes an ignored portion of syntax.
https://spec.graphql.org/June2018/#sec-Input-Object-Field-Uniqueness
This query should be considered invalid and the response should contain `errors`.
It appears the last usage of a duplicate input object field is what graphql-ruby accepts, without any errors.
This PR now contains a proposed fix. Adding `GraphQL::StaticValidation::InputObjectNamesAreUnique`. It seems like a pretty straightforward change, consistent with how existing validations like `ArgumentNamesAreUnique` work.
> Add InputObjectNamesAreUnique static validation

- lib/graphql/schema/field.rb
- spec/graphql/schema/field_extension_spec.rb
Previously, any modifications to `args` were lost. cc @swalkinshaw 
This is a hack, but it's a _hack with a test_ 🎉 .
> Pass along extended args even when an extension shortcuts the normal resolve

- lib/graphql/execution/interpreter/arguments.rb
- lib/graphql/execution/interpreter/arguments_cache.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/query.rb
- lib/graphql/query/context.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/field/scope_extension.rb
- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/types/string.rb
Inspired by https://github.com/rmosolgo/graphql-ruby/issues/3213
For `rake bench:profile_large_result`, I see about 30% faster and 45% less memory. (But this is _just overhead_ -- application benchmarks will see less improvement, since changes here won't improve application performance.)
<details>
<summary> Before benchmark</summary>
<p>
```
1.000  i/100ms
2.760  (± 0.0%) i/s -     14.000  in   5.075846s
Thread ID: 407040
Fiber ID: 407020
Total: 1.595308
%self      total      self      wait     child     calls  name                           location
9.64      0.307     0.154     0.000     0.153 …
```
> Tighten up some runtime performance and object allocations

- lib/graphql/tracing/prometheus_tracing/graphql_collector.rb
I noticed that the GraphQLCollector wasn't correctly supporting ![custom_labels](https://github.com/discourse/prometheus_exporter#client-default-labels) for metrics, so I added support.
Same implementation as the `prometheus_exporter` gem's build-in collectors. https://github.com/discourse/prometheus_exporter/blob/master/lib/prometheus_exporter/server/sidekiq_collector.rb#L19-L22
> GraphQLCollector support for prometheus' custom_labels

- guides/errors/execution_errors.md
Current link: https://graphql.github.io/graphql-spec/draft/#example-fce18
New link: https://spec.graphql.org/draft/#example-fce18
The server uses 301 https code but with non-HTTPS scheme for new website.
Update the link to avoid further redirection and keep using HTTPS scheme.
> Update GraphQL spec link which is moved permanently

- lib/graphql/relay/array_connection.rb
I recently extracted a gem called [graphql-page_cursors](https://github.com/artsy/graphql-page_cursors) that extracts Artsy's graphql pagination approach but it relies on all connections exposing first and last methods. Unless I'm missing something, I believe in the case of Relay's Array connection these methods have been marked private by mistake. Any reason to not promote these two up?
> Promote methods to public on relay's array conn

- lib/generators/graphql/object_generator.rb
- spec/integration/rails/generators/graphql/object_generator_spec.rb
This PR is an attempt to fix `object_generator` as described on https://github.com/rmosolgo/graphql-ruby/issues/3244
Given the following schema:
```ruby
create_table "posts", force: :cascade do |t|
t.string "title"
t.text "body"
t.decimal "rating", precision: 2, scale: 1
t.datetime "created_at", precision: 6, null: false
t.datetime "updated_at", precision: 6, null: false
end
```
When we generate `Post` object type with:
```ruby
#> rails g graphql:object post comments:[Comment]
create  app/graphql/types/post_type.rb
```
We get the following `app/graphql/types/post_type.rb` output:
```ruby
module Types
class PostType < Types::BaseObject
field :id, ID, null: false
field :title, String, null: true
field :body, String, null: true
field :rating, Types::DecimalType, null: true
field :created_at, …
```
> Update object generator to use Float for AR decimal columns

- benchmark/run.rb
- lib/graphql/static_validation/rules/fields_will_merge.rb
The Fields Will Merge validation rule seeks to ensure that when multiple field selections with the same response names are encountered during execution, the field and arguments to execute and the resulting value are to be unambiguous ([spec](http://spec.graphql.org/June2018/#sec-Field-Selection-Merging)). There are some examples of this behaviour within [GraphQL Java blog post](https://www.graphql-java.com/blog/deep-dive-merged-fields/).
The runtime of the graphql-ruby algorithm implementation grows exponentially. As a more extreme example, for `n = 5000` repetitions of the same field: `1/2 * (n^2 - n) = 12497500`
As far as I can tell, this is not a perfectly solved problem in other GraphQL server implementations either. For example, [graphql-js reproduction …
> Validation: fields will merge: Faster argument comparison 

- guides/queries/phases_of_execution.md
This step/phase no longer applies when the interpreter is used which is the default now.
I figured it's easier just to remove this entirely instead of adding some note/explanation about it being interpreter dependent?
> Remove rewrite from Phases of execution doc

- guides/type_definitions/field_extensions.md
I was puzzled on how to retrieve the options passed to an `extension`, since the hash passed to `after_resolve` simply did not contain them. I poked around at the test specs and realized that `options` is actually an attribute on the `GraphQL::Schema::FieldExtension`, not a function parameter of `after_resolve`.
> Clarify documentation on using field extension options

- lib/graphql/schema/relay_classic_mutation.rb
- spec/graphql/schema/relay_classic_mutation_spec.rb
We automatically generate a description for the auto-generated input type, but we don't assign that description to the mutation's argument for the new input type.
This updates the code to copy the description from the input type to the argument on the mutation.
This was prompted by the graphql-schema-linter tool saying the argument `mutationName.input` doesn't have a description.
> RelayClassicMutation: set description for auto-generated input argument

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/schema/argument_spec.rb
Fixes #3266
Fixes problems in my initial example (see original issue). I've also tested it with our internal GraphQL API at $DAYJOB and looks OK.
> Handle GraphQL::UnauthorizedError in execution interpreter runtime

- CHANGELOG.md
Backports the changelog entries from the 1.9.x branch so they can be easily discovered on github.
I initially didn't notice that there were changelog entries that only existed on the 1.9.x branch. This makes them discoverable on master.
from https://github.com/rmosolgo/graphql-ruby/issues/3255
> Adds 1.9.19, 1.9.20, and 1.9.21 changelog entries

- CHANGELOG.md
Hi 👋 . I am updating my application and think the breaking `authorized!` method signature changes in the CHANGELOG should link to #2520, instead of #2536.
> Correct PR number in CHANGELOG

- guides/type_definitions/scalars.md
It should also be written in documentation for https://github.com/rmosolgo/graphql-ruby/pull/2150 because it doesn't work if field is defined as `BigInt`, but `GraphQL::Types::BigInt`.
Please check if the explanation of BigInt is suitable.
> Add GraphQL::Types::BigInt to documentation

- guides/fields/validation.md
I was stuck for a bit because I had expected the `message` argument to be an argument on `validates`, rather than inside the hash passed to `required`. This adds a code example to the docs for validators to make usage more obvious.
Also fix the link to the RequiredValidator API Docs.
> Add example code for the `message` argument on validates.

- guides/dataloader/sources.md
Looks like this doc was written when there was a method `Dataloader#for`, at least now there is no such method 🙂
> Replace .for with .with in Dataloader Overview

- lib/graphql/query/variable_validation_error.rb
- spec/graphql/query/variable_validation_error_spec.rb
I encountered this error while attempting to monkey patch `GraphQL::ExecutionError`:
```ruby
require 'graphql/execution_error'
module ExecutionErrorMonkeyPatch
def extensions
{
code: 'EXECUTION_ERROR',
group: 'GRAPHQL',
}.merge(Hash(super))
end
end
GraphQL::ExecutionError.prepend(ExecutionErrorMonkeyPatch)
```
This change should fix the error, but I'm going to use this opportunity to ask how I can accomplish this without monkey patching. Any ideas?
> Pass symbol to respond_to? to fix NameError

- lib/graphql/dataloader/request.rb
- lib/graphql/dataloader/request_all.rb
- lib/graphql/dataloader/source.rb
- spec/graphql/dataloader_spec.rb
Applying the changes suggested in #3317.
We're now rescuing all the errors happening in dataloader sources while fetching records and then re-raise the error later in the GraphQL runtime context where they can be handled by any defined error handlers.
Fixes #3317
> Dataloader source errors

- lib/graphql/schema/find_inherited_value.rb
- lib/graphql/schema/member/has_fields.rb
- spec/support/jazz.rb
Prior this commit the following failed with `SystemStackError`:
```ruby
module WithNameField
def self.prepended(base)
base.field :name, String, null: false
end
end
module NamedEntity
include BaseInterface
prepend WithNameField
end
```
This :point_up: is a reproduction of [some code from the GitLab](https://gitlab.com/gitlab-org/gitlab/-/merge_requests/53629/diffs#note_504260946).
> Allow types to be prepended by a module

- javascript_client/package.json
Right now, If I use the javascript client(specifically ActionCableLink) in a project that uses the javascript graphql dependency at version 15 my bundle will include 2 full versions of the graphql dependency(one at 14 for the graphql-ruby-client dependency and version 15 from the product)
This _SHOULD_ make it so you can use either graphql 14 OR 15 without having duplicate dependencies in your bundle, but I am having trouble testing that.
> Allow using graphql@15 in javascript client

- guides/testing/schema_structure.md
I could not access the URL before the fix, so I found the new URL from your(@rmosolgo ) blog and fixed it.
> Fix the URL of "Tracking Schema Changes with GraphQL-Ruby" used in the schema_structure of guide.

- guides/relay/range_add.md
- guides/schema/sdl.md
- lib/graphql/pagination/connection.rb
- lib/graphql/relay/range_add.rb
Add a short guide and improve support for connections that require modification to the `items` to generate cursors. 
Fixes #3316 
Fixes #2184  (with a pro release)
> Improve RangeAdd and add a guide

- guides/mutations/mutation_authorization.md
I noticed the overridable `load_#{argument}` method from this issue: (https://github.com/rmosolgo/graphql-ruby/issues/1733#issuecomment-510072753) on resolvers wasn't documented and found it useful.
> Document resolvers have an overridable load method

- javascript_client/package.json
- javascript_client/src/subscriptions/AblyLink.ts
- javascript_client/src/subscriptions/ActionCableLink.ts
- javascript_client/src/subscriptions/PusherLink.ts
- javascript_client/src/subscriptions/__tests__/ActionCableLinkTest.ts
- javascript_client/src/subscriptions/__tests__/PusherLinkTest.ts
Quick fix for #3348 
This is just a find/replace to change imports from `@apollo/client` to `@apollo/client/core`. The JS tests pass, but I have not yet done more thorough testing.  My plan is to test this more thoroughly in our application's QA environment tomorrow.
> Remove unintentional dependency on React

- guides/dataloader/sources.md
It is returns always empty because ActiveRecord primary key is being Integer instance by default and ID scalar type is regarded as String instance.
I suppose it needs `String#to_i` method call in this guides.
> Improve active record dataloader example

- lib/graphql/pagination/connection.rb
- lib/graphql/pagination/connections.rb
- lib/graphql/schema/field/connection_extension.rb
- spec/graphql/schema/field/connection_extension_spec.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/3359
(And makes new connections work like old ones)
> Add arguments reference to new connection classes

- guides/javascript_client/apollo_subscriptions.md
We had issues with our subscriptions after following the guide, because the back end is running Action Cable 6 but the front end was running Action Cable 5. The client package [got renamed to `@rails/actioncable`](https://github.com/rails/rails/pull/34905) in Rails 6.
> Suggest @rails/actioncable package for Rails 6

- lib/graphql/pagination/relation_connection.rb
- spec/graphql/pagination/active_record_relation_connection_spec.rb
This PR adds an optimization for an edge case (probably very common code path though) in pagination when querying for `hasNextPage`.
Currently, we get the value of `hasNextPage` by comparing the result of `count` query with limit `first + 1` with `first (query param) + 1`.
We can eliminate the `count` query in cases where nodes are already fetched and there's less than specified in `first` param.
> Remove extra count query for hasNextPage when paginating

- lib/graphql/static_validation/rules/variable_usages_are_allowed.rb
- spec/graphql/static_validation/rules/variable_usages_are_allowed_spec.rb
Oops, this line wasn't updated to use class-based types 😖 . I updated it to an approach that supports both. 
Fixes #3369
> Fix bug in input object argument validation

- javascript_client/package.json
Since the `graphql-ruby-client` package on npm is compiled via tsc, typescript should not be required to run it and therefore I believe `typescript`, and any `@types/**` packages should be a dev dependencies instead of a regular dependencies.  As it it now, it adds an extra 60ish mb your bundle if using `graphql-ruby-client`.
> Move typescript & @types packages to dev dependencies

- guides/queries/ast_analysis.md
This is now the default, it is no longer necessary to `use GraphQL::Analysis::AST` per https://github.com/rmosolgo/graphql-ruby/blob/5c3a8ec6f45319f40cb59f2ffb5961bb1071aa80/lib/graphql/analysis/ast.rb#L18
> Remove suggestion to use deprecated functionality

- guides/errors/error_handling.md
This seems like a typo where `an` was meant.
> Fix typo in errors/error_handling.md guide

- lib/graphql/types/relay/connection_behaviors.rb
- spec/graphql/types/relay/base_connection_spec.rb
Oops, these assignments and reads didn't actually work when the values were `false`, since `false` fails the `||` check.
> Connections: fix logic when boolean attributes are false

- lib/graphql/types/relay/connection_behaviors.rb
- spec/graphql/types/relay/base_connection_spec.rb
This adds the option to set `nodes_field(false)` in your connection classes(base classes) to make this configurable at the class level.
> Add option for connection class level configuration of nodes_field

- lib/graphql/types/relay/edge_behaviors.rb
- spec/graphql/types/relay/base_edge_spec.rb
This adds the option to set `node_nullable(false)` in your edge classes(base edge classes) to make this configurable at the class level.
> add class level config to allow for edge.node to be non-nullable

- lib/graphql/query/validation_pipeline.rb
- lib/graphql/subscriptions/broadcast_analyzer.rb
Updates documentation to reflect `validation_errors` can include `GraphQL::Query::VariableValidationError` due to variable validation. https://github.com/rmosolgo/graphql-ruby/blob/46cae92e6e87be8adade48e5a5004843bab8c48f/lib/graphql/query/validation_pipeline.rb#L80
Additionally removes a `binding.pry` statement that I assume was not meant to be included in `master`.
> Update validation_errors documentation string

- lib/graphql/execution/errors.rb
- lib/graphql/schema.rb
- spec/graphql/execution/errors_spec.rb
- spec/graphql/schema_spec.rb
Both the previous implementation, and, afaict, graphql-errors, use order-dependent algorithms for matching a handler to an error. So, an error subclass might match a superclass, depending on how the underlying data structures are constructed. 
This can cause incompatibilities in migrating from graphql-errors in cases where, previously, handlers were ordered to match specificity, but graphql-ruby builds the underlying structures differently (and matches them differently). This implementation makes the behavior deterministic based on class hierarchy: an error will be matched to the _most specific_ handler registered for it on a schema class (or a parent class of the schema class).
> Errors: reliably pick the most specific handler

- guides/type_definitions/extensions.md
- lib/graphql/types/relay/base_connection.rb
Add to docs of GraphQL::Types::Relay::BaseConnection the new options to customize nullable options and presence of nodes field.
> Add example of nullable options to Types::Relay::BaseConnection

- lib/graphql/pagination/active_record_relation_connection.rb
- lib/graphql/pagination/relation_connection.rb
- spec/graphql/pagination/active_record_relation_connection_spec.rb
Optimizes the ActiveRecordRelationConnection#has_next_page method by using `exists?` instead of a full count statement.
Fixes #3401.
> Optimize ActiveRecordRelationConnection#has_next_page

- lib/graphql/static_validation/rules/argument_literals_are_compatible.rb
- lib/graphql/static_validation/rules/argument_literals_are_compatible_error.rb
- lib/graphql/static_validation/rules/arguments_are_defined.rb
- lib/graphql/static_validation/rules/arguments_are_defined_error.rb
- spec/graphql/static_validation/rules/argument_literals_are_compatible_spec.rb
- spec/graphql/static_validation/rules/arguments_are_defined_spec.rb
Ability to analyze static validation errors that can be caused due to scheme member visibility. Where possible, the analysis would look at the corresponding type definitions of related schema members (argument, enum type, enum value, field, input object, interface, mutation, object, union).
Related to [#3365 - AST Analysis on invalid queries?](https://github.com/rmosolgo/graphql-ruby/issues/3365)
The following errors would be considered for this purpose:
- `GraphQL::StaticValidation::ArgumentLiteralsAreCompatibleError`
- `GraphQL::StaticValidation::ArgumentsAreDefinedError`
- `GraphQL::StaticValidation::FieldsAreDefinedOnTypeError`
- `GraphQL::StaticValidation::FragmentTypesExistError`
- `GraphQL::Query::VariableValidationError`
A couple static validation errors do not currently contain …
> Store additional details in select static validation errors

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/execution/interpreter_spec.rb
Moved the `RawValue` check into `continue_value` so it returns the direct `RawValue` and `HALT`s rather than continuing down the tree.
This allows using partial fragments to return a list, like this:
```ruby
def resolver
query = Something.where(other_thing_id: object.id, status: ['submitted', 'in-progress', 'completed'])
query.map { |something| cache_fragment(something) }
end
```
Fixes #3402
> Fixes returning a RawValue as part of a list

- lib/graphql/execution/errors.rb
- spec/graphql/execution/errors_spec.rb
parent_handler will be assigned the result of find_handler_for method.
https://github.com/rmosolgo/graphql-ruby/blob/ba3a0ceb7b61182270406fb61e98621afadb30ba/lib/graphql/execution/errors.rb#L142
Since the parent_handler expects a hash object with :handler and :class as keys, find_handler_for method must maintain that interface
https://github.com/rmosolgo/graphql-ruby/blob/ba3a0ceb7b61182270406fb61e98621afadb30ba/lib/graphql/execution/errors.rb#L150
> Fix find_handler_for method

- lib/graphql/pagination/connections.rb
- spec/graphql/pagination/connections_spec.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/2840
Derp, `x || y` is not going to work when you _want_ `x`'s value of `nil` 🤦
> Fix when field max_page_size override is nil

- guides/fields/validation.md
According to the docs (in section "Constructor Details"), `allow_null` is the name of the option accepted by all validators not `allow_nil`
(docs: https://graphql-ruby.org/api-doc/1.12.8/GraphQL/Schema/Validator.html)
> Documentation: Change `allow_nil` to the correct `allow_null`

- lib/graphql/schema/member/base_dsl_methods.rb
This ivar is assigned to payload types and input types that are generated for mutations. I don't think this check is useful because the mutation should be running its own authorization at runtime. (And evidently, it's not tested.) I can't think of any case this would be useful for!
(I noticed this while profiling #3429 and thought it could probably be simplified without any downside.)
> Skip checking @mutation during authorization

- lib/graphql/execution/interpreter/runtime.rb
I noticed this overhead while profiling #3429 , that `__typename` would call `.merge_extras`, even though it didn't _use_ extras. We can reduce this overhead. It's possible that this would "break" code for people whose resolvers _require_ `irep_node: nil` to be passed because they use `extras [:irep_node]` even though they use the new runtime. There are two options here: 
- Remove that extra, since it's meaningless in this context 
- Provide a default value in the method that expects it (eg `def resolve(irep_node: nil)`), so that Ruby doesn't :boom: when it isn't provided. 
<details>
<summary> <b>Before</b> benchmark</summary>
<p>
```
~/code/graphql-ruby % stackprof stackprof.out
Mode: cpu(10)
Samples: 97 (0.00% miss rate)
GC: 1 (1.03%) …
```
> Skip extras[:irep_node] in the interpreter

- lib/graphql/subscriptions/action_cable_subscriptions.rb
Fixes #3426
- Call `@serializer.load` only for the `initial_event` for the broadcastable subscriptions
- For non-broadcastable subscriptions cache serialization based on the message, so the same message is only serialized once.
> Subscriptions broadcast: only call deserialization once

- spec/graphql/schema/input_object_spec.rb
- spec/support/jazz.rb
`InspectableInput` has a required argument, so this test was technically
invalid. I discovered this while trying to add validation for default
values. Replace it with a new fully optional input type in this test.
Extracted as the first stand-alone mergeable piece of #3448.
@rmosolgo
> Fix test with invalid default value

- lib/graphql/static_validation/rules/directives_are_defined.rb
- spec/graphql/authorization_spec.rb
@rmosolgo this validation rule wasn't going through the warden so directives were not respecting their visibility settings.
I did this change via github's UI while investigating so I hope it's right because I haven't actually run it :P
cc @lanadz I think this is sufficient to fix your problem.
> Respect directive visibility

- guides/testing/schema_structure.md
- lib/graphql/schema.rb
- spec/graphql/schema_spec.rb
For products where the GraphQL server serves one specific frontend, query dumps that list queries that are typically executed can be helpful. `GraphQL::SchemaComparator` lists changes that are breaking in theory, but using `StaticValidation` and aforementioned query dumps, we can get certainty when it comes to which fields can safely be changed or removed.
This PR updates the existing schema structure testing documentation to describe a simple Rake task that can be used to validate queries directly against a Schema. 
What do you think?
> Update schema testing documentation

- lib/graphql/dataloader.rb
- spec/graphql/dataloader_spec.rb
The dataloader is currently breaking in Ruby 3 when used with sources that have keyword arguments in their constructor. The splat operator in `Dataloader#with` is transforming the keyword arguments into a hash and if we then try it initialize the source with that hash, it crashes. 
This PR fixes that.
MRI supports the new syntax since v2.7 but apparently, that's [not the case for TruffleRuby](https://github.com/oracle/truffleruby/issues/2004#issuecomment-724697244). That's why I'm only using it in Ruby 3. In general, I'm not a fan of having to duplicate code for different ruby versions but I couldn't come up with a better way to make this backward-compatible. 🤔
> Source keyword arguments

- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/schema/object.rb
- spec/graphql/authorization_spec.rb
Fixes #3429 
I can't say I _recommend_ it, but if it's really adding up, this makes it possible (and tested) to override `Schema::Object.authorized_new` and bypass authorization. 
I also investigated an _option_ for disabling built-in authorization at runtime, but I found it put too much complexity in the code (https://github.com/rmosolgo/graphql-ruby/compare/skip-built-in-auth). 
Instead, this approach consolidates tracing and logic in `.authorized_new`, then tests to confirm that it can be overridden (including for `DynamicFields`, which implements `__typename`).
So, with this PR, you could opt out by adding: 
```ruby 
class Types::BaseObject 
def self.authorized_new(obj, ctx)
new(obj, ctx)
end 
end 
```
and 
```ruby 
module Introspection 
class …
```
> Make it so you can opt out of object authorization

- guides/dataloader/overview.md
- lib/graphql/dataloader.rb
- spec/graphql/dataloader_spec.rb
By default, Fibers have their own storage for `Thread#[]`, which is entirely separate from the parent `Thread#[]` storage. Many gems (such as RequestStore, MiniRacer, etc.) rely on thread local vars to keep track of execution context. Since Dataloader relies on `Fiber.new`, gems that rely on thread local storage cannot keep track of what's happening within the GraphQL execution context, causing unexpected behavior for users.
This PR implements the solution from https://github.com/rmosolgo/graphql-ruby/issues/3449#issuecomment-830409933 to copy thread locals vars to fiber local vars when using Dataloader.
see #3366
see #3449
> Copy parent thread local vars to dataloader fiber local vars

- lib/generators/graphql/templates/graphql_controller.erb
This PR intends to improve the error handling in the generated controller, since rescuing all exceptions may cause some issues.
> Rescue StandardError on graphql controller.

- lib/graphql/schema/input_object.rb
- spec/graphql/schema/input_object_spec.rb
It seems that the intent was to allow default input object values to be
specified in snake_case, but we weren't camelCasing them on output which
was leading to issues (in introspection and also schema printing).
See e.g. `string_value` which is actually the default for an argument `stringValue` (because graphql-ruby automatically camelCases argument names at _definition time_), in
https://github.com/rmosolgo/graphql-ruby/blob/173ad1babed18d18b43f9988e5d409db4a3ca3b7/spec/support/jazz.rb#L543
Tweak an existing spec to cover this case (as well as the "enums
specifed as values not names" case), then add the missing call to
camelize.
@rmosolgo I'm not actually 100% sure if I'm interpreting the intention here properly. The code is obviously trivial/straightforward but maybe the intention was …
> Fix introspection of default input objects

- lib/graphql/subscriptions/action_cable_subscriptions.rb
Ruby's behavior around keyword arguments changed in Ruby 3.0. This change updates the action cable subscriptions example to account for those changes.
This was previously found in #3310
> [Documentation] Update action cable subscription setup docs

- lib/graphql/schema/loader.rb
- spec/integration/rails/graphql/schema_spec.rb
fixes #3463
It's _possible_ that this could break some uses, but it's hard to imagine why someone would depend on `.from_introspection` returning a schema that _didn't_ match the one whose JSON was loaded!
> Don't decorate connections when loading from introspection responses

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/schema/directive/query_level_directive_spec.rb
I was working on change which would benefit from having a directive working on a `query` level.
Turns out `graphql-ruby` doesn't support directives on this level.
This PRs fixes this issue.
We are able to reuse the code created for directives which use `resolve` method to alter query execution. Best example would be `Transform` directive. It uses `resolve` method and can be attached to field.
Following it as an example I was able to wrap the entry point of query interpretation (`GraphQL::Execution::Interpreter::Runtime#run_eager`) and wrap it in `resolve_with_directives` method.
`resolve_with_directives` method doesn't have any idea of what type of `node` it is working on, so it works on `field` level for `Transform` and can work on the whole query level as well.
It also supports having …
> Add support of query location for directive

- lib/graphql/static_validation/rules/required_input_object_attributes_are_present.rb
- spec/graphql/schema/directive/query_level_directive_spec.rb
Fixes #3483 
Oops, I suspect that this code path (runtime directive with input object argument) was just _never_ tested. There was no way for this code to lookup an argument definition on a directive.
> Fix validating input object arguments on runtime directives

- spec/support/appoptics.rb
It seemed to be choking on `@@config`: 
```
Error:
GraphQL::Tracing::AppOpticsTracing#test_0001_calls AppOpticsAPM::SDK.trace with names and kvs:
NameError: uninitialized class variable @@config in AppOpticsAPM::Config
Did you mean?  @@config
/home/runner/work/graphql-ruby/graphql-ruby/spec/support/appoptics.rb:30:in `[]'
/home/runner/work/graphql-ruby/graphql-ruby/lib/graphql/tracing/appoptics_tracing.rb:72:in `gql_config'
/home/runner/work/graphql-ruby/graphql-ruby/lib/graphql/tracing/appoptics_tracing.rb:43:in `platform_trace'
/home/runner/work/graphql-ruby/graphql-ruby/lib/graphql/tracing/platform_tracing.rb:25:in `trace'
/home/runner/work/graphql-ruby/graphql-ruby/lib/graphql/tracing.rb:83:in `call_tracers'
/home/runner/work/graphql-ruby/graphql-ruby/lib/graphql/tracing.rb:67:in …
```
> Try using a class ivar instead of a class variable to fix truffleruby build

- lib/graphql/schema/argument.rb
Minor refactor, no logical change. Just something I noticed while poking around argument validation still.
Get rid of has_value by moving the "no value" case to an else in the
original if with an early return.
Diff best viewed with whitespace suppressed.
@rmosolgo this one is actually mergeable :P
> Simplify arg coercion

- lib/graphql/introspection/schema_type.rb
- spec/graphql/introspection/schema_type_spec.rb
https://github.com/rmosolgo/graphql-ruby/pull/3450 updated directives to respect visibility; however, it isn't respected in introspection. This PR fixes visibility for directives in introspection.
**Expected**
Directives returned during introspective respect visibility. 
**Actual**
Directives do not respect visibility and are always returned when defined. 
cc @eapache
> Fix introspection visibility for directives

- guides/schema/class_based_api.md
Hi there! I was wondering if this would be helpful with people trying to track down legacy files for large graphql-ruby repos. I recently wrote this cop and used it to find violating files. Unfortunately I didn't write an autocorrect for it, but thought it could be a good use case here: https://github.com/DmitryTsepelev/rubocop-graphql/pull/39
> Update class_based_api.md with finding legacy members

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/execution/interpreter_spec.rb
Fixes #3504 
TODO: 
-  ~~Investigate marking the parent as dead. Is it in the spec?~~
I didn't check the spec, but I'm going to keep this behavior because: 
- It's how it used to work 
- It makes it _look_ like the first error halts subsequent execution (but I think it actually _continues_ under the hood, but never updates the result, since it's dead)
> Fix some dead marking and detection

- benchmark/run.rb
- graphql.gemspec
- guides/type_definitions/directives.md
- lib/graphql/dataloader.rb
- lib/graphql/dataloader/null_dataloader.rb
- lib/graphql/execution/interpreter/arguments_cache.rb
- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/dataloader_spec.rb
- spec/graphql/schema/directive_spec.rb
Oops, runtime directives on fragment spreads and inline fragments were never actually implemented. 
It turns out to be pretty tricky because it requires these changes: 
- Gathering selections to run should be scoped by AST, _if_ the fragments at hand have runtime directives that affect execution (eg, not `@include(if: true)`) 
- Then, those selections should be run with some degree of isolation. TBD: how much isolation? Anyways, the whole point of `@defer` is to send the whole sub-tree after-the-fact, so it's got to be executed on its own.
- Then, (I guess _depending_?), the sub-tree should be merged back to the main result, so that the result can contain the whole query. (This doesn't apply to `@defer`, but one can imagine a runtime that _doesn't_ split the result tree.) 
Doing this for …
> Runtime directives on fragments

- graphql.gemspec
- lib/graphql/schema/enum.rb
- spec/graphql/schema/enum_spec.rb
To improve debugging situations like https://github.com/rmosolgo/graphql-ruby/issues/3506
> Improve the message when a field returns an invalid enum value

- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/execution/lazy.rb
- spec/graphql/execution/interpreter_spec.rb
Fixes #3511 
The list-with-skips thing didn't work on old versions, either. Maybe it's overkill to include it here 🤔 
The perf looks about the same as master: 
```
1.000  i/100ms
4.822  (± 0.0%) i/s -     25.000  in   5.185050s
```
> Fix lazy skips

- guides/related_projects.md
add [apollo-federation-ruby](https://github.com/gusto/apollo-federation-ruby) to related projects
Signed-off-by: Phil Prasek <prasek@gmail.com>
> add apollo-federation-ruby to related projects

- lib/graphql/argument.rb
- lib/graphql/backtrace.rb
- lib/graphql/base_type.rb
- lib/graphql/directive.rb
- lib/graphql/field.rb
- lib/graphql/language/token.rb
- lib/graphql/non_null_type.rb
- lib/graphql/query/arguments.rb
- lib/graphql/query/context.rb
- lib/graphql/relay/mutation.rb
- lib/graphql/schema.rb
- lib/graphql/schema/argument.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/input_object.rb
- lib/graphql/schema/late_bound_type.rb
- lib/graphql/schema/member/base_dsl_methods.rb
- lib/graphql/schema/resolver/has_payload_type.rb
- lib/graphql/static_validation/rules/no_definitions_are_present.rb
I think this is a small optimization to the to_h call. I noticed it while stumbling through source code for a project I am working on. `#merge!` will avoid creating extra hash objects. I think this would be faster if the argument type had a lot of fields / nested fields on it.
> ⚡️ Small optimization to GraphQL::Schema::InputObject#to_h

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/execution/interpreter_spec.rb
fixes https://github.com/rmosolgo/graphql-ruby/issues/3536
Oops, there was some suspicious bits in the new runtime code. They were a misunderstanding of _this_ old code:
https://github.com/rmosolgo/graphql-ruby/blob/a9a7373a1fbf91cbcc10a1385cc4cf8c2af8254d/lib/graphql/execution/interpreter/runtime.rb#L587-L591
In that context: 
- `path` includes the names of "parent" fields ("above" this one) and _this_ field name
- `propagate_path` removes the _field name_ from the path, marking the result object as dead
But I migrated it to this: 
https://github.com/rmosolgo/graphql-ruby/blob/eb58d269ffac694ecbc2147e238d61d54c5fd0e2/lib/graphql/execution/interpreter/runtime.rb#L473-L476
My misunderstanding was about how the field name (`result_name` above) fits in. In fact, `selection_result` in the new …
> Fix parent dead marking

- lib/graphql/backtrace/table.rb
- lib/graphql/execution/interpreter.rb
- lib/graphql/execution/interpreter/resolve.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/schema/directive/transform.rb
- spec/graphql/execution/interpreter_spec.rb
- spec/graphql/schema/directive_spec.rb
This is not an awesome implementation, but it addresses the incompatibility described in #3516 
It adds a slow deep-copy step to all responses. I'm not sure how else to solve the problem: one data structure is used to collect values at runtime, while another value must be returned at the end. 
A couple other approaches I considered very briefly: 
- Using refinements instead of extending built-ins. I think it _would_ actually work here, since all the uses are in the same scope. But I have doubts about the performance, even on CRuby. And I don't think JRuby supports them at all, IIRC. 
- Each GraphQL* result class keeps another "plain" data structure in an instance variable, and replays all modifications onto it. It seems error-prone and hard to maintain. The other problem is, the "plain" …
> Transform GraphQL-related objects to plain Hashes and Arrays before returning them

- lib/graphql/argument.rb
- lib/graphql/backtrace.rb
- lib/graphql/base_type.rb
- lib/graphql/directive.rb
- lib/graphql/field.rb
- lib/graphql/language/token.rb
- lib/graphql/non_null_type.rb
- lib/graphql/query/arguments.rb
- lib/graphql/query/context.rb
- lib/graphql/relay/mutation.rb
- lib/graphql/schema.rb
- lib/graphql/schema/argument.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/input_object.rb
- lib/graphql/schema/late_bound_type.rb
- lib/graphql/schema/member/base_dsl_methods.rb
- lib/graphql/schema/resolver/has_payload_type.rb
- lib/graphql/static_validation/rules/no_definitions_are_present.rb
Ugh! `alias_method :to_hash, :to_h` made it so that if you override `def to_h`, it isn't picked up by `.to_hash`.
Since obviously I don't understand the difference between `alias_method` and `alias`, I'm reverting all these changes from #3524
> Revert alias changes

- lib/graphql/backtrace/tracer.rb
- spec/graphql/backtrace_spec.rb
Fixes #3538
Honestly, I don't know why integers were getting kicked out here. It was added back in https://github.com/rmosolgo/graphql-ruby/pull/3275/files#diff-7ba264b85d9b3b0cf7e63d1f6d7af371e94b5eb43042de2e835990282456f1baR26, when I updated Backtrace to work with the interpreter. 
Why would it just now have started failing?
cc @eapache
> Backtrace array fix

- lib/graphql/schema/printer.rb
- spec/graphql/language/document_from_schema_definition_spec.rb
- spec/graphql/language/parser_spec.rb
- spec/graphql/rake_task_spec.rb
- spec/graphql/schema/build_from_definition_spec.rb
- spec/graphql/schema/loader_spec.rb
- spec/graphql/schema/printer_spec.rb
- spec/integration/rails/graphql/schema_spec.rb
Fixes #3528 
As described there, the output of the rake task and the output of `MySchema.to_definition` should really _match_. And as described in #3480 , the file created by the rake task should really include a final newline. 
Given those two, `.to_definition` should also include a newline. People might have to add workarounds to accommodate this in their existing tooling, but on the whole, it sure seems like the _right_ thing to me.
> Include a final newline in Schema.to_definition output

- lib/graphql/query.rb
- lib/graphql/schema.rb
- spec/graphql/language/sanitized_printer_spec.rb
[It is recommended that the redact condition be customized in a subclass that inherits from SanitizedPrinter](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/language/sanitized_printer.rb#L62-L63).
However, we cannot use custom SanitizedPrinter in Query#sanitized_query_string because it does not provide a way to set a custom SanitizedPrinter in the schema.
to use a custom SanitizedPrinter, you need to create a Query object, which is very inconvenient.
This PullRequest implements a way to set a custom SanitizedPrinter from the schema so that custom SanitizedPrinter can be used with Query#sanitized_query_string.
> configure a custom printer from the schema

- lib/graphql/schema/member/build_type.rb
- spec/graphql/schema/member/build_type_spec.rb
This PR updates the behaviour of `camelize` method when `_` itself was provided.
It adds an additional check to return a string as it is when the string is `_`, while it used to give "undefined method `downcase' for nil:NilClass" in the existing code.
I also added a test for this method in [build_type_spec.rb](https://github.com/rmosolgo/graphql-ruby/blob/edd51927f71424bfeff54406ff29dbe0c2d01869/spec/graphql/schema/member/build_type_spec.rb), with a minimal set of conditional cases.
Before:
```$ bundle exec rake test TEST=spec/graphql/schema/member/build_type_spec.rb
.............E.
Finished tests in 0.002122s, 7068.8030 tests/s, 6597.5495 assertions/s.
Error:
GraphQL::Schema::Member::BuildType::.to_type_name::.camelize#test_0002_keeps an underscore
itself intact:
NoMethodError: undefined …
```
> When an underscore itself is passed, `camelize` method returns a string unchanged without any error

- lib/graphql/analysis/ast/field_usage.rb
- spec/graphql/analysis/ast/field_usage_spec.rb
- spec/support/dummy/schema.rb
Added tracking for deprecated arguments. I didn't add tracking for all arguments as my app doesn't need it, but happy to add that if you prefer!
> track deprecated arguments alongside deprecated fields

- guides/subscriptions/multi_tenant.md
- guides/subscriptions/overview.md
- lib/graphql/subscriptions/action_cable_subscriptions.rb
- spec/graphql/subscriptions/action_cable_subscriptions_spec.rb
This came up in https://github.com/rmosolgo/graphql-ruby/issues/2444 and again, recently, by email, so I thought I'd explore proper support for it. 
Here, I've added a test case for multi-tenant subscription updates with ActionCable and a brief guide describing the considerations.
> Add multi-tenant support for subscriptions

- guides/pagination/using_connections.md
Not sure how you'd prefer the wording, but would like a call out that specifies that the database query is also limited, as I (and presumably others) had assumed that it would just limit the returned data but still hit the database for a large list of items.
Is related to #3576
> Update wording of the `max_page_size` option to include database limit

- lib/graphql.rb
Refinements have a very significant performance overhead. The simple fact of refining a method, even if the refinement is never used will make calls to that method 40% slower.
On rarely called methods in doesn't matter that much, but graphql-ruby refine some common String methods, so any project including the gem suffer from a significant performance penalty.
See this benchmark for more details: https://gist.github.com/casperisfine/1c46f05cccfa945cd156f445f0d3d6fa
> Avoid refining String when not necessary

- lib/graphql/schema/subscription.rb
- lib/graphql/subscriptions/event.rb
- spec/graphql/subscriptions_spec.rb
> Support server-filtered dynamic streams for subscription

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/execution/interpreter_spec.rb
This puts the behavior _back_ to how it was in 1.12.10
Also, stop resolving lists when they become dead.
Fixes https://github.com/rmosolgo/graphql-ruby/issues/3504#issuecomment-908825696
> Fix non-null connection fields to only return one non-null error

- guides/authorization/visibility.md
Ensure specific named arguments of interest are placed before `**kwargs` catchall
> Update position of keyword argument in doc example

- .github/workflows/ci.yaml
- guides/dataloader/testing.md
- lib/graphql/dataloader.rb
- spec/graphql/dataloader_spec.rb
We were talking about this at work, just posting it here in case anyone else is curious. 
Interestingly, @mclark also identified the fact that Dataloader might be useful _without_ Fibers in cases when the loading is determinate (ie, in Ruby source code, not in dynamic, client-provided GraphQL queries). I'll add that to this example sometime, too.
> Sketch out a general-use dataloader API

- lib/graphql/schema/argument.rb
Instead of assuming any object responding to `.key?` is a hash, use `.has_key?` instead, which is less likely to conflict with some application object method name.
Fixes #3604
> Properly detect input objects for authorization

- lib/graphql/define/instance_definable.rb
When dynamically generating a schema via `GraphQL::Schema.define` while running Ruby 3, we encountered an error like thiis
```
12:16:29 GraphQL::Schema::InvalidTypeError: Query is invalid: field "api_user_coupon" arguments must be a hash of {String => GraphQL::Argument}, not a NilClass (nil)
12:16:29 /mnt/vol/tmp/bundler/pull-request/ruby/3.0.0/gems/graphql-1.12.12/lib/graphql/schema/traversal.rb:223:in `validate_type'
12:16:29 /mnt/vol/tmp/bundler/pull-request/ruby/3.0.0/gems/graphql-1.12.12/lib/graphql/schema/traversal.rb:142:in `visit'
12:16:29 /mnt/vol/tmp/bundler/pull-request/ruby/3.0.0/gems/graphql-1.12.12/lib/graphql/schema/traversal.rb:128:in `block in visit'
12:16:29 /mnt/vol/tmp/bundler/pull-request/ruby/3.0.0/gems/graphql-1.12.12/lib/graphql/schema/traversal.rb:128:in `each' …
```
> Ruby 3: Don't pass empty hash as kwargs

- lib/graphql/schema/subscription.rb
> #&nbsp;Default implementation returns the root object.
> ...
> def subscribe
- `Subscription#update` returns root object by default
- `Subscription#subscribe` returns :no_response by default
Therefore this line seems to be a typo.
> Fix typo for Subscription#subscribe documentation

- guides/schema/object_identification.md
I'm doing this in one application of mine and it's been working great. Comes out-of-the-box with Rails >= 4.2.
It's not encrypted, but one could use the signed version if that's desirable (much longer string though):
```
> signed = object.to_sgid.to_param
"BAh7CEkiCGdpZAY6BkVUSSIWR2lkOi8vYXBpL0FkbWluLzQGOwBUSSIMcHVycG9zZQY7AFRJIgxkZWZhdWx0BjsAVEkiD2V4cGlyZXNfYXQGOwBUSSIdMjAyMS0xMC0yOVQxNjo0OTozNy45ODdaBjsAVA==--e37d30ef25344e027994dbc198598e159b9b9646"
> GlobalID::Locator.locate_signed(signed)
```
> Suggest using rails/globalid for object identification

- guides/_layouts/default.html
This is how the guide looks in Chrome:
Bold text is blurry and not really bold, because the right font is missing:
And this is how it looks when all font weights are loaded:
> Add missing font-weight to guides

- lib/graphql/query.rb
- spec/graphql/query_spec.rb
This commit aims to solve the issue #3619 - providing a query argument of an incorrect type would yield a `NoMethodError` due to the incorrect type argument to be allowed through to the lexer (which assumes it to be a string).
As this parameter is, more often than not, feed from an external source (e.g. a web request), this commit assumes a more defensive approach and ensures that when the `GraphQL::Query` is initialised, the query string is indeed of the correct type (a string).
As discussed in the issue, an `ArgumentError` is raised when a type mismatch is identified.
----
I've actually just received an error notification due to this issue. I think I'll end up addressing it at a different layer (perform the input validation/coercion at the controller layer). Regardless I tried to make …
> Assert that query is a string on GraphQL::Query#initialize

- lib/graphql/schema/argument.rb
- lib/graphql/schema/input_object.rb
- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/schema/resolver.rb
- spec/graphql/schema/argument_spec.rb
- spec/graphql/schema/input_object_spec.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/3680
Fixes #3685 
TODO:
> Call def self.load_.... on Input objects to load arguments, separate loading from authorization

- guides/subscriptions/subscription_classes.md
- lib/graphql/schema/subscription.rb
- spec/graphql/schema/subscription_spec.rb
- spec/graphql/subscriptions_spec.rb
The _value_ is still `:no_update`, for compatibility, but using a constant will make typos more obvious.
fixes #3615
Only merge this _right_ before releasing the gem, so that the docs don't recommend the wrong thing.
> Recommend NO_UPDATE instead of :no_update to skip subscription updates

- lib/graphql/query/validation_pipeline.rb
- spec/graphql/query_spec.rb
This is a follow-up to https://github.com/rmosolgo/graphql-ruby/pull/3675
That PR introduced the ability to limit static validation errors.
Unfortunately, I forgot to hook it up to the validation pipeline 😿 
Anyway, this follow-up PR does just that.
> use validation_max_errors in validation pipeline

- lib/graphql/schema/subscription.rb
- lib/graphql/subscriptions.rb
- lib/graphql/subscriptions/event.rb
- spec/dummy/app/channels/graphql_channel.rb
- spec/graphql/schema/subscription_spec.rb
This is a _breaking change_ for graphql 1.13.0; to get the old behavior, add `optional: true` to any `subscription_scope ...` configurations in your schema. 
Now, if a Subscription class has a `subscription_scope`, it will be required for initial subscribe and subsequent updates, unless it's configured with `optional: true` (which falls back to the previous behavior, where `nil` is a valid subscription scope value).
Fixes #3209
> Require scope for subscription classes when  is configured

- lib/graphql/static_validation/error.rb
- lib/graphql/static_validation/rules/fields_will_merge.rb
- lib/graphql/static_validation/rules/fields_will_merge_error.rb
- lib/graphql/static_validation/validation_context.rb
- spec/graphql/static_validation/rules/fields_will_merge_spec.rb
Following the merge of https://github.com/rmosolgo/graphql-ruby/pull/3690, we have a good general solution for excessive validation error messages.
However, we may still want to improve the field-conflict error messages, since these are confusing, and include every pair-wise combination of conflicting values. A simpler representation is a list of all conflicting values, as implemented here.
Short-circuiting behavior is preserved, honoring the `validation_max_errors` configuration.
> Improve field conflict error messages

- javascript_client/src/__tests__/__snapshots__/syncTest.ts.snap
- javascript_client/src/sync/__tests__/removeClientFieldsTest.ts
- javascript_client/src/sync/removeClientFields.ts
I considered using `removeDirectivesFromDocument` from Apollo Client (https://github.com/apollographql/apollo-client/blob/d470c964db46728d8a5dfc63990859c550fa1656/src/utilities/graphql/transform.ts#L94), but I found that: 
- It didn't remove empty fragment definitions (apparently Apollo _does_ somewhere along the line though, because they're removed by the time they go over the wire) 
- It has unfixed bugs: https://github.com/apollographql/apollo-client/pull/6892 
So I rolled my own based on the examples there.
> Make sure documents are valid after removing client fields

- lib/graphql/schema/enum.rb
- lib/graphql/schema/enum_value.rb
- spec/graphql/schema/dynamic_members_spec.rb
- spec/graphql/schema/enum_spec.rb
This method isn't needed for runtime or even building schema caches, which I guess is why I missed it before. But it's handy for working with the schema.
> Add a method to access all enum values without filtering

- guides/subscriptions/subscription_type.md
Looks like we don't need it anymore—everyone is on the Interpreter nowdays and this `extend` is added by default and we [warn](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/subscriptions/subscription_root.rb#L9) when user does it.
> Remove extend GraphQL::Subscriptions::SubscriptionRoot from docs

- lib/graphql/subscriptions/action_cable_subscriptions.rb
- spec/graphql/subscriptions/action_cable_subscriptions_spec.rb
Looks like this may be the fix for #3189 and similar empty subscription updates I'm seeing in my application.
Applies the same pattern to `ActionCableSubscriptions` as `Subscriptions`, which just checks if `execute_update` returns `nil` and skips the delivery. See https://github.com/rmosolgo/graphql-ruby/blob/bace1e4027900fc8779a5c2fd393ff6456046cea/lib/graphql/subscriptions.rb#L141-L146
Given this is a subclass, I'm guessing there's a better way to rely on the superclass behavior and ensure all subclasses inherit this important feature. Open to suggestions.
> Support NO_UPDATE in ActionCable subscriptions

- lib/graphql/subscriptions/action_cable_subscriptions.rb
- spec/dummy/app/assets/javascripts/application.js
- spec/dummy/app/channels/graphql_channel.rb
- spec/dummy/app/views/pages/show.html
- spec/dummy/test/system/action_cable_subscription_test.rb
The server should send `more: false` when the server closes a connection. It turns out this is already _expected_ by the client code: 
https://github.com/rmosolgo/graphql-ruby/blob/e936d7110f54d64bfa5de996736f3afff3af7eec/javascript_client/src/subscriptions/ActionCableLink.ts#L53-L55
https://github.com/rmosolgo/graphql-ruby/blob/e936d7110f54d64bfa5de996736f3afff3af7eec/javascript_client/src/subscriptions/ActionCableSubscriber.ts#L61-L63
https://github.com/rmosolgo/graphql-ruby/blob/e936d7110f54d64bfa5de996736f3afff3af7eec/javascript_client/src/subscriptions/createActionCableHandler.ts#L57-L60
It was just never sent. Now it is :+1: 
fixes #3650
> ActionCable subscriptions: close channel when unsubscribing from server

- guides/fields/introduction.md
The null: keyword isn't required for fields, as evidenced by the examples below.
> Introduction: remove "required" when describing "null:" keyword

- lib/graphql/language/block_string.rb
- lib/graphql/language/lexer.rb
- spec/graphql/schema/build_from_definition_spec.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/3740
When rebuilding an empty trimmed whitespace string, such as `"\n"`, which can occur when a type has an empty description, a frozen string is returned, causing in place substitution with gsub to fail when replacing escaped characters in place at [GraphQL::Language::Lexer.replace_escaped_characters_in_place](https://github.com/rmosolgo/graphql-ruby/blob/489267e0fb63651bef0579dd1ced839a9a6c2ebb/lib/graphql/language/lexer.rb#L1440).
> fix(Lexer): resolved issue when rebuilding trimmed whitespace string

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/schema/input_object_spec.rb
Previously, GraphQL::ExecutionErrors could be given to `rescue_from ...` handlers in some cases. But this isn't quite right -- those are supposed to be handled by the library. So don't pass them along that way. 
Fixes #3746
> Rescue execution errors from lazies before calling schema error handlers

- lib/graphql/base_type.rb
- lib/graphql/boolean_type.rb
- lib/graphql/directive/deprecated_directive.rb
- lib/graphql/directive/include_directive.rb
- lib/graphql/directive/skip_directive.rb
- lib/graphql/float_type.rb
- lib/graphql/id_type.rb
- lib/graphql/int_type.rb
- lib/graphql/relay/global_id_resolve.rb
- lib/graphql/relay/page_info.rb
- lib/graphql/schema.rb
- lib/graphql/schema/input_object.rb
- lib/graphql/schema/interface.rb
- lib/graphql/schema/list.rb
- lib/graphql/schema/member/cached_graphql_definition.rb
- lib/graphql/schema/non_null.rb
- lib/graphql/schema/traversal.rb
- lib/graphql/string_type.rb
- spec/graphql/execution/typecast_spec.rb
- spec/graphql/schema/field_spec.rb
- spec/graphql/schema/input_object_spec.rb
- spec/graphql/schema/interface_spec.rb
- spec/graphql/schema/loader_spec.rb
- spec/graphql/schema/member/accepts_definition_spec.rb
- spec/graphql/schema/relay_classic_mutation_spec.rb
- spec/support/error_bubbling_helpers.rb
All the features that use this were _already_ deprecated (I think!) but there is some user code that calls this directly, so warn people that it's going away. 
Fixes #3736
> Deprecate .graphql_definition

- lib/graphql/types/relay/connection_behaviors.rb
- lib/graphql/types/relay/edge_behaviors.rb
- spec/graphql/types/relay/base_connection_spec.rb
- spec/graphql/types/relay/base_edge_spec.rb
Accept `edge_type(... field_options: { ... })` and `node_type(..., field_options: { ... })` for customizing those fields. 
The `edge_type(field_options:)` argument is given to _both_ `field :edges` and `field :nodes`. 
Fixes #3417
> Add field_options for edges, node, and nodes fields

- lib/graphql/schema/field.rb
- spec/graphql/analysis/ast/query_complexity_spec.rb
Oops, we were previously adding an extra multiple of the max page size for the `edges { ... }` selection and `nodes { ... }` selection. But those should each count for _1_, not the page size. 
Part of #3755
> Don't multiply count edges and nodes fields by page size

- Rakefile
- benchmark/run.rb
- lib/graphql/language/nodes.rb
- lib/graphql/static_validation/rules/fields_will_merge.rb
- lib/graphql/static_validation/rules/required_arguments_are_present.rb
Oops, I forgot to check the performance of #3698, and it seems like it has increased the memory consumption of validation a good bit. I'm investigating some improvements to it, and the old code, too. Once I get them settled for 1.12.x, I'll work them into 1.13.x, too. 
cc @such 
TODO: 
For the most extreme case benchmark, this makes a huge difference: 
```diff
- Total allocated: 1003971576 bytes (25070165 objects)
+ Total allocated: 1091296 bytes (20160 objects)
Total retained:  0 bytes (0 objects)
```
(Yes, that's ~1000x _less_)
> Validation performance improvements

- guides/type_definitions/field_extensions.md
- lib/graphql/schema/field.rb
- lib/graphql/schema/field/connection_extension.rb
- lib/graphql/schema/field_extension.rb
- spec/graphql/introspection/type_type_spec.rb
- spec/graphql/schema/field/connection_extension_spec.rb
- spec/graphql/schema/field_extension_spec.rb
This would allow field extensions to define arguments on fields _without_ overriding something from the field's definition block. 
cc @cocoahero 
TODO:
> Add an after-define hook to field extensions

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/execution/interpreter_spec.rb
Oops, this code path passes a plain hash instead of the `Interpreter::Arguments` instance. It ends up getting assigned to `context[:current_arguments]` which fails down the line.
TODO:
> Pass arguments object instead of plain Hash

- lib/graphql/schema/field.rb
- lib/graphql/schema/relay_classic_mutation.rb
- lib/graphql/schema/resolver.rb
- spec/graphql/schema/relay_classic_mutation_spec.rb
Oops -- #3738 didn't work right on loaded objects. With resolver instances, it actually introduced a double-pass on `#authorized?` -- once _before_ the object was loaded, and once after it. But I didn't have a test that caught that. (It blew up with GraphQL-Pro's pundit integration because the integration would fail to find a policy for `nil` -- the argument value _before_ loading.)
> Fix auth of loaded resolver args

- lib/graphql/schema/argument.rb
- lib/graphql/schema/input_object.rb
- spec/graphql/schema/input_object_spec.rb
Fixes #2633 
Previously, no `authorized?` methods were ever called on input objects. This meant, for input objects that used `def prepare`, there was no way to authorize the value (except inside `def prepare`, which was probably fine). But now there's a proper way to do it.
> Add InputObject.authorized?, call it

- guides/type_definitions/field_extensions.md
- lib/graphql/schema/field.rb
- lib/graphql/schema/field_extension.rb
- spec/graphql/schema/field_extension_spec.rb
Fixes #3351 
Now, extensions can configure `extras [...]` which will be added to arguments, but removed before resolving.
> Add FieldExtension.extras

- lib/graphql/language/document_from_schema_definition.rb
- spec/graphql/schema/printer_spec.rb
Fixed an error when you're trying to generate schema with inputs with arguments names that can be camelized. 
I assume my fix is the proper method, as the default value expects the original keyword when writing the code.
The bottom example will fail when generating schema. 
```ruby
class ExampleInput < Types::BaseInputObject
argument :updated_at, String, required: false
end
class ExampleQuery < BaseQuery
argument :order_by, ExampleInput, required: false, default_value: { updated_at: 'DESC' }
end
```
> Fix: schema generation with camelized default value of input arguments

- lib/graphql/tracing/active_support_notifications_tracing.rb
- lib/graphql/tracing/notifications_tracing.rb
- spec/graphql/tracing/notifications_tracing_spec.rb
It would be helpful to be able to use `dry-monitor` for a notifications engine for non-Rails apps. This PR adds support for that by abstracting out a new `NotificationsTracer` interface for that.
```ruby
$notifications_engine = Dry::Monitor::Notifications.new(:my_app)
tracer(GraphQL::Tracing::NotificationsTracing.new($notifications_engine))
end
```
I took care to make it so `ActiveSupportNotificationsTracing` uses this tracer under the hood in a backwards compatible way, but let me know if you would like me to change it at all.
> Abstract out notifications engine for tracing

- guides/fields/resolvers.md
There are a couple of errors in the code example that resulted in it not working. (field_options needs to be expanded apparently, and the blocks are evaluated in the instance context, not passing in a `self`). This resolves the issues.
> Fix custom field code example errors

- guides/schema/object_identification.md
Renamed the `id` parameter to `encoded_id_with_hint` in the `object_from_id` method. Previously, the method referenced an undefined variable (`encoded_id_with_hint`) that was supposed to be the global id that gets passed into `object_from_id`.
> [Docs] Correction in object_from_id

- lib/graphql/pagination/active_record_relation_connection.rb
- lib/graphql/pagination/relation_connection.rb
- spec/graphql/pagination/active_record_relation_connection_spec.rb
- spec/support/connection_assertions.rb
Fixes #3775 
If the connection receives an already-loaded relation and can satisfy the query _without_ running another query, then don't run another query. Instead, choose ActiveRecord methods that will use already-loaded objects.
TODO: 
cc @crpahl
> Don't run a duplicate query when paginating already-loaded relations

- lib/graphql/types/relay/node_behaviors.rb
- spec/graphql/execution/interpreter_spec.rb
- spec/graphql/types/relay/node_behaviors_spec.rb
Oops, the docs say that implementing this interface should add a field with this behavior, but it doesn't actually work this way. I think it'd be a nice improvement.
> Make Relay::Node add an id field that calls the schema hook

- lib/graphql/schema/non_null.rb
- lib/graphql/static_validation/rules/variable_usages_are_allowed.rb
- spec/graphql/schema/input_object_spec.rb
- spec/graphql/static_validation/rules/variable_usages_are_allowed_spec.rb
fixes #3793
Weirdly, `NonNull#validate_input` didn't work because that's called on _variable_ definitions with their values. But in this case, I specifically have to check a variable-provided value against the an argument type. Static validation won't work because, statically, we don't know if the variable value will be `null` or not. So it has to be dynamic in some way. 
Maybe it could have been added to `Query::Variables` -- that's where `.validate_input` is called -- but there aren't any references to variable _usages_ there, so there's no easy way to get the argument types to validate against.
> Accept nullable variables for non-null arguments when the argument has a default value

- benchmark/run.rb
- lib/graphql/execution/interpreter/arguments_cache.rb
- lib/graphql/execution/interpreter/runtime.rb
Basically, there was a legacy-style usage of `arguments_cache.fetch(...)` that had to hit the data loader directly. But it wasn't smart about when that hit could be skipped. That method still isn't great, but it reduces the hits to dataloader. 
In my benchmark, there's still an issue where `args[:if]` is allocating an array, seemingly inside `def_delegators` from the Ruby standard library, because if I replace it with `args.keyword_arguments[:if]`, it doesn't record that allocation anymore. This is a separate issue... 
Fixes #3833 
cc @gopeter -- could you give this commit a try on your project and tell me how the performance looks?
> Fix directive arguments performance issue

- lib/graphql/tracing/data_dog_tracing.rb
- lib/graphql/tracing/platform_tracing.rb
- spec/graphql/tracing/data_dog_tracing_spec.rb
- spec/graphql/tracing/new_relic_tracing_spec.rb
- spec/support/datadog.rb
Enable a developer to provide the platform trace API a fallback name to
use when a query name is not provided.
Note that this is a *fallback*, the query name is preferred when
available.
Testing is limited to Datadog and New Relic.
Support is within any tracer that delegates to
`PlatformTracing#transaction_name`, which appears to include AppSignal
and Scout. Not sure if that is exhaustive.
Fixes #3769
> Platform Tracing: fallback transaction name

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/dataloader_spec.rb
We can get better batching if each item in a list is handled in its own job. 
TODO: 
The overhead here is one `Proc` per non-scalar/non-enum list item. Previously, list items were run in the surrounding dataloader job, which meant that each list item could cause the whole list to halt. Now, each item in a list (when the list returns Union, Interface, or Object type) spins up a new dataloader job, so it runs in its own fiber.
Fixes #3840
> Dataloader: Batch across list items

- .github/workflows/ci.yaml
I'm tired of always seeing failed builds, and it seems like this is the flakiest one. Either Rails master is failing (as it did for a while when Rails generators wouldn't generate for `HEAD`, even when the invoked `rails ...` command was from `HEAD`) or TruffleRuby is failing (as it is currently because it's looking up `require "digest"` wrong, or something like that: https://github.com/oracle/truffleruby/issues/2511). 
If anyone wants to re-add a passing TruffleRuby build to this project (not truffleruby-head, not rails master), I'll try maintaining it again, but sheesh... 
cc @gogainda, in case you'd rather get this build _passing_ somehow ... (I can't figure out how to do it!)
> Remove TruffleRuby from CI

- lib/graphql/analysis/ast/visitor.rb
- spec/graphql/analysis/ast_spec.rb
On 1.12, this would actually _find_ `article` (an instance of BaseField), then visit `title`, but set `nil` for `visitor.field_definition`. After this change, it assigns `nil` in both cases, and I _think_ this is right -- `article` is hidden. It's visited, for compatibility's sake if nothing else, but the definition is nil, and same with `title`. 
I think the change that caused the error is here: 
https://github.com/rmosolgo/graphql-ruby/commit/c4f89186f59708b39ed5ae11c17e6f2d5c97c382#diff-ca02a7189be9dc9f1c0d328028ba139f8be8da82eca96bbfccd3c098b5ad03f7R1196
Previously, `Schema.get_field(type, field_name)` didn't run any visibility checks, so it would return `Query.article` without hesitation. (TODO: Why did it return `nil` for `title`?) Now, although it finds `Query.article`, it returns …
> Handle missing fields during Analysis

- lib/graphql/rubocop/graphql/default_required_true.rb
- spec/fixtures/cop/required_true.rb
- spec/fixtures/cop/required_true_corrected.rb
- spec/graphql/analysis/ast_spec.rb
- spec/graphql/cop/default_required_true_spec.rb
- spec/graphql/schema/field_extension_spec.rb
- spec/graphql/schema/field_spec.rb
- spec/support/rubocop_test_helpers.rb
Oops, the cop didn't handle the `yield(field_defn)` possibility for `field_defn.argument(..., required: true)`. Also, clean up test output.
> Find required: true when a field instance is used

- CHANGELOG.md
- spec/graphql/schema/argument_spec.rb
As discovered in #3839, the new visibility behavior could break the flow for argument default values, but it's probably the _right_ thing to do. So I've added some specs for the behavior and updated the changelog.
> Add tests for default values of non-visible arguments

- lib/graphql/types/iso_8601_date_time.rb
- spec/graphql/types/iso_8601_date_time_spec.rb
Fixes #3827 
If anyone finds this because they _want_ the old zeroing-out behavior, I recommend adding a new scalar based on the previous code: 
https://github.com/rmosolgo/graphql-ruby/blob/b4f1f428dc7f6124e4a5205962c151471dbc9388/lib/graphql/types/iso_8601_date_time.rb#L53-L63
For example:
```ruby 
class Types::Iso8691DateTimeWithZeroing < GraphQL::Types::ISO8691DateTime 
graphql_name "ISO8691DateTime"
def self.coerce_input(str_value, _ctx) 
Time.iso8601(str_value) 
rescue ArgumentError, TypeError 
begin 
Date.iso8601(str_value).to_time 
rescue ArgumentError, TypeError 
nil 
end 
end 
end 
```
> Don't accept datetime inputs with partial time parts

- lib/graphql/introspection.rb
- spec/graphql/schema/loader_spec.rb
Oops -- I added new fields in #3854 but forgot about how they can have downstream effects. Don't add them by default. 
Fixes #3873
> Make the introspection query backwards-compatible by default

- lib/graphql/schema/directive.rb
- spec/graphql/schema/build_from_definition_spec.rb
Oops, this just didn't work _at all_, but I guess nobody (except @mattpage) has noticed yet. 
I'm going to backport this to 1.13.x and 1.12.x, too
> SDL: Fix having two directives on the same type

- lib/graphql/schema/input_object.rb
- spec/graphql/schema/input_object_spec.rb
Fixes #3878 , but re-breaks #3604 
I think there's a better fix for #3604 now that InputObjects have their own `def self.authorized?(obj, value, ctx)` methods now: 
```ruby 
def self.authorized?(obj, value, ctx)
true # skip auth for this input object -- since it's covered by `prepare`
end 
```
> Input objects: authorize anything that responds to .key?

- lib/graphql/schema/input_object.rb
- spec/graphql/schema/input_object_spec.rb
Backport of #3902, fixing #3878 on 1.13.x
> [1.13.x] Input objects: authorize anything that responds to .key?

- lib/graphql/query.rb
- lib/graphql/query/validation_pipeline.rb
- spec/graphql/query_spec.rb
~~This PR skips static validation for a GraphQL operation by setting `query.skip_static_validation = true`. This allows us to skip static validation for repeated operations for which this result can be cached.~~
~~Variable validation runs irrespective whether or not static validation is skipped.~~
This PR allows a GraphQL operation to skip static validation through `query.validate` property. Though the property was available earlier, it did not work as expected. Now the dependency is inverted so that `ValidationPipeline` fetches it from `Query` class.
cc @haruska
> Provide argument to skip static validation

- lib/graphql/dataloader/null_dataloader.rb
- spec/graphql/dataloader/source_spec.rb
Without this, it gave the "circular dependency" error message instead. Reported on Slack.
> Raise a more helpful error when a Dataloader::Source is used without a Dataloader

- lib/graphql/schema/field.rb
[The Resolver docs](https://graphql-ruby.org/fields/resolvers.html#nesting-resolvers-of-the-same-type) mentions the issue of cyclical loading issues and says they can case the error `Failed to build return type for Task.tasks from nil: Unexpected type input: (NilClass)`
However, the error I get when I cause this (Ruby 3.0.3, Zeitwerk, Rails 6.1.4.4) is [`Can't determine the return type for #{self.path} (it has `resolver: #{@resolver_class}`, consider configuration a `type ...` for that class)`](https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/field.rb#L504-L506), which seems to indicate that an exception isn't being raised anymore by the resolver (since that would be caught in the `rescue` block right below this).
Since the error I was getting didn't match the …
> Improve error message (sometimes) caused by cyclical loading issues

- lib/graphql/relay/global_id_resolve.rb
- spec/support/star_wars/schema.rb
Oops -- this field helper passed _legacy_ type definitions to `schema.id_from_object`, even for class-based types. That should be updated because legacy type definitions are gone in 2.0. 
Unfortunately, I'm not sure how to give a good deprecation warning in this case. If a Schema's `.id_from_object` method is being used by other GraphQL features (eg, `loads: ...`), then it will already be future-compatible. But for anyone _expecting_ a legacy type definition, this will break, and I don't know how to make that easier :( 
Fixes #3911
> [1.13] Pass class-based definitions to id_from_object when resolving global_id_field fields

- lib/graphql/schema/warden.rb
- lib/graphql/subscriptions.rb
- spec/graphql/schema/subscription_spec.rb
Close #3897 
a73b6d58d4280964917cf0c71dac7afd4ba82294 can reproduce the problem described in #3897 :
> ![](https://user-images.githubusercontent.com/12410942/153716263-7edd2be5-dc59-43b0-a8df-97c2d4d85ba2.png)
> Support dynamic schema for Subscriptions#trigger

- lib/graphql/language/printer.rb
- lib/graphql/schema/member/has_interfaces.rb
- spec/graphql/schema/build_from_definition_spec.rb
- spec/graphql/schema/interface_spec.rb
Per #3613 I put interfaces in my interfaces 🎉   
But now my types have too many interfaces 🤢 
Specifically, if you've got a schema like this:
```graphql
interface Node { ... }
interface Named implements Node { ... }
interface Timestamped implements Node { ... }
```
And you add a type `Thing` that implements `Named` and `Timestamped`, printing the schema will give you this:
```graphql
type Thing implements Named & Node & Node & Timestamped { ... }
```
I didn't see much in the spec about this but the reference implementation doesn't like it:
https://github.com/graphql/graphql-js/blob/95dac43fd4bff037e06adaa7cfb44f497bca94a7/src/type/validate.ts#L338-L348 
It's also not stable - graphql-ruby will add an additional `& Node` each time you parse and then print the SDL.
First commit: does it …
> Same Interface Shows Up Multiple Times in "Implements"

- lib/graphql/analysis/ast/max_query_complexity.rb
This was causing a double require which resulted in warnings:
```
(…)/query_complexity.rb:22: warning: already initialized constant GraphQL::Analysis::AST::QueryComplexity::ScopedTypeComplexity::HASH_CHILDREN
(…)/query_complexity.rb:22: warning: previous definition of HASH_CHILDREN was here
```
> Remove an unnecessary `require_relative`

- Rakefile
- benchmark/run.rb
- lib/graphql/schema/argument.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/object.rb
Discussed in #3947, I thought I'd write up a benchmark for static memory footprint. It could be fleshed out to include interfaces, unions, input objects, and enums, but it's a start! 
Also, some changes to improve it by 10%:
```diff
- Total allocated: 3247310 bytes (36263 objects)
+ Total allocated: 3110758 bytes (35554 objects)
- Total retained:  1043514 bytes (6475 objects)
+ Total retained:  906962 bytes (5766 objects)
```
> Add 'rake bench:profile_schema_memory_footprint' and work on it

- guides/dataloader/nonblocking.md
Hi,
a `graphql-ruby` user pointed me to these docs https://graphql-ruby.org/dataloader/nonblocking.html
I've been playing with the [Fiber Scheduler](https://brunosutic.com/blog/ruby-fiber-scheduler) for the last couple weeks and I'm impressed you have a gem that's already using it. I literally thought no one in the WORLD has figured this out yet.
This PR proposes linking to [Fiber Scheduler List](https://github.com/bruno-/fiber_scheduler_list) instead of maintaining a list of available fiber schedulers in the [nonblocking dataloader doc](https://graphql-ruby.org/dataloader/nonblocking.html).
> Link to fiber scheduler list

- lib/graphql/schema/field.rb
- spec/graphql/schema/resolver_spec.rb
oops, in #3916, some resolver configurations started taking priority over field-level configurations. Any options provided to `field(...)` should take priority!
> Make field configs override resolver configs

- lib/graphql/relay/range_add.rb
BaseConnection was removed in 2.0 so that branch throws an error.  Context is now required
> Remove branch that uses code removed in 2.0

- lib/graphql/tracing/data_dog_tracing.rb
Datadog tracing is about to release the 1.0 version with some [changes](https://github.com/DataDog/dd-trace-rb/blob/v1.0.0.beta1/docs/UpgradeGuide.md).
The current integration is affected with one of this changes (the one about the [namespacing](https://github.com/DataDog/dd-trace-rb/blob/v1.0.0.beta1/docs/UpgradeGuide.md#namespacing--the-public-api))
This change fix the error and also keeps backward compatibility with older versions of the ddtrace gem
> support for ddtrace 1.0 and keep backward compatibility

- .github/workflows/ci.yaml
This is actually what's already running because an unquoted '3.0' in the GitHub Actions is truncated to '3', loading the latest Ruby 3 - which at time of writing is Ruby 3.1.1.  This PR makes the change explicit.
> Update the max supported Ruby version to 3.1

- lib/graphql/schema/member/has_directives.rb
- spec/graphql/schema/directive_spec.rb
When adding directives to an object, we currently overwrite any existing directives of the same class. However, if the directive is repeatable, we should be able to specify multiple directives without overwriting existing ones.
Pretty simple: Don't remove existing directives if the directive in question is repeatable.
I haven't explicitly checked the printer to make sure it does the right thing when printing multiple of the same directives. I assume it isn't really any different than if the object had multiple different directives.
> Allow multiples of repeatable directives

- lib/graphql/schema/field.rb
- spec/graphql/schema/field_spec.rb
Fixes #3989 
And was broken by #3916
> Fix Field#scoped? to check resolver return value, too

- lib/graphql/types/relay/connection_behaviors.rb
This was here to support legacy connection wrappers, but they're not part of the project anymore.
> Remove needless connection behavior

- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/schema/relay_classic_mutation.rb
- lib/graphql/schema/resolver.rb
- spec/graphql/schema/mutation_spec.rb
> Resolvers: properly inherit args from parent classes that aren't attached to the schema

- lib/graphql/schema/field.rb
- lib/graphql/schema/member/has_fields.rb
- spec/graphql/schema/field_spec.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/3944
Fixes https://github.com/rmosolgo/graphql-ruby/issues/3861
Closes #3947 as duplicate
- Removed some of the more complicated changes to focus on fixing the underlying issue first, and looking at refactoring further in later PRs to reduce the cognitive overload of having so many changes to a fundamental class
> Fix `hash_key` attribute to work with keys commonly responded to by underlying GraphQL objects

- lib/graphql/introspection.rb
- lib/graphql/introspection/type_type.rb
- lib/graphql/schema/loader.rb
- spec/graphql/introspection/type_type_spec.rb
- spec/graphql/schema/printer_spec.rb
The spec spells the specifiedByURL introspection field by capitalizing the acronym, and fields are case sensitive.
(Previously the inflector generated specifiedByUrl)
> Fix specifiedByUrl -> specifiedByURL

- lib/graphql/types/iso_8601_date.rb
- lib/graphql/types/iso_8601_date_time.rb
Link to the RFC 3339 specification https://tools.ietf.org/html/rfc3339, which in turn specifies to use ISO 8601
> Add specified_by_url for ISO8601 scalars

- guides/faq.md
A problem I’ve been struggling with is generating URLs within the resolvers using the current host and port. A common solution is to set `Rails.application.routes.default_url_options`, but this is static and with my current setup I need to be able to return the host actually used within the request (My development environment runs over both http and https, so I can’t just hardcode localhost:3000).
A solution I’ve found is to pass the controller’s request into the context, and use the `ActionController::UrlFor` concern.
And likewise for Active Storage, `ActiveStorage::SetCurrent` works similarly.
I thought it might be useful to share this with anyone else running into this use case.
> Add example of using url_helpers in resolvers

- lib/graphql/schema/resolver.rb
- spec/graphql/schema/resolver_spec.rb
Call the correct method when generating the exception message. closes #4028
> Fix error message generation when ready? returns an invalid result

- lib/graphql/schema.rb
- lib/graphql/schema/warden.rb
- spec/graphql/schema/dynamic_members_spec.rb
- spec/graphql/schema/enum_spec.rb
I need to access the name error as part of the `DuplicateNamesError` class to implement a temporal fix in my App.
This PR does two things:
1) It removes `DuplicateTypeNamesError`. This error class was removed on https://github.com/rmosolgo/graphql-ruby/pull/3651 and it isn't used anymore.
2) Expose the duplicated type name in the `DuplicateNamesError` class.
> Expose duplicated name as part of DuplicateNamesError error class.

- lib/graphql/tracing/data_dog_tracing.rb
- spec/graphql/tracing/data_dog_tracing_spec.rb
- spec/support/datadog.rb
This PR improves the support for GraphQL tracing with the Datadog tracing exporter.
The two changes are:
* Tag spans generated by GraphQL operations with an appropriate 'component' and 'operation' tags. This information was previously captured in the span name, as a concatenated pair. Having this information into two separate fields allows for richer grouping in the future.
* Span resource is not set to `nil` when `GraphQL::Tracing::DataDogTracing` cannot derive an appropriate rich value for it.  This allows for `ddtrace` to back-fill the resource value later in `ddtrace`s processing logic. Setting it explicitly to `nil`, as it was done before, sends a message to `ddtrace` that we explicitly don't want a resource, which was not the case here.
> Improve Datadog tracing support for ddtrace 1.0

- guides/schema/object_identification.md
- lib/generators/graphql/relay.rb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
Just a simple improvement.
Related: I'm curious about how this method of encoding the id is better than [what we suggested before](https://github.com/rmosolgo/graphql-ruby/pull/3627/files) (`object.to_gid.to_param`)? Why the extra work? That method produces a good looking string (like `Z2lkOi8vcmV2aWV3cy9SZXZpZXcvNDc`) too and is easier to locate.
Edit: Looks like it's even simpler: `object.to_gid_param`.
> Use GlobalID methods instead of manually handling the encoding/decoding

- guides/type_definitions/lists.md
Table in "Lists, Nullable Lists, and Lists of Nulls" section was not properly formatted and GitHub did not render it correctly.
**Before:**
**After:**
> Minor table formating fix

- lib/graphql/types/iso_8601_date_time.rb
- spec/graphql/types/iso_8601_date_time_spec.rb
https://github.com/rmosolgo/graphql-ruby/commit/d045a207e0cf8bb53e31549f82b78c72a0e661c0 changed the behaviour for parsing dates (as date times) to make the parsing much safer. However, I have several consumers of my graphql apis who currently send datetime values as a date without hyphens (eg. "20220505"). I would like to make that use case continue to work in a safe way.
> accept dates missing hyphen

- lib/graphql/schema/field.rb
- spec/graphql/schema/field_spec.rb
> Fix some hash lookup behaviors

- guides/fields/introduction.md
- lib/graphql/schema/field.rb
- spec/graphql/schema/field_spec.rb
- spec/graphql/schema/interface_spec.rb
Fixes #4020. This adds a parameter called `:fallback_value` to Field, which allows you to specify a value to be returned if the usual ways (calling the method on an object, or checking for the key in a hash) fail. It's useful if there is a query that returns objects that might or might not have a certain field.
The motivation for this is a scenario where we have a data model that has lots of entity types. All of them have an `id` property. Most of them have a `name` property, but some of them don't. We want all of them to implement an interface (Node) that has a required `id` property and an optional `name` property.
``` ruby
interface Node { id: ID! name: String }
```
The default for the `:fallback_value` param in the initializer is `:not_given`, which allows us to set `nil` as the …
> Add fallback_value option to Field

- lib/graphql/analysis/ast/field_usage.rb
- spec/graphql/analysis/ast/field_usage_spec.rb
- spec/graphql/introspection/type_type_spec.rb
- spec/support/dummy/schema.rb
Problem
---
When passing in an explicit `null` value for a nullable input object-type argument on a field, field usage analysis will raise an exception like this:
```
NoMethodError: undefined method `arguments' for nil:NilClass
graphql-ruby/lib/graphql/analysis/ast/field_usage.rb:43:in `block in extract_deprecated_arguments'
graphql-ruby/lib/graphql/analysis/ast/field_usage.rb:37:in `each_pair'
graphql-ruby/lib/graphql/analysis/ast/field_usage.rb:37:in `extract_deprecated_arguments'
graphql-ruby/lib/graphql/analysis/ast/field_usage.rb:22:in `on_leave_field'
```
Solution
---
Skip arguments with null values during field usage analysis.
> Allow null input objects in arguments during field usage analysis

- lib/graphql/tracing.rb
- lib/graphql/tracing/opentelemetry_tracing.rb
- lib/graphql/tracing/platform_tracing.rb
- spec/graphql/tracing/opentelemetry_tracing_spec.rb
- spec/support/opentelemetry.rb
Closes https://github.com/rmosolgo/graphql-ruby/issues/4001
An attempt at allowing tracing per request as per suggestions in https://github.com/rmosolgo/graphql-ruby/issues/4001
- `cached_platform_key` now accepts the trace phase as a third parameter.
- `OpenTelemetryTracing` overrides `cached_platform_key` to access execution context not available in `platform_field_key`, `platform_authorized_key`, `platform_resolve_type_key`
This PR includes
- modified copy of the [OpenTelemetry implementation](https://github.com/open-telemetry/opentelemetry-ruby/blob/99bfe640cef822adb5f173937b7a98c7d5c48758/instrumentation/graphql/lib/opentelemetry/instrumentation/graphql/tracers/graphql_tracer.rb) to demonstrate how we would make use of `PlatformTracing`
- tests to ensure the above works as expected
- …
> Add query execution context based tracing for API requests

- lib/graphql/execution/lazy.rb
It looks like this was added long ago, but never actually used by the library. The way to resolve an individual lazy is with `.value`; the way to resolve a set of them is `Lazy::Resolve.resolve_all`.
> remove unused Lazy.resolve

- lib/graphql/rake_task.rb
This file references `Rake::DSL`, and may be required in isolation, and so it should `require "rake"` before using it.
Without this, requiring this file in isolation blows up when encountering this constant.
> Require Rake before referencing `Rake::DSL`

- lib/graphql/schema.rb
- lib/graphql/subscriptions.rb
- spec/graphql/schema_spec.rb
Oops, this made it hard to test subclasses of schemas with subscriptions.
> Fix subscription inheritance/override

- lib/graphql/schema/argument.rb
- spec/graphql/schema/input_object_spec.rb
Weirdly, the order here was different for resolvers than for other arguments. I think resolvers had the right before: prepare first, then load.
Fixes #4017
> Call prepare before loads for all arguments

- lib/graphql/query.rb
- lib/graphql/query/validation_pipeline.rb
- spec/graphql/query_spec.rb
Since recently, you could assign `Query#validate=...` to tell a query whether it should run static validation or not. But the validation result is cached, so it'd be buggy to reassign this afterward. I'd like to warn people about it rather that allow a possible foot-gun. If this doesn't work, this other option is to bust the validation cache whenever this value is reassigned.
Fixes #3901
> Don't allow re-assigning Query#validate after validation

- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/schema.rb
- lib/graphql/schema/member/has_arguments.rb
- spec/graphql/schema/union_spec.rb
Fixes #4085 
Another option is to call `continue_value` in this code, which would change the behavior like this: 
```diff 
- { "myUnion" => { "b" => nil } }
+ { "myUnion" => nil }
```
This would be _more_ like how objects are handle, but it would break some other tests in library. I'm open to it and I'll consider it if requested.
> Support returning [Type, nil] from resolve_type

- guides/related_projects.md
`graphql-sources` is a collection of common [sources](https://graphql-ruby.org/dataloader/sources.html) to simplify loading data from `ActiveRecord`, fetching file from `ActiveStorage`, or using `Rails.cache`. The library documentation can be found here:
https://github.com/ksylvest/graphql-sources
> Add `graphql-sources` to related projects

- guides/related_projects.md
This fixes a rendering bug on the /related_projects page introduced by https://github.com/rmosolgo/graphql-ruby/pull/4134. Apologies for the typo not being caught earlier!
> Fix Typo in Markdown Syntax on /related_projects

- lib/graphql/language/printer.rb
- spec/graphql/schema/printer_spec.rb
> Don't print empty braces when input object has no arguments

- javascript_client/src/subscriptions/ActionCableLink.ts
Currently when I run `unsubscribe` inside an `update` method for a subscription class (in ruby) this causes the front-end to fails, because the server sends a new message to the front end that looks like: 
```
{
more: false
}
```
Now if you try to result `payload.result.data` this will error out, as result is undefined and you cannot read `.data` of undefined. 
By using conditional access to said properties, we can safely read `data` and `errors` while not trying to read some properties when `result` is undefined
> Check for nullable result value to avoid errors on unsubscription

- lib/graphql/execution/interpreter/runtime.rb
This patch might improve performance where it insert an object into frozen array.
- macOS 13.0 beta
- Apple M1 Max
- Apple clang version 14.0.0 (clang-1400.0.28.1)
- Ruby 3.1.2
```
dup, <<   735.025k i/100ms
+     1.141M i/100ms
dup, <<      7.374M (± 0.4%) i/s -     74.238M in  10.067378s
+     11.360M (± 0.5%) i/s -    114.081M in  10.042478s
Comparison:
+: 11360174.1 i/s
dup, <<:  7374162.2 i/s - 1.54x  (± 0.00) slower
```
```ruby
require 'benchmark/ips'
Benchmark.ips do |x|
x.time = 10
path = ["__schema", "types"].freeze
x.report('dup, <<') {
next_path = path.dup
next_path << 1
}
x.report('+') {
next_path = path + [1]
}
x.compare!
end
```
> Use Array#+ to insert an object to frozen Array instead of #dup and #<<

- guides/index.html
[Flexport](https://flexport.com), a digital freight forwarder, is a big fan and user of `graphql-ruby`. It is the package that underlies our monolith's GraphQL usage, and we have anywhere between 50-100k LOC in Ruby GraphQL code made possible by this library. We'd love to be acknowledged as a "verified" user of `graphql-ruby`!
The placement of Flexport in the list of users was determined by organization size -- by my rough estimates (and perhaps some degree of bias), this order is roughly Shopify > Flexport > Chime > Kickstarter (ignoring GitHub). I'm happy to move Flexport around in the list as necessary.
> Add Flexport as a graphql-ruby user

- guides/authorization/visibility.md
https://github.com/rmosolgo/graphql-ruby/blob/master/guides/authorization/visibility.md#argument-visibility
I guess there is a typo. Probably the `visible?` method should be used there
Compare the `authorized?` and `visible?` method signatures
https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/argument.rb#L144-L146
https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/schema/argument.rb#L136-L138
> Fix typo in code example in Argument Visibility docs

- guides/queries/tracing.md
Look [here](https://github.com/rmosolgo/graphql-ruby/blob/v2.10.0/lib/graphql/tracing.rb#L12-L14), `GraphQL::Tracing::PrometheusTracing::GraphQLCollector` only be required when used `PrometheusExporter::Server` startup, so it throwing `NameError` exception when used other server startup.
_PS: English is not my native language; please excuse typing errors._
> Fix prometheus tracing guide

- lib/graphql/static_validation/error.rb
- lib/graphql/static_validation/rules/directives_are_defined.rb
- lib/graphql/static_validation/rules/unique_directives_per_location.rb
- spec/graphql/static_validation/rules/directives_are_defined_spec.rb
- spec/graphql/static_validation/rules/unique_directives_per_location_spec.rb
This improves memory usage when the same invalid directive is repeated over and over. 
(When the invalid directives are different, `validate_max_errors ...` in the schema is probably the best choice.) 
Part of #4154 
From the script in the original issue: 
script | before | after 
--- | --- | --- 
innocent, total time | 0.000439 | 0.000449
unique, total time | 0.148472 | 0.166246
repeat, total time |0.135613 |  0.101214
| | 
innocent, memsize | 22.728k | 22.912k
unique, memsize | 20.419M | 20.878M
repeat, memsize | 34.711M |  9.972M 
(The `unique` benchmark didn't improve because `validate_max_errors` is the best way to mitigate that.) 
I considered some kind of DRYing for "directive not defined" errors, but I found that GraphQL-JS also makes a separate error for each invalid directive: …
> Merge directive errors when they're on the same directive or location

- lib/graphql/subscriptions.rb
- spec/graphql/subscriptions_spec.rb
Oops -- the previous initialization code actually made it so that `context.query.context.to_h` was `{}`, so schema root fields might fail visibility checks even when a context was given to trigger.
> Fix trigger context initialization

- guides/queries/tracing.md
- lib/graphql/tracing/data_dog_tracing.rb
**Why & What** 
Datadog GraphQL integration is deprecating `analytics_enabled`, `analytics_sample_rate`. Hence, marking it with comment, and removing it from documentation to prevent it more usage
https://github.com/DataDog/dd-trace-rb/pull/2214
> Remove deprecated datadog tracer analytic options

- guides/subscriptions/ably_implementation.md
"The general rule is to use "a" when the indefinite article precedes a word beginning with a consonant sound and an when it precedes a word starting with a vowel sound."
> Use "an" before a vowel sound

- CHANGELOG.md
CHANGELOG mentions `max_validation_errors` method but actually the method does not exist. There is `validate_max_errors` instead.
This PR replaces `max_validation_errors` with `validate_max_errors`.
---
In #2386, this feature was developed as `max_validation_errors` but this PR was not merged. This feature has been added as `validate_max_errors` in another PR. I guess it is the reason why there was the confusion in CHANGELOG.
> Replace `max_validation_errors` with `validate_max_errors` in CHANGELOG

- lib/graphql/schema.rb
Many libraries use the file extension `.graphqls` to distinguish between files containing schema definitions vs. files containing GraphQL queries, etc.
This simple PR modifies `Schema.from_definition` to recognize this alternative file extension.
> Recognize .graphqls files as schema files in Schema.from_definition

- .github/workflows/apidocs.yaml
- .github/workflows/website.yaml
This PR adds explicit [permissions section](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#permissions) to workflows. This is a security best practice because by default workflows run with [extended set of permissions](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#permissions-for-the-github_token) (except from `on: pull_request` [from external forks](https://securitylab.github.com/research/github-actions-preventing-pwn-requests/)). By specifying any permission explicitly all others are set to none. By using the principle of least privilege the damage a compromised workflow can do (because of an [injection](https://securitylab.github.com/research/github-actions-untrusted-input/) or compromised third party tool or …
> GitHub Workflows security hardening

- lib/graphql/schema/type_membership.rb
In order to filter-out `interfaces-type` membership during `ApolloFederation` dumping the access to `TypeMembership#options` is opened.
The use case is the following:
1. We have schema like
```ruby
class Foobar < BaseType
implements FooInterface
end
```
2. In order to drop it in 0 downtime fashion we need to mark this `implements`
```ruby
class Foobar < BaseType
implements FooInterface, apollo_federation: false
end
```
3. So in order to access this `apollo_federation` key value we need to open access to `TypeMembership#options` instance variable
> Add attr_reader :options for TypeMembership

- lib/graphql/introspection.rb
#4184 added
```diff
fragment FullType on __Type {
kind
name
description
#{include_specified_by_url ? "specifiedByURL" : ""}
+  #{include_is_one_of ? "isOneOf" : ""}
fields(includeDeprecated: true) {
name
description
```
to the introspection query, which introduces a new blank line when the condition is false and needlessly changes the query's fingerprint.
By stripping out blank lines, we ensure that the query is stable even if new conditional lines are added that don't actually end up adding any content.
> Strip blank lines from introspection query

- guides/type_definitions/field_extensions.md
Field extensions can be used using the `extensions: [...]` option.
```ruby
field :name, String, null: false, extensions: [UpcaseExtension]
```
That's documented [here](https://graphql-ruby.org/type_definitions/field_extensions.html#using-an-extension).
Then [below](https://graphql-ruby.org/type_definitions/field_extensions.html#extension-options) in that same page, it presents that field extensions can receive options.
I wondered if we could pass extension options using the `extensions: [...]` option. 🤔 
It turns out that we [can](https://github.com/rmosolgo/graphql-ruby/blob/99ee3ceb4595005e63c5acc7d8a56704dc5d6b8c/spec/graphql/schema/field_extension_spec.rb#L121). So, I thought that it would useful to document that in the `Extension options` section. That's this PR 😄 .
> Update the extension options section

- lib/graphql/execution/lookahead.rb
- lib/graphql/schema/member/build_type.rb
More fixing for #4187
I used this script to check my changes:
```ruby
require "bundler/inline"
gemfile do
gem "graphql", path: "./"
gem "memory_profiler"
end
field :field, String
field :field2, String
end
query(Query)
end
query = GraphQL::Query.new(Schema, "{ field }")
lookahead = query.lookahead
lookahead.selects?(:field)
res = nil
report = MemoryProfiler.report do
res = [
lookahead.selects?(:field),
lookahead.selects?(:field2),
lookahead.selects?(:field_2),
lookahead.selects?(:field_2),
lookahead.selects?(:field_2),
lookahead.selects?(:field3),
lookahead.selects?(:field_3),
lookahead.selects?("__field_4"),
]
end
pp res
report.pretty_print
```
And found the following changes (summarized):
```diff
-Total allocated: 37960 …
```
> Reduce more allocations in Lookahead#selects?

- lib/graphql/backtrace/table.rb
- lib/graphql/dataloader.rb
- lib/graphql/execution/interpreter.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/query/context.rb
- lib/graphql/schema.rb
- lib/graphql/schema/directive/transform.rb
- spec/graphql/dataloader_spec.rb
- spec/graphql/query/context_spec.rb
Fixes #4125 
I tried this approach before, but I forgot about _skipping_ `:__graphql_runtime_info` when copying thread variables into new fibers.
> Make scoped context work with Dataloader

- lib/graphql/schema/build_from_definition.rb
👋🏼 Simply removes this unused string. This prevents ruby from generating this warning about it, especially when run from rake test:
```
build_from_definition.rb:394: warning: possibly useless use of a literal in void context
```
I am not sure why this was left here, even after looking at [the original commit](https://github.com/rmosolgo/graphql-ruby/commit/eaa1c7d5dc27a3c9c7659e0ef5f528a7b4322941#diff-1ff8d09dd48483a2bba959cc7627c912707deca2e3fd7e8896aaf1b9807fe7adR398), so I assumed it was not intentional. Spec for the module also passed, so I hope this is okay.
> Remove unused string

- javascript_client/src/subscriptions/createAblyHandler.ts
As described [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error,) `Error.captureStackTrace` is only available in V8.
> Avoid using Error.captureStackTrace

- javascript_client/src/subscriptions/__tests__/createAblyHandlerTest.ts
- javascript_client/src/subscriptions/createAblyHandler.ts
This makes Apollo 1 subscriptions keep working with the interpreter runtime, which returns `{}` in the initial response by default.
> Don't pass along empty initial responses in Ably subscriptions

- lib/graphql/subscriptions.rb
- spec/graphql/subscriptions/event_spec.rb
When a subscription is triggered, there's an param to pass a `context:` but it's lost because it's not forwarded to the `Subscription::Event`.  
Now when `Subscription#execute_update` is executed, we can now merge query's context with event's context.  
This allows to pass an id of the sender of a query and compare it with the receiver of a subscription in the `#update` method, for example to prevent the sender of the subscription to receive its own updates by skipping it when the ids match.
Example:
````ruby
module Subscriptions
class ExampleSubscription < ::Types::Base::Subscription
payload_type ::Types::ExampleSubscriptionPayload
argument :model_id, ID, required: true, loads: ::Types::Models::MyModel, can_can_action: :read
def subscribe(model:)
super
end
def update(model:)
return …
```
> Pass and merge subscription's event and query ctxs

- lib/graphql/subscriptions/action_cable_subscriptions.rb
Initialization upon miss can lead to hard to debug scenarios where potentially a concurrent array will leak out but the value in the `@events` will be different.
as described here: https://github.com/ruby-concurrency/concurrent-ruby/issues/970
> Fix events map initialization to prevent race conditions

- guides/subscriptions/pusher_implementation.md
When I was following docs I noticed that the previous link about Pusher's 10kb message limit does no longer work.
I updated it to the newest one, but this problem might happen again. :(
> [DOCS] Update Pusher's message size limit link

- lib/graphql/static_validation/definition_dependencies.rb
- spec/graphql/static_validation/rules/fragment_names_are_unique_spec.rb
> Properly handle duplicate fragment names used indirectly

- lib/graphql/schema/union.rb
- spec/graphql/schema/union_spec.rb
If you need to override this for backwards compatibility, you can redefine `def self.assert_valid_union_member(type_defn)` in your own base Union class with the previous code. (But I can't imagine what non-Object types _used_ to do here!)
> Only allow object types to be union types, fixes #4243

- lib/graphql/types/relay/default_relay.rb
- lib/graphql/types/relay/edge_behaviors.rb
- spec/graphql/types/relay/base_edge_spec.rb
Oops -- this built-in class should have returned true for `.default_relay?`, just like NodeInterface and BaseConnection: 
https://github.com/rmosolgo/graphql-ruby/blob/777291787f9aeae6c3fc7c0fe5b38234c57402d0/lib/graphql/types/relay/node_behaviors.rb#L8
https://github.com/rmosolgo/graphql-ruby/blob/777291787f9aeae6c3fc7c0fe5b38234c57402d0/lib/graphql/types/relay/connection_behaviors.rb#L12
Also, I think it should be inherited, so that subclasses return `true` here too.
> BaseEdge (and subclasses) should be .default_relay? -> true

- lib/graphql/subscriptions/event.rb
- spec/graphql/schema/subscription_spec.rb
- spec/graphql/subscriptions_spec.rb
Oops -- this _never_ worked, as far as I can tell. 
The "topic" would be created with the `as:` name (without `Id`), but then triggering wouldn't work at all: 
- If you included `_id`, then the topic generated by `.trigger` wouldn't match the previously-generated topic 
- If you didn't include `_id`, then GraphQL-Ruby would :boom: because there wasn't a matching argument name 
So, I think the right thing to do is use the plan GraphQL argument name in the topic instead.
> Fix subscriptions that use loads/as

- lib/graphql/schema/enum.rb
- lib/graphql/schema/warden.rb
- spec/graphql/schema/enum_spec.rb
This is required by the spec (https://spec.graphql.org/draft/#sec-Enums.Type-Validation) but wasn't actually validated by GraphQL-Ruby til now. I implemented it at runtime so that, if your schema hides enum values dynamically, it will still make sure the resulting schema is valid.
> Require at least one Enum value

- lib/graphql/schema.rb
- lib/graphql/schema/enum.rb
* The docs render the correct top-level-documentation for `GraphQL::Schema` and `GraphQL::Schema::Enum`.
* When reading the top-level-documentation for `GraphQL::Schema::Enum`, it shows nothing. ([Link](https://graphql-ruby.org/api-doc/2.0.16/GraphQL/Schema/Enum.html))
* When reading the top-level-documentation for `GraphQL::Schema`, it shows the docs for `GraphQL::Schema::Enum` instead. ([Link](https://graphql-ruby.org/api-doc/2.0.16/GraphQL/Schema))
* Moved top-level-documentation within `lib/graphql/schema/enum.rb` from `Schema` to `Enum`.
* (minor): Fix typo on `GraphQL::Schema#parse_error` param docs
> docs: Fix top level docs for GraphQL::Schema::Enum

- javascript_client/src/subscriptions/PusherLink.ts
- javascript_client/src/subscriptions/__tests__/PusherLinkTest.ts
> Pass along the initial payload in PusherLink

- lib/graphql/schema/field.rb
- spec/graphql/schema/field_spec.rb
Fixes https://github.com/rmosolgo/graphql-ruby/pull/4072#issuecomment-1375790414
When a field is configured with `hash_key:`, look up that key using `[...]`, even if the underlying object isn't a Hash. (This code checks for `.respond_to?(:[])` to avoid breaking changes, which might be possible because of how `hash_key` was previously merged into `method_*` attributes.)
> 1.13: lookup given hash_key: when possible

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/authorization_spec.rb
When field authorization is lazily denied, the interpreter correctly calls `unauthorized_field` schema hook (used to wrongly call `unauthorized_object` instead).
Additionally, what do you think about creating `GraphQL::UnauthorizedObjectError` and removing all the mentions of `GraphQL::UnauthorizedError` (except for declaration and inheritance) to encourage a conscious decision since the logic is not always the same for objects and fields (as the bug shows).
Also, what do you think about asserting both `data` AND `errors` in every case of the test not to miss other edge cases like that?
> Fix wrong schema hook call on lazy denial from field authorization

- lib/graphql/schema/late_bound_type.rb
- lib/graphql/schema/member/type_system_helpers.rb
Ref: https://github.com/rmosolgo/graphql-ruby/pull/4293
I kinda got lost trying to fix many shapes issues at once, so I'm trying again one variable at a time.
This one the the third most common shape edge in our app:
```
Shape Edges Report
527  @default_graphql_name
494  @own_fields
487  @to_non_null_type
```
> Eagerly define @to_non_null_type variables for Shape Friendliness

- lib/graphql/schema/member/has_fields.rb
Ref: https://github.com/rmosolgo/graphql-ruby/pull/4293
I kinda got lost trying to fix many shapes issues at once, so I'm trying again one variable at a time.
This one the the second most common shape edge in our app:
```
Shape Edges Report
527  @default_graphql_name
494  @own_fields
```
> Eagerly define @own_fields variables for Shape Friendliness

- lib/graphql/schema/directive.rb
- lib/graphql/schema/member/base_dsl_methods.rb
Ref: https://github.com/rmosolgo/graphql-ruby/pull/4293
I kinda got lost trying to fix many shapes issues at once, so I'm trying again one variable at a time.
This one the the most common shape edge in our app:
```
Shape Edges Report
527  @default_graphql_name
```
> Eagerly define `@default_graphql_name` variables for Shape Friendliness

- javascript_client/src/cli.ts
When running `graphql-ruby-client --help`, the help text shows that the argument for the secret is `--key`. This is incorrect. The argument is `--secret`.
> fix(doc/javascript_client): secret argument name

- lib/graphql/schema/member/has_interfaces.rb
Ref: https://github.com/rmosolgo/graphql-ruby/pull/4293
I kinda got lost trying to fix many shapes issues at once, so I'm trying again one variable at a time.
This one the the fourth most common shape edge in our app:
```
Shape Edges Report
527  @default_graphql_name
494  @own_fields
487  @to_non_null_type
413  @own_interface_type_memberships
```
> Eagerly define @own_interface_type_memberships for Shape Friendliness

- lib/graphql/schema/enum_value.rb
- spec/graphql/introspection/type_type_spec.rb
- spec/graphql/schema/enum_spec.rb
- spec/support/dummy/schema.rb
Use dummy object instead of `nil` for undefined value, so we can distingush explicitly passed `nil`.
Right now we have:
```ruby
class MyEnumType < GraphQL::Schema::Enum
value 'NO_VALUE', value: nil
value 'ONE_VALUE', value: 1
end
p MyEnumType.coerce_input('NO_VALUE', GraphQL::Query::NullContext) # => 'NO_VALUE'
```
Not sure how to properly test it because added test is in `legacy tests` block, please advise.
> Allow `nil` as an enum ruby value

- guides/javascript_client/sync.md
- javascript_client/src/__tests__/cliTest.ts
- javascript_client/src/__tests__/syncTest.ts
- javascript_client/src/cli.ts
- javascript_client/src/sync/__tests__/sendPayloadTest.ts
- javascript_client/src/sync/index.ts
- javascript_client/src/sync/sendPayload.ts
Fixes https://github.com/rmosolgo/graphql-ruby/discussions/4304
TODO:
> JS: fix header handling, add changeset-version option

- Gemfile
- benchmark/run.rb
- lib/graphql/schema/member/has_fields.rb
- lib/graphql/schema/member/has_interfaces.rb
- lib/graphql/schema/warden.rb
Looking over some profiling artifacts, I noticed this call to `interface_type_memberships` wasn't cached, so objects were repeatedly building this array over and over. The more interfaces and superclasses an object has, the more this overhead would've added up. I was able to confirm a reduction in allocated memory and time spent calculating this by running the new benchmark: 
```diff 
-        176   (0.0%)          25   (0.0%)     GraphQL::Schema::Member::HasFields#get_field
+          4   (0.0%)           1   (0.0%)     GraphQL::Schema::Member::HasFields#get_field
-         32   (0.0%)          17   (0.0%)     GraphQL::Schema::Member::HasInterfaces#interface_type_memberships
+          4   (0.0%)           3   (0.0%)     GraphQL::Schema::Warden#interface_type_memberships
- Total …
```
> Improve interface type membership lookup

- Rakefile
- benchmark/run.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/schema/warden.rb
Looking at a profile, I found that `arguments(ctx)` hashes are merged over and over again at runtime, at least in these two places. We should cache these per-query, too.
```diff 
-                           3.335  (± 0.0%) i/s -     17.000  in   5.101803s
+                           3.532  (± 0.0%) i/s -     18.000  in   5.097713s
-      55774   (8.8%)       10019   (1.6%)     GraphQL::Schema::Member::HasArguments#arguments
-      93425  (14.7%)        5604   (0.9%)     GraphQL::Schema::Member::HasArguments#coerce_arguments
-      18269   (2.9%)        4890   (0.8%)     GraphQL::Schema::Warden#visible_argument?
-      26798   (4.2%)        3665   (0.6%)     GraphQL::Schema::Field#authorized?
+      58446  (10.2%)        5725   (1.0%) …
```
> Reduce argument overhead

- lib/graphql/introspection/directive_type.rb
- lib/graphql/introspection/field_type.rb
- lib/graphql/introspection/schema_type.rb
- lib/graphql/introspection/type_type.rb
This overhead seems small, but it adds up proportional to the number of lists (arguments, fields, types, enum values, interfaces, possible types) in the result. So, for big schemas, it can add up!
```diff 
-        247   (0.1%)          62   (0.0%)     GraphQL::Schema::Field::ScopeExtension#after_resolve
+
```
(Using the introspection benchmark from 8f0e9e8662edc67844074c2392e1c81a066ac3fe)
TODO:
> Don't run scoping on introspection queries

- benchmark/run.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/tracing/platform_tracing.rb
When building really big result sets (especially introspection, where there's almost nothing _except_ GraphQL overhead), these redundant `Field#type` calls add up. 
Amazingly, my profiles don't show any callees of this method, so I think they're all calls to the cached `@type` (https://github.com/rmosolgo/graphql-ruby/blob/1.13.x/lib/graphql/schema/field.rb#L602). So it's just the sheer _number_ of calls that creates the observed slowness.
It didn't make a big difference in this library's benchmark, but I think it'll do the job: 
```diff
-       1813   (0.2%)        1813   (0.2%)     GraphQL::Schema::Field#type
+        819   (0.2%)         819   (0.2%)     GraphQL::Schema::Field#type
```
TODO:
> Performance: reduce a duplicate call to Field#type

- lib/graphql/schema/directive.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/schema/member/has_interfaces.rb
- lib/graphql/schema/member/has_validators.rb
- spec/graphql/schema/interface_spec.rb
- spec/graphql/schema/object_spec.rb
Fixes #4314 
There are still a lot of calls at runtime, but these were "unnecessary" (they could be eliminated by making configuration code more complicated).
```diff 
-       6088   (1.1%)        6088   (1.1%)     Kernel#is_a?
+       4656   (0.8%)        4656   (0.8%)     Kernel#is_a?
```
<details>
<summary>`Kernel#is_a?` in before benchmark</summary>
<p>
```
$ stackprof tmp/introspection-before.dump --method="Kernel#is_a?"
Kernel#is_a? (<cfunc>:1)
samples:  6781 self (1.0%)  /   6781 total (1.0%)
callers:
1233  (   18.2%)  GraphQL::Execution::Interpreter::Runtime#evaluate_selection
1189  (   17.5%)  GraphQL::Schema::Member::HasArguments#arguments
957  (   14.1%)  GraphQL::Schema::Field#resolve
948  (   14.0%)  GraphQL::Execution::Interpreter::Runtime#evaluate_selection_with_args
781  ( …
```
> Reduce runtime .is_a? calls in schema objects

- lib/graphql/schema.rb
- lib/graphql/schema/argument.rb
- lib/graphql/schema/enum_value.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/interface.rb
- lib/graphql/schema/member/base_dsl_methods.rb
- lib/graphql/types/relay/connection_behaviors.rb
- lib/graphql/types/relay/edge_behaviors.rb
- spec/graphql/authorization_spec.rb
As far as I know, this is entirely unused now and a relic of legacy authorization. The methods weren't called anywhere, and removing them broke no tests.
> Remove unused accessible? methods

- lib/graphql/execution/interpreter.rb
I think this will fix the flaky tests in CI (eg https://github.com/rmosolgo/graphql-ruby/actions/runs/4099883449/jobs/7070213090), where `context[...]` values are spilling over into other tests.
> Clean up thread-scoped context values after running a query

- lib/graphql/schema/member/base_dsl_methods.rb
These methods can be called a lot at runtime, and simplifying their read behavior could make everything a hair faster.
> Reduce indirection in #introspection? and #graphql_name

- lib/graphql/execution/lazy.rb
I saw this was never used, so I decided to remove it. (In queries with a lot of promises, etc, this is a hot path.)
> remove error handling from Lazy#value

- benchmark/run.rb
- lib/graphql/analysis/ast/visitor.rb
- lib/graphql/language/nodes.rb
- lib/graphql/language/visitor.rb
- spec/graphql/analysis/ast_spec.rb
In analysis, `Kernel#public_send` was a big delay (and it was _own_ time -- overhead -- not the methods that end up getting called). It could mostly be eliminated by some heavy-handed codegen. It seems to me that it pays off: 
<details>
<summary>Before (3.6% own time)</summary>
<p>
```
stackprof before-stackprof.dump --method=Kernel#public_send
Kernel#public_send (<cfunc>:1)
samples:  3518 self (3.3%)  /   52917 total (49.9%)
callers:
232534  (  439.4%)  GraphQL::Language::Visitor#visit_node
22700  (   42.9%)  GraphQL::Analysis::AST::Visitor#call_analyzers
4106  (    7.8%)  GraphQL::Schema::Warden.visible_entry?
```
</p>
</details>
<details>
<summary> After (0.5% own time)</summary>
<p>
```
stackprof last-stackprof.dump --method=Kernel#public_send
Kernel#public_send (<cfunc>:1)
samples: …
```
> Eliminate dynamic dispatch from Language::Visitor and Analysis::AST::Visitor

- lib/graphql/pagination/active_record_relation_connection.rb
- spec/integration/rails/graphql/relay/relation_connection_spec.rb
- spec/support/star_wars/schema.rb
This PR removes the overridden `ActiveRecordRelationConnection#relation_larger_than` method. The overridden method was flawed as demonstrated by the test case on this PR and the parent class implementation appears to return the correct result. 
Note that some of the timing related tests are failing for me (but some of them fail on `master` as well?). It may be that my change introduces additional queries since the some of the prior work done in this area was to [address performance](https://github.com/rmosolgo/graphql-ruby/issues/2695). That said, correctness comes first. There is probably a better fix for this issue but I am unfamiliar with the code base 😅. Please let me know if this commit would introduce additional issues. 
See Issue #4337
> Ensure correct hasNextPage Value When Relation is Already Loaded

- lib/graphql/type_kinds.rb
- spec/graphql/type_kinds/type_kind_spec.rb
In this PR, I'd propose formalizing a proper `leaf?` distinction on TypeKind. 
At present, `TypeKind` provides a `fields?` distinction (Object + Interface) that is a bit awkward because it slices across both Composite and Leaf distinctions...
- `fields?` != `Composite`, because it omits Union.
- `!fields?` != `Leaf`, because it _includes_ Union, which is not a Leaf.
**This ambiguity leads to awkward situations:**
- https://github.com/rmosolgo/graphql-ruby/pull/4347 should really be checking `.leaf?` rather than `!fields?`.
- https://github.com/rmosolgo/graphql-ruby/issues/4351 stems from ambiguity with the `fields?` distinction (spec validation should be checking `composite?`).
- As a library author, I currently need [my own helper](https://github.com/gmac/graphql-stitching-ruby/blob/main/ …
> Add `leaf?` distinction to TypeKind

- javascript_client/src/subscriptions/ActionCableLink.ts
`channel` can still be `null` when the connected event fires. Use `this` instead, which is correctly set.
> Prevent race in ActionCableLink

- lib/graphql/schema/warden.rb
- spec/spec_helper.rb
Part of #4299 
This makes tests fail when a Warden is detected with an inconsistent shape, for example:
```
/Users/rmosolgo/.rbenv/versions/3.2.0/lib/ruby/gems/3.2.0/gems/rake-12.3.3/lib/rake/rake_test_loader.rb: warning: Exception in finalizer #<CheckWardenShape::CheckShape:0x00000001050e6d60 @warden=#<GraphQL::Schema::Warden:0x00000001042fba48 @schema=#<Class:0x000000010549de90>, @query=#<Class:0x000000010549e2f0>, @mutation=nil, @subscription=nil, @context=#<Query::Context ...>, @visibility_cache={GraphQL::Schema::Directive::Include=>true, GraphQL::Schema::Directive::Skip=>true, GraphQL::Schema::Directive::Deprecated=>true, GraphQL::Schema::Directive::OneOf=>true, #<GraphQL::Schema::Field Query.foo(...): Int>=>true, GraphQL::Types::Int=>true, #<Class:0x000000010549e2f0>=>true, …
```
> Assert Warden shape is consistent in tests

- lib/graphql/query/context.rb
- spec/graphql/query/context_spec.rb
Fixes #4373 
Originally I added `EmptyScopedContext` to simplify (and speed up) scoped context checks at runtime. But it introduced some incompatibilities. So I'll ditch it but roll some improvements into the normal `ScopedContext` class.
> Remove EmptyScopedContext, optimize ScopedContext allocations

- guides/queries/tracing.md
The new tracing API introduced in 2.0.18 requires custom tracers to call `super` rather than `yield` to ensure that multiple tracers can be chained together. This PR updates the docs to reflect that. It also updates the doc for the `ActiveSupport::Notifications` tracer to use the new APIs.
> Fix docs on chaining custom tracers

- lib/graphql/schema/timeout.rb
- spec/graphql/schema/timeout_spec.rb
Oops -- this call to `yield` short-circuited other traces in the mix. (Spotted by `@jturkel` here: https://github.com/rmosolgo/graphql-ruby/issues/4378#issuecomment-1466154477)
> Fix Timeout with other Traces

- guides/development.md
I found I had to compile the C extension after cloning my fork.
> Add `rake compile` to set-up instructions

- lib/graphql/execution/interpreter/runtime.rb
Under some circumstances, the `thread_info` object is empty, and there is no result. In such a case, the method should return depth 1 instead of failing.
We ran into this problem after updating to `graphql` version `2.0.19` (although it also happens in `2.0.18`).
> Fix `current_depth` method

- lib/graphql/schema.rb
- spec/graphql/schema/union_spec.rb
- spec/integration/rails/graphql/schema_spec.rb
> [2.0.17] Fix returning [Type, false] from resolve_type

- lib/graphql/language/nodes.rb
- lib/graphql/language/printer.rb
- lib/graphql/language/sanitized_printer.rb
- lib/graphql/schema/printer.rb
- spec/graphql/language/generation_spec.rb
- spec/graphql/language/nodes_spec.rb
- spec/graphql/language/printer_spec.rb
Rewrites the `GraphQL::Language::Printer` to make it more efficient and allow consumers to pass a `truncate_size` option.
Some benchmarks we ran with large queries indicated a ~2x speedup compared to the original implementation.
Even with the optimized implementation, printing large queries can fairly expensive. The `truncate_size:` option can be used by consumers that don't necessarily need to print the whole document to stop printing when the `truncate_size` is reached.
> Faster `GraphQL::Language::Printer` with `truncate_size` option

- lib/graphql/execution/interpreter/runtime.rb
The runtime code _was_ `after_lazy`'ing all argument values, even when it was already known to be empty. We can skip some of that overhead (along with `extras`- related overhead) when we know we don't need it.
> Speed up handling of fields without arguments at runtime

- lib/graphql/tracing/prometheus_tracing/graphql_collector.rb
The prometheus_exporter supports histograms if enabled, but the GraphQLCollector collector always uses summary.
See: https://github.com/discourse/prometheus_exporter#histogram-mode
Similar to the [WebCollector](https://github.com/discourse/prometheus_exporter/blob/main/lib/prometheus_exporter/server/web_collector.rb#L36) this PR  use the `PrometheusExporter::Metric::Base.default_aggregation` instead of the hardcoded `Summary` metrics
> Add support for histograms to prometheus_tracing

- lib/graphql/execution/interpreter/runtime.rb
- `set_result` checks for `dead_result?`, so we can get the same behavior here by removing these other checks. The only downside is that execution may continue _past_ a dead result in some cases -- but I think this is not the "happy path" and therefore an acceptable tradeoff. 
- Some checks to `non_null?` can be reduced by passing the result along.
Before: 
```
4.079  (± 0.0%) i/s -     21.000  in   5.151335s
Mode: wall(1)
Samples: 876887 (70.77% miss rate)
GC: 7711 (0.88%)
86300   (9.8%)       86300   (9.8%)     Kernel#class
78049   (8.9%)       78049   (8.9%)     Kernel#hash
57099   (6.5%) …
```
> Reduce dead_result? and non_null? checks at runtime

- lib/graphql/schema/warden.rb
This reduces a lot of `.respond_to?` calls at runtime and seems like it's actually faster.
> Prioritize the common case for warden lookup

- CHANGELOG.md
I recovered these entries by inspecting e.g.
`git diff v.1.11.9..v1.11.10`
> Restore lost CHANGELOG entries for 1.11

- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/query/context.rb
- spec/graphql/execution/interpreter_spec.rb
- spec/graphql/query/context_spec.rb
Oops, if a field ran another graphql query inside its resolver body, then the inner query would clobber the thread context for the outer field. This change makes it so that the outer field will still have its runtime context after the inner query is finished. 
The performance impact looks negligible: 
```diff
-                           4.562  (± 0.0%) i/s -     23.000  in   5.043385s
+                           4.447  (± 0.0%) i/s -     23.000  in   5.174162s
```
Plus two more objects allocated 🤷
> Fix runtime state when fields run nested queries

- lib/graphql/execution/interpreter/arguments_cache.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/execution/lookahead.rb
- lib/graphql/query.rb
- lib/graphql/query/null_context.rb
- lib/graphql/schema/argument.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/field/connection_extension.rb
- lib/graphql/schema/input_object.rb
- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/schema/object.rb
- lib/graphql/schema/relay_classic_mutation.rb
- lib/graphql/schema/resolver.rb
- lib/graphql/schema/warden.rb
Some hashes in GraphQL-Ruby are by-type caches of things. Those will always have the _same objects_ (Classes) as keys, so we could use compare_by_identity for them (suggested in https://github.com/rmosolgo/graphql-ruby/pull/4431#discussion_r1163159395)
Initial results are good: 
```diff
-                           4.333  (± 0.0%) i/s -     22.000  in   5.082679s
+                           4.848  (± 0.0%) i/s -     25.000  in   5.158312s
-      26656   (9.4%)       26656   (9.4%)     Kernel#hash
+      17766   (2.7%)       17766   (2.7%)     Kernel#hash
-      26300   (9.3%)       26300   (9.3%)     Kernel#class
+      68174  (10.4%) …
```
> Use compare_by_identity on some runtime caches

- benchmark/run.rb
- lib/graphql/execution/interpreter/runtime.rb
This eliminates the creation and population of the non-null result name list, reducing memory pressure and running faster, especially for queries with lots of object results which have at least one non-null field in them. (Introspection is a great example -- every type, field, and argument becomes and object result with at least one non-null field.)
```diff 
$ be rake bench:profile_large_introspection
Run large introspection
-                            2.023  (± 0.0%) i/s -     21.000  in  10.407608s
+                            2.145  (± 0.0%) i/s -     22.000  in  10.262064s
- Total allocated: 16020644 bytes (125584 objects)
+ Total allocated: 15160324 bytes (113560 objects)
```
> Pass is_non_null instead of tracking a list of non-null result names

- lib/graphql/execution/interpreter.rb
- lib/graphql/execution/interpreter/runtime.rb
This is hit a lot at runtime, but it shouldn't change after `query.multiplex = ...` is assigned, so we can safely memoize it. 
```diff
Run large introspection
-                           2.059  (± 0.0%) i/s -     21.000  in  10.204161s
+                           2.077  (± 0.0%) i/s -     21.000  in  10.132087s
39   (8.0%)          39   (8.0%)     Kernel#class
480  (98.2%)          22   (4.5%)     Array#each
18   (3.7%)          18   (3.7%)     NilClass#===
17   (3.5%)          17   (3.5%)     GraphQL::Schema::Member::HasValidators#validators
16   (3.3%)          16   (3.3%)     GraphQL::Execution::Interpreter::Runtime#dead_result?
14   (2.9%)          14   (2.9%)     Kernel#hash
-         13 …
```
> Memoize current trace

- lib/graphql/execution/interpreter/runtime.rb
I remembered (while failing at #4451) that Hash access methods are optimized by Ruby but that optimization is lost for subclasses of `Hash`. So, what if we use a plain Hash instead of `GraphQLSelectionSet` for this runtime purpose? 
```diff 
Run large introspection
-                           2.136  (± 0.0%) i/s -     22.000  in  10.300445s
+                           2.180  (± 0.0%) i/s -     22.000  in  10.095250s
-         11   (2.2%)          11   (2.2%)     Hash#[]=
-          6   (1.2%)           6   (1.2%)     Hash#[] 
```
> Use a plain Hash for selection sets when possible

- lib/graphql/execution/interpreter/arguments_cache.rb
- lib/graphql/schema/argument.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/member/has_arguments.rb
Ugh, there's an `ArgumentsCache` class that caches arguments, but as far as I can tell, the main call in `runtime.rb`: 
https://github.com/rmosolgo/graphql-ruby/blob/a692a75384b6d446d7b7ee1355a4307871f14a63/lib/graphql/execution/interpreter/runtime.rb#L460-L462
didn't use a method that cached the results :S  
So, this PR makes it _actually_ cache and improves the caching for cases when arguments don't have a `prepare` hook or any validators by using `statically_coercible?`. 
Introspection benchmark, before: 
```
Run large introspection
2.157  (± 0.0%) i/s -     22.000  in  10.202996s
Mode: wall(1000)
Samples: 471 (1.46% miss rate)
GC: 3 (0.64%)
35   (7.4%)          35 …
```
> Cache resolved arguments better

- lib/graphql/tracing.rb
- lib/graphql/tracing/notifications_trace.rb
- spec/graphql/tracing/notifications_trace_spec.rb
Legacy tracing fired `execute_multiplex.graphql` to ActiveSupport::Notifications; this PR restores that behavior for the new `ActiveSupportNotificationsTrace` mixin, and adds a few missing requires (to bring it into parity with the rest of the new Trace modules).
> add `execute_multiplex.graphql` to NotificationsTrace

- javascript_client/src/subscriptions/ActionCableSubscriber.ts
- javascript_client/src/subscriptions/addGraphQLSubscriptions.ts
- javascript_client/src/subscriptions/createActionCableHandler.ts
`ActionCableSubscriber` and `createActionCableHandler` currently do not accept a configurable `channelName` for the cable. This is an effort to support passing `channelName` down to ActionCable.
Fixes #4459
> Accept optional channelName for ActionCable handler and subscriptions

- lib/graphql/language/lexer.rb
- spec/graphql/language/lexer_examples.rb
The rewritten lexer in https://github.com/rmosolgo/graphql-ruby/pull/4369 removed UTF8 forced encoding.
It's possible for applications to force encode document strings themselves before passing it to the GraphQL gem, but it should be done at this layer to ensure that invalid encoding is properly handled.
Two questions:
1. is there any reason not to restore this behaviour?
2. is this the proper place? Previously it was done in 3 separate places, but with the new simpler lexer I believe this should cover it.
cc @tenderlove
> Force UTF-8 encoding in lexer

- lib/graphql/filter.rb
- lib/graphql/language/document_from_schema_definition.rb
- lib/graphql/query.rb
- lib/graphql/schema.rb
- lib/graphql/schema/printer.rb
- lib/graphql/schema/warden.rb
- spec/graphql/language/document_from_schema_definition_spec.rb
- spec/graphql/query_spec.rb
- spec/graphql/schema/printer_spec.rb
- spec/graphql/schema/warden_spec.rb
As part of deprecating `GraphQL::Filter`, it should be possible to make a warden without one.
TODO:
> Don't require a filter for Warden

- lib/graphql/query/null_context.rb
- spec/graphql/query/null_context_spec.rb
This PR adds the `fetch`, `dig`, and `key?` methods to `GraphQL::Query::NullContext` for consistency with `GraphQL::Query::Context`
> GraphQL::Query::NullContext support for fetch, dig, and key?

- lib/graphql/query.rb
- lib/graphql/schema.rb
- lib/graphql/tracing/legacy_trace.rb
- spec/graphql/backtrace_spec.rb
- spec/graphql/schema_spec.rb
- spec/graphql/tracing/legacy_trace_spec.rb
- spec/support/dummy/schema.rb
Previously, using a legacy `tracer ...` would silently attach a new `trace_class` called `LegacyTrace` whose only job was to call legacy tracers. However, if the parent class has new-style `trace_with` modules attached, `LegacyTrace` wouldn't call them because those modules weren't in `LegacyTrace`'s inheritace. 
This branch takes the behavior of calling legacy tracers and puts it in a _module_ instead, so that it can be added to an intact inheritance chain when it's needed, without disrupting `trace_with` setups from the parent class. (The old `LegacyTrace` class is left in place for compatibility, but error messages point to this new module now.) 
Fixes #4486
> Fix tracer compatibility with inheritance

- lib/graphql/schema/warden.rb
- spec/graphql/execution/lookahead_spec.rb
Fixes #4478 (particularly https://github.com/rmosolgo/graphql-ruby/issues/4478#issuecomment-1551598398)
> Fix Lookahead with AlwaysVisible

- spec/spec_helper.rb
RubyMine uses its own internal reporter, and needs `Minitest::Reporters` to be disabled to function properly. This change will let RubyMine users run tests in this repo out-of-the-box without needing to patch this themselves.
I know it's editor-specific, so I'd understand if this is rejected on those grounds, but it's a small just just to the spec_helper, so it won't hurt regular consumers of the gem.
> Disable `Minitest::Reporters` for RubyMine

- guides/queries/tracing.md
- lib/graphql/query.rb
- lib/graphql/schema.rb
- spec/graphql/execution/multiplex_spec.rb
- spec/graphql/query_spec.rb
This way, you can take a trace instance passed to `GraphQL.parse` and provide it for query execution. (The same thing was posssible with `context[:tracers]` but it hadn't been totally added for the new Trace API.)
> Accept trace instances during query execution

- lib/graphql/execution/interpreter/runtime.rb
Really this is just a readability improvement, but there's a nice perf side effect, too :)
This change speeds up `rake bench:profile_large_result` benchmark by about 1.8%.
Baseline (master at cbdae7612372ac5d4edf04c5e6a2404f8471671c)
```
1.000  i/100ms
8.149  (± 0.0%) i/s -    815.000  in 100.061220s
```
After this change:
```
1.000  i/100ms
8.295  (± 0.0%) i/s -    830.000  in 100.093047s
```
<hr>
This logic used to be more complicated (`t.metadata[:type_class] == owner_type`), but has …
> Speed up lookup of possible types for Fragments

- lib/graphql/language/printer.rb
- spec/graphql/language/printer_spec.rb
This PR adds `GraphQL::Language::Printer` support for printing type system extensions. Prior to this change type system extension nodes printed like this:
```
"#<GraphQL::Language::Nodes::SchemaExtension:0x000000010c3d29a0>"
```
> Print type system extensions

- spec/graphql/pagination/connections_spec.rb
This PR fixes the following test failure using Ruby 3.3.0dev:
```console
$ ruby -v
ruby 3.3.0dev (2023-06-14T23:47:25Z master 0c55ef1150) [x86_64-darwin19]
$ bundle exec ruby -Ispec spec/graphql/pagination/connections_spec.rb
F.....
Finished tests in 0.009158s, 655.1649 tests/s, 1856.3005 assertions/s.
Failure:
GraphQL::Pagination::Connections#test_0004_lets unrelated NoMethodErrors bubble up [spec/graphql/pagination/connections_spec.rb:120]
Minitest::Assertion: Expected "undefined method `no_such_method' for an instance of ConnectionErrorTestSchema::BadThing"
to include "undefined method `no_such_method' for <BadThing!>"
.
6 tests, 17 assertions, 1 failures, 0 errors, 0 skips
```
That error message has been changed by https://github.com/ruby/ruby/commit/e7b8d32e in Ruby 3.3.0dev.
cf. …
> Fix a test failure using Ruby 3.3.0dev

- graphql-c_parser/ext/graphql_c_parser_ext/lexer.c
- graphql-c_parser/ext/graphql_c_parser_ext/lexer.rl
- graphql-c_parser/ext/graphql_c_parser_ext/parser.c
- graphql-c_parser/ext/graphql_c_parser_ext/parser.y
- graphql-c_parser/lib/graphql/c_parser.rb
- spec/graphql/language/parser_spec.rb
It looks like the C _lexer_ handled this properly, but the C parser didn't handle a `BAD_UNICODE_ESCAPE` token in the same way as the Ruby parser.
Fixes #4514
> Standardize bad UTF-8 handling in C parser

- lib/graphql/dataloader/source.rb
In the  discussion https://github.com/rmosolgo/graphql-ruby/discussions/4512, we discovered an issue with `sync` related to 
https://github.com/rmosolgo/graphql-ruby/blob/250a7248cad42f387d2a784e5bdb4b14e5845c30/lib/graphql/dataloader/source.rb#L74
When the `pending_keys`, which is a duplicate of `@pending_keys`, becomes large, it tends to consume much Ruby CPU resources, particularly when dealing with `ActiveRecord` as a `Source` key.
This PR modify the function of `sync` so that it only waits for the key on which `load` was called.
https://github.com/rmosolgo/graphql-ruby/blob/250a7248cad42f387d2a784e5bdb4b14e5845c30/lib/graphql/dataloader/source.rb#L37
https://github.com/rmosolgo/graphql-ruby/blob/250a7248cad42f387d2a784e5bdb4b14e5845c30/lib/graphql/dataloader/source.rb#L49
In the …
> Improve GraphQL::Dataloader::Source#sync's efficiency

- Rakefile
- benchmark/run.rb
- lib/graphql/schema/addition.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/member/build_type.rb
Tighten up this part of schema boot to improve load times
This improved allocations by >25% (and a lot of them are long-lived allocations for the schema, anyways, which are already very optimized)
```diff 
-   GC: 11323 (16.40%)
+   GC: 6003 (11.23%)
- Total allocated: 14673646 bytes (105685 objects)
+ Total allocated: 13545718 bytes (76220 objects)
```
> Improve performance of Schema::Addition

- guides/related_projects.md
It hasn't been compatible since graphql-ruby < 1.9, and is no longer supported, as mentioned here: https://github.com/rmosolgo/graphql-ruby/issues/2398#issuecomment-515049940
> Remove mention of graphql-libgraphqlparser

- lib/graphql/tracing/appoptics_trace.rb
- lib/graphql/tracing/data_dog_trace.rb
- lib/graphql/tracing/platform_trace.rb
- spec/graphql/tracing/appsignal_trace_spec.rb
> Fix running multiple platform traces at once

- guides/authorization/pundit_integration.md
Pretty sure this is a typo. If it's not, my apologies for misreading the docs.
> fix: typo in pundit resolver authorization example

- guides/dataloader/sources.md
- lib/graphql/dataloader.rb
- lib/graphql/dataloader/source.rb
- spec/graphql/dataloader/source_spec.rb
This adds a way to deduplicate `.load(...)` calls when the passed-in object is equivalent but doesn't implement `.hash` to the same value.
> Add Source#result_key_for

- lib/graphql/language/lexer.rb
- spec/graphql/language/lexer_examples.rb
Triple quotes at the beginning and end of lines shouldn't be removed if they have been escaped.  IOW only the leading and trailing """ should be removed from the token
> Fix block string quote unescaping

- lib/graphql/schema/addition.rb
- spec/graphql/language/document_from_schema_definition_spec.rb
This is a bug-fix for #4594 and has been validated using the spec scenario created for triaging the initial issue.
**Summary:** Enum_Value nodes were not being traversed in the `GraphQL::Schema:Addition` AST-walk, resulting in any ENUM_VALUE targeted Directives not being added to the Schema IDL during document generation. This would produced incomplete IDL output that breaks downstream validators and codegenerators.
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205346733139652
> (fix) Enum_Value Directive missing from Schema IDL

- lib/graphql/schema/resolver.rb
- spec/graphql/schema/resolver_spec.rb
If you write a resolver's authorized method with a `return false, nil` in it (to early-return a value of `nil`), it was treating this just as `return false` and raising, because the early-return value was not truthy. Instead explicitly check for an array value before splitting it in two.
I also did `ready?` while I was here since it had the same pattern.
~~The tests are "correct" but won't fail even without my "fix" because the test schema doesn't implement `def unauthorized_object(unauthorized_error)`, and there are a bunch of tests already relying on it being not implemented. Not sure what the best approach is.~~
*edit: I realized after posting that it was easier and more correct to test for a false/nil distinction which sidesteps the `unauthorized_object` issue*
@rmosolgo @dougedey
> Support early-return of falsey values from ready/authorized

- lib/graphql/schema/field/connection_extension.rb
- spec/integration/mongoid/star_trek/schema.rb
These referenced `GraphQL::Relay::BaseConnection` which no longer exists
> Remove unused legacy connection code

- javascript_client/src/subscriptions/createRelaySubscriptionHandler.ts
When using this handle with the `createActionCableHandler`, , an error is thrown because it expects the observer object to have an `onCompleted` method, but `onComplete` is currently passed from the `createRelaySubscriptionHandler`. 
For reference: https://github.com/rmosolgo/graphql-ruby/blob/master/javascript_client/src/subscriptions/createActionCableHandler.ts#L60
Fixes https://github.com/rmosolgo/graphql-ruby/issues/4604
> fix: onCompleted typo in createRelaySubscriptionHandler

- Rakefile
- benchmark/run.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/schema/relay_classic_mutation.rb
- lib/graphql/schema/resolver.rb
So far, my benchmarks have all been for really big queries. But small queries shed light on other performance bottlenecks, like this one. 
```diff 
-                         327.533  (± 2.7%) i/s -      3.300k in  10.083216s
+                         359.747  (± 3.6%) i/s -      3.605k in  10.035778s
...
- Total allocated: 108864 bytes (1012 objects)
+ Total allocated: 97896 bytes (949 objects)
```
> Add small query benchmark, fix field args check

- lib/graphql/dataloader.rb
- lib/graphql/dataloader/source.rb
- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/dataloader_spec.rb
> Clear Dataloader cache around mutation root fields

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/schema/list_spec.rb
I noticed that this code was getting called over and over again, and this makes sense in some cases, because fragments may apply conditionally and directives depend on the runtime object. But in the simplest case, it was doing repeat work, over and over. So I added a cache for that simplest case. ~~(It could probably be improved to cache based on `type`, too.)~~ I went ahead and did it because it covers the built-in introspection query much better.
- `~/code/graphql-ruby $ EAGER=1 be rake bench:profile_large_result`
```diff 
-                         358.825  (± 6.1%) i/s -      3.600k in  10.082144s
+                         376.938  (± 3.2%) i/s -      3.774k in  10.023754s
-        117   (2.1%)          72 …
```
> Cache the result of gathered selections for later re-use

- lib/generators/graphql/install/templates/base_mutation.erb
- lib/generators/graphql/install/templates/mutation_type.erb
- lib/generators/graphql/templates/base_argument.erb
- lib/generators/graphql/templates/base_connection.erb
- lib/generators/graphql/templates/base_edge.erb
- lib/generators/graphql/templates/base_enum.erb
- lib/generators/graphql/templates/base_field.erb
- lib/generators/graphql/templates/base_input_object.erb
- lib/generators/graphql/templates/base_interface.erb
- lib/generators/graphql/templates/base_object.erb
- lib/generators/graphql/templates/base_scalar.erb
- lib/generators/graphql/templates/base_union.erb
- lib/generators/graphql/templates/graphql_controller.erb
- lib/generators/graphql/templates/loader.erb
- lib/generators/graphql/templates/mutation.erb
- lib/generators/graphql/templates/node_type.erb
- lib/generators/graphql/templates/query_type.erb
- lib/generators/graphql/templates/schema.erb
Adds `frozen_string_literal` comment to all templates that did not have it. reduce method size and complexity in the `graphql_controller` template.
> makes install templates more rubocop friendly.

- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/introspection/dynamic_fields.rb
- lib/graphql/introspection/entry_points.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/introspection_system.rb
- lib/graphql/schema/member/has_fields.rb
- lib/graphql/static_validation/rules/fields_will_merge.rb
- lib/graphql/static_validation/validation_context.rb
I found a faster way to do this field lookup. And apparently `def_delegators` costs an allocation?!
```
EAGER=1 be rake bench:profile_small_result
```
```diff
-                         379.826  (± 3.2%) i/s -      3.800k in  10.015388s
+                         473.957  (± 3.6%) i/s -      4.738k in  10.010388s
- Total allocated: 90240 bytes (904 objects)
+ Total allocated: 75072 bytes (788 objects)
```
But, it makes `profile_large_result` slower: 
```diff 
-                           8.338  (± 0.0%) i/s -     84.000  in  10.079985s
+                           8.160  (± 0.0%) i/s -     82.000  in  10.070237s
- Total allocated: 3461520 …
```
> Improve runtime field lookup

- lib/graphql/analysis/ast.rb
- lib/graphql/analysis/ast/analyzer.rb
- spec/graphql/analysis/ast_spec.rb
This PR adds a new `AST::Analyzer.visit?` hook that allows an analyzer to run without being included in visitation. This is different from the existing `AST::Analyzer.analyze?` hook that stops an analyzer from running entirely. This new hook is useful for analyzers that return precomputed/cached values.
Analysis can be expensive, so we may want to cache some analysis results for reuse across repeat requests. For example, complexity scoring seems like it should be easy to reuse:
```ruby
class PrecomputedComplexity < GraphQL::Analysis::AST::QueryComplexity
def result
query.context[:precomputed_complexity] || super
end
end
```
The above example isn't effective because the visitor pass itself is the primary overhead. If this were the only queued analyzer, it would still trigger a visitor pass …
> Allow precomputed analyzers to run without visitation

- lib/graphql/analysis/ast.rb
- lib/graphql/execution/lookahead.rb
- lib/graphql/language/nodes.rb
- lib/graphql/static_validation/literal_validator.rb
- lib/graphql/static_validation/rules/required_arguments_are_present.rb
- lib/graphql/static_validation/rules/required_input_object_attributes_are_present.rb
- lib/graphql/tracing/appoptics_trace.rb
- lib/graphql/tracing/appoptics_tracing.rb
Cleans up some pedantic details that reminded me of a Shopify Readme titled **"Ruby code that looks silly to a low-level programmer"**...
> 3. _Always_ use inline operations. Which means, prefer the use of `map! {...}` versus `map {...}`. Without the `!`, the interpreter will create a new Array. Only use the `map{...}` if the creation of a new array is desired. The same applies for other methods like `select!`, `filter!`, `rotate!`, `reverse!` and etc.
This is generally a pretty easy pattern to spot: when chaining multiple array transforms, all the later transforms should inline.
> Tidy chained array transforms

- graphql-c_parser/ext/graphql_c_parser_ext/parser.c
- graphql-c_parser/ext/graphql_c_parser_ext/parser.y
Fix: https://github.com/rmosolgo/graphql-ruby/issues/4640
`GraphQL_Language_Nodes_` are global variables and their value is assigned the return value of `const_get` which contrary to `rb_define_class_*` isn't pinned.
So they must be registered with `rb_global_variable`.
On a side note, `rb_global_variable` must be called before the variable is assigned, not after.
> graphql-c_parser: Properly register global variables

- lib/graphql/execution/interpreter/runtime.rb
👋🏼 Hey @rmosolgo. I don't think we've crossed paths since the Batman.js days :)
I'm in the process of writing a new directive, and got hit by this little bug in testing. It looks like it was introduced as part of https://github.com/rmosolgo/graphql-ruby/pull/4425, which was merged relatively recently.
> Reference correct variable in #merge-into

- Rakefile
- benchmark/run.rb
- lib/graphql/language/block_string.rb
- lib/graphql/language/document_from_schema_definition.rb
- lib/graphql/language/printer.rb
- lib/graphql/schema.rb
- lib/graphql/schema/member/base_dsl_methods.rb
- lib/graphql/schema/member/has_interfaces.rb
- lib/graphql/schema/warden.rb
- spec/graphql/schema/build_from_definition_spec.rb
Fixes #4635 
Includes some speedups to the SDL printer: 
```diff
$ be rake bench:profile_to_definition 
-        to_definition      1.481k (± 3.6%) i/s -      7.398k in   5.001939s
+        to_definition      1.695k (± 5.1%) i/s -      8.550k in   5.058730s
- Total allocated: 81119 bytes (672 objects)
+ Total allocated: 54327 bytes (345 objects)
```
About half as many objects and 14% faster
> Use `extend schema` when the schema has directives

- lib/graphql/schema.rb
- spec/graphql/tracing/trace_modes_spec.rb
Fixes #4632 
TODO: 
Currently, a child schema class _rebuilds_ a special modes out of inherited modules + its own default base class. So the child class in the test needs to re-call `trace_mode ...` with a class to override that created class. 
Can that be made to work _right_?
> Add Schema.default_trace_mode

- .github/workflows/ci.yaml
- graphql.gemspec
`required_ruby_version` should be `2.7` because numbered parameters are used for blocks now.
Also I updated the Ruby versions in the CI workflow to be consistent throughout
> Bump required_ruby_version to 2.7

- lib/graphql/execution/interpreter/runtime/graphql_result.rb
We just updated one of our core Shopify apps to 2.1.1 yesterday, and after rebasing I got hit with the same error that https://github.com/rmosolgo/graphql-ruby/pull/4639 intended to fix. 
Due to some bad timing, https://github.com/rmosolgo/graphql-ruby/pull/4621/commits/cf081056e0c9a73f1492d57b5fd09a45855842da —which was authored before my patch—was merged the day _after_ https://github.com/rmosolgo/graphql-ruby/pull/4639, losing the change I contributed.
This PR includes the same change, but for the new `graphql_result.rb` file :D
Is it possible to cut a 2.1.2 with this patch included? It would be much appreciated! 🙏🏼
> Include patch from #4639 in graphql_result.rb

- graphql.gemspec
It's used by the parser, and in Ruby 3.3 it's not longer a default gems, but was promoted as a bundled gem. So it need to be declared.
See: https://bugs.ruby-lang.org/issues/19702
Fixes #4650
> Declare racc as a runtime dependency

- lib/graphql/schema.rb
- spec/graphql/tracing/legacy_trace_spec.rb
- spec/graphql/tracing/trace_modes_spec.rb
Trying to fix https://github.com/open-telemetry/opentelemetry-ruby-contrib/issues/689#issuecomment-1759908542
> Fix OpenTelemetry legacy trace

- Rakefile
- benchmark/run.rb
- lib/graphql/schema.rb
- lib/graphql/schema/warden.rb
- spec/graphql/schema_spec.rb
It was already mentioned in the code how a large schema can incur a costly `Hash#merge` when using `.references_to`:
https://github.com/rmosolgo/graphql-ruby/blob/9eee764c074aad229ccf223de21b529dcfc0a2cd/lib/graphql/schema.rb#L553-L555
But the implementation there didn't address when a schema _did_ have some inherited types. In that case, the cost was still paid of merging the hashes, even for a very small query. 
We can re-work this, improving an existing implementation of `.references_to(type_name)`, so that the big, merged hash isn't used by GraphQL-Ruby execution, so it's never made at all. 
For a small schema with inherited types, it can make a big difference. The benchmark I added here: 
```diff 
-      Run small query      4.586k (± 8.1%) i/s -     23.256k in   5.108886s
+     Run …
```
> Avoid Hash#merge on large subclass schemas

- lib/graphql/schema/build_from_definition.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/loader.rb
- spec/graphql/schema/field_spec.rb
Fixes #4353  
Also, rather than clean up some areas that set `connection: ...` when building a schema, I removed it. That will make the field use the default inference in `def connection?`.
> Don't assume connection behaviors for types named Connection

- guides/type_definitions/interfaces.md
- lib/graphql/schema/interface.rb
- spec/graphql/schema/interface_spec.rb
Previously, the `DefinitionMethods` module was added (via `extend`) right away, and later inclusions would take priority over it. Now, that module is added as late as possible, so it will override any previously-added methods. 
Fixes #4657 
Another approach would be to use `prepend` on the singleton class. We can look into it if this lazy-`extend` approach doesn't work.
> Fix definition_methods with implements

- lib/graphql/pagination/connection.rb
- spec/graphql/pagination/connection_spec.rb
> Fix scoped detection in Connection#initialize

- lib/graphql/schema.rb
- lib/graphql/schema/warden.rb
Fixes #4602 
Schema _class_ methods got a third parameter added, `context`, to handle dynamic schema member. Instance-based methods (like `Schema#get_field`) didn't get that new parameter. 
I'm adding it here so that the call in `Warden#get_field` won't raise an error, but the argument is unused.
> Fix Warden#get_field in 1.13.x

- guides/mutations/mutation_classes.md
- guides/schema/definition.md
- lib/graphql/schema.rb
- spec/graphql/dataloader_spec.rb
- spec/graphql/schema/argument_spec.rb
- spec/graphql/schema/resolver_spec.rb
- spec/graphql/schema/subscription_spec.rb
`resolve_type` really _is_ part of safely using `loads:`. Make it required in GraphQL-Ruby 2.2.0. 
Fixes #4643
> Require resolve_type for loads:

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/execution/interpreter_spec.rb
#4623 Could produce execution loops in cases like the added test here, where a fragment is reused later on. 
I'm interested in trying out this cache again, but for now, yank it.
> Remove gathered selections cache

- lib/graphql/schema.rb
- spec/graphql/logger_spec.rb
Oops -- sometimes `Rails` is present but `Rails.logger` isn't defined!
> Fix default_logger when Rails doesn't have a logger

- lib/graphql/subscriptions/action_cable_subscriptions.rb
Query is the first positional argument for `Schema#execute`, not a kwarg.
At least 2 instances of users trying to use the example and bumping into cryptic errors, [this guy](https://stackoverflow.com/questions/66877742/ruby-graphql-and-or-actioncable-dumping-core-on-subscription) and myself ha.
> Fix ActionCable subscriptions channel example

- guides/schema/generators.md
Hi, first of all, thank you for making this awesome gem.
When I used the generator, I noticed a discrepancy between the options listed in the documentation and the options that were actually enabled.
This PR adds the following to the documentation, which are valid options for the current generator:
- `directory`
- `skip-mutation-root-type`
- `api`
```bash
$ pwd
spec/dummy
$ bundle exec rails g graphql:install --help
Usage:
bin/rails generate graphql:install [options]
Options:
[--skip-namespace], [--no-skip-namespace]                    # Skip namespace (affects only isolated engines)
[--skip-collision-check], [--no-skip-collision-check]        # Skip collision check
[--directory=DIRECTORY]                                      # Directory where generated files should be saved …
```
> Add install generators options that were missing in the documentation.

- guides/parser_cache.md
- lib/graphql/railtie.rb
👋 I noticed recently that this gem uses the bootsnap iseq cache dir as a basis to enable caching or not. This doesn't make much sense to me because the parser cache has nothing to do with bootsnap. This was causing problems for me on an app that precompiled bootsnap cache on CI, and marked the cache as readonly. Naturally, this caused problems when the GraphQL parser cache got written to.
Since we can't precompile this cache, and it isn't dependent on bootsnap, I think we can simply use a different directory and avoid these conditionals. This will prevent bootsnap cache to be polluted/extended by the graphql gem, and allow more apps to leverage GraphQL caching. WDYT?
> Set GraphQL cache regardless of bootsnap

- lib/graphql/schema.rb
- spec/graphql/tracing/trace_modes_spec.rb
Oops -- I _knew_ I was going to need something like this, but I forgot to actually test for it, then I removed it as unused in https://github.com/rmosolgo/graphql-ruby/commit/ef53f448d49d693e05fda801645370e14adc6d5a#diff-ca02a7189be9dc9f1c0d328028ba139f8be8da82eca96bbfccd3c098b5ad03f7L173
In a subclass, a custom trace mode should get the same default base trace class as the default mode.
> Fix custom trace mode using default base class

- guides/javascript_client/relay_subscriptions.md
- javascript_client/src/subscriptions/__tests__/createActionCableHandlerTest.ts
- javascript_client/src/subscriptions/createActionCableHandler.ts
- javascript_client/src/subscriptions/createRelaySubscriptionHandler.ts
This change should support recent Relay's  "Persisted Queries". In that case, Relay sends along a has as `id`, so this handler uses that along with the client name to integrate with the OperationStore.
> Support Relay persisted queries in ActionCable handler

- lib/graphql/schema/input_object.rb
Issue:
* https://github.com/Shopify/shopify/issues/462096
Reason for change:
This message is exposed publicly [[thread](https://shopify.slack.com/archives/C04BSPBE61K/p1698868028519919?thread_ts=1698867951.169129&cid=C04BSPBE61K)].
TL;DR:
When constructing a bad input, e.g. 
```
{
"input"=>{
"handle"=>"new-product", 
"title"=>"New product",
"status"=>"ACTIVE",
"vendor"=>"Shop 1",
"productType"=>"",
"descriptionHtml"=>"",
"giftCard"=>false,
"giftCardTemplateSuffix"=>nil, 
"options"=>["Color", "Size"], 
"requiresSellingPlan"=>false,
"tags"=>[],
"templateSuffix"=>nil,
"optionValues"=>[
{"name"=>"Color", "values"=>["Red"]}, 
{"name"=>"Size", "values"=>["Small"]}
]
}
}
```
for `productOptionsCreate` mutation,
the error response returned is
```
{
"errors":[
{
"message": "Variable $input of type …
```
> Change `INVALID_OBJECT_MESSAGE` to omit `to_h` and `to_unsafe_h`

- lib/graphql/backtrace/trace.rb
- lib/graphql/query.rb
Oops -- previously, the cleanup of `multiplex.context` caused this to break when `@defer` was used. It would get cleaned up, but then, when deferrals were running, there'd be no context to read or write from. 
Now, the state is not cleaned up -- and it doesn't have to be, since it's local to the Trace instance. 
I don't have a good test for this repo, but I do have a `backtrace: true` test in GraphQL-Pro's defer tests now.
> Fix { backtrace: true } with @defer

- lib/graphql/language/block_string.rb
- spec/graphql/language/block_string_spec.rb
GraphQL spec requires to strip lines which are not empty but contain only whitespace. The current implementation doesn't remove such lines. This probably doesn't matter in practice, but it's always nice to be spec-compliant.
Quoting the [block string spec](https://spec.graphql.org/October2021/#BlockStringValue()):
```
4. While the first item line in lines contains only WhiteSpace:
a. Remove the first item from lines.
5. While the last item line in lines contains only WhiteSpace:
a. Remove the last item from lines.
```
> Fix `BlockString.trim_whitespace` to conform to spec.

- guides/javascript_client/graphiql_subscriptions.md
- guides/subscriptions/ably_implementation.md
- guides/subscriptions/action_cable_implementation.md
- guides/subscriptions/pusher_implementation.md
- javascript_client/package.json
- javascript_client/src/subscriptions/__tests__/createAblyFetcherTest.ts
- javascript_client/src/subscriptions/__tests__/createActionCableFetcherTest.ts
- javascript_client/src/subscriptions/__tests__/createPusherFetcherTest.ts
- javascript_client/src/subscriptions/createAblyFetcher.ts
- javascript_client/src/subscriptions/createActionCableFetcher.ts
- javascript_client/src/subscriptions/createPusherFetcher.ts
I've been diving into GraphiQL support lately and I intend to add support for GraphQL-Ruby's subscription transports:
> Add GraphiQL support for subscriptions

- lib/graphql/schema/argument.rb
- spec/graphql/schema/mutation_spec.rb
- spec/support/jazz.rb
Issue: https://github.com/rmosolgo/graphql-ruby/issues/4715
I _think_ this is what @eapache-opslevel was aluding to, it checks to see if the prepare method exists on the object or the owner (class method), and handles each approproiately
* For Object, don't send the context, it'll be there already
* For the Owner, send the context (like we do already for prepare blocks)
* If neither exist, give a clear error instead of a no method found error.
> Add support for class level prepare methods on arguments

- guides/fields/resolvers.md
- guides/getting_started.md
- lib/generators/graphql/install_generator.rb
- lib/generators/graphql/templates/base_resolver.erb
After raising #4468 and getting a thumbs-up from @rmosolgo about it, I've finally gotten around to issuing this PR.
I've updated the install generator to generate a base resolver class, and directed readers of the Getting Started guide to use this class when defining fields. Similar changes have been made elsewhere in the documentation as well.
Ultimately, the goal of this change is to alter the way types such as `QueryType` are defined. Currently, the suggestion is:
```ruby
module Types
class QueryType < Types::BaseObject
include GraphQL::Types::Relay::HasNodeField
include GraphQL::Types::Relay::HasNodesField
field :repos, [RepoType], null: false
def repos
Repo.all
end
field :repo, RepoResult, null: false do
argument :id, ID, required: true
end
def repo(id:)
Repo.find(id)
end
field …
```
> Use resolver classes for queries by default

- lib/graphql/language/parser.rb
- spec/graphql/schema/build_from_definition_spec.rb
Fixes #4737 
oops, it was looking for directives _before_ `implements`, and evidently there was no test for this!
> Fix SDL interface directives in new parser

- lib/graphql/dataloader.rb
I removed these invariants in #4625, but they might have helped catch the bug from https://github.com/rmosolgo/graphql-ruby/issues/4739#issuecomment-1866671563. 
Also, this check for `finished = ...` wasn't quite right, because the fiber might `yield`, returning a value, and causing these fibers to be pushed away before they were really finished. 
Finally, I think the `manager ` fiber here was not really needed. It was added along the way to supporting the Async gem (and eventually became a `Sync do ... end` call), but it's not necessary here.
> Fix dataloader for hanging fibers

- lib/graphql/language/parser.rb
- spec/graphql/query_spec.rb
> Parser: Fix handling of single-token document

- lib/graphql/dataloader.rb
- lib/graphql/dataloader/source.rb
- spec/graphql/dataloader_spec.rb
I can't find a way to terminate a Fiber that received a transfer call, see: 
- #4745 
- #4747 
- https://bugs.ruby-lang.org/issues/20089
- https://bugs.ruby-lang.org/issues/20081
So, I'm removing it from the library until those issues are sorted out. 
Unfortunately, AsyncDataloader leaves dangling fibers anyways, I think because it uses `Fiber#transfer` under the hood. I may address that in another PR -- but I'm hoping my open issues in Ruby are addressed such that I can continue using the `async` gem!
> Remove Fiber#transfer support

- lib/graphql/dataloader.rb
- lib/graphql/dataloader/source.rb
- spec/graphql/dataloader_spec.rb
Addressing the issue from https://github.com/rmosolgo/graphql-ruby/issues/4745#issuecomment-1868101409 and #4747
TODO:
> Dataloader: fix for large queries and run_isolated

- lib/generators/graphql/install_generator.rb
- lib/generators/graphql/templates/base_resolver.erb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
Oops, this path and constant didn't match.
> Fix module and path of generated BaseResolver

- javascript_client/src/subscriptions/__tests__/createActionCableFetcherTest.ts
- javascript_client/src/subscriptions/createActionCableFetcher.ts
- Fix Typescript type for `url`
- Use supplied `url` instead of static "/graphql" path
- Support overloading channel name. For example, our channel is "GraphQLChannel" instead of "GraphqlChannel"
> Fix ActionCable fetcher

- guides/dataloader/async_dataloader.md
- lib/graphql/dataloader/async_dataloader.rb
- spec/graphql/dataloader/async_dataloader_spec.rb
By limiting the _source_ loop to use the `async` gem, I limit the "Fiber mayhem" that has led to so many bugs. The source loop is tight; sources only wait for other sources, so it never re-enters GraphQL execution. It doesn't have arbitrary `dataloader.run` depth like GraphQL execution does.
But, it means that I/O in plain resolvers _won't_ be run async.
> AsyncDataloader: only run Sources async

- lib/graphql/execution/interpreter/runtime.rb
Originally proposed in #4507 , but we don't have a Ruby 2.4 CI job anymore so it should be mergeable.
> Use `all?` to check types directly

- lib/graphql/language/parser.rb
- spec/graphql/language/parser_spec.rb
Oops, there _was_ a method to parse enum names, but this code wasn't using it.
Fixes #4770
> Fix enum values named type

- lib/graphql/schema/enum.rb
The example inherited from `GraphQL::Enum` - a constant that doesn't exist. 
Update the example to inherit from `GraphQL::Schema::Enum` instead.
> docs: fix example given for GraphQL::Schema::Enum

- lib/graphql/pagination/array_connection.rb
- lib/graphql/pagination/relation_connection.rb
- spec/integration/mongoid/graphql/relay/mongo_relation_connection_spec.rb
- spec/integration/rails/graphql/relay/array_connection_spec.rb
- spec/integration/rails/graphql/relay/relation_connection_spec.rb
- spec/support/connection_assertions.rb
About hasNextPage, the relay spec says: 
> [HasNextPage](https://relay.dev/graphql/connections.htm#HasNextPage())(allEdges, before, after, first, last)
> 
>     If first is set:
>         Let edges be the result of calling [ApplyCursorsToEdges](https://relay.dev/graphql/connections.htm#ApplyCursorsToEdges())(allEdges, before, after).
>         If edges contains more than first elements return true, otherwise false.
>     If before is set:
>         If the server can efficiently determine that elements exist following before, return true.
>     Return false.
But GraphQL-Ruby's `max_page_size` was causing it to take the "if first is set..." branch even when the client didn't provide `first`. 
After this change, it will fall down to the "Return false" branch of that spec unless `first` is …
> Fix hasNextPage when max_page_size is set

- guides/queries/complexity_and_depth.md
A frequent source of confusion internally. This summarizes the nuances of the complexity scoring process for the benefit of all.
> "How complexity scoring works" guide

- guides/dataloader/testing.md
- Fix typo with numbers of records
- Remove `load` method since the dataloader returns a record, at least according to the example here: https://graphql-ruby.org/dataloader/sources.html#example-loading-activerecord-objects-by-id.  I included that implementation in the example for reference.
> Fix typos in DataLoader testing doc + add source example

- guides/operation_store/active_record_backend.md
The order of operations was wrong in the migration
```
Caused by:
ActiveRecord::StatementInvalid: PG::UndefinedTable: ERROR:  relation "graphql_operations" does not exist /usr/local/bundle/gems/activerecord-7.0.3.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `exec' /usr/local/bundle/gems/activerecord-7.0.3.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:48:in `block (2 levels) in execute' /usr/local/bundle/gems/activesupport-7.0.3.1/lib/active_support/concurrency/share_lock.rb:187:in `yield_shares' /usr/local/bundle/gems/activesupport-7.0.3.1/lib/active_support/dependencies/interlock.rb:41:in `permit_concurrent_loads' /usr/local/bundle/gems/activerecord-7.0.3.1/lib/active_record/connection_adapters/postgresql/database_statements.r …
```
> [FIX] Update active_record_backend.md to have migration in correct order

- lib/graphql/coercion_error.rb
- spec/graphql/schema/scalar_spec.rb
> Fix CoercionError handling with null

- guides/queries/timeout.md
- lib/graphql/analysis/ast.rb
- lib/graphql/query.rb
- lib/graphql/query/validation_pipeline.rb
- lib/graphql/static_validation/validator.rb
- spec/graphql/analysis/ast_spec.rb
Fixes #4629 
I think this will be fair to apply to analysis too, since that's usually CPU work, like static validation. Please leave a comment here if you have a concern about it -- another implementation would be to add a separate `analysis_timeout ...` option.
> Apply validate_timeout to analysis, too

- javascript_client/src/subscriptions/__tests__/createActionCableHandlerTest.ts
- javascript_client/src/subscriptions/createActionCableHandler.ts
Oops -- somehow this entered back in https://github.com/rmosolgo/graphql-ruby/commit/cf0a3fe12f54e1ce3b3e3ae87fa78d8ee111f655#diff-9957e220f3cd45075c8bd11a71aa74970869a76e46eaff6007685295c806c6fdR45, but I don't think it should be there. 
Fixes #4792
> ActionCable: don't use send action

- guides/queries/tracing.md
- lib/graphql/tracing/data_dog_trace.rb
- lib/graphql/tracing/data_dog_tracing.rb
- spec/support/datadog.rb
Backport changes from: https://github.com/rmosolgo/graphql-ruby/pull/4776
> Backport datadog `span_type` change  to 2.0.x

- lib/graphql/dataloader/request.rb
- lib/graphql/schema.rb
- spec/graphql/dataloader_spec.rb
This was previously supported, but it shouldn't be -- it makes Dataloader dependent on the lazy-resolve system. I'm interested in working on that system so I'd like to disentangle them first.
> Deprecate returning `.resolve(...)` dataloader requests

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/schema/directive_spec.rb
Oops, previously this encountered: 
```
Error:
GraphQL::Schema::Directive::runtime directives#test_0003_works with backtrace: true and lazy lists:
NoMethodError: undefined method `[]' for nil:NilClass
/Users/rmosolgo/code/graphql-ruby/lib/graphql/backtrace/trace.rb:72:in `push_field_backtrace_context'
/Users/rmosolgo/code/graphql-ruby/lib/graphql/backtrace/trace.rb:37:in `execute_field'
/Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:367:in `block in evaluate_selection_with_resolved_keyword_args'
/Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:726:in `run_directive'
/Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:744:in `block in run_directive' …
```
> Fix @defer with { backtrace: true } and lazy lists

- guides/testing/helpers.md
Very excited about the new test helpers. I ran into a few issues getting it wired up and would love to help improve the documentation more. 
For instance, it would be great to document any additional set up / context required to use `with_resolution_context`. For example, the `with_resolution_context` method is erroring in the Object Cache Tracer:
```sh
NoMethodError: undefined method `[]' for nil
from .../graphql-enterprise-1.3.2/lib/graphql/enterprise/object_cache.rb:521:in `trace'
```
> Improve test helper docs

- lib/graphql/tracing/sentry_trace.rb
- spec/graphql/tracing/sentry_trace_spec.rb
Closes https://github.com/rmosolgo/graphql-ruby/issues/4827
This adds in a guard clause to make sure we don't run any instrumentation if Sentry is initialized but `with_child_span` returns a `nil`.   This can happen if Sentry is configured but no DSN is set.
> Return early if `Sentry.with_child_span` returns nil

- lib/graphql/subscriptions/serialize.rb
- spec/graphql/pagination/active_record_relation_connection_spec.rb
- spec/graphql/pagination/mongoid_relation_connection_spec.rb
- spec/graphql/pagination/sequel_dataset_connection_spec.rb
- spec/graphql/subscriptions/serialize_spec.rb
- spec/support/active_record_setup.rb
Fixes #4719 
In order for this to actually reload records, the records have to include `GlobalID::Identification` as shown in this diff.
> Support serializing ActiveRecord::Relations as Arrays

- lib/graphql/schema/field.rb
- spec/graphql/analysis/ast/query_complexity_spec.rb
Fixes #4831 
Previously, if you added a custom field to your connection type, it would get multiplied by the number of edges or nodes to calculate complexity. 
This was mostly wrong, since it was probably a metadata field. But this patch could break your complexity calculation if you used custom field names for `edges` and `nodes`. If this applies to you, please open an issue and we can look into better handling for this. As a work-around, you can put the old implementation in your base field class: 
```ruby 
def calculate_complexity(query:, nodes:, child_complexity:)
if connection? # get behavior from GraphQL-Ruby < 2.2.9
arguments = query.arguments_for(nodes.first, self)
max_possible_page_size = nil
if arguments.respond_to?(:[]) # It might have been an error
if arguments[:first] …
```
> Treat all connection subfields except nodes and edges as metadata

- graphql.gemspec
- lib/graphql/schema/interface.rb
- spec/graphql/dataloader_spec.rb
- spec/graphql/execution/lazy_spec.rb
- spec/graphql/non_null_type_spec.rb
- spec/graphql/query/context_spec.rb
- spec/graphql/query_spec.rb
- spec/graphql/schema/enum_spec.rb
- spec/graphql/schema/scalar_spec.rb
- spec/graphql/subscriptions_spec.rb
- spec/graphql/types/iso_8601_date_spec.rb
- Backtrace rendering changes, so the `caller` parsing needed to be improved.
- Minitest needed an upgrade.
- Base64 is no longer bundled.
> Fix compatibility with Ruby 3.4-dev

- lib/graphql/schema.rb
- spec/graphql/backtrace_spec.rb
Oops -- this was looking for `:default_backtrace` options, but actually, it should use the default options here. 
I ran into this with GraphQL-Batch + Backtrace, and it raised an error like this: 
```
ArgumentError: missing keyword: :executor_class
/Users/rmosolgo/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/graphql-batch-0.5.4/lib/graphql/batch/setup_multiplex.rb:17:in `initialize'
/Users/rmosolgo/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/graphql-2.2.9/lib/graphql/backtrace/trace.rb:8:in `initialize'
/Users/rmosolgo/.rbenv/versions/3.1.1/lib/ruby/gems/3.1.0/gems/graphql-2.2.9/lib/graphql/schema.rb:1194:in `new'
```
But the bug was here; GraphQL-Ruby wasn't passing the right options to the trace.
> Fix backtrace + default trace options

- lib/graphql/schema.rb
- spec/graphql/tracing/trace_modes_spec.rb
Oops -- although the trace module would be added to derived trace classes, the options were added to those options hashes. Similar to #4849  but not the same, fixes https://github.com/Shopify/graphql-batch/pull/167
> Add :default mode options to downstream modes too

- lib/graphql/schema.rb
- spec/graphql/tracing/trace_modes_spec.rb
Oops, there was some code here to handle unexpected mode names, but it didn't really work (and wasn't tested, etc). This makes it so that, when a Schema receives an unknown trace mode at runtime, it treats it like a `:default` mode. It creates a class and options hash for it just like it was registered ahead of time, both derived from `:default`.
Fixes #4855
> Handle unknown trace modes at runtime

- lib/graphql/tracing/sentry_trace.rb
- spec/graphql/tracing/sentry_trace_spec.rb
- spec/support/sentry.rb
This essentially just copies the support built into New Relic tracing for setting the transaction name to Sentry tracing
> Add support for transaction names in Sentry tracing

- graphql.gemspec
- lib/graphql/schema/interface.rb
- spec/graphql/dataloader_spec.rb
- spec/graphql/execution/lazy_spec.rb
- spec/graphql/non_null_type_spec.rb
- spec/graphql/query/context_spec.rb
- spec/graphql/query_spec.rb
- spec/graphql/schema/enum_spec.rb
- spec/graphql/schema/scalar_spec.rb
- spec/graphql/subscriptions_spec.rb
Backporting https://github.com/rmosolgo/graphql-ruby/pull/4846 to `1.13.x`.
I see a bunch of tests are failing, but seems like they are failing in `1.13.x` in general? (confirmed that in https://github.com/maxprokopiev/graphql-ruby/pull/2)
If this is fine and merged, I would also love to do the same for `2.0.x` and `2.1.x`.
> Backport the compatibility fix for Ruby 3.4-dev to 1.13.x

- graphql.gemspec
- lib/graphql/schema/interface.rb
- spec/graphql/dataloader_spec.rb
- spec/graphql/execution/lazy_spec.rb
- spec/graphql/non_null_type_spec.rb
- spec/graphql/query/context_spec.rb
- spec/graphql/query_spec.rb
- spec/graphql/schema/enum_spec.rb
- spec/graphql/schema/scalar_spec.rb
- spec/graphql/subscriptions_spec.rb
- spec/graphql/types/iso_8601_date_spec.rb
Follow-up PR to https://github.com/rmosolgo/graphql-ruby/pull/4860
> Backport the compatibility fix for Ruby 3.4-dev to 2.0.x

- lib/graphql/execution/interpreter.rb
- lib/graphql/schema.rb
- spec/graphql/schema_spec.rb
In fact, `mutation_...` and `subscription_...` have been unused for a long time, and I don't expect any integrations with this method to actually work. But for completeness's sake, I'll start with a formal deprecation before I remove these methods in 3.0.
> Deprecate execution strategy methods

- lib/graphql/analysis/ast/visitor.rb
- spec/graphql/analysis/ast/query_complexity_spec.rb
- spec/graphql/analysis/ast_spec.rb
Fixes a bug in the analysis visitor to make inline fragments and fragment spreads respond to `@skip/include` directives, [per the spec](https://spec.graphql.org/October2021/#sec--skip). This is another piece of housekeeping that may need to go into the `v3` milestone... It's a clear-cut bug to fix, though I suppose it could have implications on custom analyzer expectations out in the wild.
At present, analysis visitation only responds to field conditions. Ignoring fragment conditions manifests numerous analysis bugs, not the least of which is over-costing our old friend complexity analysis (where a skipped fragment tree gets included in the query cost). Fixing this issue for complexity is non-breaking, because costs will only go down.
> Fix fragment skip/include tracking during analysis visitation

- graphql-c_parser/ext/graphql_c_parser_ext/lexer.c
- graphql-c_parser/ext/graphql_c_parser_ext/lexer.rl
- lib/graphql/language/lexer.rb
- spec/fixtures/unicode_escapes/query1.graphql
- spec/fixtures/unicode_escapes/query2.graphql
- spec/graphql/language/lexer_examples.rb
- spec/graphql/types/string_spec.rb
> Fix escapes in string literals

- lib/graphql/schema.rb
- lib/graphql/tracing/platform_tracing.rb
- spec/graphql/language/parser_spec.rb
- spec/graphql/schema_spec.rb
- spec/graphql/tracing/legacy_trace_spec.rb
- spec/graphql/tracing/notifications_tracing_spec.rb
- spec/graphql/tracing/trace_modes_spec.rb
Continuing to migrate things to the new (faster, less memory) `.trace_with` API. This will be removed in GraphQL-Ruby 3.0. 
TODO:
> Deprecate Schema.tracer (use .trace_with instead)

- guides/fields/arguments.md
It is now safe to remove this warning, this is merged and isn't a proposal anymore, see more  https://github.com/graphql/graphql-spec/pull/805
> chore: removed warning for argument deprecation

- lib/graphql/tracing/prometheus_trace.rb
Currently PrometheusTrace does not respect other tracers
Sample code
```ruby
require 'bundler/inline'
gemfile do
gem 'graphql', '2.2.13'
gem 'prometheus_exporter'
end
require 'prometheus_exporter/client'
module TracerOne
def execute_query(query:)
puts 'TracerOne#execute_query.before'
super
puts 'TracerOne#execute_query.after'
end
end
module TracerTwo
def execute_query(query:)
puts 'TracerTwo#execute_query.before'
super
puts 'TracerTwo#execute_query.after'
end
end
field :f, Int
def f
puts 'f called'
1
end
end
query(Query)
trace_with TracerOne
trace_with TracerTwo
trace_with GraphQL::Tracing::PrometheusTrace
end
pp MySchema.execute('{ f }').to_h
```
Before changes
```
f called
{"data"=>{"f"=>1}}
```
After changes
``` …
```
> Fix PrometheusTrace with multiple tracers

- guides/related_projects.md
Graphql Filters is a DSL to define fully typed filters for list fields and compile them to Active Record relations. The documentation is here: https://github.com/moku-io/graphql-filters
> Add `graphql-filters` to related projects

- guides/operation_store/active_record_backend.md
By default, `last_used_at` timestamps are updated every 5 seconds in a background thread. However, in a test environment, this can cause some surprising and unintended side effects when the background thread update is delayed until after a test finishes, and the test transaction has been rolled back.
We were intermittently running into hanging tests in our suite, which has 1 test that checks that the operation store is set up correctly. t took awhile, but we were able to track it down, but eventually we were able to get some stacktrace details on where our test suite was getting stuck:
```
from [...]/vendor/bundle/ruby/3.3.0/gems/activerecord-7.1.3.2/lib/active_record/connection_adapters/postgresql_adapter.rb:894:in `block (2 levels) in exec_no_cache'
from …
```
> add a note to the Operation Store AR guide about test environments

- lib/graphql/testing/helpers.rb
- spec/graphql/testing/helpers_spec.rb
Bug: The `dummy_query` object created as part of `run_graphql_field` doesn't set a query string, which results in a `query_context` object that has validation errors.
Later when `object_type.wrap(inner_object, query_context)` is called with that `query_context`, it checks that the field is authorized.
If as part of checking `self.authorized?` on an object, we first ensure that the context is valid i.e. that `context.errors.empty?`, we will find that it isn't because of this missing query string.
Even if this query string isn't used, the `GraphQL::Query` object should be valid, in case there are validations that are done on these objects in a client's code. This is what we are doing in our code, which led me to this bug.
This PR sets a dummy query string value to fix this issue, and adds a …
> Fix run_graphql_field with missing query string on dummy query

- guides/type_definitions/directives.md
As highlighted in blue in the image below, the "Custom Runtime Directives" has an accidental indent at the beginning.
This is because, as highlighted in red in the image below, that `<h3>` is inside of the `<li>`. The changes in this PR make that `<h3>` **not** inside of the `<li>`, therefore fixing the indentation issue.
> Fix indentation

- guides/type_definitions/lists.md
As highlighted in blue in the image below, that value is not aligned properly.
That value should be in the "Invalid" column, and the changes proposed in this PR will fix this alignment issue.
> Fix alignment of a value in the "Invalid" column

- lib/graphql.rb
Fixes #4900 
Not needed in 2.x because the file using it isn't present. 
There _is_ another use of OpenStruct in the gem, but it will only run in applications which already use OpenStruct: 
https://github.com/rmosolgo/graphql-ruby/blob/ec1ae00fdd36d5292096e40adb7401c4832bb7ee/lib/graphql/subscriptions/serialize.rb#L85-L87
> [1.13.x] require ostruct which was previously required by rake

- lib/graphql/analysis/ast/field_usage.rb
- lib/graphql/execution/interpreter/argument_value.rb
- lib/graphql/schema/argument.rb
- lib/graphql/schema/input_object.rb
- spec/graphql/analysis/ast/field_usage_spec.rb
- spec/graphql/schema/input_object_spec.rb
- spec/support/dummy/schema.rb
Fixes #4864 
Along the way, I noticed that `InputObject#prepare` was called twice when that method returned itself. By removing the first call, this solution worked out nicely.
> Fix field usage on prepared input types with original value

- guides/defer/usage.md
Include updated details about `@defer` and apollo-client
> Update usage.md with updated Apollo client details

- lib/graphql/language.rb
- lib/graphql/language/lexer.rb
- spec/graphql/language/printer_spec.rb
When clients provide numbers that are too big for Ruby, query execution returns an error. This handles the query printer to print _something_ when that happens -- it used to raise an error. 
Technically, the right thing to do would be to raise a parse error.
Part of #4922
> Rescue printing Infinity

- .github/workflows/ci.yaml
- graphql-c_parser/ext/graphql_c_parser_ext/graphql_c_parser_ext.c
- graphql-c_parser/ext/graphql_c_parser_ext/lexer.c
- graphql-c_parser/ext/graphql_c_parser_ext/lexer.h
- graphql-c_parser/ext/graphql_c_parser_ext/lexer.rl
- graphql-c_parser/lib/graphql/c_parser.rb
- lib/graphql.rb
- lib/graphql/language.rb
- lib/graphql/language/lexer.rb
- spec/graphql/language/parser_spec.rb
- spec/spec_helper.rb
Fixes #4871 
This option is off by default now but will be on by default in GraphQL-Ruby 3.0. You can opt into the new behavior with: 
```ruby
GraphQL.reject_numbers_followed_by_names = true 
```
And you can check for invalid query strings using the helper: 
```ruby 
transformed_query_str = GraphQL::Language.add_space_between_numbers_and_names(query_str) 
if transformed_query_str.equal?(query_str) 
else 
BugTracer.report(:invalid_query_string, query_str)
query_str = transformed_query_str
end 
```
TODO: 
-  ~~Also make sure variable definitions are covered, eg `query($a: Int = 5$b: Int = 6) { ... }`~~
- I think that variable definitions and values followed by directives are technically _legal_ because the following character is either `@` or `$`, not a name. I _did_ add tests for input …
> Add an option to reject numbers followed by names

- graphql-c_parser/ext/graphql_c_parser_ext/graphql_c_parser_ext.c
- graphql-c_parser/ext/graphql_c_parser_ext/lexer.c
- graphql-c_parser/ext/graphql_c_parser_ext/lexer.h
- graphql-c_parser/ext/graphql_c_parser_ext/lexer.rl
- graphql-c_parser/lib/graphql/c_parser.rb
- lib/generators/graphql/templates/schema.erb
- lib/graphql.rb
- lib/graphql/language/lexer.rb
- lib/graphql/language/parser.rb
- lib/graphql/query.rb
- lib/graphql/schema.rb
- spec/graphql/language/clexer_spec.rb
- spec/graphql/language/lexer_examples.rb
- spec/graphql/query_spec.rb
- spec/graphql/schema_spec.rb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
This will cause the lexer to exit when receiving large query strings -- even before parsing or validation.
> Add Schema.max_query_strings_tokens limit

- lib/graphql/testing/helpers.rb
- spec/graphql/testing/helpers_spec.rb
Fixes #4925 
It injects pretty minimal `lookahead` and `ast_node` objects, but it allows real objects (or mocks) to be injected using keyword arguments.
> Support extras: [:lookahead, :ast_node] in run_graphql_field

- lib/graphql/language/nodes.rb
- spec/graphql/language/visitor_spec.rb
Fixes #4928.
This commit sets `DirectiveDefinitionNode.children_method_name` to `:definitions`. It previously defaulted to `:directive_definitions`, causing a `NoMethodError` when attempting to delete the node from the AST.
I wasn't sure how best to test this, so I added some directive definitions to the SDL test case in the visitor spec. Let me know if there's a more suitable way.
> Set DirectiveDefinitionNode.children_method_name

- lib/graphql/schema/argument.rb
- spec/graphql/schema/input_object_spec.rb
When the argument is a list of input objects we need to call prepare on each item of the list.
> Call prepare on lists of input objects

- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/execution/interpreter/runtime/graphql_result.rb
This is an experiment in managing runtime state. 
We already have a lot of per-field metadata in `current_runtime_state`, and most of it is derived from `GraphQLResult` objects. I think it should be possible to: 
- Move per-object state to `GraphQLResult` objects (not _everything_ -- can't be per-field since leaf values don't get `GraphQLResult` objects)
- Remove per-object state values from runtime method signatures, since they're accessible from the passed-in `GraphQLResult` 
- Update `current_runtime_state` to use GraphQLResult in more cases (it already does for path, at least) 
If _that_ works, then I'm hoping that `GraphQLResult` can be the basis for a run-and-return (trampoline) -style execution instead of a recursive one, where the `GraphQLResult` itself contains information about …
> Move runtime state into result objects

- lib/graphql/language/nodes.rb
- lib/graphql/language/parser.rb
Fixes #4945 
These methods had simple implementations, but when there was a million validation errors, they could really add up.
> Optimize #line and #col methods

- lib/graphql/language/nodes.rb
- lib/graphql/language/parser.rb
- spec/graphql/language/nodes_spec.rb
Also fixes a bug where `ListType` and `NonNullType` would raise an error when you asked for their `line` or `col`.
Fixes #4955
> Fix Marshal with parsed documents

- .gitignore
- lib/graphql/query.rb
- spec/graphql/query/fingerprint_spec.rb
Now a `nil` query string is fingerprinted as if it was an empty string. 
Fixes #4942
> Handle nil query_string in fingerprint

- .github/workflows/ci.yaml
- gemfiles/rails_7.0.gemfile
- gemfiles/rails_7.1.gemfile
- gemfiles/rails_master.gemfile
- lib/graphql/schema.rb
- lib/graphql/schema/addition.rb
- lib/graphql/schema/late_bound_type.rb
- lib/graphql/schema/warden.rb
- spec/graphql/static_validation/rules/argument_literals_are_compatible_spec.rb
- spec/integration/rails/graphql/dataloader/async_dataloader_spec.rb
- spec/integration/rails/graphql/schema_spec.rb
- spec/support/active_record_setup.rb
This allows us to `compare_by_identity` which is faster than hashing strings. And it simplifies the API (in advance of addressing #4919)
> Use type objects, not names, in references_to hash

- lib/graphql/language/parser.rb
This PR removes a duplicate `when` clause from `GraphQL::Language::Parser#parse_name` which currently causes a warning.
https://github.com/rmosolgo/graphql-ruby/blob/ec5208ae56d8f1b707263ea87c46263ba09b273c/lib/graphql/language/parser.rb#L585-L587
https://github.com/rmosolgo/graphql-ruby/blob/ec5208ae56d8f1b707263ea87c46263ba09b273c/lib/graphql/language/parser.rb#L618-L620
```
/Users/thomasmarshall/.gem/ruby/3.3.1/gems/graphql-2.3.4/lib/graphql/language/parser.rb:618: warning: duplicated `when' clause with line 585 is ignored
```
> Remove duplicate when clause from parser

- .github/workflows/ci.yaml
- lib/graphql/execution/interpreter.rb
- lib/graphql/query.rb
- lib/graphql/schema.rb
> Update docs for result return type

- Rakefile
- lib/graphql/language/parser.rb
- spec/graphql/dataloader/source_spec.rb
- spec/graphql/language/parser_spec.rb
> Fix enum values that match keywords

- lib/graphql/schema/argument.rb
- spec/graphql/dataloader_spec.rb
Fixes #4979 
`.run_isolated` is not ideal because it may break some batching that previously existed, but I think it's more important to handle this use case. (And it didn't break any of the many dataloader tests, which cover so many happy paths...)
> Fix dataloader with argument loading and auth

- javascript_client/src/subscriptions/__tests__/createRelaySubscriptionHandlerTest.ts
- javascript_client/src/subscriptions/createRelaySubscriptionHandler.ts
Oops -- this was falling back to `""` when no query string was given, which breaks when using the OperationStore.
> Fix Relay subscription handler sending an empty string

- guides/fields/validation.md
- lib/graphql/schema/validator.rb
- lib/graphql/schema/validator/all_validator.rb
- spec/graphql/schema/validator/all_validator_spec.rb
I found I needed to validate a set of values coming into a field, like this:
```ruby
field :slices do
argument :uuids, [String], validates: { all: { format: { with: UUID::REGEXP } } } }
end
```
I thought an `all` validator which composes the other validators might be a good idea. What do you think? This is a rough spike to demonstrate the idea and see if it might work.
> Allow validating a set of array values

- lib/graphql/introspection/schema_type.rb
- spec/graphql/subscriptions_spec.rb
Fixes #5017 
Derp, I had a typo in the `case` statement and no test for this specific code.
> Fix typo in introspection code

- lib/graphql/schema/enum.rb
- spec/graphql/schema/enum_spec.rb
> Use base class for errors in anonymous enum classes

- lib/graphql/static_validation/rules/variable_default_values_are_correctly_typed.rb
- spec/graphql/static_validation/rules/variable_default_values_are_correctly_typed_spec.rb
This rule isn't actually part of the spec, and GraphQL-JS allows this construction. 
From a compatibility standpoint, I don't think this poses any risks: any queries that were previously returned as invalid (wrongly) will now be executed. But I think anyone who encountered this in the past probably removed the `!`.
Fixes #5029
> Remove rule that prohibits non-null variables from having default values

- lib/graphql/language/parser.rb
- spec/graphql/language/parser_spec.rb
> Fix parsing operation names that match keywords

- lib/graphql/query.rb
- lib/graphql/query/context.rb
- lib/graphql/query/null_context.rb
- lib/graphql/schema.rb
- lib/graphql/schema/field/connection_extension.rb
- spec/graphql/execution/interpreter_spec.rb
These were used many years ago and have returned `true` since GraphQL-Ruby v2.0. If you find these in your code, remove usages because they're always `true`.
> Remove old interpreter?, using_ast_analysis?, and new_connections? flags

- lib/graphql/introspection/schema_type.rb
- lib/graphql/schema.rb
- lib/graphql/schema/introspection_system.rb
- lib/graphql/schema/subset.rb
- lib/graphql/schema/types_migration.rb
- lib/graphql/testing/helpers.rb
- spec/graphql/introspection/directive_type_spec.rb
- spec/graphql/language/document_from_schema_definition_spec.rb
- spec/graphql/schema/addition_spec.rb
- spec/graphql/schema/argument_spec.rb
- spec/graphql/schema/build_from_definition_spec.rb
- spec/graphql/schema/directive_spec.rb
- spec/graphql/schema/dynamic_members_spec.rb
- spec/graphql/schema/input_object_spec.rb
- spec/graphql/schema/interface_spec.rb
- spec/graphql/schema/union_spec.rb
- spec/integration/rails/graphql/schema_spec.rb
To support lazy-loading types, this turns off eager-loading when `Schema::Subset` is enabled. 
Part of #5014  and #4919 
TODO: 
- Memory usage was identical, runtime was within margin of error
> Schema::Subset: Don't build schema caches, sort directives in introspection

- lib/graphql/schema/validator/all_validator.rb
- spec/graphql/schema/validator/all_validator_spec.rb
When you want to validate an array only has values within a pre-defined set (`all: inclusion: []`), but also want to permit it to be `null`, right now it will crash on `undefined method `each' for nil:NilClass`
Example field and query that will crash before the patch, and won't after.
```ruby
field :pets, [Types::PetsType] do
argument :filters, [String],
description: 'Filters to apply -- nil for all',
validates: {
all: {
allow_null: true,
inclusion: { in: %w[cat dog turtle bird] },
},
}
end
```
```graphql
query MyFavoritePets {
pets(filters: null) {
name
}
}
```
> fix: avoid iterating on null array if all validator permits null value

- lib/graphql/rubocop.rb
- lib/graphql/rubocop/graphql/field_type_in_block.rb
- lib/graphql/schema/addition.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/member/has_fields.rb
- lib/graphql/schema/subset.rb
- lib/graphql/schema/types_migration.rb
- spec/fixtures/cop/.rubocop.yml
- spec/fixtures/cop/field_type.rb
- spec/fixtures/cop/field_type_corrected.rb
- spec/graphql/cop/field_type_in_block_spec.rb
- spec/graphql/schema/directive/one_of_spec.rb
- spec/graphql/schema/field_spec.rb
- spec/support/dummy/schema.rb
This way, in theory, loading `my_object.rb` doesn't _necessary_ load the field return types of these fields. (Rails won't try to load files until the constants are actually referenced, and in this case, it can be deferred until execution.)
cc @gmcgibbon  -- would this approach work in your type-checking setup? Like this:
```ruby 
field :thing do 
type Types::Thing 
end 
field :thing { type(Types::Thing) } 
field(:thing) { Types::Thing } # <- not implemented yet
```
I think that would give you plain Ruby constants in the source. 
The downside is the need to call `ensure_loaded` everywhere. It's too bad and reminds me of how GraphQL-Ruby used to be full of `ensure_defined`, yuck 😩 . But, I think it's the right thing, and thanks to caching by the schema / Warden / Subset, calls to that …
> Defer calling field do ... end blocks until needed

- lib/graphql/rubocop.rb
- lib/graphql/rubocop/graphql/root_types_in_block.rb
- lib/graphql/schema.rb
- spec/fixtures/cop/.rubocop.yml
- spec/fixtures/cop/root_types.rb
- spec/fixtures/cop/root_types_corrected.rb
- spec/graphql/cop/root_types_in_block_spec.rb
- spec/graphql/schema_spec.rb
- spec/graphql/subscriptions_spec.rb
- spec/support/dummy/schema.rb
With this, the schema could defer loading a root type until necessary (thus also deferring loading all types referenced by it, resolvers, etc). 
In this implementation, calling `schema.query` returns the deferred definition which means that if, say, a plug-in references that root type, all the magic is lost. 
To be really effective, we'd also need some plugin behavior like `extend(:query) { ... }` where callbacks could be registered by the plugin, then called by GraphQL-Ruby after the type is actually loaded. I think that can be added later.
Part of #5014  
TODO:
> Accept blocks to reference schema root types

- lib/graphql/schema.rb
- spec/graphql/schema_spec.rb
Oops -- If a subscription extension was added first, then a non-block `subscription` type was added, it didn't add the necessary field extension. 
Fixes https://github.com/rmosolgo/graphql-ruby/commit/f5033aaee0227c39692d0468d407b832f1f75e4e#commitcomment-145318416
> Fix subscription setup

- lib/graphql/schema.rb
Allow for `validate_timeout` to be cleared such that the timeout behaviour is removed by setting a `nil` value. Technically `0` does work already.
`nil` is the default value so we cannot distinguish between a get and set.
Use existing `NOT_CONFIGURED` sentinel value as the default argument value. 
A schema can have a default `validate_timeout` but can be overridden to be removed.
> Allow `validate_timeout` to be cleared/reset after being set

- graphql-c_parser/lib/graphql/c_parser.rb
- lib/graphql/language/lexer.rb
- lib/graphql/language/parser.rb
- spec/graphql/language/clexer_spec.rb
- spec/graphql/language/parser_spec.rb
Ability to apply [`max_query_string_tokens`](https://graphql-ruby.org/api-doc/2.3.14/GraphQL/Schema#max_query_string_tokens-class_method) setting without breaking any existing operations.
We don't know the current distribution of the size of the tokens in existing operations.
Expose `tokens_count` on `Parser#tokens_count`. Trigger parsing if not already done.
To gather data, temporarily swap from the convenient `GraphQL.parse` to `GraphQL::Language::Parser.new` (or similar)
> Expose parser `tokens_count`

- lib/generators/graphql/orm_mutations_base.rb
- lib/generators/graphql/type_generator.rb
this will allow the following to work:
Rails.application.config.generators do |g|
g.graphql namespaced_types: true
right now, the config needed is a bit quirky:
Rails.application.config.generators do |g|
g.graphql "namespaced_types" => true
> Use symbols for namespaced_types generator option

- lib/graphql/schema.rb
Allow for `validate_max_errors` to be cleared such that the bounding behaviour is removed by setting a `nil` value.
`nil` is the default value so we cannot distinguish between a get and set.
Use existing `NOT_CONFIGURED` sentinel value as the default argument value. 
A schema can have a default `validate_max_errors` but can be overridden to be removed.
> Allow `validate_max_errors` to be cleared/reset after being set

- lib/graphql/tracing/notifications_trace.rb
- spec/graphql/tracing/notifications_trace_spec.rb
Fixes #5044 
Oops, this was not migrated to correctly call `super`. It still called GraphQL code without any problem (from `blk.call`), but it didn't interact properly with other trace modules.
> Call super in NotificationsTrace

- lib/graphql/static_validation/rules/directives_are_in_valid_locations.rb
- spec/graphql/introspection/directive_type_spec.rb
- spec/graphql/static_validation/rules/directives_are_in_valid_locations_spec.rb
- spec/support/dummy/schema.rb
Allow variable definition directives in the `DirectivesAreInValidLocations` static validation rule.
This also adds a test, but it feels a bit odd that it only tests the variable definition case and no others. I could remove the test, or add cases to cover more of the possible valid locations.
> Allow variable definition directives in validation

- lib/graphql/schema/resolver.rb
- spec/graphql/analysis_spec.rb
- spec/graphql/tracing/statsd_trace_spec.rb
- spec/graphql/tracing/statsd_tracing_spec.rb
Just a small suggestion Rubocop found a while back.
Methods generated by `attr_reader` are technically ever-so-slightly faster than regular Ruby methods, though these aren't hot paths, so that doesn't matter much.
> Use `attr_reader` where applicable

- guides/schema/object_identification.md
closes #5089 
Is this ok? I didn't want to pull too much content into the guide as it might confuse folks, went with little trail and a link to detailed guide.
> Docs: Mention SQIDs as an alternative to `to_pid_param`

- lib/graphql/language.rb
Inspired by #5094 
This makes the function ~20% faster in my little benchmark and reduces memory usage by ~40% (and down to _one_ object in the no-op case) 🎉  
<details>
<summary>Benchmark</summary>
<p>
```ruby
require "bundler/inline"
gemfile do
gem "graphql", path: "./"
gem "benchmark-ips"
gem "memory_profiler"
end
no_strings = %|
mutation($arg1: String, $arg2: String) {
doStuff(with: $arg1) { some result { fields } }
doOtherStuff(with: { something: $arg2 }) {
some {
result {
fields
}
}
}
}
|
strings_with_nl = %|
mutation($arg1: String = "something
invalid") {
doStuff(with: $arg1) { some result { fields } }
doOtherStuff(with: { something: "in
val
id" }) {
some {
result {
fields
}
}
}
}
|
strings_without_nl = %|
mutation($arg1: String = "something valid") {
doStuff(with: $arg1) { some …
```
> Optimize escape_single_quoted_newlines

- .rubocop.yml
- graphql.gemspec
- lib/graphql/rubocop/graphql/field_type_in_block.rb
- spec/fixtures/cop/.rubocop.yml
- spec/fixtures/cop/small_field_type.rb
- spec/graphql/cop/field_type_in_block_spec.rb
- spec/graphql/schema/printer_spec.rb
- spec/graphql/subscriptions_spec.rb
- spec/support/rubocop_test_helpers.rb
I also updated RuboCop and made some fixes accordingly
Fixes #5097
> Handle single-line classes in field_type_in_block cop

- lib/graphql/invalid_null_error.rb
- spec/graphql/invalid_null_error_spec.rb
I was listing the modules in my app with `ObjectSpace.each_object(Module)` and it failed while inspecting this class.
I also wanted to test the behavior of using the parent class's mutation but I couldn't find a way.
> Don't raise NoMethodError on InvalidNullError.inspect

- .github/workflows/ci.yaml
- lib/graphql/subscriptions/action_cable_subscriptions.rb
- spec/dummy/test/channels/graphql_channel_test.rb
> Add server-side action cable tests

- javascript_client/src/subscriptions/AblyLink.ts
Hey, I'm a new Pro subscriber integrating Ably subscriptions.  It went well aside from this issue.
If you look further down in the code, `_getSubscriptionChannel` ALWAYS returns an object, regardless of whether the headers were passed:
```
_getSubscriptionChannel(operation: Operation) {
const response = operation.getContext().response
// Check to see if the response has the header
const subscriptionChannel = response.headers.get("X-Subscription-ID")
// The server returns this header when encryption is enabled.
const cipherKey = response.headers.get("X-Subscription-Key")
return { channel: subscriptionChannel, key: cipherKey }
}
```
So this logic check:
```
if (subscriptionChannelConfig) {
```
was always returning true.
> fix logic that checks whether a request has a subscription header

- lib/graphql/schema/field.rb
- spec/graphql/schema/field_extension_spec.rb
https://github.com/rmosolgo/graphql-ruby/pull/5054 introduced a regression where an extension registered eagerly (using the kwarg) can no longer register another extension in its `apply` method. I fix the bug here by restoring the previous `@call_after_define` logic.
> bug fix: extensions can register more extensions via apply method

- lib/graphql/schema.rb
- spec/graphql/tracing/trace_modes_spec.rb
https://github.com/rmosolgo/graphql-ruby/pull/5045 introduced a new behaviour to `add_trace_options_for` where it no longer merges options when trace class does not include `DefaultTraceClass`. While it did update `build_trace_mode` to include `DefaultTraceClass` in the trace classes, there is still `trace_class` method where it can register a new trace class in default mode without including `DefaultTraceClass`. So I fix the issue by ensuring `DefaultTraceClass` is included in the `new_class` in `trace_class`.
> bug fix: respect options when using `trace_with` after `trace_class`.

- lib/graphql/query.rb
- spec/graphql/execution/lookahead_spec.rb
Resolves https://github.com/rmosolgo/graphql-ruby/issues/5126
> Handle no selected operation for `Query#lookahead`

- lib/graphql/static_validation/rules/fields_will_merge.rb
It was observed that if a query includes thousands of non-existing fields, it takes a lot of processing time within the [FieldsWillMerge#find_conflicts_within](https://github.com/rmosolgo/graphql-ruby/blob/c66362145bd120a22fdbc14aac612b486c32b3d8/lib/graphql/static_validation/rules/fields_will_merge.rb#L197-L211). 
The iteration loop represents `n(n-1^2)/2`, where `n` is the number of duplicated fields being queried, and the underlying call to [#find_conflict](https://github.com/rmosolgo/graphql-ruby/blob/c66362145bd120a22fdbc14aac612b486c32b3d8/lib/graphql/static_validation/rules/fields_will_merge.rb#L205
) is using considerable time. For example, a query with `2000` times the same non-existing field i.e.`query { a a ... 2000 times }` takes ~6000 ms to process and skipping these fields …
> Optimization - Skip processing non-existing fields in FieldsWillMerge

- Gemfile
`bundle install` gave me a warning because yard was specified twice in Gemfile: once from the gemspec and once explicitly in the file.
It seems we no longer need to pin yard to a specific commit as Ruby 3.2 is supported in recent releases.
> No longer pin yard to specific commit

- lib/graphql/schema/validator/required_validator.rb
- spec/graphql/schema/argument_spec.rb
- spec/graphql/schema/validator/required_validator_spec.rb
- spec/graphql/schema/validator_spec.rb
This PR updates the error message when a `one_of` validation is not satisfied to be more explicit about what the issue is.
Before: "{field_name} has the wrong arguments"
After: "{field_name} must include exactly one of the following arguments: a, b."
Note: PR seems to be failing due to unreliable tests. [Example 1](https://github.com/rmosolgo/graphql-ruby/actions/runs/11447293332/job/31848303250?pr=5130), [Example 2](https://github.com/rmosolgo/graphql-ruby/actions/runs/11447896670/job/31850249461?pr=5130)
> Update validation message for one_of

- lib/graphql/dataloader.rb
- lib/graphql/dataloader/async_dataloader.rb
- lib/graphql/dataloader/source.rb
- spec/graphql/dataloader/nonblocking_dataloader_spec.rb
- spec/graphql/dataloader/source_spec.rb
- spec/graphql/dataloader_spec.rb
> Add Dataloader fiber_limit option

- lib/graphql/schema/input_object.rb
- spec/graphql/schema/argument_spec.rb
> Don't require input object argument when default value is configured

- lib/graphql/schema/input_object.rb
- spec/graphql/schema/input_object_spec.rb
Using an argument named `objectId` currently [emits a warning](https://github.com/ruby/ruby/blob/1001ea9606fd9bbbce70deaab0e6a31c5af1a20c/vm_method.c#L1066-L1070) because it redefines the `#object_id` method. This should technically be safe to do because Ruby doesn't use that method internally, but it still warns because third party code might.
`objectId` is a valid name for an argument, and a useful one too. This commit suppresses the warning by temporarily setting `$VERBOSE` to `nil` while defining the method. It's unlikely any code is relying on the `#object_id` method for GraphQL input argument objects, but if so it's already broken—this commit just silences the warning.
Host projects could of course suppress the warnings themselves, but it's tricky to do in a localized way when using …
> Suppress warning for objectId arguments

- lib/graphql/schema/printer.rb
- lib/graphql/schema/visibility/migration.rb
- lib/graphql/schema/warden.rb
- spec/graphql/analysis_spec.rb
- spec/graphql/authorization_spec.rb
- spec/graphql/introspection/entry_points_spec.rb
- spec/graphql/introspection/schema_type_spec.rb
- spec/graphql/language/document_from_schema_definition_spec.rb
- spec/graphql/schema/always_visible_spec.rb
- spec/graphql/schema/argument_spec.rb
- spec/graphql/schema/directive/flagged_spec.rb
- spec/graphql/schema/dynamic_members_spec.rb
- spec/graphql/schema/introspection_system_spec.rb
- spec/graphql/schema/printer_spec.rb
- spec/graphql/schema/subscription_spec.rb
- spec/graphql/schema/warden_spec.rb
- spec/graphql/static_validation/rules/required_arguments_are_present_spec.rb
- spec/graphql/subscriptions_spec.rb
- spec/graphql/testing/helpers_spec.rb
- spec/spec_helper.rb
- spec/support/jazz.rb
In a future version, visibility filtering will be disabled by default Eventually `Warden` will go away. (`Schema::Visibility` is the future implementation.) But for now, warn so that people using the current default won't be surprised when the default changes. 
TODO:
> Warn when Warden isn't explicitly enabled

- lib/graphql/query/null_context.rb
- lib/graphql/schema/enum.rb
- lib/graphql/schema/enum_value.rb
- lib/graphql/schema/visibility/migration.rb
- lib/graphql/schema/visibility/profile.rb
- lib/graphql/schema/warden.rb
- lib/graphql/testing/helpers.rb
- spec/graphql/schema/enum_spec.rb
Fixes #5140 
This has uncovered a bit of confusion in the codebase. There are two different kind of "dummy" visibility checks which are used when a real Query context isn't available: 
- One implementation skips any kind of `.visible?` check at all 
- Another implementation calls visible with `NullContext.instance` 
The only reason this worked with warden is because somewhere in the call stack, it shifted from using one of those approaches to the other. I think it'd be good work to follow the threads here an clearly delineate where one is used vs. where the other is used.
> Add support for dynamic enum_values in Visibility::Profile

- lib/graphql/static_validation/rules/fields_are_defined_on_type.rb
- spec/graphql/schema_spec.rb
Since https://github.com/rmosolgo/graphql-ruby/pull/4966/files#diff-2252722dfaf6594778838471788047281b9c06a3f2419c5342a84221d75f086cR17, a query that select a (non existing) field on an enum type results in an exception: `"NoMethodError: undefined method 'fields' for class <an enum type>"`.
> handle non-existing field selection on enum type correctly

- javascript_client/src/subscriptions/__tests__/createActionCableHandlerTest.ts
- javascript_client/src/subscriptions/createActionCableHandler.ts
> Make sure ActionCableHandler only unsubscribes once

- javascript_client/src/subscriptions/SubscriptionExchange.ts
- javascript_client/src/subscriptions/createActionCableHandler.ts
Fixes #5149
- prevent double unsubscribe calls in createUrqlActionCableSubscription
- call onCompleted only when we subscribed to AC for Relay & Urql handlers
> Fix double unsubscribe calls for Urql and Relay subscriptions

- javascript_client/src/__tests__/__snapshots__/syncTest.ts.snap
- javascript_client/src/__tests__/syncTest.ts
- javascript_client/src/sync/index.ts
Fixes #5139 
Oops -- I think the missing `resolve(...)` call was the problem.
> Fix dumping payload with outfile

- lib/graphql/schema/visibility.rb
- spec/graphql/schema/visibility_spec.rb
Fixes #5154 
This adds a top-level cache, like `Schema` makes when using `Warden`, but it supports lazy-loading. Currently, the cache rebuilds whenever something is lazy-loaded, but it could probably be made to grow in-place instead if it becomes a problem. 
Running the same benchmark from the original issue shows good results: 
```
$ N=1000 ruby types_bench.rb
GraphQL gem 2.4.2--accessing `GraphQL::Schema#types` 1000 times
user     system      total        real
Not using Visibility   0.291171   0.012367   0.303538 (  0.303684)
Using Visibility       0.156794   0.005118   0.161912 (  0.162134)
```
> Add top-level caches for Schema::Visibility

- lib/graphql/schema.rb
- lib/graphql/schema/visibility.rb
- lib/graphql/schema/visibility/profile.rb
- lib/graphql/schema/visibility/visit.rb
- lib/graphql/static_validation/validation_context.rb
- lib/graphql/testing/helpers.rb
- spec/graphql/schema/visibility/profile_spec.rb
- spec/graphql/schema/visibility_spec.rb
In order to support lazy-loading in development, I had bypassed the existing top-level caches for types, possible types, and schema references. But, that turned out to be noticeably slow when validating lots of queries all at once. So in this PR, I'm trying to have it all: 
- Continue supporting lazy-loading 
- Support thread-safe preloading in production 
- Be as fast as Warden when validating lots of queries 
I wrote a benchmark based on #5151: 
<details>
<summary>Validation benchmark, Warden vs Schema::Visibility</summary>
<p>
```ruby 
require "bundler/inline"
gemfile do
gem "graphql", path: "~/code/graphql-ruby" 
gem "graphql-pro", path: "./"
gem "benchmark-ips"
gem "stackprof"
gem "memory_profiler"
end
puts "GraphQL-Ruby: #{GraphQL::VERSION} / GraphQL-Pro: #{GraphQL::Pro::VERSION}" …
```
> Add top-level schema caches to Schema::Visibility for better performance

- Rakefile
- spec/integration/mongoid/star_trek/data.rb
- spec/integration/rails/data.rb
- spec/integration/rails/generators/graphql/input_generator_spec.rb
- spec/integration/rails/generators/graphql/object_generator_spec.rb
- spec/spec_helper.rb
- spec/support/active_record_setup.rb
Somehow, the Sqlite database gets messed up _sometimes_, where one of the tables isn't present for one of the tests. I'm trying to debug that but I'm not really sure how to hunt it down :S 
TODO: 
- Test: 10206 -> 10206
- Mongodb: 10192 -> 10192
- Rails Master: 11099 -> 11099
> Simplify requires for test files

- lib/graphql/static_validation/error.rb
- lib/graphql/static_validation/rules/argument_names_are_unique.rb
- lib/graphql/static_validation/rules/fields_have_appropriate_selections.rb
- lib/graphql/static_validation/rules/no_definitions_are_present.rb
> Remove unused ErrorHelper

- lib/graphql/schema/visibility.rb
- lib/graphql/schema/visibility/profile.rb
- spec/graphql/schema/warden_spec.rb
Fixes #4882 
This adds _some_ hiding of directives when their uses are hidden. It only checks "one level" deep. Directives are hidden if: 
- They aren't registered to the schema with `directive(...)` configurations
- AND no types with `field(...)` configurations using the directive are visible 
- AND no resolvers and fields with `argument(...)` configurations using the directive are visible
- AND no enums with `value(...)` configurations using the directive are visible 
It doesn't do recursive checking, so if a type is hidden because fields using it are hidden, then the directive will still be visible. Maybe that's possible but I'm guessing that adding `visible?` implementations to the app is a less complicated solution in that case.
> Hide directives when their uses are hidden

- lib/graphql/dataloader/source.rb
- spec/graphql/dataloader_spec.rb
In ruby:
```rb
[nil].any? #=> false
[false].any? #=> false
```
When sending [nil] to load_all, it was making the source think that there are no pending keys, and raised GraphQL::InvariantError.
> Fix bug in DataLoader::Source#load_all when sending only falsy values

- lib/graphql/schema/input_object.rb
- spec/graphql/schema/input_object_spec.rb
This allows Ruby's case/in syntax, like:
```ruby
case input
in { x:, y: }
end
```
This is easy for individual projects to add in their own `InputObject` superclass, but it seems generally useful, so I figured I'd raise a PR with it. No hard feelings if you don't want it upstream. :slightly_smiling_face:
> Allow InputObject instances to be pattern matched via #deconstruct_keys

- lib/graphql/language/document_from_schema_definition.rb
- spec/graphql/schema/printer_spec.rb
> Properly hide definition directives in SDL

- lib/graphql/current.rb
- lib/graphql/dataloader.rb
- lib/graphql/dataloader/async_dataloader.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/pagination/connection.rb
- lib/graphql/query/context.rb
- lib/graphql/schema/field/scope_extension.rb
- lib/graphql/types/relay/connection_behaviors.rb
- lib/graphql/types/relay/edge_behaviors.rb
- spec/graphql/execution/interpreter_spec.rb
- spec/graphql/pagination/connection_spec.rb
- spec/graphql/query/context_spec.rb
Trying out part of the suggestion from #5173 
TODO: 
- I searched google for `:__graphql_runtime_info` and didn't find anything outside of GraphQL-Ruby. I also checked GraphQL-Pro and GraphQL-Enterprise and didn't find any usages.
> Migrate internal runtime state to Fiber storage

- lib/graphql/language/lexer.rb
- spec/graphql/language/parser_spec.rb
**Fix issue #5101**
Actual error message:
> _Expected a number, but it was malformed ("-")_
Expected error message:
> _Argument 'arg' on Field 'hello' has an invalid value (-foo). Expected type 'MyEnum!'._
> Fix: Incorrect/incomplete error message

- guides/code_loading.md
- lib/graphql.rb
- lib/graphql/autoload.rb
- lib/graphql/query.rb
- lib/graphql/query/context.rb
- lib/graphql/railtie.rb
- lib/graphql/schema.rb
- lib/graphql/schema/relay_classic_mutation.rb
- lib/graphql/types.rb
- spec/fixtures/eager_module/eager_class.rb
- spec/fixtures/eager_module/other_eager_class.rb
- spec/fixtures/lazy_module/lazy_class.rb
- spec/graphql/autoload_spec.rb
- spec/graphql/types/iso_8601_date_spec.rb
- spec/graphql/types/iso_8601_date_time_spec.rb
Reduces require time from ~160ms to ~5ms. Autoloads all constants under `GraphQL` to optimize boot time. Also autoloads `GraphQL::Types` and `GraphQL::Query` because they can't be required in sequence.
Script:
```rb
#!/usr/bin/env ruby
require "bundler/setup"
require "benchmark"
ms = 1000 * Benchmark.realtime do
require "graphql"
end
puts "#{ms}ms"
```
Before:
```
> bin/boot
169.55200000666082ms
```
After:
```
> bin/boot
5.60200004838407ms
```
Rails will automatically eager load GraphQL, but other frameworks / setups will need to call `GraphQL.eager_load!`. If we agree with the approach, I can document this. Because we don't require on Active Support, we need to manually implement eager loading. `ActiveSupport::Autoload` implements the `eager_load!` method for you.
Also, if you're …
> Autoload nested constants

- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/schema/visibility/migration.rb
- lib/graphql/schema/visibility/profile.rb
- lib/graphql/schema/warden.rb
- spec/graphql/schema/union_spec.rb
> Check possible_types for objects loaded by orphaned unions

- lib/graphql.rb
- lib/graphql/schema.rb
Followup to #5178 
Types reference schema, which reference types, so we need to take the part of schema that reference types, and autoload it.
Currently, if you reference `GraphQL::Types::String`, you'll get:
```
graphql-ruby/lib/graphql/schema/built_in_types.rb:6:in `<class:Schema>': unin
itialized constant GraphQL::Types::String (NameError)
"String" => GraphQL::Types::String,
^^^^^^^^
Did you mean?  StringIO
STDIN
from graphql-ruby/lib/graphql/schema/built_in_types.rb:3:in `<module:
GraphQL>'
from graphql-ruby/lib/graphql/schema/built_in_types.rb:2:in `<top (required)>'
from /opt/rubies/3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `require'
from /opt/rubies/3.3.6/lib/ruby/3.3.0/bundled_gems.rb:69:in `block (2 levels) in replace_require'
from graphql-ruby/lib/graphql/schema.rb:1813:in …
```
> Fix autoloading of GraphQL::Types

- lib/graphql/railtie.rb
We want to make sure the gem is fully loaded in a production context before the application begins eagerly loading, otherwise we emit a warning. So, let's use `config.before_eager_load` to make sure gem eager loading happens before the app.
Before:
```
> RAILS_ENV=production bin/rails runner ""
GraphQL-Ruby thinks this is a production deployment but didn't eager-load its constants. Address this by:
- Calling `GraphQL.eager_load!` in a production-only initializer or setup hook
- Assign `GraphQL.env = "..."` to something _other_ than `"production"` (for example, `GraphQL.env = "development"`)
More details: https://graphql-ruby.org/schema/definition#production-considerations
```
After:
```
RAILS_ENV=production bin/rails runner ""
```
> Use config.before_eager_load

- lib/graphql.rb
- lib/graphql/autoload.rb
- lib/graphql/railtie.rb
- lib/graphql/schema.rb
- spec/graphql/autoload_spec.rb
I wish there was a reliable way to detect this condition, but it seems like ... there isn't. So: 
- remove this warning 
- use Rails's `eager_load_namespaces` instead, since it seems like the intended integration point
> Remove ensure_eager_load, use eager_load_namespaces

- graphql-c_parser/ext/graphql_c_parser_ext/lexer.c
- graphql-c_parser/ext/graphql_c_parser_ext/lexer.rl
- spec/graphql/language/parser_spec.rb
`StringValueCStr` returns a null-terminated char* for a String but a Ruby string might contain null bytes and `StringValueCStr` will raise an `ArgumentError` ("string contains null byte").
This switches to using a `StringValuePtr` to get a (possibly unterminated) char* combined with `RSTRING_LEN` to get the string's length.
Note: I can't build or test this because I need ragel 7 which I have no idea how to install. But in theory this solution is good? 😅
> Update C lexer to handle strings with null bytes

- lib/graphql/schema/resolver.rb
- spec/graphql/schema/resolver_spec.rb
Oops -- I think this was just an oversight that `description` wasn't passed down to children.
> Make resolvers inherit description from superclass

- guides/schema/definition.md
Fix the copy from autoload to eager load.
> Fix definition.md copy from autoload to eager load

- gemfiles/mongoid_7.gemfile
- gemfiles/rails_7.0.gemfile
- guides/type_definitions/enums.md
- lib/graphql/introspection/directive_location_enum.rb
- lib/graphql/schema/enum.rb
- spec/graphql/schema/enum_spec.rb
- spec/support/jazz.rb
This is a pretty minor change, but might be helpful: now you can grab GraphQL name of the enum value using the method instead of a complex spell.
Before: `Jazz::Family.values["STRING"].graphql_name`
Now: `Jazz::Family.string`
> Allow accessing enum value names via methods

- lib/graphql/schema/validator/required_validator.rb
- spec/graphql/schema/validator/required_validator_spec.rb
The goal of this PR is to fix two bugs identified in the `required` validation.
When defining a required validation, if the first option defined is a set and that option is matched, the validation will pass, even if other options in the mutually exclusive group would match.
Consider the following query.
```gql
{
findObject(node_id: '1', object_type: 'Invoice', object_id: '1') {
id
}
}
```
The behaviour of the required validation is different depending on how the validation is defined.
```ruby
field :find_object, Node, null: true do
argument :node_id, ID, required: false
argument :object_type, String, required: false
argument :object_id, Integer, required: false
validates required: { one_of: [:node_id, [:object_type, :object_id]] }
validates required: { one_of: [[:object_type, :object_id], …
```
> Fix two bugs (order dependency and false positive) in the `required` validation

- lib/graphql/schema/build_from_definition.rb
- lib/graphql/schema/enum.rb
- spec/graphql/dataloader_spec.rb
- spec/graphql/schema/dynamic_members_spec.rb
- spec/graphql/schema/enum_spec.rb
- spec/spec_helper.rb
Modifies #5206, some cleanup elsewhere
> Rename enum value_name: to value_method:, fix some test warnings

- lib/graphql/schema/loader.rb
- spec/graphql/schema/loader_spec.rb
Avoid stderr output when using `GraphQL::Schema.from_introspection` to load a Scheme containing Enums with values like e.g. `"NAME"`. 
Copied somewhat-naively from a [similar change](https://github.com/rmosolgo/graphql-ruby/commit/52153a243e265fb75b01d1a6a62766a3583ef2c9). Please ensure this solution is appropriate!
Not sure where/if I should add a test
> Avoid warnings during Schema.from_introspection

- lib/graphql/language/parser.rb
- spec/graphql/language/parser_spec.rb
> Return a parse error when a variable type is missing

- lib/graphql/schema.rb
- spec/graphql/schema_spec.rb
Fix: https://github.com/rmosolgo/graphql-ruby/issues/5222
In GraphQL 2.4.9, there was a change in how exceptions are handled when using `GraphQL::Backtrace`. 
This PR restores the 2.4.8 behavior when using backtrace and rescue_from.
> Fix GraphQL::Backtrace::TracedError handling

- lib/graphql/schema.rb
- spec/graphql/backtrace_spec.rb
Fixes #5232
I cherry-picked this commit onto 2.4.8 to make sure that these tests also passed there (ie, this is _compatible_ with that version)
> Don't wrap GraphQL::ExecutionError with a Backtrace error

- guides/authorization/visibility.md
- lib/graphql/query.rb
- lib/graphql/schema/visibility.rb
- lib/graphql/schema/visibility/profile.rb
- spec/graphql/schema/visibility/profile_spec.rb
As discussed in #5231: 
- Always use `context[:visibility_profile]`, route the query argument to that context key 
- When that key is present, used the configured context for `.visible?` calls (not the query context). The full query context is still used for dynamic queries (without `context[:visibility_profile]`) 
- For good measure, freeze passed-in profile hashes.
> Improve Visibility profile contexts

- lib/graphql/schema/visibility.rb
- lib/graphql/schema/visibility/profile.rb
- spec/graphql/schema/visibility_spec.rb
> Fix possible_type membership when inherited from superclass

- .rubocop.yml
- cop/development/trace_methods_cop.rb
- lib/graphql/execution/interpreter.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/schema/object.rb
- lib/graphql/static_validation/validator.rb
- lib/graphql/tracing/new_relic_trace.rb
- lib/graphql/tracing/perfetto_trace.rb
- lib/graphql/tracing/trace.rb
- spec/graphql/tracing/new_relic_trace_spec.rb
- spec/graphql/tracing/trace_spec.rb
- spec/support/new_relic.rb
Basically, using `do ... end`-type instrumentation can get confused when there's a `Fiber.yield` inside the block. (Dataloader does this when a field calls `.load`.) You can end up with situations where the sum of segments adds up to more than the total request time, because Fiber _wait_ time is being added to the time when another Fiber is running. This makes sense-ish from New Relic's standpoint; they can't really know when the application handed over control in a way that "shouldn't count." See discussion at https://github.com/newrelic/newrelic-ruby-agent/issues/3026. 
So, what we can do is _stop_ spans when there's a `.yield` called, then create a new span after the Fiber resumes control. I developed this in PerfettoTrace and I intend to roll it out to the other tracers, too. 
-----
I …
> Rewrite NewRelicTrace to support fiber stops/starts

- lib/graphql/invalid_name_error.rb
> Use a non-runtime error class for InvalidNameError

- .github/workflows/ci.yaml
- gemfiles/mongoid_8.gemfile
- gemfiles/mongoid_9.gemfile
Old mongoid versions depended on versions of ActiveSupport which didn't have `Notifications.monotonic_subscribe`. I'd rather just update these builds to use modern versions than support Rails 5 😩
> Update to Mongoid 8 and 9

- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/invalid_null_error.rb
- lib/graphql/schema.rb
- spec/graphql/execution/errors_spec.rb
- spec/graphql/execution/multiplex_spec.rb
- spec/graphql/non_null_type_spec.rb
- spec/graphql/query/executor_spec.rb
- spec/graphql/schema/mutation_spec.rb
Closes https://github.com/rmosolgo/graphql-ruby/issues/5239
`InvalidNullError` was modeled as a `RuntimeTypeError` but also implemented `to_h` to act like an `ExecutionError`. It was a strange hybrid which made it harder for applications to change how the errors were handled.
It also caused limitations such as not being easy to add `extensions` or `path` to the error in the response.
This changes `InvalidNullError` to inherit from the base `GraphQL::Error` instead of `RuntimeTypeError`. Instead of adding the instance of `InvalidNullError` directly to `context.errors`, the default implementation is changed to create a new `ExecutionError` instead.
This provides a simpler middle ground where applications can still choose to handle `InvalidNullError` exceptions differently (such as reporting …
> Improve default InvalidNullError handling

- lib/graphql/schema/build_from_definition.rb
- lib/graphql/schema/enum.rb
- lib/graphql/schema/input_object.rb
- lib/graphql/schema/loader.rb
- spec/graphql/schema/dynamic_members_spec.rb
- spec/graphql/schema/enum_spec.rb
- spec/graphql/schema/loader_spec.rb
- spec/support/jazz.rb
To opt in, add 
```ruby 
value_methods(true)
```
To your base enum class. Fixes #5254
> Make Enum value_methods optional

- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/invalid_null_error.rb
- spec/graphql/non_null_type_spec.rb
Resolves https://github.com/rmosolgo/graphql-ruby/issues/5243
`InvalidNullError#value` is always set to `nil`, it won't be a `GraphQL::ExecutionError` as the docs suggests.
https://github.com/rmosolgo/graphql-ruby/blob/c2dedb0dacb3c52f0531e5d035bc566961a30c93/lib/graphql/execution/interpreter/runtime.rb#L469-L476
> Remove `InvalidNullError#value` as it is always `nil`

- lib/graphql/language/lexer.rb
- lib/graphql/language/parser.rb
- spec/graphql/language/parser_spec.rb
Somehow between the lexer and parser, this last brace is being ignored. Something about `lexer.eos?` returning true even though there's an unhandled token still there.
> Raise a ParseError on dangling close curly brace

- lib/graphql/analysis.rb
- lib/graphql/analysis/visitor.rb
- lib/graphql/schema.rb
- spec/graphql/analysis_spec.rb
`Timeout::timeout` may interrupt I/O operations leading to messed up connection handles. By implementing the timeout in Ruby instead, we can be sure that I/O operations will have terminated cleanly. 
Downsides: a long-running I/O operation will not be killed halfway through. To mitigate this, you'll need timeouts on your client libraries themselves. Also, the timeout is only checked periodically so it's not 100% accurate (runtime may be a tiny bit longer than the timeout).
Also I removed `on_fragment_definition`. This is because the `super(query.selected_operation)` line in `def initialize` means that fragment definitions are never actually visited. I discovered this because I added a `check_timeout` to the old `def on_fragment_definition` and I couldn't get a test to fail for it 🤦 
part …
> Use a manual timeout implementation in Analysis to handle I/O gracefully

- guides/queries/timeout.md
- lib/graphql/schema.rb
- spec/graphql/schema_spec.rb
Currently, `graphql-ruby` does not enforce a timeout for schema validation by default. When `validate_timeout` isn't explicitly set, maliciously crafted queries can consume substantial server resources and potentially cause denial of service (DoS) conditions.
Through Shopify's bug bounty program, we've received multiple reports demonstrating that a single host can leverage this behavior to impact an entire API.
Add a reasonable default timeout (3 seconds) for schema validation that:
- protects all downstream consumers
- maintains backward compatibility and 
- preserves the ability to customize or disable the timeout
- **Data-Driven Decision**: We analyzed performance metrics across many GraphQL services at Shopify, examining the 95th percentile of GraphQL execution time (not including …
> Set default timeout for GraphQL schema validation

- cop/development/trace_methods_cop.rb
- lib/graphql/tracing/new_relic_trace.rb
- spec/graphql/tracing/new_relic_trace_spec.rb
Oops, this option was accidentally removed in #5240 
Also, I learned while working on #5270  that a stack isn't really necessary here. Since a single fiber can only do one thing, just a `Fiber[...]` assignment will do.
> Fix(NewRelic) reimplement trace_scalars

- lib/graphql/execution/interpreter.rb
- spec/graphql/execution/interpreter_spec.rb
- spec/graphql/tracing/new_relic_trace_spec.rb
Version `2.4.10` changed the NewRelicTrace class to support fiber stops/starts.
Now `GraphQL::Execution::Interpreter` calls `begin_execute_multiplex`, which relies on the [first multiplex query](https://github.com/rmosolgo/graphql-ruby/blob/v2.4.10/lib/graphql/tracing/new_relic_trace.rb#L68) in the list:
```ruby
def begin_execute_multiplex(multiplex)
query = multiplex.queries.first
set_this_txn_name = query.context[:set_new_relic_transaction_name]
...
end
```
Theoretically, it is possible to call multiplex with an empty array (I know, this is an edge case, but it is possible). In this case, we don't have any query to run and can return an empty result.
If the Schema uses the NewRelic tracer, `GraphQL::Tracing::NewRelicTrace#begin_execute_multiplex` fails with error because …
> Immediately return empty array in multiplex if queries list is empty

- lib/graphql/schema.rb
- lib/graphql/schema/build_from_definition.rb
- spec/graphql/schema/build_from_definition_spec.rb
Something I've been considering for a while now... it'd be useful to be able to build a schema from SDL while also providing base type classes. This would allow the base type classes to setup features like visibility hooks in the constructed schema.
```ruby
sdl = %|
type A { a:Int } 
type B @private { a:Int } 
type Query { 
a:A
b:B
}
|
class BaseObject < GraphQL::Schema::Object
def visible?(ctx)
ctx[:visibility_profile] == "private" || !directives.find { _1.name == "private" }
end
end
GraphQL::Schema.from_definition(sdl, base_types: { object: BaseObject })
```
At present you'd need to either modify the base library classes, or else build the schema with generic base types and then [step through all elements adding behavior mixins](https://github.com/gmac/graphql-stitching-ruby/pull/124/fil …
> Base type classes for `Schema.from_definition`

- CHANGELOG.md
- lib/graphql/query/validation_pipeline.rb
- lib/graphql/schema.rb
- lib/graphql/static_validation/base_visitor.rb
- lib/graphql/static_validation/rules/fields_will_merge.rb
- lib/graphql/static_validation/rules/fragments_are_finite.rb
- lib/graphql/static_validation/validation_context.rb
- lib/graphql/static_validation/validator.rb
- spec/graphql/query_spec.rb
- spec/graphql/static_validation/rules/argument_names_are_unique_spec.rb
- spec/graphql/static_validation/rules/fields_will_merge_spec.rb
- spec/graphql/static_validation/rules/fragments_are_finite_spec.rb
- spec/graphql/static_validation/rules/fragments_are_used_spec.rb
- spec/graphql/static_validation/rules/input_object_names_are_unique_spec.rb
- spec/graphql/static_validation/rules/operation_names_are_valid_spec.rb
- spec/graphql/static_validation/rules/required_input_object_attributes_are_present_spec.rb
- spec/graphql/static_validation/rules/unique_directives_per_location_spec.rb
- spec/graphql/static_validation/rules/variable_names_are_unique_spec.rb
- spec/graphql/static_validation/rules/variable_usages_are_allowed_spec.rb
- spec/graphql/static_validation/rules/variables_are_used_and_defined_spec.rb
- spec/integration/rails/graphql/schema_spec.rb
- spec/support/static_validation_helpers.rb
Oops, these were lost when I released 1.11.11 because I recreated the 1.11.x branch from the wrong tag (I used 1.11.8 instead of 1.11.10). I'm getting these changes back on the branch and I'll cut 1.11.12 including _all_ this stuff.
> [1.11.x] Re-merge changes from 1.11.9, 1.11.10

- lib/graphql/schema/build_from_definition.rb
- spec/graphql/schema/build_from_definition_spec.rb
Type extensions are a neat prospect for managing schema supersets. It'd be handy if `Schema.from_definition` supported them. They're already fully supported in the language, so this adds them into the schema builder.
```graphql
type T { a:Int }
type Query { t:T }
extend type T { b:Int }
```
Using `Schema.from_definition` on the above gives type `T` with two fields on it.
> Support type extensions in `Schema.from_definition`

- .github/workflows/ci.yaml
- .github/workflows/pronto.yaml
- graphql.gemspec
Oops, it didn't work on PRs from forks because `on: pull_request` doesn't have permission to do that.
> Redo pronto action to work on forks

- lib/graphql/tracing/appoptics_tracing.rb
- lib/graphql/tracing/appsignal_trace.rb
- lib/graphql/tracing/data_dog_trace.rb
- lib/graphql/tracing/monitor_trace.rb
- lib/graphql/tracing/prometheus_trace.rb
- lib/graphql/tracing/scout_trace.rb
- lib/graphql/tracing/sentry_trace.rb
- lib/graphql/tracing/statsd_trace.rb
- spec/graphql/tracing/appsignal_trace_spec.rb
- spec/graphql/tracing/prometheus_trace_spec.rb
- spec/graphql/tracing/prometheus_tracing_spec.rb
- spec/graphql/tracing/scout_trace_spec.rb
- spec/graphql/tracing/sentry_trace_spec.rb
- spec/graphql/tracing/statsd_trace_spec.rb
- spec/graphql/tracing/statsd_tracing_spec.rb
- spec/support/scout_apm.rb
- ~~Appoptics~~ deprecated instead, this has been out of use for a long time 
- Datadog: revisit `prepare_span` compatibility -- it's broken right now but shouldn't be.
- I'm going to release this in 2.5 instead with a breaking change note
> Update other monitoring platform traces to handle fiber stops and starts

- javascript_client/src/subscriptions/ActionCableLink.ts
- javascript_client/src/subscriptions/__tests__/ActionCableLinkTest.ts
This is another attempt at #5226 using a more generic approach. It includes support for `connected`, `disconnected` and `received` and passes the arguments to the user-defined callback.
> Proposal: ActionCable callbacks

- lib/graphql/language/parser.rb
- spec/graphql/language/parser_spec.rb
> Parser: raise when variable type doesn't include a type name

- lib/graphql/tracing/sentry_trace.rb
- spec/graphql/tracing/sentry_trace_spec.rb
- spec/support/sentry.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/2929#issuecomment-2771991624
Apparently Sentry's current_span is sometimes `nil`, the library itself is full of `nil` handling, for example:
https://github.com/getsentry/sentry-ruby/blob/a884caee95ddf3c29cec4761ab423ed56e0b16b5/sentry-ruby/lib/sentry/hub.rb#L137-L138
The previous code in GraphQL-Ruby had handling for `span` being nil, but my new code didn't. Now it does.
> Sentry trace: handle nil current_span

- gemfiles/rails_master.gemfile
- lib/graphql/tracing/monitor_trace.rb
- spec/dummy/test/controllers/dashboard/limiters/limiters_controller_test.rb
- spec/dummy/test/controllers/dashboard/operation_store/clients_controller_test.rb
- spec/dummy/test/controllers/dashboard/operation_store/index_entries_controller_test.rb
- spec/dummy/test/controllers/dashboard/operation_store/operations_controller_test.rb
- spec/dummy/test/controllers/dashboard/subscriptions/topics_controller_test.rb
- spec/graphql/tracing/data_dog_trace_spec.rb
- spec/support/datadog.rb
Swaps in the "platform_source_class_key" method instead of the previously unused "platform_source_key" to prevent a NoMethodError on initialization.
With the fix, suffix tracing works as expected
Relates to
- https://github.com/rmosolgo/graphql-ruby/issues/5316
> Fix monitor trace suffix method

- lib/graphql/schema/visibility/profile.rb
- spec/graphql/schema/visibility_spec.rb
Part of #5265 
This boiled down to two changes: 
- Extend argument visibility check to include a check to its owner 
- When checking a type's visibility, add a `referenced?` check which also makes a check of the reference's visibility
> Visibility: hide unreferenced arg types

- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/execution/interpreter/runtime/graphql_result.rb
- spec/graphql/backtrace_spec.rb
- spec/graphql/dataloader/async_dataloader_spec.rb
- spec/graphql/dataloader/nonblocking_dataloader_spec.rb
- spec/graphql/dataloader_spec.rb
- spec/graphql/execution/interpreter_spec.rb
- spec/graphql/execution/lazy_spec.rb
- spec/graphql/execution/multiplex_spec.rb
- spec/graphql/language/visitor_spec.rb
- spec/graphql/schema/build_from_definition_spec.rb
- spec/graphql/schema/directive_spec.rb
- spec/graphql/schema/field_spec.rb
- spec/graphql/schema/input_object_spec.rb
- spec/graphql/schema/interface_spec.rb
- spec/graphql/schema/timeout_spec.rb
- spec/graphql/schema/union_spec.rb
- spec/graphql/schema/validator_spec.rb
- spec/graphql/static_validation/rules/variable_usages_are_allowed_spec.rb
- spec/graphql/types/iso_8601_date_spec.rb
- spec/graphql/types/iso_8601_date_time_spec.rb
- spec/integration/rails/graphql/dataloader/async_dataloader_spec.rb
- spec/spec_helper.rb
Trying again at #5011 and #4252, replaces #5060
GraphQL-Ruby happens to return correctly-ordered results in simple cases because of Ruby's ordered Hash (results are inserted in the order they're encountered in the query). But a few things can cause it to be out-of-order: 
- Runtime directives (but not `@skip` or `@include`) are evaluated separately then merged back in -- merging causes mis-ordering
- Dataloaded values are written to the hash after non-Dataloaded values, therefore mis-ordered
`lazy_resolve(...)` values (like GraphQL-Batch's promises) don't have this problem because they're written immediately. But I'm trying to rebuild lazy resolve on top of dataloader to simplify execution code, so they might end up having this problem.
TODO: 
- Can it detect when order _might_ be wrong, …
> Return hashes with correctly ordered keys

- lib/graphql/schema/directive/flagged.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/member/has_deprecation_reason.rb
- lib/graphql/schema/resolver.rb
- spec/graphql/schema/resolver_spec.rb
> Add Resolver.deprecation_reason

- lib/graphql/schema/input_object.rb
- spec/graphql/schema/input_object_spec.rb
> Fix InputObject validation when it's a nested input object and has a prepare method

- lib/graphql/schema/visibility/profile.rb
Fixes #5324 
This code worked fine for small lists, where `.find` was trivial, but for large lists, it's better to use a `Set` (which uses a Hash under the hood). I think the memory overhead here won't be a problem since the cost here is basically one new Set per uniquely-named list in the current query (6 new objects in the example in #5324, 318 -> 324, but queries which use more distinct GraphQL types during execution will add more objects).
> Visibility: better duplicate name lookup

- lib/graphql/schema/always_visible.rb
- lib/graphql/schema/visibility.rb
This will be faster since the schema won't build any caches during execution. See benchmarks in https://github.com/rmosolgo/graphql-ruby/issues/5324#issuecomment-2789785528
> Refactor AlwaysVisible to use Schema::Visibility under the hood

- lib/graphql/schema.rb
- lib/graphql/static_validation/rules/fields_have_appropriate_selections.rb
- spec/graphql/static_validation/rules/fields_have_appropriate_selections_spec.rb
Fixes #4351 
This implementation: 
- Warns if an invalid query is encountered and no compat mode is selected;
- Provides a hook for handing invalid queries (which can permit, deny, or provide a custom message) 
- Provides a config to reject invalid queries 
I think this is a safe default to roll out to anyone already using the gem.
cc @gmac -- finally...
> Require selections on Unions, with backwards compat

- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/invalid_null_error.rb
- spec/graphql/execution/errors_spec.rb
- spec/graphql/execution/interpreter_spec.rb
- spec/graphql/schema/list_spec.rb
Hello and thanks for the gem!
Currently for a field like
```ruby
field :dog_names, [String], null: false
def dog_names
["wedge", nil]
end
```
You would get an error message like `Cannot return null for non-nullable field Query.dogNames`.  The phrasing of that message leads a person to think that the problem is that the return value of the `dog_names` method is `nil` when the error is actually referring to the value at index 1 of the returned array.
The purpose of this PR is to change the messaging so that, if the error is caused by a list value with an invalid element, it says that explicitly.
I had hoped to include the path to the element so the user would know the index of the failing element, but I couldn't figure out how to best do that.  It seems like the `idx` int the …
> Improve nullable array element type error reporting

- lib/graphql/dataloader/active_record_source.rb
- lib/graphql/dataloader/source.rb
- spec/graphql/dataloader/active_record_association_source_spec.rb
- spec/graphql/dataloader/active_record_source_spec.rb
- spec/graphql/tracing/snapshots/example-rails-7-0.json
- spec/graphql/tracing/snapshots/example-rails-7-1.json
- spec/graphql/tracing/snapshots/example-rails-8-1.json
- spec/support/active_record_setup.rb
This makes ActiveRecordSource and ActiveRecordAssociationSource work with composite primary keys.
> ActiveRecordSource: Improve composite primary key support

- lib/graphql/dataloader/active_record_association_source.rb
- spec/graphql/dataloader/active_record_association_source_spec.rb
- spec/support/active_record_setup.rb
I have always argued _against_ batch-loading `has_many` associations, because I think it's better to paginate them (and you can't do both), but admittedly there _are_ legitimate reasons to not paginate them (when they're scoped in to other ways or somehow guaranteed to be not-huge), so this source should support them somehow.
> Support has_many in ActiveRecordAssociationSource

- lib/graphql/schema/input_object.rb
Fixes #2994
(Technically, there are two points in that issue -- but I'm sure point #2, benchmarking `get_argument`, has been done!)
This exposes an interesting bug where the first error created by an input object argument would give its name to the error message, while subsequent error messages add "problems." Reordering this code means that a new argument name may appear in the error message and the problems may appear in a different order.
> Simplify check for non-null input object arguments

- lib/graphql/tracing/notifications_trace.rb
- spec/graphql/tracing/active_support_notifications_trace_spec.rb
> ActiveSupport::Notifications: fix fiber resume without previous event

- lib/graphql/analysis/query_complexity.rb
I was upgrading from 2.5.2 to 2.5.3 and notice the message about breaking fixes in complexity cost system. When I tried to open the url I noticed it is not working so I updated it to the correct one.
> Fix typos in complexity cost mode note

- lib/graphql/analysis/query_complexity.rb
- spec/graphql/analysis/query_complexity_spec.rb
Oops, this argument was missing and it defaulted to new behavior. It should have been defaulting to the old behavior to retain compatibility in all cases.
> Default complexity behavior to legacy

- lib/graphql/schema/warden.rb
Fixes #5337 
This method can return without building `reachable_types_set`, instead using the schema cache of `@references`.
I wrote a little script to demonstrate the regression: 
<details>
<summary>Using an otherwise-unreferenced union as `loads:` in a large schema</summary>
<p>
```ruby
require "bundler/inline"
gemfile do
gem "graphql", path: "./"
gem "benchmark-ips"
gem "stackprof"
gem "memory_profiler"
end
module Thing
include GraphQL::Schema::Interface
field :id, ID
end
all_object_types = []
20.times do |i|
obj_type = Class.new(GraphQL::Schema::Object) do
i.times do |i2|
field "f#{i2}", "MySchema::Object#{i2}"
end
implements Thing
end
const_set("Object#{i}", obj_type)
all_object_types << obj_type
end
class AllObjects < GraphQL::Schema::Union
end …
```
> [2.4] Use a faster check for `loadable?`

- lib/graphql/schema/scalar.rb
`GraphQL::Language.serialize` already has its own special handling for `Float::INFINITY`. It serializes it as "Infinity" which is inconsistent with this empty string as well.
> Scalar validation: remove redundant infinity handling

- lib/graphql/schema/timeout.rb
- spec/graphql/schema/timeout_spec.rb
Now, inside `handle_timeout`, you can disable the timeout for the rest of the query like this: 
```ruby 
class MyCustomTimeout < GraphQL::Schema::Timeout 
def handle_timeout(error, query)
if some_condition?
disable_timeout(query) 
else 
end 
end 
end 
```
> Support disabling timeout mid-way through

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/schema/scalar_spec.rb
Adds improved handling for `coerce_result` errors which results in more spec compliant errors with `path` and `locations` present.
Separated out from https://github.com/rmosolgo/graphql-ruby/pull/5306 because this can be merged more easily.
> Improve scalar result coercion execution errors

- lib/graphql/execution/interpreter/runtime.rb
I'm extracting some improvements I noticed while working on #5389
> Remove needless job counting 

- lib/graphql/schema/build_from_definition.rb
This will reused a cached lookup rather than looking it up from scratch (and allocating `ancestors`) every time.
> Use a cached lookup for field resolution from SDL

- lib/graphql/schema/validator/required_validator.rb
- spec/graphql/schema/validator/required_validator_spec.rb
- spec/graphql/schema/validator/validator_helpers.rb
> RequiredValidator: remove non-visible definitions from the error message

- lib/graphql/dataloader/active_record_association_source.rb
- spec/graphql/dataloader/active_record_association_source_spec.rb
> Fix association loads with different scopes on the same object

- lib/graphql/execution/interpreter/resolve.rb
- spec/graphql/dataloader_spec.rb
Fixes #5399 
Previously, the promises were all resolved inside a single fiber, so when a promise led to a Dataloader `.load` call, that fiber would pause until Dataloader ran. Then that fiber would resume again, make the next `.load` call, then pause again. 
Now, each promise is handled in a separate fiber, so when it calls `.load`, Dataloader can continue running other fibers (and then it can accumulate other `.load` calls before running `#fetch`).
> Support dataloader calls after batched lazy resolve

- lib/graphql/schema/build_from_definition.rb
- spec/graphql/schema/build_from_definition_spec.rb
Fixes #5366 
This supports the case that a directive definition references a later type in the schema _and_ that type references a directive which is _also_ later in the document.
> Fix loading directives from SDL

- lib/graphql/schema/member/has_arguments.rb
Add explicit `@api public` documentation to the `load_application_object_failed` method to clarify that it's a public hook intended to be overridden by users
As noted in #5418, the `load_application_object_failed` method appears to be marked as a private API in the generated documentation, which conflicts with the mutation guides that explicitly recommend overriding this method for custom error handling.
**In prod:** 
**Local yard server:**
> Mark load_application_object_failed as public API
