rmosolgo/graphql-ruby

.gitignore, Gemfile.lock, graphql.gemspec, lib/graph_ql/directive.rb, lib/graph_ql/parser.rb, lib/graph_ql/query.rb, lib/graph_ql/schema.rb, lib/graph_ql/static_validation.rb, lib/graph_ql/types/type_definer.rb, lib/graphql.rb
Make the dependency loading explicit (we're not lazy anyway since we
instantiate many types at load time). Getting the order right here is a
bit messy, but having it be explicit seems better than masking the chain
of dependencies.
r? @rmosolgo
=> Remove activesupport dependency

lib/graphql/query.rb, readme.md
Code clean up: remove deprecated `params:` keyword in `Query#initialize`
=> Remove deprecated params: keyword

lib/graphql/query/directive_chain.rb, spec/graphql/directive_spec.rb
Tried to look at other implementations and how they did this but their implementation doesn't usually this type of chain and will just return only if there's a `@skip` not taking in consideration future `directives`.
This checks if there is a `skip` directive and if so removes all `include` directives from `ast_directives`
Not sure if that's the best way to go about it. Let me know if you see a better way :dancers:
=> Skip directive has precedence over include

lib/graphql.rb, spec/graphql/query_spec.rb
1. Passing `error.cause.pos` into `line_and_column is necessary to avoid getting 1,1. It still doesn't help a ton, since the error is almost always the first character of your query (i.e. it only skips whitespace), but at least now it matches the pos in the error message.
1. Wrap the response in a `GraphQL::ParseError` so that it's easier to catch/handle.
=> Better raise for parse errors

lib/graphql/query/base_execution.rb
This removed the get_class method, since it was always called with a constant class name.
E.g. `self.class::FieldResolution` does the same thing as `self.class.const_get(:FieldResolution)`
=> Use self.class::Name rather than get_class(:Name)

readme.md
The "To Do" section of the readme said "Write Ruby bindings for libgraphqlparser and use that instead of Parslet", so I linked to existing ruby bindings for libgraphqlparser.
=> Link to already written ruby bindings for libgraphqlparser.

lib/graphql/base_type.rb, readme.md, spec/graphql/introspection/schema_type_spec.rb, spec/graphql/query/type_resolver_spec.rb, spec/graphql/union_type_spec.rb, spec/support/dairy_app.rb, spec/support/dairy_data.rb
https://github.com/rmosolgo/graphql-ruby/blob/60d27b1351cc7212925c06f92ef36a75d02349eb/lib/graphql/query/type_resolver.rb#L11
This line here raises undefined method `#include?` for `UnionType` when using a union type field.
I've added an `#include?` method to the `HasPossibleTypes` module. Please correct me if this is not a bug and just me incorrectly using the type :)
=> Add include method to has possible types module

CHANGELOG.md, guides/defining_your_schema.md, lib/graphql/query/serial_execution/field_resolution.rb, lib/graphql/schema.rb, lib/graphql/schema/middleware_chain.rb, lib/graphql/schema/rescue_middleware.rb, readme.md, spec/graphql/query/executor_spec.rb, spec/graphql/schema/middleware_chain_spec.rb, spec/graphql/schema/rescue_middleware_spec.rb, spec/graphql/schema_spec.rb, spec/support/dairy_app.rb
- Add middleware to query execution 
- This could also be used for metrics or permissions 
- Add RescueMiddleware for handling exceptions 
The resulting API: 
```ruby
MySchema.rescue_from(ActiveRecord::NotFound) { |err| "Some items weren't found" }
```
When a field raises that error, the field returns `nil` and the error message is put in the response
=> Middleware

guides/introduction.md
Go to the [Introduction guide](https://github.com/rmosolgo/graphql-ruby/blob/6c66f7c85dd93d7346cd308010644beb3b2e9b9c/guides/introduction.md#more-info) and click on the "Type & Field Helpers" link and it will take you to a 404 page.
The guide being linked to was renamed to [Defining Your Schema](https://github.com/rmosolgo/graphql-ruby/blob/6c66f7c85dd93d7346cd308010644beb3b2e9b9c/guides/defining_your_schema.md), so I linked to that instead.
=> Fix link in Introduction guide to Defining Your Schema guide.

lib/graphql.rb, lib/graphql/base_type.rb, lib/graphql/introspection/arguments_field.rb, lib/graphql/introspection/field_type.rb, lib/graphql/introspection/input_fields_field.rb, lib/graphql/introspection/input_value_type.rb, lib/graphql/introspection/interfaces_field.rb, lib/graphql/introspection/possible_types_field.rb, lib/graphql/introspection/type_type.rb, lib/graphql/list_type.rb, lib/graphql/non_null_type.rb, lib/graphql/schema/printer.rb, spec/graphql/schema/printer_spec.rb
This implements the schema printer, similar to the one in [graphl-js](https://github.com/graphql/graphql-js/blob/v0.4.4/src/utilities/schemaPrinter.js), which outputs the schema as a string in graphql format.
This can be useful for inspecting the schema, which actually turned up some differences between the inspection type system in graphql-ruby and the [graphql specification](http://facebook.github.io/graphql/#sec-Schema-Introspection), which I also fixed in this pull request.
Being able to save the schema is also useful for sharing with a client, which may be written in another language.
=> Implement a schema printer

lib/graphql/base_type.rb, lib/graphql/definition_helpers/defined_by_config.rb, lib/graphql/enum_type.rb, lib/graphql/non_null_type.rb, lib/graphql/query/arguments.rb, lib/graphql/query/base_execution/value_resolution.rb, lib/graphql/scalar_type.rb, lib/graphql/static_validation/literal_validator.rb, spec/graphql/enum_type_spec.rb, spec/graphql/query/value_resolution_spec.rb
This is the start of a fix for issue #47, which splits input and result coercion.
The most noticeable change is that enum's now get properly coerced to their value and their value gets coerced back to the enum name in result coercion.
However, as noted in https://github.com/rmosolgo/graphql-ruby/issues/46#issuecomment-145977865, we aren't actually actually coercing most values, so the follow-up to this will add input coercion for non-scalars, so we can coerce all values in `GraphQL::Query::Arguments`.
=> Seperate input and result coercion for scalars.

lib/graphql/language/parser.rb, spec/graphql/language/transform_spec.rb
Previously the operation wouldn't be transformed if the operation name is missing
```
irb> GraphQL.parse('query { name }')
=> {:document_parts=>[{:operation_type=>"query"@0, :variables=>[], :directives=>[], :selections=>[#<GraphQL::Language::Nodes::Field:0x007fac6157a278 @name="name", @alias=nil, @arguments=[], @directives=[], @selections=[], @line=1, @col=9>]}]}
```
returning a hash from GraphQL.parse rather than a GraphQL::Language::Nodes::Document object, resulting in queries to fail with an exception like `NoMethodError - undefined method `parts' for #<Hash:0x007f5fc63dc3e0>`
I fixed this by having it capture the optional name rather than making the capture optional, since the transform needs that `:name` key to exist in the hash.
=> Fix parslet transformation for unnamed operations.

lib/graphql/query/arguments.rb, spec/graphql/query/arguments_spec.rb
Calling `.each`, `.keys` or `.values` on an GraphQL::Query::Arguments object will result in a NoMethodError (e.g. undefined method `each' for nil:NilClass)
def_delegators was just specifying the wrong instance variable name, so I corrected that.
=> Fix delegators on GraphQL::Query::Arguments.

readme.md
Having them listed out there right at the top of the README I think
improves discoverability. Previously, it just link directly to the
introduction, which if you didn't read all the way to the bottom, you
might not realize that more guides exist.
=> Link to the individual guides right in the README

lib/graphql/schema/type_reducer.rb, spec/graphql/schema/type_reducer_spec.rb
Currently when defining a field with a non-valid type, such an active record model class instead of the GraphQL type, this is raised:
`NoMethodError (undefined method unwrap for #<Class:0x007faf41021848>)`
This PR adds a check in `reduce_type` to see if the type is a subclass of `GraphQL::BaseType`. This removes the need for the nil check in initialize and will help debugging the schema when hitting that problem.
Let me know what you think!
=> Raise when a field's type is not a valid GraphQL::BaseType object

lib/graphql/language/transform.rb, spec/graphql/language/transform_spec.rb
The Parslet transform fails on nested lists in field arguments, leading to line 27 of lib/graphql.rb raising:
```
raise("Parse failed! Sorry, somehow we failed to turn this string into a document. Please report this bug!")
```
I used this spec while figuring out the fix, it's a good example of the issue: https://gist.github.com/charlieschwabacher/d97d6631523aad272b84, the tests at lines 43 and 48 will fail in master.  
I didn't include it in the pull - I think the addition to transform_spec.rb should be enough to cover this, but let me know if there is anywhere you think it would make sense to add a spec similar to that gist.
=> fix transform failure on nested lists in field arguments

lib/graphql/language/parser.rb, lib/graphql/language/transform.rb, spec/graphql/language/transform_spec.rb
cc @eapache
We noticed that newline characters in graphql strings were getting replaced with the character `n`, e.g.
```ruby
QueryRoot = GraphQL::ObjectType.define do
name "Query"
field :hello, types.String do
argument :name, types.String
resolve -> (obj, args, ctx) {
puts args[:name].inspect
}
end
end
Schema = GraphQL::Schema.new(query: QueryRoot)
Schema.execute("{ hello(name: \"new\\nline\") }")
```
outputs `"newnline"` rather than `"new\nline"`
The transform on the escaped string was being done with a regex which matched the escaped sequence `\n` but then just replaced it with it with the second character `n` rather than unescaping it.  I instead used a hash as a second argument to `gsub!` to replace `\n` with a newline, along with handling the other control character …
=> Fix parsing and transforming of string escapes.

lib/graphql/object_type.rb, spec/graphql/interface_type_spec.rb
cc @dylanahsmith 
Remove stale `possible_types` entries and add to only the ones that are new.
We ran into this due to the way we were structuring some of our code, our schema ended up with duplicate possible types.
=> Correctly handle `interfaces` being re-assigned

lib/graphql/query/serial_execution/selection_resolution.rb, spec/graphql/interface_type_spec.rb, spec/graphql/introspection/type_type_spec.rb, spec/spec_helper.rb, spec/support/dairy_app.rb, spec/support/dairy_data.rb
Demonstrates that fields on interfaces overwrite each other. Per discussion in the Ruby GraphQL Slack.
=> Add a failing spec for merging fields on interfaces.

guides/defining_your_schema.md, lib/graphql/query/serial_execution/field_resolution.rb, spec/graphql/execution_error_spec.rb, spec/graphql/introspection/schema_type_spec.rb, spec/support/dairy_app.rb
If an GraphQL::ExecutionError object is returned from a field resolve proc, then it is reported as an error on that field.  However, it would be more natural to raise an exception of a specific class to report an error, which would require the rescue middleware.
Unfortunately, the rescue middleware currently doesn't catch all the errors during field resolution, since it misses type resolution and value coercion.
Allow a GraphQL::ExecutionError to be intentionally raised from a resolve, coercion or type resolution proc and have that error affect only that field rather than causing the whole query to fail.
=> feat(Query): Rescue GraphQL::ExecutionError in field resolution.

lib/graphql.rb, lib/graphql/language/nodes.rb, lib/graphql/language/transform.rb, lib/graphql/query.rb, lib/graphql/query/literal_input.rb, lib/graphql/static_validation/literal_validator.rb, lib/graphql/static_validation/rules/variable_default_values_are_correctly_typed.rb, lib/graphql/static_validation/rules/variables_are_input_types.rb, lib/graphql/static_validation/validator.rb, spec/graphql/language/transform_spec.rb, spec/graphql/query/variables_spec.rb, spec/graphql/static_validation/validator_spec.rb
This will make libgraphqlparser integration easier because you can build up the AST bit-by-bit instead of giving everything to the node at `initialize`. 
- Remove the required-argument initialize (it helped during prototyping, but it's pointless now)
- Rename some AST classes and properties to present a more consistent API
__Todo__:
=> refactor(Language::Nodes) support libgraphqlparser

lib/graphql.rb, lib/graphql/invalid_null_error.rb, lib/graphql/non_null_type.rb, lib/graphql/null_non_null_error.rb, lib/graphql/query/serial_execution/field_resolution.rb, lib/graphql/query/serial_execution/selection_resolution.rb, lib/graphql/query/serial_execution/value_resolution.rb, spec/graphql/introspection/schema_type_spec.rb, spec/graphql/query/executor_spec.rb, spec/support/dairy_app.rb
@rmosolgo @dylanahsmith I spent the last day and a bit down a rabbit-hole of nulls and type coercion. This fixes the immediate issue but raises several more interesting questions:
- We do not currently provide a way for types to specify a coercion for `nil`
values. According to the GraphQL spec on non-null types [1], you *are*
supposed to run coercion for `nil`s and only fail if the *coercion* produces
`nil` (so e.g. the boolean scalar type is allowed to coerce `nil` to false if
it wants). I took a quick try to do this but ran aground quickly.
- We do not distinguish at the scalar coercion level between nullable and
non-null-wrapped types. It may make sense, for example, for a regular boolean
to let `nil` stay as `nil` but to coerce `nil` to `false` when wrapped in a
non-null; this …
=> Error when non-null fields resolve to nil

lib/graphql/static_validation/literal_validator.rb, lib/graphql/static_validation/rules/argument_literals_are_compatible.rb, spec/graphql/static_validation/rules/argument_literals_are_compatible_spec.rb
We were getting an exception when specifying a field on an input object literal that wasn't in the input object type.  This can be reproduced with the following script:
```ruby
TestInputType = GraphQL::InputObjectType.define do
name "TestInput"
input_field :foo, types.String
end
QueryType = GraphQL::ObjectType.define do
name "Query"
field :test, types.Boolean do
argument :input, TestInputType
resolve -> (obj, args, ctx) { 42 }
end
end
Schema = GraphQL::Schema.new(query: QueryType)
query = '{ test(input: { bar: "value" }) }'
puts Schema.execute(query)
```
which gives the exception
```
/Users/dylansmith/src/graphql-ruby/lib/graphql/static_validation/literal_validator.rb:40:in `block in present_input_field_values_are_valid': undefined method `type' for nil:NilClass …
```
=> fix: Avoid exception from input object literal with an undefined field.

lib/graphql/query/serial_execution/field_resolution.rb
@rmosolgo & @eapache for review
This refactoring will allow graphql-batch to remove the adding of the error to the context in its override of get_finished_value (https://github.com/Shopify/graphql-batch/blob/7467505e80d2fd21333f5ca028f689692f6a5393/lib/graphql/batch/execution_strategy.rb#L54-L56) and replace those lines with `super(error)`
The adding of the error to the context was actually done in get_finished_value in the latest release (https://github.com/rmosolgo/graphql-ruby/blob/v0.10.9/lib/graphql/query/serial_execution/field_resolution.rb#L30) so this just reverts it back to working that way, while still catching execution errors raised from get_raw_value
=> refactor: Move code to add the error to the context in field resolution.

lib/graphql/query/serial_execution.rb, lib/graphql/query/serial_execution/execution_context.rb, lib/graphql/query/serial_execution/field_resolution.rb, lib/graphql/query/serial_execution/operation_resolution.rb, lib/graphql/query/serial_execution/selection_resolution.rb, lib/graphql/query/serial_execution/value_resolution.rb, spec/graphql/query/serial_execution/execution_context_spec.rb
As we add more and more features to the Executor, our `initialize` adds more and more arguments.
This PR introduces am `ExecutionContext` object that currently wraps `query` and `execution_strategy` as well as providing method to access or modify these fields.
This object wraps values that are carried all the way from the base execution up to the value resolution, and will be helpful to add any other values related to an entire query (from start to end)
I've added tests for it, but it might not be necessary as other parts are already tested.
Let me know what you think.
=> ExecutionContext object to wrap query and strategy during execution

lib/graphql/interface_type.rb, lib/graphql/introspection/fields_field.rb, lib/graphql/object_type.rb, lib/graphql/schema.rb, lib/graphql/schema/printer.rb, lib/graphql/schema/type_reducer.rb, lib/graphql/static_validation/rules/fields_are_defined_on_type.rb, readme.md, spec/graphql/introspection/schema_type_spec.rb, spec/graphql/introspection/type_type_spec.rb, spec/graphql/object_type_spec.rb, spec/graphql/schema/type_reducer_spec.rb, spec/support/dairy_app.rb
As described in [our earlier conversation](https://github.com/rmosolgo/graphql-ruby/issues/91#issuecomment-184615939), this allows interfaces to be used as mixins. 
You can get field implementations from the interface _or_ you can override them in the object type. 
One outstanding issue is, can we cache the result of looking up a field? At what level? Some things I want to support, but don't support well yet, are: 
- Rails development reloading 
- Multiple schemas in one application
=> feat(ObjectType) lookup field implementations from interface, too

lib/graphql/base_type.rb, lib/graphql/enum_type.rb, lib/graphql/float_type.rb, lib/graphql/input_object_type.rb, lib/graphql/list_type.rb, lib/graphql/non_null_type.rb, lib/graphql/query.rb, lib/graphql/query/input_validation_result.rb, lib/graphql/query/variable_validation_error.rb, lib/graphql/query/variables.rb, lib/graphql/scalar_type.rb, spec/graphql/enum_type_spec.rb, spec/graphql/input_object_type_spec.rb, spec/graphql/list_type_spec.rb, spec/graphql/query/executor_spec.rb, spec/graphql/query_spec.rb, spec/graphql/scalar_type_spec.rb, spec/support/minimum_input_object.rb
This PR adds more details to the error messages that you get when you provide invalid input variables to a GraphQL query.
Currently, you get error messages like this:
```js
errors: [
{
message: "Variable input of type [DairyProductInput] was provided invalid value [{\"foo\":\"bar\"}]",
locations: [{line: 1, column: 11}]
}
]
```
The message doesn't include much information about _what_ is wrong with the value. So the goal here is to provide more information, so that you can debug faster:
```js
errors: [
{
message: "Variable input of type [DairyProductInput] was provided invalid value",
locations: [{ line: 1, column: 11 }],
value: [{ foo: "bar" }],
problems: [
{ path: [0, "foo"], explanation: "Field is not defined on DairyProductInput" },
{ path: [0, "source"], explanation: "Expected value …
```
=> More details on input validation errors

lib/graphql/schema.rb, lib/graphql/static_validation/all_rules.rb, lib/graphql/static_validation/rules/does_not_exceed_max_depth.rb, spec/graphql/static_validation/rules/does_not_exceed_max_depth_spec.rb, spec/support/dairy_app.rb
This is a simple "security" feature, [inspired by Sangria](http://sangria-graphql.org/learn/#limiting-query-depth)
=> feat(StaticValidation) don't accept queries which exceed Schema#max_depth

lib/graphql/definition_helpers.rb, lib/graphql/definition_helpers/defined_by_config.rb, lib/graphql/definition_helpers/non_null_with_bang.rb, lib/graphql/definition_helpers/string_named_hash.rb, lib/graphql/definition_helpers/type_definer.rb
As commented here https://github.com/rmosolgo/graphql-ruby/issues/98, this PR is only a refactor to move inner class/module definitions to nested style.
It have a big diff (cause the indentation for all refactored files changed), but there are no functional changes so no specs update is required.
=> Refactor: One line class/module definitions to nested style

lib/graphql/boolean_type.rb, lib/graphql/float_type.rb, lib/graphql/id_type.rb, lib/graphql/int_type.rb, lib/graphql/scalar_type.rb, lib/graphql/string_type.rb, spec/graphql/boolean_type_spec.rb, spec/graphql/float_type_spec.rb, spec/graphql/id_type_spec.rb, spec/graphql/int_type_spec.rb, spec/graphql/static_validation/rules/variable_default_values_are_correctly_typed_spec.rb, spec/graphql/string_type_spec.rb
Oops, the built-in scalars weren't properly implementing input coercion. They should be more picky about what they accept! ([Spec](http://facebook.github.io/graphql/#sec-Scalars))
This will be a breaking change, but users who depend on the previous behavior can redefine it: 
```ruby 
GraphQL::BOOLEAN_TYPE.coerce = -> (value) { !!value }
GraphQL::ID_TYPE.coerce = -> (value) { value.to_s }
GraphQL::STRING_TYPE.coerce = ->  (value) { value.to_s }
```
PS. looking at the error messages, it looks like there's still a win to be made by getting the new validation messages into `StaticValidation`
cc @theorygeek
=> fix(Scalar) coerce inputs according to spec

lib/graphql/field.rb, lib/graphql/query/serial_execution/field_resolution.rb, spec/graphql/field_spec.rb
@rmosolgo is there any reason why the default resolve proc doesn't just resolve the value?
We are using a custom field that allows preload to be specified independently from the actually resolve proc, so we can call methods on a model and test that it doesn't result in N+1 queries.  We are doing this by enumerating fields and using the Field#resolve_proc directly after calling a preload proc.  However, we are overriding build_default_resolver to avoid having to detect and handle when the resolve proc returns GraphQL::Query::DEFAULT_RESOLVE.
Call `obj.public_send(name)` in Field#build_default_resolver rather than returning `GraphQL::Query::DEFAULT_RESOLVE`
=> Handle the default resolving in GraphQL::Field.

lib/graphql/execution_error.rb, lib/graphql/query.rb, lib/graphql/query/executor.rb, spec/graphql/query/executor_spec.rb
This gem would send standard errors to clients, which could include sensitive information.  For example, when using the mysql2 gem, the error message could include the database query.
Ironically, we have been using the `debug: true` option to both hide the internal error messages and get access to the full error information for logging and for error reporting.  I would like to get rid of that hack.
Use `"Internal error"` as the error message for standard errors.  ExecutionError should be used to report client errors.
Also, add the error to `query.context.errors` for logging and error reporting.
I also used an ExecutionError for OperationNameMissingError since I didn't want it to be treated as an internal error.  I also changed ExecutionError.to_h to omit the locations key so …
=> Avoid providing internal server error messages to clients.

lib/graphql/schema.rb, lib/graphql/schema/type_reducer.rb
Provides better error messages when you have an invalid field definition. Specifically adds context to error messages when you use an invalid type:
* As the return type for a field
* As the argument type for a field argument
* As an input type on an input object
It also tells you the class of the object that you provided as a type.
**Example Use Case**
It's probably not uncommon that a GraphQL type shares a name with an Active Record model. Sometimes, it's easy to accidentally specify the model as a field type, instead of the GraphQL type that corresponds to the model:
```ruby
CreateCommentMutation = GraphQL::Relay::Mutation.define do
name "CreateComment"
...
return_field :comment, !Comment # should be CommentType, not Comment
end
```
If you make this mistake presently, you get a fairly …
=> Contextual errors when invalid types are provided for fields

lib/graphql.rb, lib/graphql/directive.rb, lib/graphql/directive/include_directive.rb, lib/graphql/directive/skip_directive.rb, lib/graphql/introspection.rb, lib/graphql/introspection/directive_location_enum.rb, lib/graphql/introspection/directive_type.rb, lib/graphql/introspection/introspection_query.rb, lib/graphql/query/directive_chain.rb, lib/graphql/static_validation/all_rules.rb, lib/graphql/static_validation/rules/directives_are_in_valid_locations.rb, spec/graphql/directive_spec.rb, spec/graphql/introspection/directive_type_spec.rb, spec/graphql/schema/printer_spec.rb, spec/graphql/static_validation/rules/directives_are_in_valid_locations_spec.rb
A little bit ago, the Directive spec changed: https://github.com/facebook/graphql/pull/152
So, update!
=> feat(Directive) update to new spec for Directive locations

lib/graphql/language/parser.rb, lib/graphql/language/transform.rb, lib/graphql/query/serial_execution/selection_resolution.rb, lib/graphql/static_validation/rules/fragment_spreads_are_possible.rb, lib/graphql/static_validation/rules/fragment_types_exist.rb, lib/graphql/static_validation/rules/fragments_are_on_composite_types.rb, lib/graphql/static_validation/type_stack.rb, spec/graphql/directive_spec.rb, spec/graphql/language/parser_spec.rb, spec/graphql/language/transform_spec.rb
A graphql query with an inline fragment that doesn't have a type condition would be considered an invalid query.
See the [Inline Fragments section of the graphql spec](http://facebook.github.io/graphql/#sec-Inline-Fragments) which shows that the type condition is optional and includes examples of queries with inline fragments without a type condition.
There were several places where it was assumed that a fragment always had a type, so I had to update the parser, transformer, static validator and the selection resolution.  Basically if the type condition isn't specified, then we can skip the type check and continue using the parent type.
=> feature: Support inline fragments without a type condition

lib/graphql/field.rb
Sometimes it's easy to use a symbol for a field name, instead of a string. That causes problems inside of [`GraphQL::Introspection::FieldsField`](https://github.com/rmosolgo/graphql-ruby/blob/563c2fa275825d61f973690f4b51aeaaa931f8e2/lib/graphql/introspection/fields_field.rb#L11), because it attempts to sort the fields by name.
I think that having non-string field names might also break other things (ex, enforcing uniqueness), and it's probably usually a mistake.
One alternative would be to allow strings or symbols, but convert symbols to strings. But it seems like that is not as transparent to the developer.
=> Field names must be strings

lib/graphql/static_validation/rules/variable_usages_are_allowed.rb, spec/graphql/introspection/type_type_spec.rb, spec/graphql/static_validation/rules/variable_usages_are_allowed_spec.rb, spec/support/dairy_app.rb
This fixes a bug where a variable of type `[DairyAnimal!]!` was considered invalid for an argument of type `[DairAnimal!]`.
According to the [GraphQL Spec §5.7.6](https://facebook.github.io/graphql/#sec-All-Variable-Usages-are-Allowed):
> If any list level of _variableType_ is not non‐null, and the corresponding level in _argument_ is non‐null, the types are not compatible.
This seems to suggest that the types _are_ compatible if any list level of _variableType_ is non-null, and the corresponding level in _argument_ is not non-null. (You have to read that sentence twice for it to make sense :P)
So I've added a test to ensure that:
* a variable of type `[DairyAnimal!]!` is compatible with an argument of type `[DairyAnimal!]`
* a variable of type `[[DairyAnimal!]!]!` is compatible with an …
=> Fixing bug with list nullability checks

lib/graphql/query/context.rb, spec/graphql/query/context_spec.rb
Thoughts about defaulting `@values = {}` in `Query::Context`?  I ran into an issue where my query would check if `context[:some_key]` exists, but it would raise an error because `@values = nil` if no context is passed into the query.
Thanks!
=> fix(context) handle empty @values

lib/graphql/define/assign_argument.rb, spec/graphql/introspection/input_value_type_spec.rb, spec/support/dairy_app.rb
Allow Argument `description` and `default_value` to be defined in the block
=> fix(Define::AssignArgument) block definition

CHANGELOG.md, graphql.gemspec, lib/graphql/schema.rb, lib/graphql/schema/type_map.rb, lib/graphql/schema/type_reducer.rb, spec/graphql/interface_type_spec.rb, spec/graphql/introspection/type_type_spec.rb, spec/graphql/schema/type_reducer_spec.rb, spec/support/dairy_app.rb
We'll do it like graphql-js in the next version, so here's some deprecation warnings
=> feat(Schema) add deprecation warning for interface type inferrence

lib/graphql/base_type.rb, lib/graphql/interface_type.rb, lib/graphql/introspection/possible_types_field.rb, lib/graphql/object_type.rb, lib/graphql/query/context.rb, lib/graphql/query/executor.rb, lib/graphql/query/serial_execution/execution_context.rb, lib/graphql/query/serial_execution/selection_resolution.rb, lib/graphql/query/serial_execution/value_resolution.rb, lib/graphql/query/type_resolver.rb, lib/graphql/schema.rb, lib/graphql/schema/possible_types.rb, lib/graphql/schema/type_reducer.rb, lib/graphql/schema/type_validator.rb, lib/graphql/static_validation/rules/fragment_spreads_are_possible.rb, lib/graphql/union_type.rb, readme.md, spec/graphql/interface_type_spec.rb, spec/graphql/introspection/type_type_spec.rb, spec/graphql/query/context_spec.rb, spec/graphql/query/type_resolver_spec.rb, spec/graphql/schema/type_reducer_spec.rb, spec/graphql/union_type_spec.rb, spec/support/dairy_app.rb
Taking a cue from graphql/graphql-js#327
Previously, `InterfaceType#possible_types` was implemented as an array which was mutated for every object that implemented it. This caused bugs and resulted in complex gem code. 
So instead, determine possible types _within_ the schema. This will fix some nasty bugs, support Rails development better, and remove the lingering caveat when people ask "can you make multiple schemas". 
The downer is that it's a breaking change: any orphan type must be passed to `types:` (where previously it was discovered at load-time). 
Before shipping this change, I'll push a minor version with deprecation warnings.
=> refactor(InterfaceType) determine possible_types based on the schema

lib/graphql/schema/middleware_chain.rb, spec/graphql/schema/middleware_chain_spec.rb
Allows middleware to change the arguments that will be passed to the next middleware.
**Use Case**
Currently, middleware can be used if you want to stop execution and return a value early. For example, this is helpful for authorizing field access and returning an error.
However, sometimes you may simply want to _modify_ the value that is passed to the next middleware. In my case, I have a hash that tells me how fields on my GraphQL schema map to attributes on my models. Sometimes, I need to traverse across an association to produce the value.
This change allows me to load the associations in middleware, and then provide the associated model to the field's resolver, before the attribute access happens.
=> Middleware Argument Override

lib/graphql/query.rb, spec/graphql/query_spec.rb
Allow passing a `document` to the `Query`.
This can help building a server query cache to avoid parsing the strings everytime.
@rmosolgo 
cc @theorygeek
=> allow passing a pre parsed query to Query.new

lib/graphql/query.rb, lib/graphql/query/serial_execution/operation_resolution.rb, spec/graphql/introspection/schema_type_spec.rb, spec/graphql/query_spec.rb, spec/support/dairy_app.rb
There is no way to specify an object to the root query or mutation types. This is something that is supported in graphql-js with a [rootValue option](https://github.com/graphql/graphql-js/blob/v0.6.0/src/graphql.js#L32).
Having a root value can be useful since the default resolving calls methods on the object and there may be a natural root object.
Add a `root_value` optional argument when constructing the query which the operation resolution can use for the object of the root type.
=> feat(Query): Allow an object for the root type to be specified.

lib/graphql/object_type.rb, lib/graphql/query/serial_execution/value_resolution.rb, spec/graphql/query/serial_execution/value_resolution_spec.rb
Improves the error message when you have a field that returns an interface or a union, but the field's resolver returns a value that can't be resolved to one of the possible types.
Previously, it would fail with a somewhat cryptic error: 
>undefined method `kind' for nil:NilClass
I'm not sure the best way to construct a test case for this; @rmosolgo any ideas?
=> Better errors when resolve_type fails

lib/graphql/query/literal_input.rb, spec/graphql/query_spec.rb, spec/support/dairy_app.rb
The schema now validates that `default_value` values are valid (they pass
through `coerce_non_null_input`) however it wasn't actually coercing them before
passing them to resolve blocks.
For the majority of types this is not a problem (e.g. 42 is a valid int and
works just fine in the context of a resolve block). However, for enums this
required that the default value be in the set of *names* but then was passing
the name unconverted into the resolve block, where the resolve block was
expecting the equivalent *value*.
The fix is to coerce default values before use, the same way we might coerce any
other input literal.
@rmosolgo @dylanahsmith cc @lreeves
=> Automatically coerce default inputs

lib/graphql/enum_type.rb, spec/graphql/enum_type_spec.rb
It is currently required that `coerce_non_null_input` return `nil` for invalid
inputs to signal an error. `EnumType` was raising a `KeyError` instead.
@rmosolgo @dylanahsmith cc @lreeves
=> Make EnumType conform to input coercion

guides/defining_your_schema.md, guides/executing_queries.md, lib/graphql/query.rb, lib/graphql/schema.rb, lib/graphql/schema/catchall_middleware.rb, spec/graphql/schema/catchall_middleware_spec.rb
Issue some warnings before removing `debug:` in #161
=> refactor(Query) deprecate debug, provide CatchallMiddleware

lib/graphql/query.rb, lib/graphql/query/executor.rb, lib/graphql/query/serial_execution/field_resolution.rb, readme.md, spec/graphql/query/executor_spec.rb, spec/graphql/query/serial_execution/execution_context_spec.rb, spec/graphql/query/serial_execution/value_resolution_spec.rb, spec/graphql/query_spec.rb
- Improve documentation for `rescue_from` 
- Stop gobbling errors by default, remove `debug:` option
- Add `CatchallMiddleware` as a migration path 
Early on, I grabbed the gobble-all-errors behavior from graphql-js. It's really a poor fit, you know something is _off_ when you deploy with `debug: true`! 
Now, error handling is all opt-in, otherwise any error raised during execution will propagate back to the application.
=> Revamp error handling

lib/graphql/schema/validation.rb
This pull request modifies the validation rules to allow for one or more possible types inside of a union. As mentioned [here](https://goo.gl/Mr0jvQ), a previous version of the GraphQL specification asserted:
> A Union type must define two or more member types.
But has since been [changed](https://git.io/vouAt) to:
> A Union type must define one or more member types.
It appears that the tests and error messages are both already crafted in such a way to support this change. For example, previous to this pull request an error message would read:
```
Field Star.starrable is invalid: must have at least one possible type
```
When at least one possible type was specified. Similarly the validation test also has already been written in such a way to support this change:
```ruby
it "requires at …
```
=> Allows for one or more possible_types in a union

lib/graphql/base_type.rb, lib/graphql/field.rb, lib/graphql/object_type.rb, lib/graphql/union_type.rb, spec/graphql/schema/validation_spec.rb, spec/support/dairy_app.rb
It's possible for ObjectTypes and Interfaces to depend on each other, or Objects and Unions, so support the same lazy-loading options as field type when defining an object's interfaces or a union's members
=> feat(types) support circular loading for interfaces and unions

lib/graphql/enum_type.rb
We're opting to keep our descriptions out of code, in YAML files. I noticed that `description=` yields a `NoMethodError`.
This PR allows one to programmatically set a description for enum values.
=> Allow me to programatically set enum strings

lib/graphql/query/serial_execution/field_resolution.rb, lib/graphql/query/serial_execution/operation_resolution.rb, lib/graphql/query/serial_execution/selection_resolution.rb, lib/graphql/query/serial_execution/value_resolution.rb, readme.md, spec/graphql/introspection/schema_type_spec.rb, spec/graphql/non_null_type_spec.rb, spec/support/dairy_app.rb
Oops, we were previously out-of-line with the spec. 
When a non-null field resolves to `nil` (which it shouldn't, this is an error), it nullifies the _whole_ selection which it is a part of. Then, if the parent field was _also_ non-null, that field nullifies its _whole_ selection, and so on, until you get to a nullable field. 
Makes sense: you never want to give `null` to a client which is expecting non-null. So ascend the query tree to make sure that doesn't happen.
=> fix(SerialExecution) non-null errors propagate to the nearest nullable field 

lib/graphql/query/context.rb, spec/graphql/query/context_spec.rb
Thanks @gjtorikian for these commits from #153 ... sorry, I wasn't ready to admit my need for them then :P 
I want to write to context from a middleware, in a way the the individual query doesn't have to "worry" about. This runs the risk of key conflicts ... so be it!
=> Mutable context

guides/defining_your_schema.md, guides/introduction.md, lib/graphql/argument.rb, lib/graphql/base_type.rb, lib/graphql/define/instance_definable.rb, lib/graphql/directive.rb, lib/graphql/enum_type.rb, lib/graphql/field.rb, lib/graphql/input_object_type.rb, lib/graphql/interface_type.rb, lib/graphql/object_type.rb, lib/graphql/scalar_type.rb, lib/graphql/union_type.rb, readme.md, spec/graphql/define/instance_definable_spec.rb, spec/support/dairy_app.rb
Previously, self-referencing or mutually-dependent types required a proc to make references: 
```ruby 
PostType = GraphQL::ObjectType.define do 
field :similarPosts, -> { types[PostType] }
end 
```
Now, you can leave of the proc wrapper: 
```ruby 
PostType = GraphQL::ObjectType.define do 
field :similarPosts, types[PostType]
end 
```
The `.define { ... }` block won't be called until one of the defined values is accessed, so `PostType` will be available by then. `-> { }`-style type references are still supported in case you _really_ need to put off calculation until Schema build-time!
=> feat(InstanceDefinable) lazy-eval the .define block to handle circular dependencies

lib/graphql/language/generation.rb, lib/graphql/language/lexer.rb, lib/graphql/language/lexer.rl, lib/graphql/language/nodes.rb, lib/graphql/language/parser.rb, lib/graphql/language/parser.y, lib/graphql/query.rb, lib/graphql/schema/printer.rb, spec/graphql/language/generation_spec.rb, spec/graphql/language/parser_spec.rb, spec/graphql/query_spec.rb, spec/graphql/schema/printer_spec.rb
I would like to have the ability parse a schema printed using in the [GraphQL schema IDL](https://github.com/facebook/graphql/pull/90) format so that I can compare an old version of the schema (stored in git) against a new version to detect breaking schema changes.
Currently this PR updates the existing parser so that GraphQL.parse can also be used to parse a schema string.  This is the approach taken by graphql-js of having a single parser for both GraphQL queries and schemas (https://github.com/graphql/graphql-js/pull/163).  The alternative would be to have a separate parser for just the schema.
@rmosolgo If you are happy with this approach and interested in having this feature in this repo, then I'll start adding tests for this feature to this PR.
=> Allow the schema IDL to be parsed

lib/graphql/relay/base_connection.rb, lib/graphql/relay/connection_field.rb, lib/graphql/relay/connection_resolve.rb, spec/graphql/relay/connection_type_spec.rb, spec/support/star_wars_schema.rb
Kind of kicking myself for not doing this earlier. I need the `field_name` for some error message handling, so let's pass it in as a kwarg to the resolver.
=> Pass `field_name` to `connection_class` resolver

lib/graphql/relay/base_connection.rb, spec/graphql/relay/mutation_spec.rb, spec/support/star_wars_schema.rb
Oops, when I merged #206, I forgot about the use case of creating connection objects during range-add mutations (eg #213) 
In that case, I think it's safe to allow fields to be nil. Previously, I supported requiring it, so we didn't forget it in any internal code, but I think it's important support this case. 
I've also "fixed" the mutation spec to be a proper RANGE_ADD example. 
@gauravtiwari & @gjtorikian, does this look alright to you? Did I miss anything?
=> Connection#initialize(field:) is optional

lib/graphql/execution/typecast.rb, lib/graphql/query/serial_execution/selection_resolution.rb, spec/graphql/execution/typecast_spec.rb, spec/graphql/interface_type_spec.rb, spec/graphql/introspection/schema_type_spec.rb, spec/support/dairy_app.rb
- Stop checking `value` when typecasting -- only use info from types at hand 
- Reorder values passed to `compatible?`, they were passed in the wrong order :S 
- Include the tests from #209 and add some negative examples
I think issues can arise when different interfaces return different results for `resolve_type` -- but it's hard for me to figure out exactly which cases affect which things. 
Maybe it would be better to adopt a "full-Relay" strategy for the whole schema: the user defines a `resolve_type` function for the _schema_, rather than individual interfaces, that way you never get conflicting results.
=> Fix typecast api

lib/graphql/query.rb, spec/graphql/static_validation/rules/fragment_types_exist_spec.rb, spec/graphql/static_validation/rules/fragments_are_used_spec.rb
Currently, a query with no operations causes an infinite loop ( #218 ). This is because query validation is a trainwreck! What I _want_ to do is: 
- Provide enough public API on `Query` that other parts of the system don't have to worry about whether the query was previously validated or not, eg: 
- `AnalyzeQuery` can just ask for `query.internal_representation` and _get it_.
- `Executor` can just ask for `query.selected_operation` and _get it_.
- Make validation a lazy operation -- only run it if needed (is this pointless? is there a case where you make a query but don't try to execute it? The only _really_ public API for `GraphQL::Query` is via `Schema#execute`). 
- Make the steps in the process decoupled enough that they can be tested in isolation 
~~These are all 👎  in this patch:~~
- …
=> Fix empty queries

spec/graphql/static_validation/rules/fragments_are_used_spec.rb
We noticed a weird edge case where, if a query is nothing but a comment, an endless loop occurs with the fragment validator. The test I've pushed demonstrates the issue:
<details>
GraphQL::StaticValidation::FragmentsAreUsed::queries that are comments
test_0001_handles them gracefully                              ERROR (0.25s)
SystemStackError:         SystemStackError: stack level too deep
/Users/gjtorikian/Development/graphql-ruby/lib/graphql/static_validation/type_stack.rb:44:in `block in initialize'
/Users/gjtorikian/Development/graphql-ruby/lib/graphql/language/visitor.rb:73:in `call'
/Users/gjtorikian/Development/graphql-ruby/lib/graphql/language/visitor.rb:73:in `block in apply_hooks'
/Users/gjtorikian/Development/graphql-ruby/lib/graphql/language/visitor.rb:73:in `each' …
=> Query with nothing but comments causes stack overflow

lib/graphql/invalid_null_error.rb
I'm seeing some `GraphQL::InvalidNullError` exceptions bubble through to our exception tracker and without any message set it's really hard to figure out where this exception is coming from.
This pull request changes `initialize` to call super with the existing message in the `to_h` method.
=> Set exception message in InvalidNullError

lib/graphql/static_validation/rules/argument_literals_are_compatible.rb, spec/graphql/static_validation/rules/argument_literals_are_compatible_spec.rb
The inspiration behind this was the more helpful error messages that GraphiQL has.
Two questions/possible changes:
1. I could unwrap `arg_defn` but I'm on the fence as to what's more helpful.
2. I initially wanted to output `node.value` as well but it could be nested with arguments. I couldn't find an existing way to get to the underlying value so leaving it out for now.
This is still an improvement regardless.
=> Include expected type in validation error message

guides/defining_your_schema.md, guides/executing_queries.md, guides/introduction.md, guides/relay.md, guides/security.md, lib/graphql.rb, lib/graphql/query.rb, lib/graphql/schema.rb, lib/graphql/schema/printer.rb, readme.md, spec/graphql/analysis/query_complexity_spec.rb, spec/graphql/argument_spec.rb, spec/graphql/field_spec.rb, spec/graphql/query/context_spec.rb, spec/graphql/query/executor_spec.rb, spec/graphql/query/serial_execution/value_resolution_spec.rb, spec/graphql/relay/array_connection_spec.rb, spec/graphql/relay/connection_type_spec.rb, spec/graphql/relay/global_node_identification_spec.rb, spec/graphql/relay/mutation_spec.rb, spec/graphql/relay/page_info_spec.rb, spec/graphql/relay/relation_connection_spec.rb, spec/graphql/schema/printer_spec.rb, spec/graphql/schema/reduce_types_spec.rb, spec/graphql/schema/timeout_middleware_spec.rb, spec/spec_helper.rb, spec/support/dairy_app.rb, spec/support/star_wars_schema.rb
Schema initialization has slowly grown unwieldy: 
- some values are passed to `.new` (eg `query:`, `mutation:`, `max_depth:`)
- others are reassigned _after_ initialization (eg `schema.query_execution_strategy = `) 
- others are added by mutating the schema (eg `middleware << MyMiddleware.new`).
- others are defined by calling methods on the schema (eg `schema.rescue_from(err_class, &block)`)
To me, this is sloppy and confusing (and hard to maintain). This gem already includes a DSL for configuring GraphQL-related objects, so let's apply it here too. So, you can create schemas using the same `.define` API as types, fields and arguments. 
```ruby 
MySchema = GraphQL::Schema.define do 
query QueryType 
mutation MutationType 
end 
```
This also provides `Schema#metadata`, which makes schema …
=> refactor(Schema) create schemas with Schema.define

guides/defining_your_schema.md, lib/graphql/base_type.rb, lib/graphql/object_type.rb, lib/graphql/query/serial_execution/value_resolution.rb, lib/graphql/relay/global_node_identification.rb, lib/graphql/schema.rb, spec/graphql/interface_type_spec.rb, spec/graphql/query/serial_execution/value_resolution_spec.rb, spec/graphql/relay/global_node_identification_spec.rb, spec/graphql/schema_spec.rb, spec/graphql/union_type_spec.rb, spec/support/dairy_app.rb, spec/support/star_wars_schema.rb
(This depends on #208)
The previous design of interface & union resolution could lead to undefined behavior when `.resolve_type` functions returned different results for the same object. This is especially possible in Relay, where `Node` uses the `type_from_object` function, but each _other_ interface uses its own `resolve_type` (which defaults to `HasPossibleTypes::DEFAULT_RESOLVE_TYPE`)
Is there a use case for treating the same object as two different object types? I can't think of one, and indeed, it's completely disallowed by Relay, which is GraphQL's largest use case. 
So, I think we should adopt Relay's "once and for all" object-to-type function as a member of `GraphQL::Schema`. Then, all type resolution can be passed to that function. It removes the possibility that functions would …
=> Unify type resolution

lib/graphql/argument.rb, lib/graphql/enum_type.rb, lib/graphql/field.rb, lib/graphql/input_object_type.rb, lib/graphql/object_type.rb, spec/graphql/argument_spec.rb, spec/graphql/enum_type_spec.rb, spec/graphql/field_spec.rb, spec/graphql/object_type_spec.rb
(Extraction from #207)
Suggestion from https://github.com/rmosolgo/graphql-ruby/pull/207#issuecomment-240608269.
Adds some additional parameters to `Type.define` to allow types to be constructed without a lazy `define do` block.
-
To: @rmosolgo
=> Add additional Type.define convenience arguments

lib/graphql.rb, lib/graphql/interface_type.rb, lib/graphql/schema/loader.rb, spec/graphql/schema/loader_spec.rb
This library currently defines the introspection query (`GraphQL::Introspection::INTROSPECTION_QUERY`) for dumping a schema, but no mechanize for loading it back in elsewhere.
This initial PR is mostly a spike/PoC. Theres still alot of cases to implement, but I wanted to maintainer feedback first before putting more work into it.
``` ruby
json = JSON.load("swapi-schema.json")
schema = GraphQL::Schema::Loader.load(json)
schema.execute(...) 
query = GraphQL::Query.new(schema, "query { ... }")
validator.validate(query)
```
-
To: @rmosolgo 
CC: @kdaigle @charliesome
=> Implement loading schema from JSON introspection query dump

lib/graphql/language/generation.rb, spec/graphql/language/generation_spec.rb
This has been bugging me 😁 
Just `...friendFields` is more conventional than `... friendFields`.
=> Remove extra space between ...FooFragment

lib/graphql/schema/loader.rb, spec/graphql/schema/loader_spec.rb
1. Fix "Schema.new is deprecated, use Schema.define instead" deprecation warning.
2. Fix loading `ObjectType`'s interfaces
3. Fix loading other root types: mutation and subscriptions
I discovered the interface bug after switching from `Schema.new` to `Schema.define`. As `Schema.define` discovers all types from the roots, I noticed that the interface in the test file was no longer being discovered. So this case already has test coverage.
=> A few Schema loader bug fixes

lib/graphql/introspection/type_by_name_field.rb, spec/graphql/introspection/type_type_spec.rb
The `__type` introspection field in the GraphQL spec is
```
__type(name: String!) : __Type
```
but graphql-ruby made it a non-null type, which gets a runtime error when the type isn't found.
Make the result type nullable and return null if the type doesn't exist
=> Resolve __type to null for type that doesn't exist

lib/graphql/language/nodes.rb, spec/graphql/language/equality_spec.rb, spec/graphql/language/nodes_spec.rb
In Ruby, `Object#equal?` is true reference equality while `Object#eql?` exists for *value* equality.
This implements a deep value equality check for any `AbstractNode`. This allows you to compare the results from `GraphQL.parse` to see if they produce an identical AST.
`Object#eql?` is also used for `Set#include?` checks, so this allows for:
``` ruby
validated_documents = Set.new
doc = GraphQL.parse(str)
if !validated_documents.include?(doc)
validate_document!(doc)
validated_documents << doc
end
```
=> Implement Node value equality

lib/graphql/define/assign_connection.rb
Derp, this was definitely from a faulty refactor, let me try to find that commit. Fixes #234 
Amazingly, it still worked because `ConnectionField` _modifies_ the incoming field instead of creating a new one. I guess if it had made a new field, we would have noticed this right away though, since tests would have broken.
cc @gjtorikian
=> fix(connection) use the field name, not the module name

lib/graphql.rb
Hey,
I created a simple file like:
```ruby
require 'faraday'
introspection_query = GraphQL::Introspection::INTROSPECTION_QUERY.gsub("\n", "")
response = Faraday.post(ENV['GRAPHQL_URL'], "{\"query\": \"#{introspection_query}\"}")
File.write('graph/schema.json', response.body)
```
And when I try to run it:
```
> GRAPHQL_URL="http://127.0.0.1:5000/graphql" ruby lib/dump_schema.rb
```
I raises an error:
```
graphql-0.18.7/lib/graphql/schema/type_map.rb:10:in `<class:TypeMap>': 
uninitialized constant GraphQL::Schema::TypeMap::Forwardable (NameError)
```
In my opinion, `graphql` should require `Forwardable` explicitly as it's a part of Ruby `stdlib` (not `core`).
=> Require forwardable explicitly

lib/graphql/boolean_type.rb
Constants defined in blocks are hoisted into the parent module scope. In this `GraphQL::BOOLEAN_TYPE` case, the global `Object` scope.
``` ruby
GraphQL::BOOLEAN_TYPE.name
::ALLOWED_INPUTS #=> [true, false]
```
In this case I simply replaced the constant with an equality test. Its probably faster in some micro benchmark since it doesn't need to go through `Array#include?` first.
=> Fix leaked global constant

lib/graphql/static_validation/rules/fields_are_defined_on_type.rb, spec/graphql/static_validation/rules/fields_are_defined_on_type_spec.rb
Unless I'm missing some edge case, doesn't it make more sense to report the line/column of the invalid field than the parent object?
``` graphql
query {          # 1
viewer {       # 2
id           # 3          
missingField # 4
}              # 5
}                # 6
```
I'd expect `"Field 'missingField' doesn't exist on type 'User'"` on line `4` rather than line `2`.
=> Validation: Report field doesn't exist error on field, not parent

lib/graphql/language.rb, lib/graphql/language/definition_slice.rb, lib/graphql/language/nodes.rb, spec/graphql/language/definition_slice_spec.rb
Follow up discussion from #236.
``` ruby
document = GraphQL.parse <<-'GRAPHQL' 
query FooQuery { ...FooFragment }
query BarQuery { ...BarFragment }
query BazQuery { ...BarFragment }
mutation FooMutation { ... }
fragment FooFragment on Foo { ... }
fragment BarFragment on Bar { ... }
GRAPHQL
sliced_document = document.slice_definition("FooQuery")
sliced_document == <<-'GRAPHQL'
query FooQuery { ...FooFragment }
fragment FooFragment on Foo { ... }
GRAPHQL
```
I think the name "slice" is okay, but I don't love it. Trying to brainstorm some other terminology for this algorithm.
=> Definition slicing

lib/graphql/query/arguments.rb, lib/graphql/query/literal_input.rb, spec/graphql/query/arguments_spec.rb
Only put keys in the `Arguments` instance if the key was present in the query in some way. And use `#key?` to show whether it was present or missing.
=> feat(Arguments#key?) show when arguments were missing from the query

lib/graphql/internal_representation/rewrite.rb, lib/graphql/static_validation/all_rules.rb, lib/graphql/static_validation/rules/mutation_root_exists.rb, lib/graphql/static_validation/rules/subscription_root_exists.rb, spec/graphql/static_validation/rules/mutation_root_exists_spec.rb, spec/graphql/static_validation/rules/subscription_root_exists_spec.rb
If a mutation is attempted on a schema that does not have a mutation root a `NoMethodError: undefined method unwrap for nil:NilClass` will occur originating from [lib/graphql/static_validation/type_stack.rb:108](https://github.com/rmosolgo/graphql-ruby/blob/dccbe895ca0cd194a0a8971850a7e13d37c37138/lib/graphql/static_validation/type_stack.rb#L108):
I noticed `graphql-js` handles this case by [returning a GraphQL error](https://github.com/graphql/graphql-js/blob/988508c9ee8e64e549b1028ffebdbbf4d22b4047/src/execution/execute.js#L268-L275).
@rmosolgo is a `StaticValidation` rule the right place for this?
=> Gracefully handle mutations when there is no mutation root

lib/graphql/static_validation/rules/fragments_are_finite.rb, spec/graphql/static_validation/rules/fragments_are_finite_spec.rb, spec/graphql/static_validation/validator_spec.rb
Oops, the previous implementation of validating infinite loops only checked the _first level_ of fragment definitions! Now, it checks deeply.
Closes #257
=> fix(FragmentsAreFinite) find fragment spreads below the first level of a fragment definition

lib/graphql/static_validation/rules/fields_will_merge.rb, spec/graphql/static_validation/rules/fields_will_merge_spec.rb
⚠️  blocked on #256 ⚠️ 
This PR skips "fields will merge" validation for @skip and @include directives, since they can be safely merged with behavior defined in the GraphQL spec.
```graphql
query {
hello,
...F0
}
fragment F0 on RootQueryType {
hello @include(if: true)
}
```
The issue is where directives cannot merge cleanly unless their semantics are known. However, in the case of `@skip` and `@include` in particular, their [semantics are specified](https://github.com/facebook/graphql/blob/master/spec/Section%203%20--%20Type%20System.md#include), so they should not generate these validation errors.
I wrote specs for this behavior, included in this PR. To validate this behavior, I also implemented these same specs in javascript against Facebook's graphqljs. These other tests can be found …
=> Update `fields_will_merge` validation to ignore directives

lib/graphql/static_validation/message.rb, spec/graphql/static_validation/rules/argument_literals_are_compatible_spec.rb, spec/graphql/static_validation/rules/arguments_are_defined_spec.rb, spec/graphql/static_validation/rules/directives_are_defined_spec.rb, spec/graphql/static_validation/rules/directives_are_in_valid_locations_spec.rb, spec/graphql/static_validation/rules/fields_are_defined_on_type_spec.rb, spec/graphql/static_validation/rules/fields_have_appropriate_selections_spec.rb, spec/graphql/static_validation/rules/fragment_spreads_are_possible_spec.rb, spec/graphql/static_validation/rules/fragment_types_exist_spec.rb, spec/graphql/static_validation/rules/fragments_are_finite_spec.rb, spec/graphql/static_validation/rules/fragments_are_named_spec.rb, spec/graphql/static_validation/rules/fragments_are_on_composite_types_spec.rb, spec/graphql/static_validation/rules/fragments_are_used_spec.rb, spec/graphql/static_validation/rules/mutation_root_exists_spec.rb, spec/graphql/static_validation/rules/required_arguments_are_present_spec.rb, spec/graphql/static_validation/rules/subscription_root_exists_spec.rb, spec/graphql/static_validation/rules/variable_default_values_are_correctly_typed_spec.rb, spec/graphql/static_validation/rules/variable_usages_are_allowed_spec.rb, spec/graphql/static_validation/rules/variables_are_input_types_spec.rb, spec/graphql/static_validation/rules/variables_are_used_and_defined_spec.rb, spec/graphql/static_validation/validator_spec.rb
Conflicts with graphql-js **execution only** error JSON-path which uses the same key name.
https://github.com/graphql/graphql-js/blob/89f3f1a319bb913616f2910e8a806170155ffaf0/src/error/GraphQLError.js#L42-L48
Some other naming ideas:
* `queryPath`
* `documentPath`
* `validationPath`
Personally, this error path isn't that useful to me. `locations` tells me what I need to resolve the query AST node in the query text for reporting. But I don't see the harm in keeping it.
-
To: @rmosolgo
=> Rename validation error `path` key

lib/graphql/analysis/query_complexity.rb, lib/graphql/analysis/query_depth.rb, lib/graphql/directive.rb, lib/graphql/directive/include_directive.rb, lib/graphql/directive/skip_directive.rb, lib/graphql/execution/directive_checks.rb, lib/graphql/internal_representation/node.rb, lib/graphql/internal_representation/rewrite.rb, lib/graphql/query/serial_execution/selection_resolution.rb, spec/graphql/directive_spec.rb
This PR corrects some of the behavior around @skip and @include directives.
- fixes `@skip` and `@include` execution in graphql-ruby to be in line with spec and graphql-js behavior
```graphql
query getCheese ($include: Boolean!, $skip: Boolean!) {
cheese(id: 1) {
flavor @include(if: false) @skip(if: true),
withVariables: flavor @include(if: $include) @skip(if: $skip)
}
}
```
with variables
```
skip: true,
include: false
```
The expected result is that `flavor` would not be included in the result document, but it is. The spec updates in this PR include other cases.
We encountered this error in production with queries that were being generated with Relay (0.9.2) for queries where the same field in some cases had `@include` directives on one fragment but not on another.
The GraphQL spec …
=> Update @skip and @include processing with specs

lib/graphql/object_type.rb
Note, I believe that the guide was misleading for the object_type.  Using the argument `arguments` (plural) seems to have thrown an exception.  I see that in other examples, it is `argument`, so I believe that this may have been an error.
=> Fix: remove pluralization of argument in docs for object_type

lib/graphql/internal_representation/node.rb, spec/graphql/execution_error_spec.rb, spec/graphql/query/executor_spec.rb, spec/graphql/schema/catchall_middleware_spec.rb
Was correct for anonymous query definitions, but I forgot to test what would happen if a query name was set. It incorrectly gets prepended to the `"path"` array.
-
To: @rmosolgo
=> Remove definition name from error `path`

lib/graphql/static_validation/rules/fields_will_merge.rb, lib/graphql/static_validation/rules/fragment_spreads_are_possible.rb, spec/graphql/static_validation/rules/argument_literals_are_compatible_spec.rb, spec/graphql/static_validation/rules/arguments_are_defined_spec.rb, spec/graphql/static_validation/rules/directives_are_defined_spec.rb, spec/graphql/static_validation/rules/directives_are_in_valid_locations_spec.rb, spec/graphql/static_validation/rules/fields_are_defined_on_type_spec.rb, spec/graphql/static_validation/rules/fields_have_appropriate_selections_spec.rb, spec/graphql/static_validation/rules/fields_will_merge_spec.rb, spec/graphql/static_validation/rules/fragment_spreads_are_possible_spec.rb, spec/graphql/static_validation/rules/fragment_types_exist_spec.rb, spec/graphql/static_validation/rules/fragments_are_finite_spec.rb, spec/graphql/static_validation/rules/fragments_are_named_spec.rb, spec/graphql/static_validation/rules/fragments_are_on_composite_types_spec.rb, spec/graphql/static_validation/rules/fragments_are_used_spec.rb, spec/graphql/static_validation/rules/mutation_root_exists_spec.rb, spec/graphql/static_validation/rules/required_arguments_are_present_spec.rb, spec/graphql/static_validation/rules/subscription_root_exists_spec.rb, spec/graphql/static_validation/rules/variable_default_values_are_correctly_typed_spec.rb, spec/graphql/static_validation/rules/variable_usages_are_allowed_spec.rb, spec/graphql/static_validation/rules/variables_are_input_types_spec.rb, spec/graphql/static_validation/rules/variables_are_used_and_defined_spec.rb, spec/support/static_validation_helpers.rb
This is a refactor of the "test harness" for query validation in preparation for #268 . 
Although the current code is not so good, it does have quite a lot of test coverage. I'd like to keep that coverage during the "switch", so that: 
- I can avoid any regressions 
- Any specific changes in behavior will be evident from a diff (ie, changes to the test code) 
In order to accomplish that, I: 
- DRYed up the `query_string -> errors` pipeline so that all validation tests pass through the same code. (This way, to migrate, I just have to update `StaticValidationHelpers` to point at the new implementation) 
- Changed the validation tests to pass through _all_ rules, not just the one named by the spec file. The previous testing arrangement made for easy testing, but it led to bugs: it was …
=> refactor(specs) test all validators through the whole set

lib/graphql/directive.rb, lib/graphql/directive/deprecated_directive.rb, lib/graphql/directive/include_directive.rb, lib/graphql/directive/skip_directive.rb, lib/graphql/introspection/arguments_field.rb, lib/graphql/introspection/directive_location_enum.rb, lib/graphql/introspection/directive_type.rb, lib/graphql/introspection/enum_value_type.rb, lib/graphql/introspection/enum_values_field.rb, lib/graphql/introspection/field_type.rb, lib/graphql/introspection/fields_field.rb, lib/graphql/introspection/input_fields_field.rb, lib/graphql/introspection/input_value_type.rb, lib/graphql/introspection/interfaces_field.rb, lib/graphql/introspection/of_type_field.rb, lib/graphql/introspection/possible_types_field.rb, lib/graphql/introspection/schema_type.rb, lib/graphql/introspection/type_kind_enum.rb, lib/graphql/introspection/type_type.rb, lib/graphql/type_kinds.rb, spec/graphql/introspection/directive_type_spec.rb, spec/graphql/schema/printer_spec.rb
While working [on adding descriptions to the schema dumper](https://github.com/graphql/graphql-js/pull/464), I noticed our introspection schema descriptions don't match graphql-js'.
This means we need to maintain [our own copy of the introspection schema](https://github.com/rmosolgo/graphql-ruby/blob/9c6ebbda48b59c0a23467ab9dd45179654279282/spec/graphql/schema/printer_spec.rb#L71).
This PR brings us back to parity with graphql-js by [using their introspection schema](https://github.com/graphql/graphql-js/blob/a725499b155285c2e33647a93393c82689b20b0f/src/utilities/__tests__/schemaPrinter-test.js#L600-L797) in our tests.
As graphql-js evolves this means we'll be able to easily copy over their introspection schema to ensure the gem remains compliant.
👀 @rmosolgo
=> Parity with graphql-js' introspection schema

guides/defining_your_schema.md, guides/relay.md
A simple fix but helpful when you're getting started.
=> Remove errant commas and equals in documentation.

lib/graphql/base_type.rb, lib/graphql/interface_type.rb, lib/graphql/query/serial_execution/value_resolution.rb, lib/graphql/union_type.rb, spec/support/dairy_app.rb
Interface-level `resolve_type` was previously deprecated in favor of `Schema#resolve_type`. Now it's time to remove it.
=> refactor(Interface) remove type-level resolve_type hook

lib/graphql.rb, lib/graphql/define/instance_definable.rb, lib/graphql/object_type.rb, lib/graphql/query/serial_execution/value_resolution.rb, lib/graphql/relay/node.rb, lib/graphql/schema.rb, lib/graphql/schema/loader.rb, lib/graphql/schema/validation.rb, lib/graphql/unresolved_type_error.rb, spec/graphql/analysis/query_complexity_spec.rb, spec/graphql/define/instance_definable_spec.rb, spec/graphql/field_spec.rb, spec/graphql/query/context_spec.rb, spec/graphql/query/executor_spec.rb, spec/graphql/query/serial_execution/value_resolution_spec.rb, spec/graphql/schema/loader_spec.rb, spec/graphql/schema/printer_spec.rb, spec/graphql/schema_spec.rb, spec/graphql/static_validation/rules/mutation_root_exists_spec.rb, spec/graphql/static_validation/rules/subscription_root_exists_spec.rb
Previously, schema validation was deferred until the first call to `Schema#types`. This call constructed the `TypeMap` and validated each entry. This means you might start up your app and get an error backtrace that points to validation, which is annoying. 
Also, it might have been the culprit in some thread-safety bugs. If you start accepting requests on different threads, one thread might start building the schema's type map, then the other thread might see that the type map was already there, and try to use it, but it's not complete, so :boom: .
Now, run validations as part of `Schema.define`. This will find errors earlier and reduce the likelihood of thread-unsafety with the `TypeMap`.
=> Eager load schema

lib/graphql/query/serial_execution/value_resolution.rb, spec/graphql/query/serial_execution/value_resolution_spec.rb
Raise when Schema resolves an object to a Type, but that Type does not implement the interface. ( Is not part of possilbe_types)
Example in tests :)
@rmosolgo
=> Raise when resolved_type not part of possible types

lib/graphql/invalid_null_error.rb, lib/graphql/query/serial_execution/value_resolution.rb, spec/graphql/non_null_type_spec.rb, spec/graphql/query/executor_spec.rb
When investigating an invalid null error, the first thing I end up having to do is find the type for the field, which can take a big more work when we have the error occurs on a generic field name.  E.g. multiple object types may have a field named `:name` or `:id`.  Having the type name in the error message would allow us to avoid that extra work to debug an error.
=> Add parent type name to the InvalidNullError message

lib/graphql/query/serial_execution/field_resolution.rb, spec/graphql/execution_error_spec.rb, spec/support/dairy_app.rb
For single values, resolvers can return a `GraphQL::ExecutionError` instance. It'd be great if lists offered a single ability to fail partially. Its a bit of an implementation edge case since individual list values don't have their own `resolve` function.
For GitHub's GraphQL API, I'd like our root `nodes(ids: [ID!]!): [Node]!` batch lookup to fail partially if a given ID fails to resolve. The returned collection itself is non-nullable, but the list values are nullable `Node`s.
``` graphql
type Query {
node(id: ID!): Node
nodes(ids: [ID!]!): [Node]!
}
```
=> Support partial ExecutionError in lists

lib/graphql/query/serial_execution/field_resolution.rb
For https://github.com/Shopify/graphql-batch/issues/18
The execution strategy in the graphql-batch gem overrides FieldResolution#get_finished_value because the resolution hasn't been completed, so it chains the promise to passes the resolved result using `super` rather than the promise object.
However, https://github.com/rmosolgo/graphql-ruby/pull/174 added error handling into FieldResolution#result, which only receives a promise from get_finished_value, so the rescue effectively gets skipped when using graphql-batch.
This pull request moves the rescue into FieldResolution#get_finished_value to avoid the need to have to duplicate the invalid null rescue in the graphql-batch execution strategy.
=> Move invalid null rescue for graphql-batch execution strategy.

lib/graphql/schema/printer.rb, spec/graphql/schema/printer_spec.rb
cc @xuorig & @cjoudrey 
When trying to upgrade to the newest release of this gem we noticed that our schema dump changed for enum values.  This can be seen with this PR's test changes for this regression without the changes to the code under test:
```
GraphQL::Schema::Printer::.print_schema
test_0001_returns the schema as a string for the defined types  FAIL (0.01s)
Minitest::Assertion:         --- expected
+++ actual
@@ -26,7 +26,7 @@
}
type Query {
-  post(id: ID!, varied: Varied = {id: \"123\", int: 234, float: 2.3, enum: FOO, sub: [{string: \"str\"}]}): Post
+  post(id: ID!, varied: Varied = {id: \"123\", int: 234, float: 2.3, enum: foo, sub: [{string: \"str\"}]}): Post
}
input Sub {
@@ -38,6 +38,6 @@
int: Int
float: Float
bool: Boolean
-  enum: Choice = FOO
+  enum: Choice = foo
sub: …
```
=> Fix bug in schema printer for enum values with custom ruby value.

lib/graphql/relay/connection_type.rb, lib/graphql/relay/edge_type.rb, lib/graphql/relay/node.rb, lib/graphql/relay/page_info.rb
We recently noticed that [some default relay objects were missing descriptions](https://developer.github.com/early-access/graphql/interface/node/). This super minor PR pulls in descriptions for edges, nodes, cursors, etc. to match what can be found the reference implemtation for relay over in [graphql/graphql-relay-js](https://github.com/graphql/graphql-relay-js).
This is of course, just default documentation mirroring graphql-relay-js and descriptions can be overridden at will.
=> [minor] Adding missing descriptions to default relay objects

guides/relay.md, lib/graphql/relay/mutation.rb, spec/graphql/relay/mutation_spec.rb
Previously, we would only dynamically generate a type based on the `return_fields`, but we can do this too 
```ruby 
Mutation.define do 
name "CreatePost"
return_type PostType 
resolve -> (obj, input, ctx) { Post.create!(input) } 
end 
```
You have to handle `clientMutationId` on the `return_type` yourself, though
=> feat(Mutation) accept a user-defined return_type

lib/graphql/introspection/introspection_query.rb, spec/graphql/introspection/introspection_query_spec.rb
There are some schemas that require deeply nested types, such as a 3-dimensional array of non-null Ints (`[[[Int!]!]!]!`) that the current introspection query does not handle. Instead of 3, change the `ofType` query to go 7 deep.
It looks like graphql-js added support for this https://github.com/graphql/graphql-js/pull/364. As the introspection query in the gem is from that repo, I think it's safe to pull this is an as well.
Is there a better spot for this test?
=> Support 7 level introspection query instead of 3

lib/graphql/input_object_type.rb, lib/graphql/query/arguments.rb, lib/graphql/query/literal_input.rb, spec/graphql/query/arguments_spec.rb
Some people have a "JSON Scalar" that parses a string into a Ruby hash. Previously, we were wrapping that in a `Query::Arguments` instead of passing the plain hash to the resolve function. Now, we don't wrap it in `Arguments` unless it's an input object!
=> Argument type fix

lib/graphql/relay/base_connection.rb
Looking at the API docs and seeing http://www.rubydoc.info/github/rmosolgo/graphql-ruby/GraphQL/Relay/BaseConnection#order-instance_method confused me for a good 15 minutes, so I dug through history and found https://github.com/rmosolgo/graphql-relay-ruby/pull/33.
It doesn't seem like this was cleaned up 100% and artifacts are still showing in the docs, so I'm hoping this is the right PR here. Let me know if it needs any changes, or if I have the wrong understanding. Thanks!
=> Cleanup order in base connection

spec/support/dairy_data.rb, spec/support/star_wars_data.rb
Std-lib doc shows the needed `require` statement, not sure why the builds pass without it:
http://ruby-doc.org/stdlib/libdoc/ostruct/rdoc/OpenStruct.html
It was failing during the Ruby 1.9.3 experiments.
Extracted from #306.
=> Add missing requires for OpenStruct objects

spec/graphql/relay/mutation_spec.rb, spec/support/star_wars_data.rb
This is also how doc (http://ruby-doc.org/stdlib-2.1.0/libdoc/ostruct/rdoc/OpenStruct.html) uses getters in most example.
This will make maintaining the Ruby 1.9.3 branch easier. Any strong opinion on this?
Extracted from #306.
=> Use dot-notation for OpenStructs as [] is not available in Ruby 1.9.3

guides/introduction.md
Prior to this change, guides on the website were redirecting to the Rubydoc pages.
This also brings the advantage of not leaving the HTTPS world.
Of course, note that with this change, the links in the Rubydoc pages now redirect to the website...
I'll let you decide if this is an issue to you or not. Maybe you're perfectly aware and fine with that, I don't have an opinion, just giving you the option 😅.
=> Fix links to other guides in website

guides/testing.md
There should be double curly braces, like in the docs:
http://www.rubydoc.info/github/rmosolgo/graphql-ruby/file/guides/testing.md
=> Fixed typo in testing guide

lib/graphql/enum_type.rb, lib/graphql/introspection/input_value_type.rb, lib/graphql/scalar_type.rb
From https://github.com/rmosolgo/graphql-ruby/pull/306#issuecomment-254020617:
> One more thing, I'd like to get the `JSON`-related changes in `master`. Recently, someone else reported a bug for that, where another JSON implementation was 💥-ing.
Exported from #306. This was failing on Ruby 1.9.3 as well.
=> Use JSON's generate+quirks_mode to allow dumping scalar values

lib/graphql/language/generation.rb, lib/graphql/language/parser.rb, lib/graphql/language/parser.y, lib/graphql/language/parser_tests.rb
While working on an utility method to convert an `AST` to `Schema` (like [graphql-js' `buildASTSchema.js`](https://github.com/graphql/graphql-js/blob/345400987c67bc67f57d1d07f637bc9acbfd1016/src/utilities/buildASTSchema.js)), I noticed two spots where we parse referenced types as a string instead of a `TypeName` node:
1. We parse an object type definition's interfaces as strings. In graphql-js [they are parsed as a `NAMED_TYPE` node](https://github.com/graphql/graphql-js/blob/345400987c67bc67f57d1d07f637bc9acbfd1016/src/language/parser.js#L816-L825).
2. We parse union members as strings. In graphql-js [they are parsed as a `NAMED_TYPE` node](https://github.com/graphql/graphql-js/blob/345400987c67bc67f57d1d07f637bc9acbfd1016/src/language/parser.js#L929-L935).
On the surface this might not …
=> Parse implemented interfaces and union members as TypeName instead of String

lib/graphql/language/generation.rb, lib/graphql/schema/printer.rb, spec/graphql/language/generation_spec.rb, spec/graphql/schema/printer_spec.rb
As per graphql/graphql-js#470, schema definition should be omitted from IDL when root types match convention names: `Query`, `Mutation`, `Subscription`.
The diff might be easier to look at with `&w=1` in query params as I indented a big chunk in `generation_spec.rb`.
=> Omit schema definition from IDL when type names match convention

.rubocop.yml, Rakefile, graphql.gemspec, lib/graphql/schema/timeout_middleware.rb, lib/graphql/static_validation/rules/fields_will_merge.rb, spec/graphql/introspection/introspection_query_spec.rb
We currently have `.rubocop.yml` but it is not enforced by CI. This means we will end up having code violations in `master` unless every person thinks about running `rubocop` locally, which isn't realistic.
This PR will make CI fail when Rubocop finds bad code.
I also made a few adjustments to our `.robucop.yml` file. We can discuss each change in the diff.
I also ran `rubocop` and corrected offenses in the codebase.
:eyes: @rmosolgo @astorije
=> Add Rubocop to CI

lib/graphql/query/arguments.rb, spec/graphql/query/arguments_spec.rb
Fixes #325 
Introduce `ArgumentValue` as the backing object for `Query::Arguments`
=> feat(Query::Arguments) preserve underlying definitions with argument values

lib/graphql/schema/printer.rb, spec/graphql/schema/printer_spec.rb
There was a small indentation bug in `Schema::Printer` when printing arguments that have comments.
Here's an example that displays the bug:
**Currently**
```graphql
type Query {
post(
id: ID!
varied: Varied = {id: \"123\", int: 234, float: 2.3, enum: FOO, sub: [{string: \"str\"}]}
): Post
}
```
**With this PR**
```graphql
type Query {
post(
id: ID!
varied: Varied = {id: \"123\", int: 234, float: 2.3, enum: FOO, sub: [{string: \"str\"}]}
): Post
}
```
=> Fix indentation when printing args that have comments

guides/relay/mutations.md
Two arg signatures are deprecated; this little bit in the docs just was missed in all the updates lately, looks like.
=> Update mutation resolve() signature

lib/graphql/query.rb, lib/graphql/query/serial_execution/value_resolution.rb, lib/graphql/query/variables.rb, lib/graphql/static_validation/validator.rb, spec/graphql/static_validation/validator_spec.rb, spec/spec_helper.rb, spec/support/static_validation_helpers.rb
- Remove `validate: false` option (it hasn't worked since introducing `InternalRepresentation` since the rewrite follows along with validation, so obviously nobody is `validate: false`-ing 😬 )
- Some parts of query initialization used to raise errors (which were rescued by Query). Now those errors are caught earlier on. 
- Validation & analysis errors used to be exposed from `Query` as hashes, now they're exposed as Error objects (which respond to `#to_h`)
=> Query cleanup

lib/graphql/define/assign_enum_value.rb, lib/graphql/enum_type.rb, lib/graphql/schema/loader.rb
Support `.define` with enum values (cherry-picked from #300)
=> Enum value refactor

lib/graphql/relay/base_connection.rb, spec/graphql/relay/base_connection_spec.rb
This PR updates the way GraphQL::Relay::BaseConnection.connection_for_nodes resolves Connection class implementations from collection types.
The current algorithm is depth-first, so custom Nodes collection classes which inherit from Array will resolve to ArrayConnection even if there is a more specific subclass of BaseConnection registered.
With this PR, it changes to breadth-first to search all registered CONNECTION_IMPLEMENTATIONS for ancestors of the nodes class, starting with the most specific.
=> Resolve connection class by most specific class type

lib/graphql/execution/directive_checks.rb
The last usage I could find of `skip?` was in 3b773899a4855194c595892a34a6abfe6c3d81c3. Now only the `include?` directive check is being used to determine if a field/spread node  should be skipped or included (see [rewriter.rb](https://github.com/rmosolgo/graphql-ruby/blob/2e59be6482ce94a6124ce27766ad4a7910e6c589/lib/graphql/internal_representation/rewrite.rb)).
=> Removes unused `skip?` method

lib/graphql/list_type.rb, lib/graphql/non_null_type.rb, spec/graphql/introspection/directive_type_spec.rb, spec/graphql/introspection/input_value_type_spec.rb, spec/graphql/introspection/type_type_spec.rb, spec/graphql/static_validation/type_stack_spec.rb
Fixes #352.
This modifies both `ListType#name` and `NonNullType#name` to return `nil`, so that introspection responses correctly return `null` names for these types as per the GraphQL spec. This is a breaking change, both because it modifies the introspection responses, and because downstream code may be relying on the `name` method on types always returning a string.
=> nameless LIST and NON_NULL

lib/graphql/define/instance_definable.rb, spec/graphql/define/instance_definable_spec.rb
Now you can shallow-copy schema members with `.redefine`
=> feat(Define) support shallow redefinition with #redefine

lib/graphql/schema/validation.rb, spec/graphql/introspection/input_value_type_spec.rb, spec/graphql/schema/validation_spec.rb, spec/support/dairy_app.rb
While working on schema comparisons I realized we currently allow non-nullable types to have default values.
According to [`graphql-js`](https://github.com/graphql/graphql-js/blob/89f3f1a319bb913616f2910e8a806170155ffaf0/src/validation/rules/DefaultValuesOfCorrectType.js#L19) this is not valid.
This PR adds the same validation to `graphql-ruby`.
I'm not sure if this will change in the future due to facebook/graphql#83 but in the meantime it's probably best that we have this.
:eyes: @rmosolgo /cc @theorygeek
=> Non-nullable arguments cannot have default values

lib/graphql/query/context.rb, lib/graphql/query/serial_execution/field_resolution.rb, lib/graphql/query/serial_execution/operation_resolution.rb, lib/graphql/query/serial_execution/selection_resolution.rb, lib/graphql/query/serial_execution/value_resolution.rb
Some of these objects don't need to be objects at all, but being a pure function will do. I didn't touch `FieldResolution` because I think graphql-batch depends on it!
You can see a bit less `Class#new` in the profile 
- Before: 
```
Thread ID: 70200716433880
Fiber ID: 70200724772180
Total: 0.166652
%self      total      self      wait     child     calls  name
7.83      0.013     0.013     0.000     0.000    11461  *GraphQL::Define::InstanceDefinable#ensure_defined
6.97      0.037     0.012     0.000     0.026     7067  *Class#new
6.32      0.011     0.011     0.000     0.000     8520   Kernel#instance_variable_get
4.37      0.007     0.007     0.000     0.000     8721   Kernel#hash
3.93      0.052     0.007     0.000     0.045     1700 …
```
=> refactor(SerialExecution) make fewer objects

guides/schema/instrumentation.md, lib/graphql/query.rb, lib/graphql/query/variables.rb, lib/graphql/schema.rb, lib/graphql/schema/instrumented_field_map.rb, spec/graphql/schema_spec.rb
A hot take on #186 
- Apply field instrumentation at build time 
- Apply query instrumentation at runtime 
- _Very_ specific implementation of instrumentation hooks 
Buyer beware: if you _modify_ the passed-in type or field, it will be changed _everywhere_ it's used (since it's the same object). I want to provide a shallow-copy API for these objects so that wrapping them is easier. 
If there just _happened_ to be any [widely used extensions](https://github.com/Shopify/graphql-batch) to this gem, they could accept instrumentation of their own: 
``` ruby
MySchema = GraphQL::Schema.define do 
instrument(:batch, MyBatchInstrumentation) 
end 
```
And fetch it out & apply it as they see fit: 
``` ruby
MySchema.instrumenters[:batch] # => array of instrumenters (empty if `instrument` was not …
```
=> Instrumentation

lib/graphql/compatibility/query_parser_specification.rb, lib/graphql/language/lexer.rl
Oops, I just removed this in #366, But I think I shouldn't have. Here are some specs for this behavior in other parsers: 
https://github.com/graphql/graphql-js/blob/master/src/language/__tests__/lexer-test.js#L166-L173
https://github.com/graphql/libgraphqlparser/blob/master/test/ParserTests.cpp#L134-L137
So I think the old way was right. But `graphql-libgraphqlparser` doesn't pass this test, and that's what made me second-guess it in the first place. So I'll look into that.
=> fix(Lexer) replace backslash-u-escaped unicode

lib/graphql/query/context.rb, lib/graphql/query/serial_execution/field_resolution.rb, spec/graphql/execution_error_spec.rb, spec/graphql/introspection/schema_type_spec.rb, spec/support/dairy_app.rb
Returning an `ExecutionError` from a resolver automatically annotates the error object with the current ast node and path. Super handy.
However, this only works with nullable fields. If you want to return a sensible value on a non-nullable field you must annotate the ast node and path by hand.
This adds `Context#add_error` to automatically annotate resolver errors.
``` ruby
resolve -> (repo, args, ctx) {
ctx.add_error GraphQL::ExecutionError.new("Repository stars could not be fetched")
return 0
}
```
An alternative API might be allowing another special error type that would hold a value and error.
``` ruby
resolve -> (repo, args, ctx) {
return GraphQL::ExecutionErrorWithValue.new(value: 0, error: "Repository stars could not be fetched")
}
```
<hr>
To: @rmosolgo 
CC: @mcolyer
=> Improve API for returning value and error

lib/graphql/analysis/analyze_query.rb, lib/graphql/analysis/field_usage.rb, lib/graphql/analysis/query_complexity.rb, lib/graphql/internal_representation/node.rb, lib/graphql/internal_representation/rewrite.rb, lib/graphql/query/serial_execution/execution_context.rb, lib/graphql/query/serial_execution/selection_resolution.rb, readme.md, spec/graphql/analysis/analyze_query_spec.rb, spec/graphql/internal_representation/rewrite_spec.rb, spec/graphql/introspection/type_type_spec.rb, spec/graphql/schema/reduce_types_spec.rb, spec/support/dairy_app.rb
Fixes #370 
That was a doozy! 
Sadly this is a breaking change to `InternalRepresentation::Node`, but I don't see a way around it. 
The old structure kept _shallow_ typed branches in the form of `definitions[type] # => field_defn`. But the problem was that `children` wasn't branched by type, so when we deeply merged children, we lost information about which type condition that branch applied to. 
Now, `children` is replaced by `typed_children`, whose keys are GraphQL types and values are `{ string => node }` hashes (what `children` was previously). 
There's still an issue: when _executing_ divergent branches, it's possible that we'll do redundant work. For example, this would result in double work: 
```graphql
{
thing {
... on InterfaceA {
inner1 { inner2 }
}
... on InterfaceB {
inner1 { …
```
=> Fix nested typed fields

lib/graphql/argument.rb, lib/graphql/base_type.rb, lib/graphql/define/instance_definable.rb, lib/graphql/directive.rb, lib/graphql/enum_type.rb, lib/graphql/field.rb, lib/graphql/input_object_type.rb, lib/graphql/interface_type.rb, lib/graphql/object_type.rb, lib/graphql/relay/mutation.rb, lib/graphql/scalar_type.rb, lib/graphql/schema.rb, lib/graphql/union_type.rb, spec/graphql/define/instance_definable_spec.rb
This is a slightly tamer approach to reduce the overhead of lazy definitions. It also opens the door to the more bonkers approach in #344 . 
It seems to result in a modest improvement over master, looks like because it uses built-in `attr_accessor` rather than `instance_variable_get`: 
- Master: 
<details>
```
Thread ID: 70159054412240
Fiber ID: 70159063195160
Total: 0.161769
%self      total      self      wait     child     calls  name
8.34      0.014     0.013     0.000     0.000    12614  *GraphQL::Define::InstanceDefinable#ensure_defined
5.73      0.009     0.009     0.000     0.000     7844   Kernel#instance_variable_get
4.32      0.053     0.007     0.000     0.046     3985  *Class#new
4.06      0.051     0.007     0.000     0.044     1748 …
```
=> Move ensure defined

lib/graphql/query/context.rb
https://github.com/rmosolgo/graphql-ruby/pull/379 changed the API of FieldResolution which broken graphql-batch https://github.com/Shopify/graphql-batch/pull/32 for version 1.2.0 of the graphql gem.  Now I'm not sure what the best way to get access to the execution strategy from a FieldResolution object.
I found that adding an strategy alias in FieldResolutionContext would allow https://github.com/rmosolgo/graphql-ruby/pull/379 to work with older and newer versions of the graphql gem.
=> Add strategy alias for execution_strategy in FieldResolutionContext

lib/graphql/schema.rb, lib/graphql/schema/build_from_definition.rb
As per https://github.com/rmosolgo/graphql-ruby/pull/384#discussion_r86922870, this will make it a bit more obvious to the reader what is being exposed in `Schema` as well as where `BuildFromDefinition` is used.
=> Expose Schema#from_definition directly in schema.rb

lib/graphql/static_validation/arguments_validator.rb, lib/graphql/static_validation/rules/fields_are_defined_on_type.rb, lib/graphql/static_validation/rules/fields_have_appropriate_selections.rb, lib/graphql/static_validation/rules/required_arguments_are_present.rb, lib/graphql/static_validation/validation_context.rb, spec/graphql/static_validation/rules/argument_literals_are_compatible_spec.rb, spec/graphql/static_validation/rules/arguments_are_defined_spec.rb, spec/graphql/static_validation/rules/fields_are_defined_on_type_spec.rb, spec/graphql/static_validation/rules/required_arguments_are_present_spec.rb
Fixes #387
Validation of dynamic fields (i.e. `__schema`, `_type`, and `__typename`) seem broken (see tests for examples) because we were early returning for them.
I believe we can treat these fields as any other field since [`Schema.get_field`](https://github.com/rmosolgo/graphql-ruby/blob/1246912b777b5e82665349c592f85f8885c376b0/lib/graphql/schema.rb#L150) is aware of these special fields.
Also added a bit more test coverage around validating these dynamic fields.
=> Fix validations for dynamic fields

lib/graphql/query/arguments.rb, spec/graphql/enum_type_spec.rb, spec/graphql/query/arguments_spec.rb
Oops, the old code assumed that any array was of `List` type, but in fact, an enum value could be an array! (Fixes #397)
=> fix(Arguments) wrap based on type, not value

lib/graphql/input_object_type.rb, spec/graphql/input_object_type_spec.rb, spec/graphql/relay/mutation_spec.rb
Based on the original order of execution, `input_fields` was still aliased to the un-`ensure_defined` version of `arguments`.
=> `input_fields` did not ensure_define

lib/graphql/execution/execute.rb, lib/graphql/execution/lazy/lazy_method_map.rb, lib/graphql/query.rb, lib/graphql/query/context.rb, lib/graphql/query/serial_execution/field_resolution.rb, lib/graphql/query/serial_execution/value_resolution.rb
Trying to find some low hanging fruit while checking out ruby-prof output. (I'll come for `ensure_defined` soon...)
```
Thread ID: 70265958824400
Fiber ID: 70265955160600
Total: 0.232596
%self      total      self      wait     child     calls  name
6.59      0.034     0.015     0.000     0.018     6457  *Class#new
4.33      0.010     0.010     0.000     0.000    12118  *GraphQL::Define::InstanceDefinable#ensure_defined
3.48      0.008     0.008     0.000     0.000     8873   Kernel#hash
2.78      0.032     0.006     0.000     0.025     3496  *GraphQL::Schema::MiddlewareChain#call
2.67      0.006     0.006     0.000     0.000     5245   Array#first
2.52      0.012     0.006     0.000     0.006     3856   #<Module:0x007fd0231882b0>#type
2.12 …
```
=> Optimizations

lib/graphql/define/assign_object_field.rb, lib/graphql/define/instance_definable.rb, lib/graphql/field.rb, lib/graphql/relay/node.rb, lib/graphql/schema.rb, lib/graphql/schema/instrumented_field_map.rb, lib/graphql/schema/validation.rb, spec/graphql/define/instance_definable_spec.rb, spec/graphql/field_spec.rb, spec/graphql/schema_spec.rb
This allows you to call `#instrument` _after_ `.define`, eg 
```ruby 
MySchema = Schema.define do 
end 
MySchema.instrument(:field, SomeInstrumenter)
```
It points out some issues with this approach: if an attribute wasn't assigned via `.define`, it's not copied by `redefine`. I found some bugs in the gem. I'll keep an eye out for others: if they pop up, I'll either find another way to support this API or investigate `#dup` as an implementation of `#redefine`.
cc @tmeasday
=> Add instrumenters after schema.define 

lib/graphql/language/visitor.rb, lib/graphql/static_validation/type_stack.rb
I think these APIs are unused (or, can be unused with this refactor). These are removed:
- Returning `SKIP` no longer skips sibling nodes (did that actually work? untested.)
- Visitor no longer has global `enter` and `leave` hooks (called for every node)
cc @josh do you care if I remove these? I didn't see them in use at graphql-client. 
(I don't know anyone else consuming `GraphQL::Language::Visitor`)
=> refactor(Visitor) remove global hooks; remove sibling skips

lib/graphql/enum_type.rb, spec/graphql/enum_type_spec.rb
In error messages for `EnumType#validate_non_null_input`, display the enum value names instead of the default ruby object representation.
=> convert enum type values to names for error messages

lib/graphql/relay/connection_field.rb, spec/graphql/relay/connection_field_spec.rb
This isn't really a fix, just a test that this doesn't mess with the Field instance anymore (it's shallow-copied by the `field` helper)
=> test(Connection) assert that connection helper doesn't modify passed-in field

lib/graphql/query.rb, spec/graphql/schema_spec.rb
With this change, `after_query` hooks are _always_ run, even if the query raises a Runtime error
=> feat(Query) run after_query hooks even if an error occurs

lib/graphql/static_validation/all_rules.rb, lib/graphql/static_validation/message.rb, lib/graphql/static_validation/rules/unique_directives_per_location.rb, spec/graphql/static_validation/rules/unique_directives_per_location_spec.rb
This implements facebook/graphql#229, in order to adhere with the October 2016 edition of the spec.
ref. implementation: graphql/graphql-js#552
=> Add validation rule for unique directives per location

lib/graphql/define/defined_object_proxy.rb
I would like to run the graphql-batch tests against both graphql-ruby master and the latest release, however, the version hasn't been bumped on graphql-ruby master and I wasn't able to get this feature detection to work.
```ruby
has_lazy_resolve = nil
GraphQL::Schema.define do
has_lazy_resolve = respond_to?(:lazy_resolve)
end
```
The problem was that inside the `GraphQL::Schema.define` block `self` is a DefinedObjectProxy object that defines `method_missing` to support methods like `lazy_resolve` but it doesn't implement `respond_to_missing?` to support `respond_to?`
Add a `respond_to_missing?` method to DefinedObjectProxy to return true for proxied methods
=> Allow feature detection on DefinedObjectProxy

lib/graphql/compatibility/lazy_execution_specification.rb, lib/graphql/execution/execute.rb, spec/graphql/execution/lazy_spec.rb, spec/graphql/non_null_type_spec.rb, spec/graphql/query/executor_spec.rb
As mentioned in https://github.com/rmosolgo/graphql-ruby/pull/334#issuecomment-262440736, there is a regression on master where GraphQL::ExecutionError is now used instead of an invalid null error, which prevents this internal error from being found in the context errors by error class for internal error reporting.
E.g.
```ruby
QueryType = GraphQL::ObjectType.define do
name "Query"
field :nonNullButIs, !types.String do
resolve proc { nil }
end
end
Schema = GraphQL::Schema.define do
query QueryType
end
query = GraphQL::Query.new(Schema, '{ nonNullButIs }')
result = query.result
internal_errors = query.context.errors.reject { |err| err.is_a?(GraphQL::ExecutionError) }
puts internal_errors.inspect
```
would output `[#<GraphQL::InvalidNullError: Cannot return null for …
=> Use GraphQL::InvalidNullError in the new executor

guides/schema/configuration_options.md, lib/graphql/compatibility/execution_specification.rb, lib/graphql/compatibility/execution_specification/specification_schema.rb, lib/graphql/execution/execute.rb, lib/graphql/query/serial_execution/field_resolution.rb, lib/graphql/query/serial_execution/selection_resolution.rb, lib/graphql/query/serial_execution/value_resolution.rb, lib/graphql/schema.rb, lib/graphql/schema/default_type_error.rb, spec/graphql/non_null_type_spec.rb
There are a few judgment calls made by library internals that could be customized by users: 
- What to do when we get `nil` for a non-null type (currently, the library adds an error to the errors key) 
- What to do when a union/interface object can't be resolved to a member type (currently, the library :boom:s) 
This PR adds a hook for those two cases, with the default implementation being the current behavior. 
In the future, this hook could be expanded to handle more cases, like scalar coercion.
=> Type error hook

lib/graphql/compatibility/lazy_execution_specification.rb, lib/graphql/compatibility/lazy_execution_specification/lazy_schema.rb, lib/graphql/execution/execute.rb, lib/graphql/execution/lazy.rb, lib/graphql/relay/connection_resolve.rb
The forthcoming `lazy_resolve` feature should play nice with connections: if you provide a connection resolve function and it's a registered lazy object, we'll treat it lazily, then continue with a connection object wrapping the lazily-resolved nodes.
Fixes #420
=> feat(Execution::Lazy) support lazy connection values

lib/graphql/schema/validation.rb, spec/graphql/schema/validation_spec.rb
Ref: https://github.com/graphql/graphql-js/pull/600
> GraphQL type system authors must not define any types, fields, arguments, or any other type system artifact with two leading underscores.
Spec: http://facebook.github.io/graphql/#sec-Naming-conventions
---
This PR enforces type, argument, and field names cannot begin with `__`.
=> Uphold spec for reserved `__` naming

lib/graphql/query.rb, spec/graphql/query_spec.rb
Make queries a bit more useful in instrumentation: 
- Expose `provided_variables`
- Allow calling `result` from inside `after_query`
=> Query accessors

graphql.gemspec, guides/schema/configuration_options.md, lib/graphql.rb, lib/graphql/compatibility/execution_specification.rb, lib/graphql/compatibility/execution_specification/specification_schema.rb, lib/graphql/execution/execute.rb, lib/graphql/invalid_null_error.rb, lib/graphql/non_null_type.rb, lib/graphql/query/serial_execution/value_resolution.rb, lib/graphql/schema.rb, lib/graphql/schema/default_type_error.rb, lib/graphql/type_error.rb, lib/graphql/unresolved_type_error.rb, spec/graphql/non_null_type_spec.rb
Pass a `TypeError` instance to `Schema#type_error` instead of a long list of marginally useful arguments 😬  Includes assertions about those error objects' APIs.
cc @dylanahsmith thanks for this suggestion!
=> feat(Schema#type_error) use TypeError to pass info to type_error hook

lib/graphql/invalid_null_error.rb, lib/graphql/query/executor.rb, lib/graphql/query/serial_execution/field_resolution.rb, lib/graphql/query/serial_execution/operation_resolution.rb, lib/graphql/query/serial_execution/selection_resolution.rb, lib/graphql/query/serial_execution/value_resolution.rb
As originally mentioned in https://github.com/rmosolgo/graphql-ruby/pull/416#issuecomment-263365631
> I ran the graphql-batch tests and found that this PR caused a regression as seen from this graphql-batch test failure:
> 
> ```
>   1) Failure:
> GraphQL::GraphQLTest#test_non_null_field_promise_raises [/Users/dylansmith/src/graphql-batch/test/graphql_test.rb:116]:
> --- expected
> +++ actual
> @@ -1 +1 @@
> -{"data"=>nil, "errors"=>[{"message"=>"Error", "locations"=>[{"line"=>1, "column"=>3}], "path"=>["nonNullButPromiseRaises"]}]}
> +{"data"=>{"nonNullButPromiseRaises"=>:__graphql_propagate_null__}, "errors"=>[{"message"=>"Error", "locations"=>[{"line"=>1, "column"=>3}], "path"=>["nonNullButPromiseRaises"]}]}
> ```
The bug came from the serial execution engine refactor to use a …
=> Raise a PropagateNull exceptions to keep compatibility with graphql-batch

lib/graphql.rb, lib/graphql/invalid_null_error.rb, lib/graphql/runtime_type_error.rb, lib/graphql/type_error.rb, lib/graphql/unresolved_type_error.rb
The previous name breaks existing "rescue TypeError" clauses inside the GraphQL namespace, boo hiss.
=> refactor(TypeError) rename to RuntimeTypeError to avoid conflicts

guides/schema/instrumentation.md, lib/graphql/compatibility/lazy_execution_specification.rb, lib/graphql/compatibility/lazy_execution_specification/lazy_schema.rb, lib/graphql/execution/execute.rb, lib/graphql/field.rb, lib/graphql/relay/connection_resolve.rb
Now, you can "hook in" to `lazy_resolve` similar to `resolve`. You get access to the same things: type, field, runtime object (eg, Promise), arguments, and field context. 
I think you could use the runtime object to group `lazy_resolves` by _actual_ database operation. For example, I think `Promise#source` will point to the `Loader` instance.
=> feat(Field#lazy_resove) add hook for instrumenting lazy methods

lib/graphql/compatibility/execution_specification.rb, lib/graphql/compatibility/execution_specification/specification_schema.rb, lib/graphql/execution/execute.rb, lib/graphql/query/serial_execution/value_resolution.rb
Previously, it was an unspecified requirement that any object behind a `List` type had to implement `each_with_index` to return an enumerator. 
Now, it's a specified requirement that any `List` object must implement `#each`, yielding each member.
=> feat(Execute) specify requirements of list objects

guides/index.md, guides/related_projects.md
Makes it clear the Apollo Client and graphql-ruby are totally compatible.
=> Adds Apollo to docs

lib/graphql/static_validation/rules/fields_will_merge.rb, spec/graphql/static_validation/rules/fields_will_merge_spec.rb
I ported over a bunch of tests from [graphql-js](https://github.com/graphql/graphql-js/blob/ba422261bfec5ad653a6812fab4718f4f22101c2/src/validation/__tests__/OverlappingFieldsCanBeMerged-test.js).
I also made a change to how we report variable names in error messages. It was previously broken as we were calling `print_arg` on `arg` which was always a `String`.
Before: `Field 'doesKnowCommand' has an argument conflict: {"dogCommand":"SIT"} or {"dogCommand":"dogCommand"}?`
After: `Field 'doesKnowCommand' has an argument conflict: {"dogCommand":"SIT"} or {"dogCommand":"$dogCommand"}?`
There is a few tests that I didn't add because they caused the build to fail (for example: #418). We can either add them to the spec commented out, or I can open an issue for each failing test.
=> Better test coverage for FieldsWillMerge validation

lib/graphql/relay/mutation.rb, spec/graphql/relay/mutation_spec.rb, spec/support/star_wars_schema.rb
Now, a mutation can return a lazy value (like a graphql-batch Promise).
Thanks @theorygeek for pointing this out ... by the way, did it _ever_ work, I mean, did it work in a previous version? (I was looking back over the changes of this code and I couldn't figure out how it ever worked 😆 )
=> feat(Mutation) support lazy return values

lib/graphql/schema/build_from_definition.rb, lib/graphql/schema/loader.rb, spec/graphql/schema/build_from_definition_spec.rb, spec/graphql/schema/loader_spec.rb
Previously, custom scalars had `nil` coerce functions, which would case validation to fail with `NoMethodError`. Now, they have no-op functions which consider _anything_ valid. It limits the strength of the validation, but it's better than the NoMethodError! 
Thanks @nevesenin for tracking this down in #424!
=> Fix coerece for generated schemas

lib/graphql/static_validation/rules/fields_will_merge.rb
Fixes #446 
Problem: 
```
[ERROR] only generation of JSON objects or arrays allowed
arg: true
```
Solution: Enable `quirks_mode` so that `JSON.generate` will handle an `arg` of `true`.
```ruby
def print_arg(arg)
case arg
when GraphQL::Language::Nodes::VariableIdentifier
"$#{arg.name}"
when GraphQL::Language::Nodes::Enum
"#{arg.name}"
else
JSON.generate(arg, { quirks_mode: true })
end
end
```
=> Fixes rmosolgo/graphql-ruby/issues#446 - Use explicit quirks_mode: true on JSON.generate

lib/graphql/base_type.rb, lib/graphql/define/instance_definable.rb, lib/graphql/enum_type.rb, lib/graphql/execution/lazy/lazy_method_map.rb, lib/graphql/field.rb, lib/graphql/input_object_type.rb, lib/graphql/interface_type.rb, lib/graphql/object_type.rb, lib/graphql/schema.rb, lib/graphql/union_type.rb, spec/graphql/base_type_spec.rb, spec/graphql/enum_type_spec.rb, spec/graphql/field_spec.rb, spec/graphql/input_object_type_spec.rb, spec/graphql/interface_type_spec.rb, spec/graphql/object_type_spec.rb, spec/graphql/schema_spec.rb, spec/graphql/union_type_spec.rb
this makes `#redefine` use `#dup` instead of keeping a log of previous `#define` calls and replaying them. 
The advantage is that any change _outside_ of a `#define` call (eg, assigning a metadata key directly) _will_ be captured by `#redefine`. 
The disadvantage is that it's possible for bugs to slip in where `#dup`-ed objects are accidentally sharing some state!
=> feat(InstanceDefinable) use #dup; make schema members #dup-able

lib/graphql/enum_type.rb, lib/graphql/introspection/input_value_type.rb, lib/graphql/language.rb, lib/graphql/language/generation.rb, lib/graphql/scalar_type.rb, lib/graphql/static_validation/rules/fields_will_merge.rb
Occasionally, we serialize values but forget `quirks_mode` true, resulting in breakage for JSON implementations _other_ than the stdlib one. 
So, let's reduce the risk of doing that again by passing through this one helper.
=> feat(Language.serialize) add unified method for serializing values

lib/graphql/schema/validation.rb, spec/graphql/schema/validation_spec.rb
As I was preparing the changelog for 1.3.0, I realized that we could make this transition more gradual. I don't want to put a blocker in front of people who want to upgrade! 
In a later version, we can make this fail by default but provide an option to use the old way. Then maybe someday we can remove it altogether. (I didn't take that approach now because `Schema::Valdiation`'s design is not conducive to it.)
@chollier, this one is for you :)
=> refactor(Schema::Validation) only warn on __

lib/graphql/relay/array_connection.rb, spec/graphql/relay/array_connection_spec.rb, spec/graphql/relay/relation_connection_spec.rb
This fixes a bug with the ArrayConnection. The failure condition is if the field resolver returns an array with N elements, and you then query against that connection with the starting offset of N+1.
```
2.3.1 :004 > x = (0...20).to_a
=> [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19] 
2.3.1 :005 > x[21..-1]
=> nil 
```
The `sliced_nodes` method ends up returning `nil`. And then `paged_nodes` tries to do:
```ruby
items.first(limit)
```
And it 💥  because of a null reference. This can happen if the connection _used_ to have plenty of elements in it, but now it doesn't anymore.
=> Bug with ArrayConnection

lib/graphql/relay/connection_type.rb, spec/graphql/relay/connection_type_spec.rb, spec/support/star_wars_schema.rb
While the `Connection`/`Edge`/`Node` model provides a useful place to attach join model annotations, most of @github's usage has just been enumerating a connection's node list. Cursor data is simply accessed via `PageInfo.endCursor`.
This change adds and additional `Connection.nodes` as a shortcut for accessing `Connection->edges->node`.
I understand this isn't part of the Relay spec specifically, so maybe it could be opt-in if you think its  necessary?
I'm hoping I'm remember this right, but I believe @dschafer (@facebook) mentioned this alias to me at a GraphQL conference/meetup thing.
=> Add Connection.nodes shorthand

lib/graphql/query.rb
From a middleware or instrumentation, there's no way to know the runtime type of an object except by calling `resolve_type`. That's ok, but we don't need to call the user-provided function again. Let's assume that the same object will return the same runtime type!
=> refactor(Query#resolve_type) cache the value of #resolve_type

lib/graphql/relay/relation_connection.rb, spec/graphql/relay/relation_connection_spec.rb, spec/support/star_wars_schema.rb
If a relation contains a `.group` clause, a `.count` will return a `Hash`. So to know a connection length we have to count also the `Hash`'s content.
_Another solution would be to use `.length` instead of `.count`, but that would not ask the databse, but load all the records into the memory, which… is bad._
=> Fix grouped connection with only `last` argument specified

lib/graphql/introspection/schema_type.rb, lib/graphql/query.rb, lib/graphql/query/executor.rb, lib/graphql/schema.rb, lib/graphql/schema/warden.rb, lib/graphql/static_validation/rules/mutation_root_exists.rb, lib/graphql/static_validation/rules/subscription_root_exists.rb, spec/graphql/schema/warden_spec.rb
Oops, @bgentry discovered that hiding _root_ types didn't quite work right!
Now, `root_type_for_operation` is correctly filtered.
=> fix(Warden) also support hiding root types

guides/schema/lazy_execution.md
Fix initialization of LazyFindPerson on Lazy Execution documentation.
Missing: ```.new```
=> Fix initialization of LazyFindPerson on Lazy Execution documentation

guides/schema/types_and_fields.md
This was being rendered with the HTML of a link instead of an actual link.
=> docs(types_and_fields) Fix api_doc usage

lib/graphql/query.rb
As per [this warning](https://github.com/cjoudrey/graphql-ruby/blob/40da6dc463bb0efc04574a92225eadfb6e6d3011/lib/graphql/query.rb#L302), `except` method should accept two arguments. This is just a quick change to the docs to reflect this.
As a side note, I noticed [rubydoc](http://www.rubydoc.info/github/rmosolgo/graphql-ruby/file/CHANGELOG.md) is outdated. Is there anything we need to do to force a rebuild of the docs?
=> Fix documentation for Query#initialize "except" keyword argument

lib/graphql/execution/execute.rb
This can reduce GC pressure for very large responses -- sometimes these objects are totally unneeded! 
Here's a before-and-after of the test schema's introspection result:
=> refactor(Execute) don't allocate FieldResult if you don't need one

lib/graphql/field.rb, spec/graphql/field_spec.rb
If you have two instrumenters and they both read `#resolve_proc`, one of them will get a stale value because the previous definition wasn't run!
=> Ensure defined when reading the resolve proc

lib/graphql/define/defined_object_proxy.rb, spec/graphql/define/instance_definable_spec.rb
Was: 
```
#<GraphQL::Define::DefinedObjectProxy::NoDefinitionError: Garden::Vegetable can't define 'nonsense'>
.../gems/graphql/lib/graphql/define/defined_object_proxy.rb:23:in `method_missing'
/your/application/code.rb:124
```
Is: 
```
#<NoMethodError: Garden::Vegetable can't define 'nonsense'>
/your/application/code.rb:124
```
=> feat(define) improve typo error message and backtrace

lib/graphql/directive.rb, lib/graphql/field.rb, lib/graphql/query.rb, lib/graphql/query/arguments.rb, lib/graphql/query/literal_input.rb, spec/graphql/query/arguments_spec.rb
We make a lot more `Query::Arguments` instances than we really _need_. When no arguments are present in the query string, the `Arguments` will always be populated with the same, static default values. So we can reuse an `Arguments` instance for those.
This improvement has a smaller impact than I thought it would. I forgot that `Arguments` instances were created per-AST-node, so the number doesn't grow with the size of the response (Instead, it grows with the size of the query string). 
Running the introspection query on the test schema reduces the number of Arguments instances from  64 to 2 
- before: 
```
%self     total      self      wait     child     calls  name
0.04      0.000     0.000     0.000     0.000       64   GraphQL::Query::Arguments#initialize
```
- after: 
```
%self …
```
=> Reuse Arguments when only default values are present

lib/graphql/internal_representation/rewrite.rb, lib/graphql/static_validation.rb, lib/graphql/static_validation/definition_dependencies.rb, lib/graphql/static_validation/rules/fragment_spreads_are_possible.rb, lib/graphql/static_validation/rules/fragments_are_finite.rb, lib/graphql/static_validation/rules/fragments_are_used.rb, lib/graphql/static_validation/validation_context.rb, spec/graphql/internal_representation/rewrite_spec.rb, spec/graphql/static_validation/rules/fragments_are_used_spec.rb, spec/support/dummy/schema.rb
Trying #497 again, but without depending on `AbstractNode#path`
=> refactor(StaticValidation) only resolve fragment dependencies once

lib/graphql/schema/validation.rb
An actual definition would look like this:
```ruby
resolve_type -> (obj, ctx) { ... }
```
with the dash rocket coming before the argument list.
=> fix proc syntax ordering on validation errors

lib/graphql/language/lexer.rb, lib/graphql/language/lexer.rl
So I was trying to track down why most AST `Language::Node`s had UTF-8 tagged strings and why a few others were untagged as binary.
Stuff like `Language::Node#name` gets surfaced in different ways on introspection queries. This leads to some binary tagged strings leaking into execution result.
I figured fixing the encoding at the source would be the best way to solve this. It looks like some of these strings are already being retagged after they are repacked. https://github.com/rmosolgo/graphql-ruby/blob/571ceab99f3076f269a3d92cc133d559151e3bfd/lib/graphql/language/lexer.rl#L190
Does the parser even support parsing input strings in anything else besides UTF-8?
=> Set UTF-8 encoding other parsed tokens

lib/graphql/define/instance_definable.rb, lib/graphql/input_object_type.rb, lib/graphql/relay/mutation.rb
I'm looking for some way to remove the overhead of lazy definitions. 
We delay calling `define { }` blocks to avoid circular dependencies, but we pay an overhead because on every call, we make sure that we don't have an outstanding `define { }` block. 
Here's one attempt. It seems a bit faster, but it's pretty gnarly code. I'll clean it up a bit if it looks promising, but either way, we're plucking methods and moving them around 😖 . This isn't _meant_ to be on any hot paths -- methods get messed with during definition, but once the schema starts taking queries, they stay put.
Here's a benchmark running the introspection query on the test schema: 
```
~/code/graphql $ git co master
Switched to branch 'master'
~/code/graphql $ ruby -Ilib:spec/support introspection_profile.rb
Warming up …
```
=> refactor(InstanceDefinable) swap out method defns when they're pending

guides/relay/object_identification.md, lib/graphql/field.rb, lib/graphql/relay/node.rb, spec/graphql/relay/node_spec.rb, spec/support/star_wars/schema.rb
Adds a helper method to define the `nodes` field.
Was recently added to `graphql-relay-js`: https://github.com/graphql/graphql-relay-js/pull/141
> The nodes field should accept a single argument ids: [ID!]!. It should return one result per input id, in an order matching the input arguments. For ids that do not exist or cannot be fetched, it should return null in order to ensure the ordering requirement."'
Field is talked about in https://github.com/facebook/relay/issues/1496
Suggestions welcome for a better name 💃
=> [Relay] Nodes field definition

lib/graphql/relay/mutation.rb, spec/graphql/relay/mutation_spec.rb, spec/support/star_wars/schema.rb
Oops, proper handling for `GraphQL::ExecutionError` should be used for lazy values, too! 
Fixes #527
=> fix(Mutation) handle errors from lazy values

Rakefile, benchmark/run.rb, graphql.gemspec, spec/support/dummy/schema.rb
I've had some code like this in my local directory for a long time and I thought I'd share it. I don't claim that it's the most scientific measure in the world, but maybe it'll get the ball rolling!
```
~/code/graphql $ be rake bench:query
query     3.000  i/100ms
query     38.278  (± 5.2%) i/s -    192.000  in   5.026674s
~/code/graphql $ be rake bench:validate
validate    37.000  i/100ms
validate    372.743  (± 3.5%) i/s -      1.887k in   5.069387s
```
=> feat(benchmark) add basic benchmark tasks

lib/graphql/relay/connection_type.rb, spec/support/star_wars/schema.rb
I've got this weird error going on in my sample app where I get a Duplicate type definition error on any connection used more than once.
I was able to reproduce in the tests:
`/graphql-ruby/lib/graphql/schema/type_map.rb:24:in `[]=': Duplicate type definition found for name 'ShipConnection'`
If i add anything that touches the object in `def connection_type` on `BaseType`,  (https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/base_type.rb#L142) then the error goes away :thinking:
This makes me think theres something lazily loaded / something is resetting `@connection_type` to `nil`, voiding the memoization.
@rmosolgo
=> Weird duplicate connection error

lib/graphql/relay/base_connection.rb, spec/graphql/relay/base_connection_spec.rb
I need access to the context in a custom EdgeClass so we can do authorization checks on the edge resource. Adding `context` to the `attr_reader` seems like the easiest approach.
=> Allow public access to context for Relay Connection

lib/graphql/analysis/query_complexity.rb, lib/graphql/analysis/query_depth.rb, lib/graphql/execution/execute.rb, lib/graphql/internal_representation/node.rb, lib/graphql/internal_representation/rewrite.rb, lib/graphql/query/serial_execution/field_resolution.rb, lib/graphql/query/serial_execution/selection_resolution.rb, spec/graphql/directive_spec.rb, spec/graphql/internal_representation/rewrite_spec.rb
Oops, I realized this while I was falling asleep a couple nights ago! It makes much more sense to just skip these altogether during the rewrite, then you don't have to worry about them down the line. 
What's more is that I can imagine extracting this to a `rewrite_node` hook, something like 
```ruby 
def rewrite_node(query, ast_node) 
if include?(query, ast_node)
yield(ast_node) 
else 
end 
end 
```
That could be the beginning of a custom directive API ... :thinking:
=> Fix: don't include children of skipped nodes

lib/graphql/field.rb, spec/graphql/field_spec.rb
Name changes when redefining a field now reset the resolve proc instead of raising.
@rmosolgo
=> refactor(Field) Rebuild the default NameResolve when name is changed

lib/graphql/base_type.rb, lib/graphql/schema/printer.rb, spec/graphql/base_type_spec.rb, spec/graphql/schema/printer_spec.rb
Ref https://github.com/rmosolgo/graphql-ruby/issues/534
Refactors `Printer` from a module to a class to make it easier to print out the definition of a single type.
@rmosolgo this is a WIP approach to exposing `print_type`. Wanted to see if you like it before going much further.
Turns out that adding `to_definition` is not that easy for a few reasons:
1. Warden is used in all the printers
2. Warden is scoped to a schema
So adding a `#to_definition` *without* requiring a schema/warden would result in a lot of duplication of the printers. It also might be a bad thing to expose printers without the ability to mask anything.
The one downside to this API is that calling `to_definition` requires a schema.
This was the most direct refactor which also maintains the existing `print_schema` and …
=> [WIP] Add to_definition to BaseType to print definition

lib/graphql/relay/mutation.rb, spec/graphql/relay/mutation_spec.rb, spec/graphql/schema/reduce_types_spec.rb
In a Relay Mutation with a generated payload type using `return_field`, if you make the mistake of returning anything but a Hash, you'll get an exception when building the result. `NoMethodError each`.
This is pretty hard to debug for someone new to the gem, would be great to raise a helpful exception here.
@rmosolgo
cc @cjoudrey
=> Better error msg mutation result

lib/graphql/relay/mutation.rb
@rmosolgo 
Should not raise when mutation returns nil, only if its returning something that is not a hash.
=> Mutation error: dont raise when mutation is nil

guides/schema/types_and_fields.md, lib/graphql/argument.rb, lib/graphql/define/assign_argument.rb, lib/graphql/query/arguments.rb, spec/graphql/argument_spec.rb, spec/graphql/query/arguments_spec.rb, spec/support/dummy/schema.rb
related to https://github.com/rmosolgo/graphql-ruby/issues/540
Allow specifying a key that will present in the `Arguments` at resolve time instead of the specified argument name.
```ruby
field :post, PostType do
argument :postId, types.Id, as: :id
resolve ->(obj, args, ctx) {
Post.find(args['id'])
}
end
```
good for review @rmosolgo, I'm open to other names for the arg 🤔
=> feat(Arguments) Allow specifying an alternate key for arguments, used in resolvers

.travis.yml, lib/graphql/id_type.rb, spec/graphql/schema/validation_spec.rb
Let's see if this works... need to: 
- https://bugs.ruby-lang.org/issues/13107
=> test on Ruby 2.4

guides/relay/object_identification.md, lib/graphql/object_type.rb, spec/graphql/object_type_spec.rb
As per #546, this adds `ObjectType#implements` as a way to add an interface to a type.
**Usage**
```ruby
GraphQL::ObjectType.define do 
name "Page" 
implements GraphQL::Relay::Node.interface 
implements TitledEntityInterface
end 
```
You can also pass multiple interfaces at once:
```ruby
GraphQL::ObjectType.define do 
name "Page" 
implements GraphQL::Relay::Node.interface, TitledEntityInterface
end 
```
=> Add ObjectType#implements

guides/relay/object_identification.md, lib/graphql/relay/node.rb, spec/graphql/relay/node_spec.rb, spec/support/star_wars/schema.rb
As mentioned in https://github.com/rmosolgo/graphql-ruby/pull/550 by @rmosolgo. It think its even nicer to allow anything to be redefined on the standard node and nodes field.
=> feat(Relay::Node) extend node & nodes fields using definition block

guides/schema/lazy_execution.md
We should remove pending IDs once they get retrieved to remove redundant DB requests.
Also avoid duplicate IDs to reduce SQL length.
=> Tweak lazy find sample code

lib/graphql/define/assign_object_field.rb, spec/graphql/function_spec.rb
This PR demonstrates how overriding function definitions might work. 
The DSL is a little bleh, but, given a `function: kwarg`, I couldn't think of any other way to support overrides other than passing in a block, too. I didn't think that supporting
``` ruby
field :overwrittenDescription, "A description", function: TestFunc.new
```
made much sense.
Happy to address any feedback or changes here. ✌️
=> Add support for functional overrides

lib/graphql/string_type.rb, spec/graphql/string_type_spec.rb
Today its possible to return binary or non-utf8 compatible strings as GraphQL String scalars. If this happens it will likely crash later when the actual JSON serialization step. This sort of thing is really hard to track down, especially if most of the time you're returning valid but untagged UTF-8 data and invalid data slips in crashing the entire response.
Since UTF-8 is a requirement, I think it would be good to enforce at the scalar casting phase.
Test failure depends on https://github.com/rmosolgo/graphql-ruby/pull/516.
My concern is that this is a backwards incompatible change. Should we add some kind of flag to opt into this behavior?
Also, I'm letting US-ASCII data through as it should be a proper subset of UTF-8. An alternative would be to upgrade the encoding to UTF-8. Or we …
=> Ensure returned String types are encoded as UTF-8

lib/graphql/define/defined_object_proxy.rb, lib/graphql/define/instance_definable.rb, spec/graphql/define/instance_definable_spec.rb
@rmosolgo @xuorig @dylanahsmith 
As per the discussion in https://github.com/Shopify/graphql-batch/pull/49, this adds a way to write plugins that have access to the DSL.
**Some example usages:**
```ruby
GraphQL::Schema.define do
use GraphQL::Batch # This will call GraphQL::Batch.use(self)
end
module GraphQL
module Batch
def self.use(schema_defn)
schema_defn.lazy_resolve(Promise, :sync)
schema_defn.instrument(:query, GraphQL::Batch::Setup)
end
end
end
```
You can also accept arguments and keyword arguments:
```ruby
GraphQL::Schema.define do
use GraphQLPro::Authorization, strategy: :devise
end
```
This will work on any object that supports `.define` so you could use it on object types and fields too:
```ruby
GraphQL::ObjectType.define do
field :cheeses, !types[!Cheese] do
use Pagination
end …
```
=> Add DefinedObjectProxy#use

lib/graphql/relay/relation_connection.rb
The code is a mess, but I wanted to try this out, apparently this is how join-monster does it!
Before:
```sql
StarWars::Base Load (0.2ms)  SELECT  "bases".* FROM "bases" WHERE "bases"."id" IN (SELECT "bases"."id" FROM "bases" WHERE "bases"."faction_id" = ?) LIMIT ? OFFSET ?  [["faction_id", 2], ["LIMIT", 2], ["OFFSET", 0]]
(0.2ms)  SELECT COUNT(count_column) FROM (SELECT  1 AS count_column FROM "bases" WHERE "bases"."id" IN (SELECT "bases"."id" FROM "bases" WHERE "bases"."faction_id" = ?) LIMIT ? OFFSET ?) subquery_for_count  [["faction_id", 2], ["LIMIT", 3], ["OFFSET", 0]]
```
After: 
```sql
StarWars::Base Load (0.2ms)  SELECT  "bases".* FROM "bases" WHERE "bases"."id" IN (SELECT "bases"."id" FROM "bases" WHERE
```
=> refactor(RelationConnection) check for next page when fetching items

.rubocop.yml, Gemfile, graphql.gemspec, lib/graphql/define/assign_mutation_function.rb, lib/graphql/introspection/schema_type.rb, lib/graphql/schema.rb, lib/graphql/schema/build_from_definition.rb, lib/graphql/static_validation/definition_dependencies.rb, lib/graphql/static_validation/rules/operation_names_are_valid.rb, lib/graphql/static_validation/validation_context.rb, spec/graphql/field_spec.rb, spec/graphql/schema/printer_spec.rb, spec/graphql/schema/warden_spec.rb, spec/graphql/schema_spec.rb, spec/spec_helper.rb
This cop was added to RuboCop by https://github.com/bbatsov/rubocop/pull/3656.
This PR ensures #313 will be consistently enforced. It was discussed in #306, #326 and #320.
_**Caveat:** ~~I'm jumping the gun a bit here because that PR wasn't merged yet~~, nor RuboCop's next version was release, but at least my PR will be ready as soon as these happen. I'll be rebasing this PR accordingly.
**Edit:** PR was merged, no new release yet._
=> Ensure there are no spaces after lambda arrows throughout the code

lib/graphql/field/resolve.rb, spec/graphql/field_spec.rb, spec/graphql/query/variables_spec.rb, spec/graphql/schema/warden_spec.rb
This will allow us to build method-like fields just like the example on http://graphql.org/graphql-js/.
With this, I will be able to use class methods as simple resolvers. It makes simple and modular usages possible and it's more intuitive.
```ruby
Todo = Struct.new(:text)
class Root
attr_accessor :todos
def initialize
@todos = [
Todo.new("Pay the bills."),
Todo.new("Go to dentist."),
Todo.new("Buy milk.")
]
end
def todoAdd(args)
todo = Todo.new(args[:text])
@todos << todo
todo
end
def allTodos
@todos
end
end
app = Root.new
Schema.execute("mutation {
todoAdd(text: \"Heyo\") {
text
}
}", root_value: app)
result = Schema.execute("query {
allTodos {
text
}
}", root_value: app)
```
Since it covers all the method-like argument accepting fields, it will work on any level.
=> Passing arguments to root_value (and sub-fields) fields when they are methods.

lib/graphql/execution/execute.rb, spec/graphql/execution/execute_spec.rb
=> Stop resolving siblings if one of them propagates a `null`

lib/generators/graphql/interface_generator.rb, lib/generators/graphql/object_generator.rb, lib/generators/graphql/type_generator.rb, lib/generators/graphql/union_generator.rb
Oops, this was showing as a false positive:
```
$ rails g graphql:type -h
Usage:
rails generate graphql:type TypeName [options]
Runtime options:
-f, [--force]                    # Overwrite files that already exist
-p, [--pretend], [--no-pretend]  # Run but do not make any changes
-q, [--quiet], [--no-quiet]      # Suppress status output
-s, [--skip], [--no-skip]        # Skip files that already exist
Description:
Create graphql files for type generator.
```
now, appropriately: 
```
$ rails g graphql:type -h
Could not find generator 'graphql:type'. Maybe you meant 'graphql:object', 'graphql:loader' or 'graphql:union'
Run `rails generate --help` for more options.
```
cc @cjoudrey
=> Fix(generators) rename base class so it's not a generator

lib/graphql/execution/typecast.rb, spec/graphql/execution/typecast_spec.rb
I noticed this function was unused. It wasn't _marked_ private, but it wasn't publicized in the guides and it hasn't _worked_ for quite a while, since it uses the long-dead `InterfaceType#possible_types` method.
=> refactor(Typecast) remove unused compatible? function

lib/graphql/compatibility/execution_specification/counter_schema.rb, lib/graphql/execution/typecast.rb, lib/graphql/object_type.rb, lib/graphql/schema/validation.rb, spec/graphql/execution/typecast_spec.rb, spec/graphql/introspection/type_type_spec.rb, spec/graphql/object_type_spec.rb, spec/graphql/schema/validation_spec.rb, spec/support/dummy/schema.rb
I'd like to take advantage of the new `implements` method to improve interface support. Currently: 
- `interfaces(...)` causes an object to "inherit" fields from the interface 
- the object can override those fields in breaking ways 
- there is no way to _prevent_ inheritance 
What I want to do is: 
- `implements SomeInterface` _doesn't_ inherit fields from the interface 
- `implements SomeInterface, inherit: true` inherits definitions from the interface 
- Add a proper interface validation to schema setup
Cleanup task:
=> Validate interfaces, don't inherit by default with `implements`

.rubocop.yml, benchmark/run.rb, lib/graphql/define/assign_mutation_function.rb, lib/graphql/function.rb, lib/graphql/internal_representation/node.rb, lib/graphql/internal_representation/rewrite.rb, lib/graphql/relay/range_add.rb, lib/graphql/runtime_type_error.rb, lib/graphql/schema/base_64_encoder.rb, lib/graphql/schema/null_mask.rb, lib/graphql/static_validation/definition_dependencies.rb, spec/generators/graphql/function_generator_spec.rb, spec/generators/graphql/install_generator_spec.rb, spec/generators/graphql/interface_generator_spec.rb, spec/generators/graphql/loader_generator_spec.rb, spec/generators/graphql/mutation_generator_spec.rb, spec/generators/graphql/object_generator_spec.rb, spec/generators/graphql/union_generator_spec.rb, spec/graphql/directive/skip_directive_spec.rb, spec/graphql/function_spec.rb, spec/graphql/relay/range_add_spec.rb, spec/support/base_generator_test.rb
Apparently this cop only runs if target ruby is 2.3+
=> fix(rubocop) target Ruby 2.3 for proper frozen_string_literal checking

lib/graphql/field/resolve.rb, lib/graphql/schema.rb, lib/graphql/schema/build_from_definition.rb, spec/graphql/field_spec.rb, spec/graphql/schema/build_from_definition_spec.rb, spec/graphql/schema/warden_spec.rb
With this patch: 
- Previous behavior for DSL-created schemas is unchanged 
- New default behavior for IDL-created schemas is unchanged 
- Custom execution for IDL-created schemas is possible 
I've included an example in the specs how field resolution can be specified any way you can imagine. In that example, resolve functions are provided in a two-level map, `{ type_name => { field_name => resolve_fn } }`. What do you think, is this a good fit?
Also, lexical scopes are fun :) 
cc/ @f @tberman @theorygeek
=> feat(Schema.from_definition) accept custom resolve behavior for runnable schemas

lib/graphql/analysis/analyze_query.rb, lib/graphql/internal_representation/node.rb, lib/graphql/internal_representation/rewrite.rb, lib/graphql/internal_representation/visit.rb, lib/graphql/query.rb, spec/graphql/internal_representation/rewrite_spec.rb
These were regressions introduced in 1.5.0, inefficiencies in validation
=> fix(Rewrite) use a Set to avoid storing duplicate AST nodes

lib/graphql/introspection/input_value_type.rb, lib/graphql/schema/loader.rb, spec/graphql/schema/loader_spec.rb
Oops, apparently they should be `FOO`, not `"FOO"` (which makes sense as the ["String encoding (using the GraphQL language)"](https://facebook.github.io/graphql/#sec-The-__InputValue-Type)). This is what comes from GraphQL js according to #592.
=> fix(defaultValue) serialize and load enum values as bare identifiers

lib/graphql/static_validation/arguments_validator.rb, spec/graphql/static_validation/rules/argument_literals_are_compatible_spec.rb
Oops, the logic previously said "skip if the argument's type is scalar", but this left it broken for enum types as shown in #531. So fix the logic: "skip if the argument's type _isn't_ input object"
=> fix(ArgumentsValidator) ignore input object if the argument's type isn't input object

lib/graphql/static_validation/rules/variable_usages_are_allowed.rb, spec/graphql/static_validation/rules/variables_are_input_types_spec.rb
Oops, previously invalid input would result in a Ruby exception, yuck!
=> fix(validation) don't raise on unknown input type

lib/graphql/schema/build_from_definition.rb, spec/graphql/schema/build_from_definition_spec.rb
Using `#[]` instead of `#fetch` allows hash fallbacks to be used, reducing boilerplate
=> feat(BuildFromDefinition) allow resolver hashes to have defaults

.github/contributing.md
The tricky part here is the "Legal" section, which requires that PR authors transfer copyrights to the maintainer (me) when contributing code. My goal is to make relicensing possible in the future, but it's the distant future. This clause doesn't apply to previous contributions (81 contributors, ~25% of commits), so relicensing would present a serious challenge! However, I'd like to stop making it _harder_. 
The end goal is to provide a software experience like Sidekiq: rock-solid, well-maintained software with good developer support and a sustainable future :) I plant to improve graphql-pro by adding features, but dual-licensing would make easier to upstream some smaller features (eg monitoring, versioned connections) as time goes on, since graphql-pro would have another viable revenue …
=> doc(CONTRIBUTING) Add Sidekiq-like contributing.md

lib/graphql/relay/base_connection.rb, spec/graphql/relay/base_connection_spec.rb
This scrubs out `first: -1` before it hits the connection implementation. In a subsequent PR I may apply max_page_size at the same time, but that will be a bit bigger change.
=> fix(BaseConnection) replace negative pagination args with 0

lib/graphql/define/assign_enum_value.rb, spec/graphql/enum_type_spec.rb
Hello. Thank you for implementing & maintaining graphql-ruby.
I'd like to ensure that names of enum values are strings. I think that passing a symbol for the 2nd argument (`name`) is right since it is also used for the default value of `value`. However, the variant name can't be other than a string in GraphQL-land.
=> Make sure the variant name of an enum is a string

guides/relay/mutations.md
Noticed an inconsistency in the documentation about returning connections in a mutation.
=> Fix docs about returning connections in mutations

lib/graphql/static_validation/rules/variable_usages_are_allowed.rb, spec/graphql/static_validation/rules/argument_literals_are_compatible_spec.rb, spec/graphql/static_validation/rules/variable_usages_are_allowed_spec.rb
Fixes #636 and adds tests for those other cases, which must be short-circuited by `GraphQL::Language::Visitor::SKIP`.
=> fix(VariableUsagesAreAllowed) handle unexpected input objects

lib/graphql/define/instance_definable.rb, spec/graphql/define/instance_definable_spec.rb
This always bugs me, when working on Rails, if you load the schema and there's a configuration error in the schema, you have to restart the server in order to reload properly. 
I think it's an issue with Rails constant loading. The constants _are_ successfully loaded, and their definition blocks are stored for later. Then, the blocks are run, but they get an error and :boom:. The blocks are nullified, so what you're left with is useless instances of GraphQL objects. Blah! 
AFAICT this fixes that issue. If the schema hits an error during loading, it will preserve the definition block and re-run it on the next request.
=> fix(InstanceDefinable) handle errors during definition 

lib/graphql/query/literal_input.rb, spec/graphql/query_spec.rb
Hi,
I created a query type ```fooCollection(uuid: [Uuid!]....)```.
When executing a query like this
```
query bar($uuid: [Uuid!]) {
fooCollection(uuid: $uuid) {
totalCount
edges {
node {
uuid
}
}
}
}
```
with variables ```{uuid: nil}``` the query arguments look like this:
```
#<GraphQL::Query::Arguments:0x00000005468430>
{"uuid"=>nil}
```
Same when executing the query via GraphiQL interface with variables ```{"uuid": null}```. This is what I expected
But when I execute this
```
{
fooCollection(uuid: null) {
totalCount
edges {
node {
uuid
}
}
}
}
```
query arguments is
```
#<GraphQL::Query::Arguments:0x000000054f9700>
{"uuid"=>[nil]}
```
which is not what I expected.
This PR would fix that, but I'm not sure if the fix is at the right place.
=> nil for GraphQL::Language::Nodes::NullValue input

spec/graphql/query_spec.rb
I'm sorry. There is an embarrassing mistake in the specs for #637.
=> Fix query specs for GraphQL::Language::Nodes::NullValue arguments

guides/related_projects.md
GraphQL::QueryResolver is an add-on to graphql-ruby that allows your field resolvers to minimize N+1 SELECTS issued by ActiveRecord.
=> Add graphql-query-resolver

guides/schema/mutations.md, guides/schema/types_and_fields.md
Ok sorry for the last one, that was messy and a bit too hasty.
Here a second attempt to get these docs in order.
In this PR i propose:
- Give mutations its own spot in schema
- Add nested mutations syntax for embedding
=> Give mutation its own section and nested mutations

.rubocop.yml, lib/graphql/execution/execute.rb, lib/graphql/execution/field_result.rb, spec/graphql/execution/execute_spec.rb
This fixes two bugs:
- When a required list member is found to be `nil`, properly backtrack the `nil` to the next nullable field 
- When a nullable list member is `nil`, leave the `nil` in the result.
=> Fix null list members

lib/graphql/relay/mutation.rb
Using `:as` on mutations arguments is ignored:
```ruby
LoginMutation = GraphQL::Relay::Mutation.define do
name 'Login'
input_field :username, !types.String, as: :user_name # The :as option has no effect
input_field :password, !types.String
end
```
=> Fix mutations using :as option on arguments

graphql.gemspec, lib/graphql/execution/lazy/lazy_method_map.rb, lib/graphql/schema.rb, spec/graphql/execution/lazy/lazy_method_map_spec.rb, spec/spec_helper.rb
This mapping of `class => lazy_method_name` was not threadsafe because two threads could run the hash's default value block at the same time, resulting in a modification during enumeration, which is not allowed. 
So, I've wrapped the modifications in a mutex. Key _hits_ in `.get` won't be synchronized, is that safe?
I originally wrote a test for this: 
```ruby 
require "spec_helper"
describe GraphQL::Execution::Lazy::LazyMethodMap do
let(:lazy_method_map) { GraphQL::Execution::Lazy::LazyMethodMap.new }
it "handles multithreaded access" do
a = Class.new
b = Class.new(a)
c = Class.new(b)
lazy_method_map.set(a, :a)
1000.times.map do |i|
Thread.new {
d = Class.new(c)
lazy_method_map.get(d)
}
end.map(&:join)
end
end
```
But on CRuby, I couldn't make it fail without putting an explicit …
=> fix(LazyMethodMap) wrap hash modification with a mutex

.rubocop.yml, lib/graphql/analysis/query_complexity.rb, lib/graphql/compatibility/execution_specification.rb, lib/graphql/compatibility/lazy_execution_specification.rb, lib/graphql/execution/execute.rb, lib/graphql/schema/catchall_middleware.rb, lib/graphql/schema/validation.rb, lib/graphql/static_validation/arguments_validator.rb, lib/graphql/static_validation/rules/operation_names_are_valid.rb, spec/graphql/base_type_spec.rb, spec/graphql/language/lexer_spec.rb, spec/graphql/relay/array_connection_spec.rb, spec/graphql/relay/page_info_spec.rb, spec/graphql/relay/relation_connection_spec.rb, spec/support/dummy/schema.rb
Hello.
I noticed there are some assignments which look unnecessary. I think that removing them makes codes more readable since it avoids unnecessary guessing. That's why I removed some assignments and added [a rule](https://github.com/bbatsov/rubocop/blob/master/manual/cops_lint.md#lintuselessassignment) to `.rubocop.yml`.
Thank you!
=> Remove useless assignments

guides/schema/types_and_fields.md, lib/graphql/argument.rb, lib/graphql/query/literal_input.rb, spec/graphql/argument_spec.rb, spec/graphql/query/literal_input_spec.rb
This is an attempt to implement the argument `prepare` function discussed on https://github.com/rmosolgo/graphql-ruby/issues/540. I'm not too familiar with this code base, so I'm open to any suggestions you may have. 
Also, my specs for `LiteralInput.from_arguments` look more like end-to-end tests than unit tests. Let me know if you'd like to move them to a better spec file or test the feature in a different way.
=> feat(Arguments) accept a prepare function to modify or validate arguments

lib/graphql/input_object_type.rb, spec/graphql/input_object_type_spec.rb
Unless I'm mistaking the intent it appears I've encountered an issue with `false` `default_value`s not being applied. I believe this is because the conditional in `InputObjectType` checks that the coerced value is falsey and not explicitly `nil`, meaning that `false` values are being left behind.
See attached patch for (what I suspect) is the correct behaviour. I think my test might be a bit flimsy so I'm open to suggestions. =)
Thanks!
```ruby
IntroduceShipMutation = GraphQL::Relay::Mutation.define do
name "IntroduceShip"
description "Add a ship to this faction"
input_field :isCoolShip, types.Boolean, default_value: false
return_type types.Boolean
resolve ->(_, inputs, _) { inputs[:isCoolShip] }
end
```
- Considering the above mutation when called with variables `{ "clientMutationId": …
=> Apply default values that are 'false'

.travis.yml
Hello. According to the `.travis.yml`, on 2.2 or later, latest rubies of each minor version have been being used. I've updated them.
=> Test against latest ruby on Travis CI

Appraisals, gemfiles/rails_4.2.gemfile, lib/graphql/execution/lazy/lazy_method_map.rb
Fixes #662 
Before: 
> `NoMethodError: undefined method `each' for #<Concurrent::Map:0x007fdb279f9048>`
After: 
> `✓`
=> Support concurrent-ruby 1.0.0

lib/graphql/schema.rb, lib/graphql/schema/build_from_definition.rb, lib/graphql/schema/loader.rb, spec/graphql/field_spec.rb
Fixes #651 
I don't know why, but raising an error during `Schema.define` causes `Types` to appear in `ActiveSupport::Dependencies.autoloaded_constants` _twice_. As a result, `ActiveSupport.remove_unloadable_constants!` goes into a loop and the server hangs. Sad! 
Moving the `raise` into `#execute` circumvents the issue by allowing the constant to load properly. The user experience _should_ be the same: you can't execute a query on an invalid schema. 
(Technically, this arrangement is a bit more flexible: you _could_ define an invalid schema, then `.redefine` it to become valid. This was impossible before, but obviously it doesn't matter much 😆 )
=> refactor(Schema) raise definition errors lazily to avoid messing with Rails constant loading

lib/graphql/define/assign_object_field.rb, spec/graphql/relay/connection_field_spec.rb
Oops, the accessor was there but I don't think it was ever assigned
Fixes #669
=> Populate Field#function when defined from a function

lib/graphql/internal_representation/node.rb, spec/graphql/internal_representation/rewrite_spec.rb
Oops, `node.definition` raised on root nodes which broke some query analyzers.
=> fix(Rewrite) root nodes have nil definition

guides/relay/mutations.md
Thank you for maintaining such a great gem!
The example code in Relay mutation guide which accessing input fields seems to be not up to date.
Example uses `args` to access input field, but it causes error.
```
NoMethodError (GraphQL::Relay::Mutation can't define 'args'):
```
I think this should to be `inputs`. 🤔
=> Fix accessing input fields in Relay mutations guide

lib/graphql/relay/page_info.rb
According to the [Relay spec](https://facebook.github.io/relay/graphql/connections.htm#sec-undefined.PageInfo.Fields), the `hasNextPage` and `hasPreviousPage` fields in PageInfo require `first` or `last` arguments to be meaningful:
> hasPreviousPage is only meaningful when last is included, as it is always false otherwise. hasNextPage is only meaningful when first is included, as it is always false otherwise. When both first and last are included, both of the fields are set according to the above algorithms, but their meaning as it relates to pagination becomes unclear. This is among the reasons that pagination with both first and last is discouraged.
(NB this was decided [for performance purposes](https://github.com/graphql/graphql-relay-js/issues/58#issuecomment-169542843))
Since this …
=> Add some details to hasNextPage/hasPreviousPage descriptions.

lib/graphql/execution/typecast.rb, lib/graphql/internal_representation.rb, lib/graphql/internal_representation/node.rb, lib/graphql/internal_representation/print.rb, lib/graphql/internal_representation/rewrite.rb, spec/graphql/internal_representation/print_spec.rb, spec/graphql/internal_representation/rewrite_spec.rb, spec/graphql/static_validation/rules/fields_will_merge_spec.rb
Fixes #668 
And in the meantime added a debugging utility, `InternalRepresentation::Print.print(schema, query_str)`. It shows you `Rewrite`'s output which matches actual query execution.
=> Fix fragment scoping, add InternalRepresentation::Print

lib/graphql/interface_type.rb, lib/graphql/object_type.rb, lib/graphql/schema.rb, lib/graphql/schema/instrumented_field_map.rb, lib/graphql/schema/warden.rb, spec/graphql/introspection/type_type_spec.rb
Oops, it was returning fields without instrumentation, not the instrumented fields which are present on `Schema`
=> fix(Warden) return fields with instrumentation

lib/graphql/compatibility/execution_specification.rb, lib/graphql/compatibility/execution_specification/specification_schema.rb, lib/graphql/compatibility/lazy_execution_specification.rb, lib/graphql/compatibility/lazy_execution_specification/lazy_schema.rb, lib/graphql/execution/execute.rb, lib/graphql/execution/field_result.rb, lib/graphql/execution/selection_result.rb, lib/graphql/query/context.rb, lib/graphql/query/serial_execution/field_resolution.rb
This will help on subscriptions, where untriggered root fields will be skipped. I think it'll also help for `@defer`-like behavior where some fields should be entirely absent from the result, but we have to do the skip at runtime in order to have access to the backing `obj`.
__TODO:__
- Improve `SelectionResult#delete` to not be O(n). I'm feeling a lot of pain here in the parallel trees of `Context` and `Result` objects, I think they should be merged.
- Test for lists of scalars? Or this is unsupported for lists? (The whole list must be `ctx.skip`?)
=> Support skipping fields altogether from user code

lib/graphql/string_encoding_error.rb, lib/graphql/string_type.rb, spec/graphql/string_type_spec.rb
Fixes an issue where strings such as "f2f962bd-2216-4c00-a8b0-8f9c71818285"
encoded as ASCII-8BIT would raise GraphQL::StringEncodingError when they
could be easily transcoded.
Strings containing code points that cannot be mapped to UTF-8 will still
raise GraphQL::StringEncodingError.
=> Transcode string results to UTF-8 when possible

lib/graphql/query/context.rb, lib/graphql/schema/timeout_middleware.rb, spec/graphql/query/context_spec.rb
Subscriptions do some query-level bookkeeping and I can simplify the integration between layers by using `context`. However, part of subscription management is dumping & loading `context` as needed. This can become very brittle when your `context` has "other peoples'" values in it. (That is, libraries, instrumentation, middleware, whatever, may have added values to your context hash.)
So, this PR introduces namespaced storage on context: a `Hash<Object => Hash>` where libraries, instrumentation, etc can pick a namespace and store values there in a way that's transparent to user code. There's no code to avoid naming conflicts, but an easy way to ensure nobody is using your namespace is to use the class or module as the key 😆 
As a bonus, this PR throws in better checks for context storage: …
=> feat(Context#namespace) add isolated storage to context, use it for TimeoutMiddleware

lib/graphql/relay/mutation.rb, lib/graphql/relay/mutation/instrumentation.rb, lib/graphql/relay/mutation/resolve.rb, lib/graphql/relay/mutation/result.rb, lib/graphql/schema.rb, spec/support/star_wars/schema.rb
Add an accessor to the derived result object based on `property`, not `field.name`.
Closes #686
=> Fix `property:` on mutation return_fields`

guides/pro/installation.md
Trying to use the old shorthand version of Gem sources results in the following error on recent Bundler versions:
```
[!] There was an error parsing `Gemfile`: The source must be an absolute URI. For example:
source 'https://rubygems.org'. Bundler cannot continue.
>  source "gems.graphql.pro" do
```
=> Fix bundler source URL for pro

lib/generators/graphql/templates/schema.erb, spec/generators/graphql/install_generator_spec.rb
`v0.3.2` includes the `use` functionality
Not sure if the `# GraphQL::Batch setup:` comment is still needed or not?
=> Update graphql-batch usage in generators

guides/schema/code_reuse.md, lib/generators/graphql/templates/function.erb, lib/graphql/function.rb, spec/generators/graphql/function_generator_spec.rb
`types` is exposed in functions as of `1.5.6` (in https://github.com/rmosolgo/graphql-ruby/pull/654)
I figured the whole section on Types wasn't even needed anymore?
=> Function docs: update types usage

lib/graphql/list_type.rb, lib/graphql/non_null_type.rb
Its bugged me that `p GraphQL::STRING_TYPE` gives a nice `String` output while `p !types.String` just prints *nothing* for a strange reason.
It looks like these subclasses forgot to realias the `inspect` method. `p !types.String` now outputs `String!`. 😎
=> Improve pretty print debugging of ListType and NonNullType

lib/graphql/static_validation/definition_dependencies.rb, spec/graphql/query/executor_spec.rb
As per @rmosolgo's wise comment on https://github.com/rmosolgo/graphql-ruby/pull/701#discussion_r114229506.
It turns out operations and fragment names live in separate namespaces. An operation can share a fragments name. I tested and confirmed on the reference implementation (graphql-js) and it does indeed work.
=> Support Operation and Fragment definitions of the same name

lib/graphql/schema.rb, lib/graphql/schema/build_from_definition.rb, spec/graphql/schema/build_from_definition_spec.rb
This adds a callable `parser` option to `from_definition`.
The main use case for changing the default `GraphQL.parse` is if you're using `graphql-libgraphqlparser-ruby`. That gem overrides `GraphQL.parse` which does not support parsing an IDL string.
The workaround for this would be to pass in a callable that uses `GraphQL.parse_without_libgraphqlparser`.
=> BuildFromDefinition: add parser option

lib/graphql/query.rb, spec/graphql/query_spec.rb
This'll be nice for subscriptions where we'll need to re-run the query. It's basically a shortcut to `selected_operation.operation_name`, but you don't have to check whether selected_operation is nil.
=> feat(Query#operation_name) return selected operation name

lib/graphql/schema/build_from_definition.rb, lib/graphql/schema/build_from_definition/resolve_map.rb, lib/graphql/schema/build_from_definition/resolve_map/default_resolve.rb, spec/graphql/schema/build_from_definition_spec.rb
Work in progress! Need some help from @xuorig and @rmosolgo 
In this PR i will try to make resolvemap behave a little more like graphql-tools. I.e. make it easy to build resolvers from a hash much like the JS version - https://github.com/apollographql/graphql-tools. The end goal is to clone all functionality from its Js counterpart for rapid api prototyping.
See for context https://gist.github.com/rmosolgo/ba31acf93f07f8007d99ba365a662d8f#file-app-rb-L126-L174
From this map:
```ruby
Resolvers = {
"Mutation" => {
"incrementCounter" => ->(o, a, c) {
counter = App::Counter.find(a["id"])
counter.increment
API::Schema.subscriber.trigger("counterIncremented", a, counter)
counter
}
},
"Query" => {
"counter" => ->(o, a, c) { App::Counter.find(a["id"]) }
},
"Counter" => {
"value" => ->(o, a, c) { …
```
=> Make resolvemap work more like graphql-tools

lib/graphql/query.rb, spec/graphql/query_spec.rb
While working through subscriptions, I found that my current approach to persisted queries (`GraphQL::Pro::Repository`, which wraps a schema) won't work. 
It won't work because events are triggered on the schema itself, and the schema has no way to access any repositories that wrap it. 
So, this feature will add a much better point for hooking up persisted queries. They can be added as query instrumentation, for example: 
```ruby 
def before_query(query) 
if query.operation_name && !query.query_string 
query.query_string = fetch_from_storage(query.operation_name)
end 
end 
```
A similar approach could be used for an in-memory document cache, although that would need some testing, I'm not sure if `Query#document=` is properly supported!
=> feat(Query) support adding query string after initialization

lib/generators/graphql/type_generator.rb, spec/generators/graphql/object_generator_spec.rb
Thank you for this great gem!
I think it is better to care lower case same as Rails' generator.
For example, `bin/rails g model foo` will generate:
```
class Foo < ApplicationRecord
end
```
=> Camelize type name

lib/graphql/list_type.rb, spec/graphql/list_type_spec.rb
According to the [GraphQL Spec](https://facebook.github.io/graphql/#sec-Lists):
> If the value passed as an input to a list type is not a list and not the null value, it should be coerced as though the input was a list of size one, where the value passed is the only item in the list. This is to allow inputs that accept a “var args” to declare their input type as a list; if only one argument is passed (a common case), the client can just pass that value rather than constructing the list.
As best I can tell, this should apply to both lists of scalars or lists of input objects. One of the recent refactors modified `GraphQL::ListType` so that instead of using `ensure_array(value)`, it would use `Array(value)`.
The problem is that when you pass a hash into the `Array` method, you get the …
=> Fix: List of Input Objects

lib/graphql/relay/connection_resolve.rb, spec/graphql/relay/connection_resolve_spec.rb, spec/support/star_wars/schema.rb
Fixes a problem if you have a field resolver that returns `nil` for a connection.
Otherwise, you get this error: 
```
RuntimeError:
No connection implementation to wrap NilClass ()
```
=> Fix bug when connection is nil

.travis.yml
After fixing the last two remaining bugs in JRuby (https://github.com/jruby/jruby/issues/4564 + https://github.com/jruby/jruby/issues/4555) all tests pass unaltered. 🎉
This pull requests fully enables JRuby on Travis.
=> Fully enable JRuby on Travis

lib/graphql/relay/mutation/instrumentation.rb, lib/graphql/relay/mutation/resolve.rb, spec/graphql/relay/mutation_spec.rb
When a mutation's `resolve` raises or returns a `GraphQL::ExecutionError`, we should nullify the _whole_ object, not just the `return_field`s. 
See the diff of `mutation_spec.rb` to see how the nullability is different. In short, `clientMutationId` will _not_ be present if the mutation has an error. This is inline with Facebook's approach: https://github.com/facebook/relay/issues/360
This was fixed for one case in #722 but other cases should be brought into alignment.
Fixes #723
=> refactor(Relay::Mutation) returning/raising an error makes the result null

lib/graphql/define/instance_definable.rb, spec/graphql/define/instance_definable_spec.rb
I'd like to not necessarily require values when adding my own metadata definitions.
For example, the comment in this file shows
``` ruby
subaru_baja = Car.define do
all_wheel_drive true
end
```
Wouldn't it be much nicer like this? 😀 
``` ruby
subaru_baja = Car.define do
has_all_wheel_drive
end
```
=> Permit valueless definitions

lib/graphql/relay/connection_instrumentation.rb, lib/graphql/relay/connection_resolve.rb, lib/graphql/schema.rb, spec/graphql/relay/connection_resolve_spec.rb, spec/support/star_wars/data.rb, spec/support/star_wars/schema.rb
Oops, `Connection#parent` was broken when you used a `GraphQL::Batch::Promise` as the connection's `nodes`. 
This meant that if you try to use the parent object's `counter_cache` to implement a `totalCount` field, you're gonna have a bad time.
=> fix(ConnectionResolve) preserve parent when nodes is a lazy object

CHANGELOG.md, lib/graphql/relay/array_connection.rb, lib/graphql/relay/relation_connection.rb, lib/graphql/version.rb, spec/graphql/relay/array_connection_spec.rb, spec/graphql/relay/page_info_spec.rb, spec/graphql/relay/relation_connection_spec.rb
Fix the ArrayConnection to work as described in the Relay Connection spec.
* Both `before` and `after` can be specified now.
* Both `first` and `last` can be specified now. Note that doing so is discouraged and the result is confusing.
This also fixes an issue where `max_page_size` in combination with `before` and no `last` would return results from the end of the list instead of from the beginning.
=> Fix ArrayConnection and RelationConnection issues

spec/support/star_wars/schema.rb
This change just follows what the error message says, upgrading to the newer syntax.
I encountered this error when working on #742, and it was a simple straight-forward fix.
=> fix(spec): Update usage of Sequel in test schema

lib/graphql/query.rb, spec/graphql/query_spec.rb
Oops, #707 and #710 didn't play nicely together. If you checked for `#operation_name`
but query string wasn't present yet, it would raise an error.
Instead, return the user-provided value as `#operation_name` and return
the inferred value as `#selected_operation_name`.
=> fix(Query#operation_name) return provided value, add #selected_operation_name

lib/graphql/relay/relation_connection.rb
The error was NameError: uninitialized constant ActiveRecord.
=> Prevent name error when ActiveRecord not exists.

guides/fields/arguments.md
As per https://github.com/rmosolgo/graphql-ruby/pull/730, Argument prepare functions receive the context as a second argument. This PR updates the guides to reflect this change.
=> fix(Argument#prepare) guides to reflect 1.6.0 changes

lib/graphql/execution/multiplex.rb, lib/graphql/query/executor.rb, lib/graphql/schema.rb, spec/graphql/query_spec.rb
Oops, adding Schema#multiplex bypassed this altogether!
=> fix(Schema#query_execution_strategy) support custom strategy when running 1 query

lib/graphql/query.rb, spec/graphql/query_spec.rb
Since adding lazy AST preparation, I missed a couple of attributes which depend on the AST.
So this ensures that it's been prepared before trying to check it.
=> fix(Query#mutation? Query#query?) fix op-type methods to load AST

guides/relay/connections.md, lib/graphql/relay/base_connection.rb, lib/graphql/schema.rb, spec/graphql/relay/array_connection_spec.rb, spec/graphql/relay/relation_connection_spec.rb, spec/support/star_wars/schema.rb
https://github.com/rmosolgo/graphql-ruby/issues/751
Usage:
```ruby
MySchema = GraphQL::Schema.define do
default_max_page_size 100
end
```
For any relation where `max_page_size` is not defined, or if it is `nil`, the `default_max_page_size` will be used instead.
Also, partially for my own benefit, here's the complete list of bases in order:
| Name | Cursor |
| -----|-------|
| Yavin      | MQ==       |
| Echo Base | Mg== |
| Secret Hideout | Mw== |
| Death Star | NA== |
| Shield Generator | NQ== |
| Headquarters | Ng== |
(Yavin being the first base, Headquarters being the last).
=> Implement "default_max_page_size"

lib/graphql/execution/execute.rb, spec/support/dummy/data.rb
This is to support cases when `#==(other)` doesn't support comparison with arbitrary objects.
Sure, it should be fixed in application code, but I also want to reduce the burden for people who are upgrading. It's a nasty surprise to find this issue!
=> fix(Execute) use .is_a?(Skip) instead of ==(Skip) to avoid touching user code

lib/graphql/backwards_compatibility.rb, lib/graphql/schema/middleware_chain.rb
* Adds support fo `Method` to `get_arity`.
* Updates MiddlewaChain to use `BackwardsCompatibility.get_arity`
=> BackwardsCompatibility arity check: support Method

lib/graphql/execution/multiplex.rb, lib/graphql/schema.rb, spec/graphql/query_spec.rb
Oops, if you overrode _one_ strategy but not _all_ of them, you'd get `undefined method "new" for NilClass`
cc @swalkinshaw
=> fix(Multiplex) correctly check for any overridden execution strategy

lib/graphql/compatibility/lazy_execution_specification.rb, lib/graphql/execution/execute.rb, spec/graphql/execution/multiplex_spec.rb
This behavior of eager execution was not properly implemented in lazy execution
=> fix(Execute) if a lazy returns an invalid null, stop running its siblings

lib/graphql/schema/printer.rb, spec/graphql/base_type_spec.rb, spec/graphql/schema/build_from_definition_spec.rb, spec/graphql/schema/printer_spec.rb
Sorts fields, arguments, etc. by name when printing the IDL. (In my code base, these are getting flip-flopped around sometimes).
I think this is justified by the spec:
- [Arguments are unordered](http://facebook.github.io/graphql/#sec-Language.Arguments)
- [Input object fields are unordered](http://facebook.github.io/graphql/#sec-Input-Object-Values)
There isn't a statement in the spec for some of the other items, but it seems safe.
=> Stable Schema Printing

.rubocop.yml
When running Rubocop you'll get these warnings:
```
.../src/graphql-ruby/.rubocop.yml: Style/EmptyLineBetweenDefs has the wrong namespace - should be Layout
.../src/graphql-ruby/.rubocop.yml: Style/IndentationWidth has the wrong namespace - should be Layout
.../src/graphql-ruby/.rubocop.yml: Style/LeadingCommentSpace has the wrong namespace - should be Layout
.../src/graphql-ruby/.rubocop.yml: Style/SpaceInLambdaLiteral has the wrong namespace - should be Layout
```
This PR fixes the namespace and resolves the warnings.
=> Resolves RuboCop namespace warnings

lib/graphql/query.rb, lib/graphql/query/validation_pipeline.rb, lib/graphql/static_validation/validator.rb, spec/graphql/query_spec.rb, spec/graphql/static_validation/validator_spec.rb
You can save a few ms if you know for sure that your query is valid (eg, static queries which were validated in development/test, as with github/graphql-client)
If you run an invalid, lots of safeguards are thrown out the window:
- Fields which should be hidden by `only:`/`except:` may be visible 
- Runtime errors will probably happen 
The validation step involves a full visit to the AST, we can't skip that because we have to do a rewrite to InternalRepresentation. Soon, I will refactor that step to be static, so you can run it at build-time and never parse/visit the AST again :)
=> fix(Query validate: false) support skipping validation to live on the wild side

lib/graphql/query/serial_execution/field_resolution.rb
I made this patch to Execution in #761 but i forgot to make the same patch here!
=> fix(SerialExecution) use .is_a? to avoid calling user-defined #==

lib/generators/graphql/templates/graphql_controller.erb, spec/generators/graphql/install_generator_spec.rb
For multi-operation queries, GraphQL Controller throws error on default executor template:
```json
{
"errors": [
{
"message": "An operation name is required"
}
]
}
```
In case of `operationName` sent by client in the query with multi-operation queries, pass `operation_name` to `execute` to avoid this error.
```graphql
query getDiscounts {
discounts {
name
}
}
query getEmployees {
employees {
first_name
}
}
```
I'm sending this query with `operationName=getEmployees` and get the error above. Solved passing `operationName` to the `execute` method. This change may help others not to face this issue again.
=> Add operation name for multiple operation queries.

lib/graphql/input_object_type.rb, spec/graphql/query/variables_spec.rb
Gem would crash when an InputObject variable was provided an array as a value:
```
gems/graphql-1.6.3/lib/graphql/input_object_type.rb:136[]	
gems/graphql-1.6.3/lib/graphql/input_object_type.rb:136block in validate_non_null_input	
gems/graphql-1.6.3/lib/graphql/input_object_type.rb:135each	
gems/graphql-1.6.3/lib/graphql/input_object_type.rb:135map	
gems/graphql-1.6.3/lib/graphql/input_object_type.rb:135validate_non_null_input
```
https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/input_object_type.rb#L108-L122
The Input Object class validates that the provided value responds to `to_h` or `to_unsafe_h` (Parameters). However, `Array` does respond to `to_h`, but `array["string"]` would cause the error to happen.
Instead of checking for `to_h`. This PR assigns the value of the …
=> fix(variables) Fix error when InputObjectType receives array as provided value

lib/graphql/execution/execute.rb, spec/graphql/query/literal_input_spec.rb
This change fixes #798, but also improves the error and data results from synchronous queries.  Specifically, errors that happen during argument preparation get path info now, and also less of the result is nil'ed out.
=> improve error handling in argument prepare procs

guides/fields/arguments.md
I was looking for the DSL syntax to add a default value for a field argument and couldn't find it in the docs. This patch adds a quick usage example to the [field arguments docs](http://graphql-ruby.org/fields/arguments.html).
=> Document usage of default_value for field argument

lib/graphql/execution/multiplex.rb, lib/graphql/schema.rb, spec/graphql/analysis/max_query_complexity_spec.rb
#774 
I cherry picked the failing test from #804 
Much to my surprise it appears the analyzer in the test was being run twice! If I understand things correctly, there's an analyzer being run for the query itself (analyzer no. 1) and an analyzer being run for the collection of all queries -- the multiplex -- (analyzer no. 2). It was this second analyzer that was causing the failure described in #774, as it could not be overridden by providing arguments to `execute`, and so would always default to the schema defined `max_complexity`. 
The analyzer no. 2, the one for the multiplex, gets added here: https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/execution/multiplex.rb#L165
So, yes. A lot of figuring out, very little actual code changes :smile: . The issue is fixed by passing …
=> Fix 774: cannot increase max complexity at query time

lib/graphql/argument.rb, spec/graphql/argument_spec.rb
When using `as` and `prepare` in argument blocks, they were overwritten by
the default values:
```ruby
argument :fooBar, types.String do
as :foo_bar # will be overwritten by the default value (nil)
end
```
=> Fix bug concerning `as` and `prepare` on arguments

lib/graphql/argument.rb, lib/graphql/define.rb, lib/graphql/define/defined_object_proxy.rb, lib/graphql/define/no_definition_error.rb, spec/graphql/argument_spec.rb, spec/graphql/define/assign_argument_spec.rb, spec/graphql/define/instance_definable_spec.rb, spec/spec_helper.rb
Oops, custom definitions were not accepted as keywords, only with a block! Now, custom definitions can also be passed as keywords.
=> fix(Argument.accepts_definitions) accept custom keywords

lib/generators/graphql/core.rb, lib/generators/graphql/install_generator.rb, lib/generators/graphql/mutation_generator.rb, lib/generators/graphql/templates/mutation.erb, lib/generators/graphql/templates/mutation_type.erb, lib/generators/graphql/templates/schema.erb, readme.md, spec/generators/graphql/install_generator_spec.rb
Currently a work in progress for #769 
There is a pretty major change here, in that I'm no longer using NamedBase for the mutation generator. Considering that if you're to do: `rails g graphql:mutation createUser` you get the wrong output.
Now if you do:
```
rails g graphql:mutation createUser
rails g graphql:mutation CreateUser
rails g graphql:mutation Create_User
rails g graphql:mutation create_user
```
All will now result in the exact same mutation being created. The field added to the root will be the lower-camelcase of the NAME, the module will be upper-camelcase of the NAME, and the file name will be lower-underscore-case of the NAME. This makes the output more reliable a predictable.
p.s., don't look at the code to NamedBase, it's confusing because it's so messy. A lot of the rails …
=> WIP: Improved mutation generator

guides/queries/mutations.md
I believe this is the more consistent naming used throughout the guide.
=> Consistent root type naming in code examples

lib/graphql/enum_type.rb, spec/graphql/enum_type_spec.rb
Raises an exception when trying to add a value that already exists with the same name.
From the [spec](https://facebook.github.io/graphql/#sec-Enum):
> There must be at least one and they must have unique names.
Two questions:
1. is this a good place for the validation or should it be done during schema validation?
2. is there a better existing exception to raise?
=> Enforce EnumValue name uniqueness

lib/graphql/base_type.rb, lib/graphql/execution/execute.rb, lib/graphql/interface_type.rb, lib/graphql/union_type.rb, spec/graphql/introspection/schema_type_spec.rb, spec/graphql/union_type_spec.rb, spec/support/dummy/data.rb, spec/support/dummy/schema.rb
This feature allows a union type to resolve to more specific types when handling a value. This is useful when working with objects that may fit into multiple types. When executing the query
will call `resolve_type(value, field_ctx)` on either Unions or Interfaces.
Union type's call can be definable via `resolve_type ->(value, ctx) { }`. Interface type's call returns `ctx.query.resolve_type(value)` which is the default implementation for resolving both types.
- Added a new test that raises an error if a returned type is not within possible_types
- Added an implementation in the dummy schema, though I would consider altering this by adding a new type derived from MilkType (for example KefirType) in which it is re-casted as a MilkType - but this would alter a significant portion of other …
=> Add UnionType#resolve_type for more ganular control in unions

guides/schema/lazy_execution.md
Disclaimer: I'm an author.
[facebook/dataloader](https://github.com/facebook/dataloader) accepted my solution as alternative implementation of their library, so I though I could add it here as well.
Dataloader tries to mimic facebook/dataloader api as best as possible. In contrast to `batch-graphql` it offers more general solution that can be used even without graphql-ruby. The loaders created with `dataloader` also compose better as their return type is A+ [promise](https://github.com/lgierth/promise.rb).
EDIT: Link for better access:
https://github.com/sheerun/dataloader
=> Mention dataloader as other batching solution

guides/related_projects.md
`SearchObject::Plugin::GraphQL` is a plugin for [SearchObject](https://github.com/rstankov/SearchObject), for defining search resolvers. 
Example:
```ruby
class PostResolver
include SearchObject.module(:graphql)
type types[PostType]
scope { Post.all }
option(:name, type: types.String)       { |scope, value| scope.where name: value }
option(:published, type: types.Boolean) { |scope, value| value ? scope.published : scope.unpublished }
end
```
=> Add search_object_graphql to related projects list.

lib/graphql/query.rb, lib/graphql/query/context.rb, spec/graphql/query/context_spec.rb, spec/graphql/query_spec.rb
- Allow operation_name to be assigned later 
- Don't `raise` if there's no operation name; return a client error instead
- Support query-level errors with `query.context.add_error(err)`
=> More flexibility with query string / operation_name

lib/graphql/compatibility/lazy_execution_specification.rb, lib/graphql/execution/field_result.rb, lib/graphql/execution/lazy/resolve.rb, spec/graphql/execution/lazy_spec.rb
This issue was identified in https://github.com/Shopify/graphql-batch/pull/58. 
graphql-ruby's implementation of batching missed a feature of graphql-batch's implementation. Consider a query like this: 
```
field1 {
field {
batchMe 
}
}
field2 {
field {
batchMe 
}
}
```
Previously, these fields were not properly batched. 
Now, "cousin" fields (that is, children of siblings) are batched to any level.
=> fix(Lazy) resolve cousin fields in the same pass

lib/graphql/backwards_compatibility.rb, lib/graphql/compatibility/execution_specification/counter_schema.rb, lib/graphql/compatibility/execution_specification/specification_schema.rb, lib/graphql/interface_type.rb, lib/graphql/query.rb, lib/graphql/schema.rb, lib/graphql/schema/build_from_definition.rb, lib/graphql/schema/build_from_definition/resolve_map.rb, lib/graphql/schema/loader.rb, lib/graphql/union_type.rb, spec/graphql/analysis/query_complexity_spec.rb, spec/graphql/interface_type_spec.rb, spec/graphql/introspection/schema_type_spec.rb, spec/graphql/introspection/type_type_spec.rb, spec/graphql/object_type_spec.rb, spec/graphql/query/executor_spec.rb, spec/graphql/query/serial_execution/value_resolution_spec.rb, spec/graphql/relay/mutation_spec.rb, spec/graphql/schema/build_from_definition_spec.rb, spec/graphql/schema/loader_spec.rb, spec/graphql/schema/printer_spec.rb, spec/graphql/schema/traversal_spec.rb, spec/graphql/schema/warden_spec.rb, spec/graphql/schema_spec.rb, spec/graphql/union_type_spec.rb, spec/spec_helper.rb, spec/support/dummy/data.rb, spec/support/dummy/schema.rb, spec/support/star_wars/schema.rb
This is the interface equivalent of #829 
Also, it changes the signature of `Schema#resolve_type`, so you should migrate code from: 
```ruby
MySchema = GraphQL::Schema.define do 
resolve_type ->(obj, ctx) { ... }
end 
```
to: 
```ruby
MySchema = GraphQL::Schema.define do 
resolve_type ->(type, obj, ctx) { ... }
end 
```
=> feat(InterfaceType) add type-level resolve_type support

lib/graphql/static_validation/rules/variable_usages_are_allowed.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/839
It looks like active_support happens to be included in the tests, which is why
this succeeded in the first place. Nevertheless, we want to avoid this dependency!
Introduced in https://github.com/rmosolgo/graphql-ruby/pull/824
=> fix: remove usage of Rails' Array.wrap

lib/graphql/relay/relation_connection.rb, spec/graphql/relay/relation_connection_spec.rb
Sometimes ActiveRecord gets a really tricky query, but then `.count` fails. So we have to specify `count(:all)` which overrides other selected fields and runs `COUNT(*)` instead.
TODO:
=> fix(RelationConnection) correctly count when ActiveRecord has already added an alias

lib/graphql/input_object_type.rb, spec/graphql/query/arguments_spec.rb
When using `prepare` in a nested input type, the provided block wasn't called. This PR fixes it.
=> Prepare arguments for nested input types

lib/graphql/schema.rb, lib/graphql/schema/build_from_definition.rb, spec/graphql/schema_spec.rb, spec/support/magic_cards/schema.graphql
Support a `.graphql` filepath in `Schema.from_definition`, cherry-picked from #810
=> feat(Schema.from_definition) support loading schema from file path

guides/schema/lazy_execution.md
Hey @rmosolgo!
I created a new gem called [batch-loader](https://github.com/exAspArk/batch-loader) which helps to avoid N+1 queries. I saw the repository was already starred by you 💛 
I'd like to add it to your list. In addition to the detailed description in [README](https://github.com/exAspArk/batch-loader) I also created a small presentation. I'm using the [slides](https://speakerdeck.com/exaspark/batching-the-powerful-way-to-solve-n-plus-1-queries-every-rubyist-should-know) to describe to my internal team why the gem was created and how it can be used even in existing legacy applications during the migration from REST APIs to GraphQL. Would be happy to receive your feedback :)
In the PR I moved the gems below your simple and very helpful example. I left them in FIFO order, but can …
=> Add batch-loader as a gem for batching

lib/graphql/static_validation/rules/fields_will_merge.rb, spec/graphql/static_validation/rules/fields_will_merge_spec.rb
oops, the short whitelist of node classes here didn't include input objects. better to just use `to_query_string` since it's supported across the board!
=> fix(FieldsWillMerge) handle input objects properly

lib/graphql/relay/relation_connection.rb, spec/graphql/relay/relation_connection_spec.rb
Sequel, contrarily to ActiveRecord, does not support `limit(0)` queries
and raises a `Sequel::Error` instead.
To fix this, we need to deal with this differently by using `where(false)`
instead when we are attempting to perform a query for zero rows in Sequel.
Fixes #887
=> Fix Sequel::Error when limit is 0

lib/graphql/static_validation/rules/arguments_are_defined.rb, spec/graphql/static_validation/rules/arguments_are_defined_spec.rb
The `node` reported when an error occurs in `ArgumentsAreDefined` seems incorrect.
Suppose the `cheese` field does not accept the argument `silly` we currently report this error:
```graphql
query getCheese {
cheese(silly: false, id: 2) { source }
^^^^^^
}
```
In reality I think we want:
```graphql
query getCheese {
cheese(silly: false, id: 2) { source }
^^^^^
}
```
I'm not sure if this was intentional, but with this fix we are more aligned with the reference implementation: https://github.com/graphql/graphql-js/blob/6953f9714b785bbcd89f0103fd73401c06d5f6fe/src/validation/__tests__/KnownArgumentNames-test.js#L118-L126
cc @rmosolgo
=> Use argument node instead of parent in ArgumentsAreDefined errors

guides/relay/object_identification.md
I assume `nodes` here is a typo otherwise it should define `GraphQL::Relay::Node.plural_field`.
=> plural nodes is not correct here

lib/graphql/execution/multiplex.rb, lib/graphql/query.rb, lib/graphql/query/result.rb, spec/graphql/query/result_spec.rb
Sometimes you need query-related data, but `Schema#execute` returns a hash. You can work around this using `Query#result`, but then you can't do multiplexing. So, let's attach query data to the `Query::Result`.
Specifically, I need this for subscriptions: after running a query, we should open a channel for updates if `result.query.subscription?`
=> feat(Query::Result) add a first-class result object

guides/relay/object_identification.md
Documentation has the older/deprecated syntax. I changed the example to something a bit more OO.
Thanks for the great gem and documentation!
=> documentation has Schema#resolve_type deprecation warning

guides/operation_store/authentication.md, guides/operation_store/client_workflow.md
I'm going to add subscription client implementations to this JS project, so I want to rename it to be more general
=> refactor(js-client) rename to graphql-ruby-client

lib/graphql/relay/relation_connection.rb
Fixes #899 
This PR changes `has_next_page` to first check the length of `paged_nodes` to see if its less than the number of entities requested through `first` to avoid a separate COUNT query when know from the `paged_nodes` query that there is no next page.
The only negative performance impact is that in the rare case `hasNextPage` is called without `edges` the full paged nodes query will be run instead of just a COUNT query.
In a future optimization, we could possibly request `last + 1` nodes and avoid the COUNT(*) query altogether.
=> Fix unnecessary `hasNextPage` COUNT() query

lib/graphql/relay/relation_connection.rb, spec/graphql/relay/relation_connection_spec.rb, spec/support/star_wars/data.rb, spec/support/star_wars/schema.rb
_EDIT: mixed up less than / greater than_
A query where `last` is bigger than the # of sliced nodes causes the offset to be negative, which throws an error in Postgres.  Example of a problematic query:
```
query {
users(last: 10) {  # PG will throw an error if there are less than 10 users
edges {
...
}
}
}
```
This was not caught earlier because the tests all use a very small `max_page_size` of 2 or 3 against queries that return 6+ nodes so `relation_count(items) - last` was always positive.  I added tests that use a `max_page_size` of 1000.
Note that this will only catch the problem when the tests are run with `POSTGRESQL=true` since it is postgres that throws the error, not rails.  In sqlite, a negative offset is evaluated as 0 instead of throwing an error.
=> Fix negative offset error in postgres with `last` argument

lib/graphql/query.rb, spec/graphql/query_spec.rb
Noticed Query would 💥 in two places when a query with no operations is executed, for example a query with only comments.
=> Fix selected operation name when there are no selections in a query

guides/fields/limits.md
without this, I was seeing:
```
TypeError:
no implicit conversion of nil into String
```
=> update limits guide to include the context parameter

lib/generators/graphql/templates/mutation_type.erb
This PR fixes the following issue:
**Issue**
1. rails new graphql-app
2. cd 
2. add the `gem 'graphql'` to the `Gemfile`
3. bundle update
4. rails db:create
5. rails db:migrate
6. open http://localhost:3000
7. The following issue appears in the right side of the `GraphiQL` browser:
```
invariant@http://localhost:3000/assets/graphiql/rails/graphiql-0.11.2.self-c0b0dd0bd735a2c1f549e8d44e329b9a8b227cfffca61119d2e71d3f38740b4d.js?body=1:24809:20
defineFieldMap@http://localhost:3000/assets/graphiql/rails/graphiql-0.11.2.self-c0b0dd0bd735a2c1f549e8d44e329b9a8b227cfffca61119d2e71d3f38740b4d.js?body=1:28078:27
getFields@http://localhost:3000/assets/graphiql/rails/graphiql-0.11.2.self-c0b0dd0bd735a2c1f549e8d44e329b9a8b227cfffca61119d2e71d3f38740b4d.js?body=1:28035:58 …
```
=> Add default mutation field

lib/graphql/unresolved_type_error.rb, spec/graphql/query/serial_execution/value_resolution_spec.rb
Adds a bit more information on how to fix an `UnresolvedTypeError` by hinting to `type_from_object` and displaying the value trying to be resolved to a type.
I've seen confusion from teammates trying to implement Interfaces and unions and we've added similar errors, thought it might be useful here too 🤷‍♂️
=> Add more information in UnresolvedTypeError message

lib/graphql.rb
This workaround was added in a hurry, but I think we really only need to use it for non-2.4.0 Ruby versions.
=> refactor(GraphQL::Delegate) use Forwardable for non-2.4.0 versions

lib/graphql/field.rb
If warnings are turned on when parsing an IDL, the following errors are spat out:
```
/Users/gjtorikian/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/graphql-1.6.7/lib/graphql/field.rb:194: warning: instance variable @edge_class not initialized
/Users/gjtorikian/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/graphql-1.6.7/lib/graphql/field.rb:194: warning: instance variable @edge_class not initialized
/Users/gjtorikian/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/graphql-1.6.7/lib/graphql/field.rb:194: warning: instance variable @edge_class not initialized
/Users/gjtorikian/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/graphql-1.6.7/lib/graphql/field.rb:194: warning: instance variable @edge_class not initialized
/Users/gjtorikian/.rbenv/versions/2.4.0/lib/ruby/gems/2.4.0/gems/graphql-1 …
```
=> Define a default `nil` @edge_class

lib/graphql/schema/build_from_definition.rb, spec/graphql/schema/build_from_definition_spec.rb
When using ` GraphQL::Schema.from_definition`, it seems that `connection?` is always `false`. I've added a failing test, but have yet to find a root cause.
=> `connection?` is not properly set when parsing the IDL

lib/graphql/argument.rb, spec/graphql/argument_spec.rb, spec/graphql/define/assign_argument_spec.rb
https://github.com/rmosolgo/graphql-ruby/issues/933
Allows defining an argument from an existing argument a bit like it's already possible with fields.
=> Existing argument def

lib/graphql/query.rb, spec/graphql/query_spec.rb
As reported in https://github.com/rmosolgo/graphql-ruby/issues/956
This PR does the quick fix to avoid the inconsistency in `GraphQL::Query` at runtime to avoid breaking changes.
=> Raise when both query string and document are provided to Query

lib/graphql/compatibility/execution_specification.rb, lib/graphql/relay/connection_resolve.rb
oops, this is used in implementing GitHub's `rateLimit(dryRun: true)`, but we discovered this bug.
=> fix(Relay::Connection) properly skip connections when ctx.skip

lib/graphql/backtrace/inspect_result.rb, lib/graphql/backtrace/table.rb, lib/graphql/relay/base_connection.rb, lib/graphql/relay/edge.rb, spec/graphql/backtrace_spec.rb, spec/graphql/relay/base_connection_spec.rb, spec/graphql/relay/edge_spec.rb
Took a serious look at hooking this up with github, found issues 😬  
Also I took a quick look at performance. First, I ran the query benchmark in this gem source: 
<p><details>
<summary>Before</summary>
<pre>
~/code/graphql-ruby $ be rake bench:query
query     2.000  i/100ms
query     24.588  (± 8.1%) i/s -    124.000  in   5.068650s
~/code/graphql-ruby $ be rake bench:query
query     2.000  i/100ms
query^[[A     25.837  (± 3.9%) i/s -    130.000  in   5.042497s
~/code/graphql-ruby $ be rake bench:query
query     2.000  i/100ms
Calculating …
=> Backtrace improvements

.gitattributes, guides/javascript_client/sync.md, javascript_client/__tests__/__snapshots__/syncTest.js.snap, javascript_client/__tests__/project/frag_4.graphql, javascript_client/__tests__/project/op_3.graphql, javascript_client/__tests__/project/op_isolated_1.graphql, javascript_client/__tests__/project/op_isolated_2.graphql, javascript_client/__tests__/syncTest.js, javascript_client/cli.js, javascript_client/sync/__tests__/__snapshots__/prepareIsolatedFilesTest.js.snap, javascript_client/sync/__tests__/__snapshots__/prepareProjectTest.js.snap, javascript_client/sync/__tests__/prepareIsolatedFilesTest.js, javascript_client/sync/__tests__/prepareProjectTest.js, javascript_client/sync/addTypenameToSelectionSet.js, javascript_client/sync/index.js, javascript_client/sync/prepareIsolatedFiles.js, javascript_client/sync/prepareProject.js
This should fix #961, by adding a new `--add-typename` option on the `graphql-ruby-client` CLI.
We're taking advantage of the work that [apollo-client](https://github.com/apollographql/apollo-client/blob/fec6457746b1cb63c759f128349e66499328ae43/src/queries/queryTransform.ts#L22-L56) has for adding the typenames to a GraphQL AST.
I've added this approach to both the project and isolated approaches.
I've refactored the isolated approach to take advantage of the visitor approach with `graphql`.
I've added and refactored tests in `graphql-ruby-client` to take advantage of [jest's snapshot testing](https://facebook.github.io/jest/docs/en/snapshot-testing.html).
-----
Side note, I haven't actually done a _full end-to-end_ test on my application yet as I was waiting for #959 (which has since …
=> Fix #961 Expose typename in persisted query sync

lib/graphql/input_object_type.rb, lib/graphql/query/arguments.rb, lib/graphql/query/literal_input.rb, spec/graphql/query/arguments_spec.rb
Oops, I realized I left one race condition in this code, `@args_class ||=`. So I refactored to build the class eagerly instead of lazily. (In fact, I didn't experience a bug from this, but I noticed it while chasing something unrelated.)
=> refactor(Query::Arguments) remove intermediary StaticArguments class

lib/graphql/schema/traversal.rb, spec/graphql/introspection/type_by_name_field_spec.rb
What a beast, if an instrumentation copied `__type`, it would not get an arguments class, resulting in a runtime error, no method on `nil`. I didn't update the traversal code properly in working on this feature!
=> fix(Traversal) don't apply instrumentation to Query.__type

lib/graphql.rb, lib/graphql/coercion_error.rb, lib/graphql/scalar_type.rb, lib/graphql/static_validation/rules/argument_literals_are_compatible.rb, spec/graphql/static_validation/rules/argument_literals_are_compatible_spec.rb
Closes #981
Error messages for invalid scalar input values were statically set during validation.
This allows for a scalar to raise a `GraphQL::CoercionError` within `coerce_input` and its error message will be used in the error response.
=> Support custom coercion error messages for scalars

guides/queries/backtrace_annotations.md, guides/queries/tracing.md, lib/graphql.rb, lib/graphql/analysis/analyze_query.rb, lib/graphql/backtrace.rb, lib/graphql/execution/execute.rb, lib/graphql/execution/lazy/resolve.rb, lib/graphql/execution/multiplex.rb, lib/graphql/language/parser.rb, lib/graphql/language/parser.y, lib/graphql/query.rb, lib/graphql/query/context.rb, lib/graphql/schema.rb, lib/graphql/static_validation/validator.rb, lib/graphql/tracing.rb, spec/graphql/analysis/analyze_query_spec.rb, spec/graphql/backtrace_spec.rb, spec/graphql/execution/execute_spec.rb, spec/graphql/language/parser_spec.rb, spec/graphql/static_validation/validator_spec.rb, spec/graphql/tracing/active_support_notifications_tracing_spec.rb, spec/graphql/tracing_spec.rb, spec/spec_helper.rb, spec/support/star_wars/schema.rb
A shortcoming of the previous `GraphQL::Tracing` implementation was that adding and removing tracers was not threadsafe. There was no way to add a trace to _one_ query without messing with any other currently-running queries. 
This new approach supports tracers at schema- and query-level, and uses that new support for query-level backtrace annotation via `context {..., backtrace: true}` (or schema-level with `use GraphQL::Backtrace`).
This way, tracers with a perf hit can be applied in cases where they are really necessary _without_ impacting other cases.
=> Thread-safe, per-query tracers

lib/graphql/execution_error.rb, spec/graphql/execution_error_spec.rb, spec/graphql/introspection/schema_type_spec.rb, spec/support/dummy/schema.rb
There are cases where I'd like to add an arbitrary data structure to error objects, like `{ "code": "payment_required" }`.
What do you think of it?
=> Add options parameter to GraphQL::ExecutionError

guides/operation_store/getting_started.md
A quick approach for locking down the provided graphql-pro's UI is to
use basic auth. Adding a section to the `Authorizing the UI` section to
present both the Rails Routing Constraints and Rack Basic Auth.
=> Add section on using Rack::Auth::Basic for UI

lib/graphql/relay/relation_connection.rb
This is already inside an `if after` block so this condition is redundant and always evaluates to true.
Unless there's some side effect I'm missing 😃
=> remove redundant 'if after'

spec/dummy/app/views/pages/show.html, spec/dummy/test/system/action_cable_subscription_test.rb
I'm still getting the hang of how to do subscriptions over ActionCable. 
This adds a new step to the test case: after making two subscriptions and triggering them separately, also unsubscribe one of them. Make sure the unsubscribed channel doesn't get more updates, but the still-subscribed one does.
=> test(ActionCableSubscriptions) test partial unsubscribe

spec/dummy/Gemfile, spec/dummy/config/application.rb
I wanted to try out the Dummy app inside the `spec` folder, but I wasn't able to run `bundle exec rails server` due to the missing gems, and because Puma was required when it shouldn't.
=> Make dummy app work

lib/graphql/backtrace/inspect_result.rb, lib/graphql/backtrace/table.rb
While running the Shopify codebase through [Mirrors](https://github.com/Shopify/mirrors), I hit a snag that caused it to blow up when trying to `inspect` the `GraphQL::Backtrace::InspectResult` module. This is because that module's `inspect` definition has an arity of 1, where the assumed arity of inspect is always 0.
This PR renames `Backtrace::InspectResult.inspect` to `Backtrace::InspectResult.inspect_result`, so that the default definition of `inspect` still exists on the object.
The [current implementation](https://github.com/rmosolgo/graphql-ruby/blob/b9433c3f5ce1554a2b37329d3eca467c02f066ba/lib/graphql/backtrace/inspect_result.rb#L8) of `Backtrace::InspectResult.inspect` (introduced in https://github.com/rmosolgo/graphql-ruby/pull/946) accepts an object to interpret and stringify, …
=> Rename Backtrace::InspectResult.inspect to .inspect_result

spec/graphql/field_spec.rb
Also ensure we test using respond_to?(:call) instead of its class.
If you think testing with a class is unnecessary I can create another PR with just with just the assertion change.
=> Test GraphQL::Field#resolver_proc with a class.

guides/fields/introduction.md
No hint or doc on this magical option which can be used instead of rewriting `resolve` with a lambda or resolver class
=> Add usage example for `hash_key` option for `field` definition

lib/generators/graphql/core.rb, lib/generators/graphql/enum_generator.rb, lib/generators/graphql/function_generator.rb, lib/generators/graphql/install_generator.rb, lib/generators/graphql/interface_generator.rb, lib/generators/graphql/loader_generator.rb, lib/generators/graphql/mutation_generator.rb, lib/generators/graphql/object_generator.rb, lib/generators/graphql/type_generator.rb, lib/generators/graphql/union_generator.rb, spec/generators/graphql/install_generator_spec.rb, spec/generators/graphql/mutation_generator_spec.rb, spec/generators/graphql/union_generator_spec.rb
This PR allows users to specify where to install generated files in Rails. At AdHawk, we setup graphql before generators were around, so it is in `app/graph`. Instead of moving all the files in git, we would like to be able to configure this option. This PR makes that happen 😄
=> Allow generator directory to be configured

lib/graphql/tracing/scout_tracing.rb, spec/graphql/tracing/scout_tracing_spec.rb
When attempting to use the built-in tracing feature and plugging in Scout, the order that you specify your dependencies in your Gemfile can cause your code to blow up. For example, if your Gemfile specifies:
```
gem 'scout_apm'
gem 'graphql'
```
Then the code works fine. If, however, it specifies `gem 'graphql'` _first_, it will blow up because `ScoutApm` is not defined when `ScoutTracing` attempts to include the module.
Per [this conversation](https://github.com/rmosolgo/graphql-ruby/pull/1062) with @rmosolgo, I have removed the offending lines and am now performing the include on initialize.
=> Include necessary Scout module from initialize on ScoutTracing

guides/fields/function.md
Otherwise you get an error:
```
NameError:
wrong constant name
```
=> Parameterize description

lib/graphql/base_type.rb, lib/graphql/list_type.rb, lib/graphql/non_null_type.rb, spec/graphql/base_type_spec.rb
Adds a couple helpers:
```ruby
type = GraphQL::EnumType.define do
name "Hello"
value 'WORLD'
end
type.non_null?
type.to_non_null_type.non_null?
type.to_non_null_type.to_list_type.non_null?
type.list?
type.to_list_type.list?
type.to_list_type.to_non_null_type.list?
```
=> Adding some helpers for querying graphql types

.travis.yml, graphql.gemspec
My interest here is in [Symbol GC](https://bugs.ruby-lang.org/issues/9634), which means we can use `.to_sym` without worrying about a DOS vulnerability. This will simplify code in Argument and Variable hashes, which can use symbols under the hood, which people prefer for access anyways. 
Oh, and I should add, support for Ruby 2.1 [ended in April 2017](https://www.ruby-lang.org/en/news/2017/04/01/support-of-ruby-2-1-has-ended/).
=> Remove support for Ruby 2.1

guides/queries/error_handling.md
Just like https://github.com/exAspArk/graphql-errors/pull/3. The `Notify` statement is confusing because it doesn't work in a default Rails setup, I copy-pasted it a few times by mistake.
Also is there anything in http://code.dblock.org/2017/10/30/generating-and-handling-errors-in-graphql-in-ruby.html that you would find valuable in this doc?
=> Remove confusing Notify statement.

lib/graphql/backtrace/tracer.rb, spec/graphql/backtrace_spec.rb
`execution_context.last` is not guaranteed to be a context object.
This can occur when an exception is raised outside of field resolution.
There's not much use in a `TracedError` in this situation, instead of
trying to normalize and find the context, let's just re-raise the
original exception.
See https://github.com/rmosolgo/graphql-ruby/pull/1071 for more background.
cc @eapache
=> Only raise TracedError when context exists

lib/graphql/subscriptions/serialize.rb, spec/graphql/subscriptions/serialize_spec.rb
Currently, this serialization module will _not_ properly reload symbols. For example: 
```ruby
[:a, {b: :c}]
["a", {"b" => "c"}]
```
However, that can be a nasty surprise if you're expecting `:current_user` in your context, not `"current_user"`. 
So, this adds support for: 
- Symbol values (bare, arrays, hashes)
- Symbol hash keys 
This approach is inspired by ActiveJob: https://github.com/rails/rails/blob/4528dd6327f35d3139a48cbac9c9192f2253cbad/activejob/lib/active_job/arguments.rb#L55-L75
It's not _exactly_ backwards compatible, since code that _expected_ this behavior won't work anymore. 
cc @cpunion , will this work for you?
=> Load and dump symbols with Subscriptions::Serialize

spec/support/dummy/schema.rb
I found same name variables are used at local variable and block params, so I fixed.
=> Fix Warning: shadowing outer local variable

spec/support/dummy/schema.rb
Add underscore to `item` of block parameter.
=> Fix useless block parameter

readme.md
This updates the url to the api documentation in the readme to http://www.rubydoc.info/gems/graphql and fixes #1088
=> Update documentation link in readme.md

javascript_client/sync/generateClient.js
This is required to use Apollo's `createBatchingNetworkInterface` API. Fortunately, the rest of the Sync client works just fine after this change (that's a different story with Apollo Client 2.0, but one step at a time!).
=> Fix Sync client compatibility with Apollo's createBatchingNetworkInterface

lib/graphql/schema/field.rb
While trying to upgrade graphql-ruby-demo to 1.8-dev I got this error:
```
NoMethodError: undefined method `ArgumentError' for #<GraphQL::Schema::Field:0x007f82dcbae170>
```
This PR fixes the error so it becomes the actual error:
```
ArgumentError: missing positional argument `type`
```
much better.
=> Fixes ArgumentError by adding the missing comma

lib/graphql/schema/member.rb, spec/graphql/base_type_spec.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/1097
=> Add convenience method "name" to point out that graphql_name exists

lib/graphql/internal_representation/node.rb
Fixes typo of instance variable name. It's only used for caching the result of `typed_children`, and the typo isn't referenced anywhere else, so no difference in behaviour.
=> Fix typo in GraphQL::InternalRepresentation::Node#typed_children

CHANGELOG.md
Summary
----------
#915 introduced a breaking change to previously expected behavior in values for `EnumType`'s - values started to get validated against `/^[_a-zA-Z][_a-zA-Z0-9]*$/`.
Applications with ruby-graphql prior to 1.6.8 might've had technically correct (not valid under the GraphQL spec) `EnumType` values because the validation was not there. 
Updating >= 1.6.8 will be catch those users by surprise since this change isn't reported in the changelog as a bug fix, but not a breaking change. 
This won't be obvious to users updating to >= 1.6.8 as a bug, since  this is [mentioned pretty obscurely](http://facebook.github.io/graphql/October2016/#sec-Enums) in the the GraphQL spec. It's fine to keep the entry in the bug fix entry, but it'd be helpful to call attention to it as a breaking …
=> Add CHANGELOG entry for v1.6.8 breaking change validating EnumType value names

lib/generators/graphql/function_generator.rb, lib/generators/graphql/loader_generator.rb, lib/generators/graphql/templates/function.erb, lib/generators/graphql/templates/loader.erb, spec/generators/graphql/function_generator_spec.rb, spec/generators/graphql/loader_generator_spec.rb
This enforces camel-casing of class names when generating functions and loaders. It also allows them to be namespaced if one wants to structure them that way.
Running `rails g graphql:function find_records` generates the following in `app/graphql/functions/find_records.rb`:
```
class Functions::FindRecords < GraphQL::Function
...
end
```
Running `rails g graphql:function finders::find_records` generates the following in `app/graphql/functions/finders/find_records.rb`:
```
class Functions::Finders::FindRecords < GraphQL::Function
...
end
```
=> Increase flexibility when generating functions and loaders through the CLI

lib/generators/graphql/mutation_generator.rb
This patch fixes issue #1099 
Now, if you run `rails g graphql:mutation TestMutation` you'll see
```
create  app/graphql/mutations
create  app/graphql/mutations/.keep
create  app/graphql/types/mutation_type.rb
add_root_type  mutation
create  app/graphql/mutations/test_mutation.rb
gsub  app/graphql/types/mutation_type.rb
```
And if you then run `rails d graphql:mutation TestMutation` you'll see
```
gsub  app/graphql/types/mutation_type.rb
remove  app/graphql/mutations/test_mutation.rb
```
`app/graphql/types/mutation_type.rb` will also be updated to remove the appropriate line of code (rather than removing the file entirely).
Some comments / tips for people trying to create rails generators in the future (because generators aren't well documented)
1. When a generator is run with `destroy`, …
=> fix: rails destroy graphql:mutation

lib/graphql/schema/member/instrumentation.rb, spec/graphql/schema/instrumentation_spec.rb
Fixes ``undefined method `map' for nil:NilClass`` for nullable lists of an Interface when resolving to `nil`
I'm not sure what the best location for a test for this is, since there is no `spec/graphql/schema/members/instrumentation_spec.rb` and the bug affects `Union`s and `Interface`s, but also `List`s.
Anyway, for now here's how to reproduce the bug:
```ruby
class Foo < GraphQL::Schema::Interface
field :name, String, null: false
def name
"something"
end
end
class Bar < GraphQL::Schema::Object
implements Foo
end
field :foos, [Foo], null: true
def foos
nil
end
end
query Query
orphan_types [Bar]
end
Schema.execute("query { foos { name } }")
```
=> [Class based API] Check for nil before checking depth

lib/graphql/schema/field.rb, spec/graphql/schema/field_spec.rb, spec/support/jazz.rb
Closes #1124
Here's a quick attempt at supporting underscored field names.
I think this is the easiest place to handle it? The only question is how opinionated the gem should be on this. This means that only camelCased field names will end up in the schema.
We could allow this to be configuration in the same way as `field_class`.
=> [1.8] Handle underscored field names

lib/graphql/schema/build_from_definition.rb, spec/graphql/schema/build_from_definition_spec.rb
`build_from_definition` would 💥 when passed a schema with input object default values. See test for example :)
=> Fix default value input object b from def

spec/graphql/analysis/max_query_complexity_spec.rb, spec/graphql/analysis/max_query_depth_spec.rb, spec/graphql/boolean_type_spec.rb, spec/graphql/execution/execute_spec.rb, spec/graphql/float_type_spec.rb, spec/graphql/id_type_spec.rb, spec/graphql/input_object_type_spec.rb, spec/graphql/int_type_spec.rb, spec/graphql/internal_representation/rewrite_spec.rb, spec/graphql/language/lexer_spec.rb, spec/graphql/language/parser_spec.rb, spec/graphql/query/arguments_spec.rb, spec/graphql/query/variables_spec.rb, spec/graphql/query_spec.rb, spec/graphql/relay/base_connection_spec.rb, spec/graphql/relay/connection_resolve_spec.rb, spec/graphql/relay/connection_type_spec.rb, spec/graphql/relay/mutation_spec.rb, spec/graphql/schema/validation_spec.rb, spec/graphql/schema/warden_spec.rb, spec/graphql/schema_spec.rb, spec/graphql/string_type_spec.rb, spec/graphql/subscriptions_spec.rb
Resolves warnings when running tests of the form `Use assert_nil if expecting nil from <file name, context>. This will fail in MT6.`
@rmosolgo
=> Replace instances of 'assert_equal nil, x' with 'assert_nil x'

guides/schema/class_based_api.md, lib/graphql/schema/argument.rb, lib/graphql/schema/field.rb, lib/graphql/schema/input_object.rb, lib/graphql/schema/member/build_type.rb, spec/support/jazz.rb
This is a follow-up to https://github.com/rmosolgo/graphql-ruby/pull/1126.
Completely forgot about arguments 😰 . The actual implementation of this was a little more involved than fields. I think it's correct?
Also updated the new guide to use this convention.
=> [1.8] Handle underscored argument names

javascript_client/sync/__tests__/sendPayloadTest.js, javascript_client/sync/sendPayload.js
using the client like this:
```
graphql-ruby-client sync --path='app/javascript/packs/myapp/graphql/' --url='https://myapp.mycompany.com/graphql/sync'
```
Was not hitting the `https` endpoints. I needed to specify the port in the url like this `url='https://myapp.mycompany.com:443/graphql/sync'`
Parse the urlString for the protocol and default to `443` for `https`, otherwise use port `80`.
=> Adds parsing for https urls passed into the client via commandline

lib/graphql/field.rb, lib/graphql/introspection/arguments_field.rb, lib/graphql/introspection/enum_values_field.rb, lib/graphql/introspection/fields_field.rb, lib/graphql/introspection/input_fields_field.rb, lib/graphql/introspection/interfaces_field.rb, lib/graphql/introspection/of_type_field.rb, lib/graphql/introspection/possible_types_field.rb, lib/graphql/introspection/schema_field.rb, lib/graphql/introspection/type_by_name_field.rb, lib/graphql/introspection/typename_field.rb
Types already had the `introspection` attribute, but without it on fields, there was no easy to check if a field is an introspection field or not.
Usually an introspection field returns an introspection type, but this breaks down for `__typename` which always returns a `String`. Instead of treating it differently, this just adds the attribute to all fields.
Now `introspection?` is available. This can be useful for analysis like computing complexity.
=> Add introspection attribute to fields

lib/graphql/input_object_type.rb, lib/graphql/query/arguments.rb, lib/graphql/query/literal_input.rb, spec/graphql/query/arguments_spec.rb
As discussed the other day in the GraphQL #ruby Slack channel, I've been looking for a way, via instrumentation http://graphql-ruby.org/queries/instrumentation.html in an `after_query` method, to determine whether an `GraphQL::Argument` defined on a `GraphQL::InputObjectType` _that has a default_ actually used the default during resolution.
Argument values can be of type `GraphQL::Language::Nodes::VariableIdentifier` when the input object value is defined in a variable, or of the type `GraphQL::Language::Nodes::InputObject` when its defined inline. I could traverse through either to determine if a given argument fell back to its default that way.
But it seems like instrumentation code that seeks to know if argument defaults were used would be greatly simplified if we simply added this …
=> Add ArgumentValue#default_used? and Arguments#default_used?

lib/graphql/schema/field.rb, spec/graphql/schema/field_spec.rb, spec/support/jazz.rb
It seems there are no objects to https://github.com/rmosolgo/graphql-ruby/issues/1158, so let's implement it!
=> allow description to be defined within field block

lib/graphql/enum_type.rb
If a value cannot be coerced to a value of an EnumType, an error is raised like the following:
```
raise(UnresolvedValueError, "Can't resolve enum #{name} for #{value}")
```
The output produced is not telling if the value is a symbol or a string. A simple call to `inspect` solves this problem:
```
raise(UnresolvedValueError, "Can't resolve enum #{name} for #{value.inspect}")
```
=> Call inspect on value when raising EnumType::UnresolvedValueError

guides/schema/class_based_api.md, lib/graphql/query.rb, lib/graphql/query/context.rb, lib/graphql/schema.rb, lib/graphql/schema/member/instrumentation.rb, spec/graphql/query/context_spec.rb, spec/support/jazz.rb
Custom context classes will allow you to put a bit of logic or caching in `@context`
This also points out a change in 1.8: 
Previously, `context` was field-specific, holding references to things like `ast_node`, `irep_node`, `parent`, `object`, `value`. But now, individual fields don't get called with their own contexts. Instead, the context is provided at object-level, then shared between fields on that object. 
So, we will need (?) some API for getting that info to fields who are using it.
=> [1.8] Support custom context classes

lib/graphql/railtie.rb, lib/graphql/upgrader/member.rb, spec/graphql/upgrader/member_spec.rb
See https://github.com/rmosolgo/graphql-ruby/issues/1177
~- [ ] Convert `description`~
~- [ ] Allow definition of `resolve` within field block~
=> Fix upgrader for some cases

lib/graphql/tracing/scout_tracing.rb
Hello, when I have added `use(GraphQL::Tracing::ScoutTracing)` to schema, i got an error.
Thanks
```ruby
Failure/Error: use(GraphQL::Tracing::ScoutTracing)
ArgumentError:
wrong number of arguments (given 1, expected 0)
```
=> fix args problem in ScoutTracing

.travis.yml
Ruby 2.4.3 has been released.
https://www.ruby-lang.org/en/news/2017/12/14/ruby-2-4-3-released/
This version has fixed [CVE-2017-17405: Command injection vulnerability in Net::FTP](https://www.ruby-lang.org/en/news/2017/12/14/net-ftp-command-injection-cve-2017-17405/)
=> Update Travis Ruby Version to 2.4.3

guides/related_projects.md
It allows you to inspect GraphQL queries in a more readable format.
[Screenshots here](https://github.com/jetruby/graphql-rails_logger#about)
=> Add graphql-rails_logger to related projects list.

lib/graphql/query.rb, spec/graphql/backtrace_spec.rb
Should fix #1121.
I looked for a place to add a test for this and couldn't figure out a good one.
=> Pass along context in Query#result

lib/graphql/schema/enum.rb, lib/graphql/schema/field.rb, lib/graphql/schema/input_object.rb, lib/graphql/schema/interface.rb, lib/graphql/schema/member/has_fields.rb, lib/graphql/schema/object.rb, spec/graphql/schema/enum_spec.rb, spec/graphql/schema/field_spec.rb, spec/graphql/schema/object_spec.rb
I previously used an array, just because I wasn't thinking about it carefully. @cjoudrey suggested this refactor because:
- Easier to lookup a value by name 
- More compatibility with previous schema objects 
I think it's worth the breaking change for both those reasons, please leave a comment here if you disagree or if you'd like to talk about migrating some existing code to this new structure!
=> [1.8, breaking] Use hashes for fields, arguments, enum values

lib/graphql/schema/field.rb, spec/graphql/schema/field_spec.rb
This PR takes another approach to Field definition blocks like this one:
```ruby
field :a, GraphQL::STRING_TYPE, null: true do
argument :id, ID, required: true
end
```
The `FieldProxy` that powers this API is currently hard to customize, making it hard to extend with custom methods like this:
```ruby
field :a, GraphQL::STRING_TYPE, null: true do
argument :id, ID, required: true
my_custom_thing(true)
end
```
This PR remove `FieldProxy` and instead chooses a more explicit approach. Instead of using `FieldProxy`, the Field Class is passed to the block, letting users call `Field` methods directly on the object:
```ruby
field :a, GraphQL::STRING_TYPE, null: true do |f|
f.argument :id, ID, required: true
f.my_custom_thing(true)
end
``
- First commit implements the change
- Second commit fixes …
```
=> [1.8] Instance_eval the Field instead of a FieldProxy

guides/schema/class_based_api.md, lib/graphql/schema/member/build_type.rb, spec/graphql/query/context_spec.rb, spec/support/jazz.rb
Previously, given type `T`, you could only create `[T!]`, not `[T]`. This is usually fine, but I want to keep compatibility with an existing schema.
=> [1.8] Support nullable list items

guides/schema/limiting_visibility.md
This PR fixes a typo in the documentation.
=> [docs] Typo in limiting_visibility.md

guides/schema/extending_the_dsl.md
This PR fixes a typo in the documentation.
=> extending_the_dsl.md: Typo fix

lib/graphql/field.rb
This PR proof-reads documentation blocks for the `field.rb` file.
(Useful stuff!)
=> field.rb: Documentation typos

guides/relay/object_identification.md
The current link in [Object Identification](http://graphql-ruby.org/relay/object_identification) is 404ing, as the url for Facebook’s _Relay Global Object Identification Specification_ has changed.
=> Update link to Relay Global Object Identification spec

lib/graphql/tracing/data_dog_tracing.rb
First off, wanted to say thanks for adding DataDog tracing support! Really cool to see support for this in GraphQL.
I was trying to setup and test out `graphql-ruby` with DataDog tracing enabled, but ran into some issues with the traces, which were being generated incorrectly, causing them not to display in DataDog.
When the `GraphQL::Tracing::DataDogTracing` receives an `execute_multiplex` operation to trace, and none of its queries have `selected_operation_name`s, it sets the resource name to an empty string. Although this doesn't raise an error in the Ruby application, when this trace gets sent through the DataDog agent, the agent prunes out 'bad looking' traces, including ones without resource names. Thus, the trace never makes it to DataDog.
The issue should be reproducible with …
=> Missing resource names for DataDog tracing

guides/types/abstract_types.md
This PR adds wording to the UnionType `resolve_type` docs, so that new users do not remove the `resolve_type` function from their Schema.
This is linguistic nudging.
=> [docs] Abstract Types - note about resolve_type

lib/graphql/schema/printer.rb, spec/graphql/schema/printer_spec.rb
The use of `inspect` was removed in the schema printer refactor (https://github.com/rmosolgo/graphql-ruby/pull/1159).
This was causing an issue with multi-line deprecation reason strings. Previously it would be printed in the schema as a single line string including line breaks. After the refactor it would be printed as a multi-line string.
I don't know what the GraphQL spec itself says about this, but it was causing issues in JavaScript parsing the IDL since the string would be unterminated.
This just restores the old behaviour using `inspect`.
Also see https://github.com/rmosolgo/graphql-ruby/pull/1159/files#r155625238 for more specific discussion around this usage and escaping strings.
cc @xuorig @eapache
=> Fix deprecation reason regression in schema printer

lib/graphql/schema.rb
Trying to upgrade the [schema](https://github.com/rmosolgo/graphql-ruby/blob/1.8-dev/guides/schema/class_based_api.md#schema-class) I encountered this error:
`ArgumentError (wrong number of arguments (1 for 0)):` on line with `max_complexity` method definition, adding class method `max_complexity` to the schema fixes the issue.
=> [1.8] Bug: Missing max_complexity class method in schema

lib/graphql/upgrader/member.rb, spec/graphql/upgrader/member_spec.rb
Oops, the upgrader didn't convert strings to symbols, which are required for Ruby kwargs. Also, it should convert the used arguments to underscore-case.
=> Upgrader: underscore & symbol args access

lib/graphql/define/assign_global_id_field.rb, lib/graphql/relay/node.rb, lib/graphql/schema/object.rb, spec/graphql/relay/node_spec.rb
Reverts rmosolgo/graphql-ruby#1252
=> Revert "fix(Relay::Node) use consistent description for id fields"

lib/graphql/language/printer.rb, spec/graphql/language/printer_spec.rb
Directives come after the implemented interfaces.
See
https://github.com/graphql/graphql-js/blob/360fa06e43fed32b63fba99b353515e7b56eee20/src/language/printer.js#L117-L129
for the canonical printer.
This is pretty difficult to add a test for (I think?) and likely why there wasn't any to begin with.
@xuorig any suggestions for how to test this? Since right now we're building a document by parsing it but I don't think it supports directives like this?
=> Fix printing object type definitions

guides/relay/connections.md
The documentation url for Relay Connections has changed. This update refreshes the link in the [Connections](http://graphql-ruby.org/relay/connections) section of the docs to reflect the new url.
=> Update link to Relay Connections documentation

lib/graphql/schema.rb, lib/graphql/schema/member.rb, spec/graphql/query/executor_spec.rb, spec/graphql/schema_spec.rb
`method_missing` is pretty confusing, it led to some very weird errors in development.
=> refactor(Schema) use explicit whitelist of delegated methods

lib/graphql/schema/field.rb, lib/graphql/upgrader/member.rb, spec/fixtures/upgrader/type_x.original.rb, spec/fixtures/upgrader/type_x.transformed.rb, spec/graphql/schema/object_spec.rb, spec/graphql/upgrader/member_spec.rb, spec/support/jazz.rb
- Properly convert `[A]` to `[A, null: true]`. I have been stupidly applying that change by hand, and I'm tired of it 😆
=> [1.8] more upgrader fixes

lib/graphql/internal_representation/node.rb
My wacky object in 1.7.10 was a bit broken, this is a simpler and better solution which is just as fast. 
I used `be rake bench:validate` to confirm that performance is the same.
=> Fix NO_TYPED_CHILDREN compatibility

lib/graphql/schema.rb, spec/graphql/rake_task_spec.rb, spec/graphql/schema_spec.rb
Certain JSON encoders (namely, Oj) were previously serializing `GraphQL::Query::Result` incorrectly. Instead of returning a schema definition, it would return serialize the output of `GraphQL::Query::Result#inspect` as a string. In order to have better compatibility, this patch opts to represent the schema as a Hash when calling `#as_json`.
=> Make Schema#as_json return an instance of Hash

guides/type_definitions/objects.md, lib/graphql/schema/input_object.rb, lib/graphql/schema/interface.rb, lib/graphql/schema/object.rb, lib/graphql/schema/union.rb, spec/support/jazz.rb
Previously, the way to customize field resolution in a method involved ivars: 
```ruby 
field :comments, [Types::Comment]
def comments 
@object.comments.visible_for(@context[:viewer])
end 
```
But this adds reader methods `#context` and `#object`: 
```ruby
def comments 
object.comments.visible_for(context[:viewer])
end 
```
Cons: 
- Magic method 
Pros: 
- Is a magic method really worse than ivar? I don't think so 
- You get `NoMethodError` in case of a typo, instead of silent nil (eg `@contxte # => nil`)
- You can override the method if you want 
~~update docs (wait for #1274 )~~
=> Add readers for context and object

lib/graphql/schema/argument.rb, lib/graphql/schema/field.rb, spec/graphql/schema/field_spec.rb
This is for backwards compat; if your schema is _all_ underscore-case, then you can override the base classes and reset the default value to `true`.
=> [1.8] Add camelize: false option

lib/graphql/schema.rb, spec/graphql/schema/printer_spec.rb
The error:
```
NoMethodError: undefined method `each_value' for nil:NilClass
/home/kerk/work/graphql-ruby/lib/graphql/schema/warden.rb:115:in `directives'
/home/kerk/work/graphql-ruby/lib/graphql/language/document_from_schema_definition.rb:236:in `build_definition_nodes'
/home/kerk/work/graphql-ruby/lib/graphql/language/document_from_schema_definition.rb:35:in `document'
/home/kerk/work/graphql-ruby/lib/graphql/schema/printer.rb:56:in `initialize'
/home/kerk/work/graphql-ruby/spec/graphql/schema/printer_spec.rb:502:in `new'
/home/kerk/work/graphql-ruby/spec/graphql/schema/printer_spec.rb:502:in `block (3 levels) in <top (required)>'
```
This is caused when you try to print a schema _without_ any directives before `.to_graphql` is called, and your schema is conforming the conventions:
``` …
```
=> [1.8] Do not crash when printing a schema without directives

lib/graphql/schema/member/build_type.rb, spec/graphql/object_type_spec.rb
Hey, I found this weird error that I'm not sure how to deal with. It looks like the validation for the `id` field declared in the interface is run for the `_id` in the object. The error message is:
```
TestObject failed to implement some interfaces: "id" is required by TestInterface to return ID! but TestObject.id returns String
```
I'm afraid this might be a bug!
=> [1.8] Validation is run for wrong field

lib/graphql/language/nodes.rb, spec/graphql/language/nodes_spec.rb
This PR removes `scalar_attributes` and `child_attributes` inherit / copy scheme and replace it with direct definitions and method calls.  This should speed things up as we don't need to do "public_send" anymore, it should (slightly) decrease memory usage as we don't have to hold on to a list of names, and we should create fewer objects on traversal (on average).
I could have made the method definitions one-liners to keep parity with the previous declarative syntax, but I like room to breathe in the code! 😀
=> Remove `scalar_attributes`, `child_attributes` etc

lib/graphql/language/document_from_schema_definition.rb, lib/graphql/language/printer.rb, spec/graphql/schema/printer_spec.rb
This fixes a bug when you have an input field, or an argument, that uses some sort of custom object for its default value. I think it was introduced 1.7.8 with #1159.
The bug is that it will raise a `TypeError`, because the [`Language::Printer`](https://github.com/rmosolgo/graphql-ruby/blob/7929ce579b77a5d57b80829d00c131326e66712b/lib/graphql/language/printer.rb#L342) doesn't handle other kinds of objects.
Previously, it looks like `Schema::Printer` would call [`to_s.inspect`](https://github.com/rmosolgo/graphql-ruby/blob/v1.7.7/lib/graphql/schema/printer.rb#L219) on your custom object types.
=> [Language::Printer] Bug with custom object default values

lib/graphql/schema/interface.rb, lib/graphql/schema/union.rb, spec/graphql/schema/interface_spec.rb, spec/graphql/schema/union_spec.rb
This fixes the class based API for [union](https://github.com/rmosolgo/graphql-ruby/blob/1.8-dev/guides/type_definitions/unions.md#defining-union-types) and [interface](https://github.com/rmosolgo/graphql-ruby/blob/1.8-dev/guides/type_definitions/interfaces.md#resolve-type) type resolution to behave like the documentation. `GraphQL::Schema::Union` was mistakenly checking for the presence of a `resolve_type` instance method rather than class method. `GraphQL::Schema::Interface` was missing the necessary code altogether.  
Fixes #1336
=> [1.8] Fix class based API for union and interface type resolution

lib/graphql/relay/relation_connection.rb, spec/graphql/relay/relation_connection_spec.rb
When querying a connection with first, then to the next "page" with
first+after, and then back to the previous "page" with last+before
(which is the first page), the `hasNextPage` field was set to false.
The expectation is that it would be set to true (when there are more
pages). Without this change, you could page forward then back, and get
into a situation where `hasPreviousPage` and `hasNextPage` are both
false, when `hasNextPage` should be true.
Fixes https://github.com/rmosolgo/graphql-ruby/issues/1318
=> Paging back to beginning sets hasNextPage to true

guides/type_definitions/interfaces.md, lib/graphql/interface_type.rb, lib/graphql/schema.rb, lib/graphql/schema/interface.rb, lib/graphql/schema/traversal.rb, lib/graphql/schema/union.rb, spec/graphql/interface_type_spec.rb, spec/graphql/schema/interface_spec.rb, spec/graphql/schema/traversal_spec.rb, spec/graphql/union_type_spec.rb
As discussed in #1335 this PR implements a method for registering "orphaned" interface implementations which leads to better encapsulation than registering this information with the schema:
```ruby
mutation Types::MutationType
query Types::QueryType
orphan_types Types::CircleType, Types::SquareType
end
class Types::Shape < GraphQL::Schema::Interface
orphan_types Types::CircleType, Types::SquareType
end
```
I went with the terminology "orphan types" vs. "implementations" to be consistent with the existing orphan types API on `GraphQL::Schema` and to avoid confusion about being required to register all implementations vs. just ones that are unreachable from the schema roots. This does introduce a cyclic dependency between the types and the interfaces they …
=> [1.8] Add GraphQL::Schema::Interface.orphan_types configuration

lib/graphql/schema/argument.rb, lib/graphql/schema/field.rb, spec/graphql/schema/argument_spec.rb
Fixes #1347
`GraphQL::Schema::Field.argument` method appears to silently ignore blocks passed to it.
=> Eval argument block when provided

lib/graphql/argument.rb, spec/graphql/argument_spec.rb, spec/support/dummy/schema.rb
Fixes: https://github.com/rmosolgo/graphql-ruby/issues/1349
Changes `Argument.from_dsl` to be a bit more like `GraphQL::Field`. Definition proc takes precedence over kwargs, and kwargs are defined before the proc is called, safer for extensions.
=> Fix argument def

guides/schema/class_based_api.md, guides/type_definitions/extensions.md, lib/graphql/schema.rb, lib/graphql/schema/argument.rb, lib/graphql/schema/enum.rb, lib/graphql/schema/enum_value.rb, lib/graphql/schema/field.rb, lib/graphql/schema/input_object.rb, lib/graphql/schema/interface.rb, lib/graphql/schema/member.rb, lib/graphql/schema/member/accepts_definition.rb, lib/graphql/schema/object.rb, lib/graphql/schema/scalar.rb, lib/graphql/schema/union.rb, spec/graphql/relay/range_add_spec.rb, spec/graphql/schema/member/accepts_definition_spec.rb, spec/graphql/schema_spec.rb, spec/spec_helper.rb
This will make the transition a bit easier. I'll use it for graphql-pro, as well as the cursor_encoder fix.
=> [1.8] Backport accepts_definition, add cursor_encoder

guides/relay/connections.md
When you create a custom connection type using [this](https://github.com/rmosolgo/graphql-ruby/blob/master/guides/relay/connections.md#connection-types) example in Rails it creates a N+1 query, because `.count`is inherited from ActiveRecord and not from Array, whereas `.size` calls the array without refetching the query for each edge.
=> Use .size instead of .count for connection counts

lib/graphql/schema/member/build_type.rb, spec/graphql/schema/field_spec.rb
I hit this bug while using some meta-programmed classes for field types. The test case shows a contrived example of this.
=> [1.8] Allow fields to use anonymous classes for types

lib/graphql/unresolved_type_error.rb, spec/graphql/query/serial_execution/value_resolution_spec.rb
`type_from_object` was previously deprecated in favour of `resolve_type`.
=> Update hint in UnresolvedTypeError to use resolve_type

lib/graphql/schema/interface.rb, lib/graphql/schema/object.rb, lib/graphql/upgrader/member.rb, spec/graphql/schema/interface_spec.rb
- better handling for some upgrader substitutions 
- always define an `Implementation` module in interfaces classes, simplifies metaprogramming because it's always present. (maybe this will 🔥  later, but it's good for now)
=> 1.8 upgrade fix; interface Implementation module fix 

lib/graphql/execution/multiplex.rb, spec/graphql/execution/multiplex_spec.rb, spec/graphql/query_spec.rb
This might fix #1362 ... Let's see 😬 
It's a nice code improvement too, that you can count on `Query::Result` acting like a hash, regardless of the error state.
=> Use an empty hash for response when an error propagates, so after_query hooks can use it

guides/queries/error_handling.md
`RescueFrom` is used in the sample class definition but `Rescuable` is used in the sample use case.
Updated class definition to use `Rescuable`
https://github.com/rmosolgo/graphql-ruby/blob/df28b7da1451931f7dbafc9bd17395d775f11367/guides/queries/error_handling.md#error-handling-with-wrappers
=> Fixing typo in error handling

lib/graphql/execution/execute.rb, spec/graphql/execution_error_spec.rb, spec/graphql/introspection/schema_type_spec.rb, spec/support/dummy/schema.rb
This PR is to enable resolvers to return an **array** of `GraphQL::ExecutionError`s and to have the same behavior we see when a single GraphQL::ExecutionError is returned from a resolver.
More detailed description here: https://github.com/rmosolgo/graphql-ruby/issues/1230
=> Allow resolvers to return multiple errors

lib/graphql/schema/field.rb, spec/graphql/schema/field_spec.rb
When using the `mutation` argument to set a mutation field and passing in `null: false`, it should blow up with an `ArgumentError` but doesn't because it's simply checking for presence (which evaluates to `false` on `false`).
This changes the code to check for a `null` argument that is anything other than `nil` instead when deciding to blow up.
=> Correctly check for `null` argument when `mutation` argument used

lib/graphql/schema/rescue_middleware.rb, spec/graphql/schema/rescue_middleware_spec.rb
Support error matching by superclasses in rescue_table.
RescueMiddleware, when attempting to rescue the errors was only matching
against the exact class if it was present in the `rescue_table`. This PR
introduces the change where we can `rescue_from` a superclass and
RescueMiddleware will be able to handle all its descendants by checking
if either the error class provided or any of it's superclasses is in the
`rescue_table`.
Closes #1392
=> Improve RescueMiddleware error matching

guides/mutations/mutation_classes.md, lib/graphql/schema/mutation.rb, lib/graphql/schema/relay_classic_mutation.rb, spec/graphql/schema/mutation_spec.rb, spec/graphql/schema/relay_classic_mutation_spec.rb, spec/support/jazz.rb
When using the class-based API for mutations (inheriting off of `GraphQL::Schema::Mutation`), there is no way to set whether or not the mutation field is nullable. This change adds a `null` helper method that subclasses can use to specify whether or not they should be nullable:
```
class MyMutation < GraphQL::Schema::Mutation
null true
end
```
This will be inherited by any subclasses:
```
class AnotherMutation < MyMutation
end
AnotherMutation.null # => true
```
If it hasn't been set, it will raise an error when you attempt to use the mutation.
`GraphQL::Schema::RelayClassicMutation` sets `null` to `true`, so no need to worry when inheriting from it:
```
class MyRelayMutation < GraphQL::Schema::RelayClassicMutation
end
MyRelayMutation.null # => true
```
Any thoughts/critiques on this from …
=> Add ability to set nullability of mutations

lib/graphql/scalar_type.rb, lib/graphql/static_validation/literal_validator.rb, spec/graphql/schema/scalar_spec.rb, spec/support/jazz.rb
This PR adds support for building a custom JSON scalar type (i.e. actual JSON not JSON encoded in a string) that is similar to [graphql-type-json](https://github.com/taion/graphql-type-json) for [graphql.js](https://github.com/graphql/graphql-js). The custom scalar can be defined as:
```ruby
class JsonType < GraphQL::Schema::Scalar
def self.coerce_input(value, _context)
value
end
def self.coerce_result(value, _context)
value
end
end  
```
The parser was converting JSON arguments to a `GraphQL::Language::Nodes::InputObject` so I had to convert it back to it's more raw form before attempting scalar coercion. The changes to `GraphQL:: StaticValidation::LiteralValidator` could definitely use some extra scrutiny to ensure I didn't break anything :)
Fixes #146
=> Support custom JSON scalar types

.travis.yml, Appraisals, Gemfile, gemfiles/rails_3.2.gemfile, gemfiles/rails_4.1.gemfile, gemfiles/rails_4.2.gemfile, gemfiles/rails_5.1.gemfile, gemfiles/rails_5.2.gemfile, lib/generators/graphql/install_generator.rb
The generated Rails apps now require bootsnap, and [AFAICT](https://blog.bigbinary.com/2018/01/01/rails-5-2-adds-bootsnap-to-the-app-to-speed-up-boot-time.html) there's no option to build without it, so we may as well just add it here.
Fixes #1425
=> Test on Rails 5.2

lib/graphql/query/variables.rb, spec/graphql/query/variables_spec.rb, spec/graphql/schema/enum_spec.rb, spec/graphql/schema/object_spec.rb
I think this will go along nicely with symbol-oriented changes in 1.8. 
When in a Rails controller, it doesn't really matter, but when hand-writing queries, I sometimes forget that before this, only strings are accepted.
=> Accept symbol-keyed hashes in variables

lib/graphql.rb, lib/graphql/backtrace.rb, lib/graphql/execution/lazy/lazy_method_map.rb, lib/graphql/non_null_type.rb, lib/graphql/query.rb, lib/graphql/query/arguments.rb, lib/graphql/query/context.rb, lib/graphql/query/null_context.rb, lib/graphql/query/result.rb, lib/graphql/query/variables.rb, lib/graphql/schema.rb, lib/graphql/schema/enum.rb, lib/graphql/schema/input_object.rb, lib/graphql/schema/middleware_chain.rb, lib/graphql/schema/scalar.rb, lib/graphql/static_validation/definition_dependencies.rb, lib/graphql/static_validation/validation_context.rb
This patch was required for 2.4.0, I'm going to remove it and include a recommendation to use another version.
Also, fixes #1438 because the patch was busted 😩
=> Stop using patched delegate

lib/graphql/schema/interface.rb, spec/graphql/schema/interface_spec.rb
If you have an interface that includes multiple other interfaces:
```ruby
module MyInterface
include GraphQL::Schema::Interface
include SomeInterface
include SomeOtherInterface
end
```
You get error messages about the `DefinitionMethods` constant being overridden. 😬
=> Fix Warnings for Multiple Interface Inheritance

guides/queries/tracing.md, lib/graphql/tracing/new_relic_tracing.rb, spec/graphql/tracing/new_relic_tracing_spec.rb, spec/support/new_relic.rb
This adds an option to new relic tracer to set the transaction name for all queries.
=> Support setting the new relic transaction name

lib/graphql/subscriptions/instrumentation.rb, lib/graphql/subscriptions/serialize.rb, spec/graphql/subscriptions_spec.rb
*NOTE:* I'm not sure I feel this is done - I got all tests green, but this solution might not be "correct". There's a lot at play here that I don't fully understand.
When using the class-based API with subscriptions, triggering the subscription blows up with the "Failed to implement" error that happens during resolve when your object doesn't implement the method/hash key being asked for.
I took the original test plus the one Robert created to prove the failing code and merged them essentially by running each way of defining the schema through the same set of tests. This way I was able to verify that both ways still worked with the changes I made.
In `GraphQL::Schema::Field`, during execution of `resolve_field_method`, the `obj` is wrapped one more time than expected, where you would have …
=> Fix class based subscriptions

lib/graphql/schema/field.rb
In file `lib/graphql/schema/field.rb`, there're 2 `resolve` in the or condition. Based on what's described in the error below, one of it should be `mutation` instead
=> Fix typo mutation/resolve

lib/graphql/railtie.rb
Rather than trying to extend a module as though it were a superclass. Fixes #1498.
=> Fix BaseInterface generator to generate a module

lib/graphql/schema/build_from_definition.rb, spec/graphql/schema/build_from_definition_spec.rb
Fixes a bug in schema parsing which was setting input field AST nodes to the input object AST node.
cc @cjoudrey @rmosolgo
=> Fix AST node on input field

lib/graphql/railtie.rb
I got the following warning from git when I commited created base files:
According to this article https://robots.thoughtbot.com/no-newline-at-end-of-file, I think we should add newline at the end of the files.
> So, it turns out that, according to POSIX, every text file (including Ruby and JavaScript source files) should end with a \n, or “newline” (not “a new line”) character.
=> Created files should end with newline

guides/pro/authorization.md
The markdown link was broken so because the underscore is missing.
=> Fix accessible_by link is documentation

lib/graphql/compatibility/schema_parser_specification.rb, lib/graphql/language/parser.rb, lib/graphql/language/parser.y
When parsing union type members, we were not tracking the position of the `TypeName` node.
This PR fixes that and adds some test coverage.
=> Track position of union member nodes

lib/graphql/enum_type.rb
Enum name is singular form name. so this is example is better to `Languages` -> `Language`
https://github.com/rmosolgo/graphql-ruby/blob/3e8295cb2c65bf2cf2675b2330d804d78629a815/lib/graphql/enum_type.rb#L13-L20
https://stackoverflow.com/questions/15755955/naming-of-enums-in-java-singular-or-plural
=> fix enum example plural to singular

spec/graphql/relay/mongo_relation_connection_spec.rb, spec/spec_helper.rb
We have mongodb support now (:tada:) but making it required for _all_ tests can be a damper on developing the gem. This change makes it so it's: 
- Only loaded when needed
- Skipped when not found 
For example, when it's absent, you get: 
```
SSSSSSSSSSSSSSSSSSSSS
Finished tests in 0.004816s, 4360.4652 tests/s, 0.0000 assertions/s.
Skipped:
GraphQL::Relay::MongoRelationConnection::results#test_0007_handles cursors below the bounds of the array [/Users/rmosolgo/code/graphql-ruby/spec/graphql/relay/mongo_relation_connection_spec.rb:12]:
Mongo not detected
```
Fixes #1522
=> Only connect to MongoDB when required

lib/graphql/static_validation/rules/fields_have_appropriate_selections.rb, spec/graphql/execution/multiplex_spec.rb, spec/graphql/static_validation/rules/fields_have_appropriate_selections_spec.rb
Previously this was only checking object types. This means a query containing a field which returns an interface type is valid without any selections. This is wrong according to the spec and the reference JS implementation though.
This updates the validation rule to use `fields?` instead of `object?`.
The error message has also been updated to reflect it's not just object types and a helpful "Did you mean" part was borrowed from graphql-js.
@rmosolgo let me know if you want the error message changed
=> Properly validate interfaces without selections

lib/graphql/execution_error.rb, spec/graphql/execution_error_spec.rb, spec/graphql/introspection/schema_type_spec.rb, spec/support/dummy/schema.rb
`ExecutionError` already supports `options` to merge in custom data. However the GraphQL spec now recommends that all additions entries to an error be under the `extensions` key to avoid conflicts with any future spec changes.
Ref: http://facebook.github.io/graphql/draft/#sec-Errors
This adds the ability to specific `extensions` which will get merged into any existing `extensions` data.
`options` has also been marked as deprecated.
=> Add extensions support for execution errors

lib/graphql/static_validation/all_rules.rb, lib/graphql/static_validation/rules/argument_names_are_unique.rb, spec/graphql/static_validation/rules/argument_names_are_unique_spec.rb
[As per the spec](http://facebook.github.io/graphql/October2016/#sec-Argument-Uniqueness):
> Fields and directives treat arguments as a mapping of argument name to value. More than one argument with the same name in an argument set is ambiguous and invalid.
This PR adds extra validation to adhere to the spec and remove ambiguity.
/cc @d12 @nickvanw as they discovered this
=> Validate argument names are unique

lib/graphql/execution/execute.rb, spec/graphql/execution/execute_spec.rb
Fixes #1510 
This is my first time playing in the executor code so I'm not sure if other changes need to be made.
I believe this fixes the issue reported by @joshjcarrier. I've tried with the repro script attached to the issue and have added similar code in our tests.
As a precaution I also confirmed this behaviour in the reference implementation:
```js
var graphql = require("graphql");
var schema = new graphql.GraphQLSchema({
query: new graphql.GraphQLObjectType({
name: 'RootQueryType',
fields: {
hello: {
type: graphql.GraphQLList(graphql.GraphQLNonNull(graphql.GraphQLString)),
resolve() {
return [null];
}
}
}
})
});
var query = '{ hello }';
graphql.graphql(schema, query).then(result => {
console.log(result);
});
// { errors:
//    [ { message: 'Cannot return null for non-nullable field …
```
=> Propagate null for list type of non-null types

lib/graphql/subscriptions/instrumentation.rb, spec/graphql/subscriptions_spec.rb
As discussed in #1427 , the resolver in subscription needs to be called for authorization checking.
This PR adds in the logic for calling resolver defined.
This should also close #1341
=> Update subscription#instrumentation to call original resolver

lib/graphql/schema.rb
Prior to 1.8, I used to be able to do:
```ruby
GraphQL::Schema.define do
default_mask(...)
end
```
This doesn't work on the class-based API in 1.8:
```ruby
default_mask(...)
end
```
This PR adds support to be compatible between the old and new APIs.
=> Fix default_mask configuration not being compatible in the class-based API

lib/graphql/schema/input_object.rb, spec/graphql/schema/input_object_spec.rb
recursively unwraps values in `InputObject#to_h` in a way that's consistent with `Arguments`
fixes #1281
=> Unwrap values in InputObject#to_h

guides/mutations/mutation_classes.md
Fixed inconsistency between field name defined with `field` macro and what's actually returned from `resolve` method.
=> Fix mutation guide example code

guides/errors/execution_errors.md
Change the example to take advantage of new `extensions` feature from https://github.com/rmosolgo/graphql-ruby/pull/1552
=> Update Execution errors guide for extensions

lib/generators/graphql/templates/interface.erb, spec/generators/graphql/interface_generator_spec.rb
changed generated class implementation to module
related to https://github.com/rmosolgo/graphql-ruby/issues/1576
=> Fix graphql:interface generator

lib/graphql/language/nodes.rb, spec/graphql/language/visitor_spec.rb
When using `GraphQL::Language::Visitor`, each node will be visited and then its child nodes (defined by the `children` method) will be visited. 
Currently the `children` of `InputObjectTypeDefinition` is only its fields. This means it is not possible to visit the directives of an `InputObjectTypeDefinition`.
This PR fixes this.
=> Include directives in InputObjectTypeDefinition's children

lib/graphql/interface_type.rb, lib/graphql/union_type.rb, spec/graphql/interface_type_spec.rb, spec/graphql/union_type_spec.rb
This adds `get_possible_type` and `possible_type?` to `InterfaceType` and `UnionType`.
These methods differ from the static `Schema.possible_types` since they take into account the context and go through warden (for things like visibility).
`get_possible_type` returns the type if it exists and is a possible type from a type name.
`possible_type?` accepts with a type definition or a type name and returns a boolean.
=> Add possible type helpers to abstract types

lib/graphql/schema/resolver.rb, spec/graphql/schema/resolver_spec.rb
Resolvers can't currently define the complexity for the field it's being applied to.  This change now allows them to do that.
I've added some tests based on how I saw it being done elsewhere, but feel free to clean them up or leave feedback on anything I should change.
Thanks!
=> Allow Resolvers to define complexity

guides/index.html
- the types/introduction text is no longer in there
- the schema definition text is _perhaps_ where to begin, now?
=> index.html page: Link to an existing article for explaining Types

lib/graphql/query/variables.rb, lib/graphql/static_validation/rules/variable_default_values_are_correctly_typed.rb, spec/graphql/query/variables_spec.rb, spec/graphql/static_validation/rules/variable_default_values_are_correctly_typed_spec.rb, spec/support/dummy/schema.rb
Currently, if a variable value for a scalar cannot be coerced, it results in an exception getting raised rather than being tracked in the `errors` array of the response.  This same thing happens when a default value for a variable is provided that cannot be coerced.
This fixes that problem by handling `GraphQL::CoercionError` in the same way we see here: https://github.com/rmosolgo/graphql-ruby/blob/bf29cde08e9707100703d0bef9464c92aced65e3/lib/graphql/static_validation/rules/argument_literals_are_compatible.rb#L10-L14
Example scenarios where this problem presents itself are shown in the specs.
This should also fix https://github.com/rmosolgo/graphql-ruby/issues/1269
=> Fix scalar coercion errors in variable values (including defaults) not being handled

lib/generators/graphql/templates/graphql_controller.erb, spec/generators/graphql/install_generator_spec.rb
This pull request borrows some logic from https://github.com/howtographql/graphql-ruby/blob/master/app/controllers/graphql_controller.rb that allows for much easier debugging of errors when using tools such as graphiql.
It basically overrides the default Rails error handling for the development environment, which shows an HTML page by default, and instead returns the stack trace in a json response.
I think these are pretty good defaults to use for scaffolding when first creating a project with this gem.
Before:
After:
=> Improve ability to debug errors in development environment

lib/graphql/query/variables.rb, spec/graphql/directive_spec.rb
👋 Hi there,
This pull request resolves a bug that was originally reported in our site's [public Discourse](https://platform.github.community/t/include-with-default-false-behaves-like-it-received-true/6302). The reporter had mentioned that given a query like:
```graphql
query($showName: Boolean = false) { 
viewer {
login @include(if: $showName)
}
}
```
Their response would include the field that was not to be included:
```json
{
"data": {
"viewer": {
"login": "bswinnerton"
}
}
}
```
This ultimately boiled down to this `case` statement:
https://github.com/rmosolgo/graphql-ruby/blob/e0b3e728f38c73529cf68846ac9c2870526a1832/lib/graphql/query/variables.rb#L46
Which, in the query above, `default_value` would have been equal to `false`.
This pull request changes the behavior to specifically …
=> Resolve directive bug when using variable with default value of false

lib/graphql/introspection/type_type.rb, lib/graphql/schema/validation.rb, lib/graphql/type_kinds.rb
This is a proposal and implementation to deprecate 'resolves?' in favour of adding 'abstract?' to `TypeKind`. The reason for this proposal is because I found that that the language 'resolves?' to be a bit misleading and 'abstract?' to be more explicit in what the check is actually doing.
I understand that abstract types need to provide a resolve type, but this might not be apparent to everyone at first glance, as it wasn't for me. It can also be easily confused with whether or not a type can actually resolve at all.
=> Deprecate 'resolves?' in favour of 'abstract?' in TypeKind

lib/graphql/static_validation/message.rb, spec/graphql/static_validation/validator_spec.rb
This may not be the best way of accomplishing this, but in our use-case we'd like to be able to pull the filename back out of the validation error, since we're concatenating definitions from multiple documents before running validation.
@rmosolgo 
cc @jackychiu @jpittis
=> Include 'filename' key in static validation error hash

lib/graphql/schema/interface.rb, spec/graphql/schema/interface_spec.rb
This PR allows methods defined in `definition_methods do ... end` blocks within interfaces to be used within classes implementing these interfaces. The change is simple enough, but I'm not entirely familiar with this project's codebase, so I may be missing some cases here. However, the changes proposed here do enable my own use case without hiccups.
=> Allow definition_methods defined in interfaces to be applied onto classes

guides/schema/testing.md
This PR updates the documentation example for testing the schema to follow RSpec's "Zero monkey patching mode".
It's more compatible.
=> [docs] Testing: Use RSpec.describe syntax

lib/graphql/schema/mutation.rb
This PR updates the documentation example for defining a mutation.
The `resolve` method uses the `errors` variable. However, the field is declared as `error_messages` above.
=> [docs] Change one field name in an example

lib/graphql/schema/interface.rb, spec/graphql/schema/object_spec.rb
See https://github.com/rmosolgo/graphql-ruby/issues/1649. Extending object classes with  `GraphQL::Schema::Interface::DefinitionMethods` will either override methods or include methods which should not be included. This PR ensures `GraphQL::Schema::Interface` is skipped.
=> Exclude GraphQL::Schema::Interface::DefinitionMethods from extend

lib/graphql/query.rb, spec/graphql/query_spec.rb
Previously, passing `variables: nil` would cause a runtime error
=> Fix: use an empty hash when variables: nil is provided

guides/authorization/authorization.md, lib/graphql/schema.rb, lib/graphql/schema/member/instrumentation.rb, lib/graphql/schema/object.rb, spec/graphql/authorization_spec.rb, spec/graphql/schema/object_spec.rb
`Schema.unauthorized_object` may return a new value in case of an UnauthorizedError
=> Support replacement values from unauthorized_object hook

lib/graphql/schema/mutation.rb
Noticed this when reading through the code, opted to keep the newer version of the method but there is no difference other than the documentation. I'm not sure if there is a purpose in having them both in there, thoughts?
=> Remove duplicated object_class method

guides/queries/tracing.md, lib/graphql/tracing.rb, lib/graphql/tracing/prometheus_tracing.rb, lib/graphql/tracing/prometheus_tracing/graphql_collector.rb, spec/graphql/tracing/prometheus_tracing_spec.rb
This commit adds Prometheus tracing
- Includes tracing implementation
- Adds a custom type collector for Prometheus exporter gem that can be used to collect observations
=> feat(Tracing) add Prometheus

lib/graphql/subscriptions/action_cable_subscriptions.rb
`MySchema.execute("subscription { ... }")` does not work on Rails console / grahpqil, as repoted in  https://github.com/rmosolgo/graphql-ruby/issues/1045; it is the spec and I have no idea to fix it.
However, the error message, `NoMethodError (undefined method `stream_from' for nil:NilClass)` can be more understandable: `KeyError (key not found: :channel)`, which suggests the `context` requires `:channel`.
In fact, use of `Hash#fetch` is always better if the key must exist.
=> improve error messages in ActionCableSubscriptions

lib/graphql/schema/interface.rb, spec/graphql/schema/interface_spec.rb
Currently an interface's `definition_methods` will not take precedence over another interface it includes which is the opposite of Ruby's normal object model.
This simply moves extending the interface's own `DefinitionMethods` *after* the base `Schema::Interface::DefinitionMethods` and any other interfaces it already includes.
The tests include a test which previously failed on master/1.8.5.
This solution seems slightly naive to me, so I'm not 100% confident it won't have any other side effects; however, all tests are passing.
edit: this would mostly close #1674.
=> Fix Interface inheritance chain

lib/graphql/internal_representation/visit.rb, lib/graphql/static_validation/validator.rb
While investigating performance on validation and analysis on queries with `validate: false`, I noticed a pretty important part was spent in: https://github.com/xuorig/graphql-ruby/blame/master/lib/graphql/internal_representation/visit.rb#L7-L21
What I realized is that even if `validate` is `false`, the way `Visit` works is that it will traverse the whole irep and call these "post-rewrite" validators. The way it was setup, even though there were no handlers to run, we would still pay the cost for traversal.
Super simple fix that I think will improve very large queries by quite a bit: don't run the visit when no handlers are registered.
=> Validation: Don't traverse irep if no handlers are registered

guides/related_projects.md
Been working on the [graphql-cache](https://github.com/stackshareio/graphql-cache) gem for a little while and thought it would be a good addition to the "Related Projects" section of the site.
=> Add graphql-cache link to related_projects.md

lib/graphql/tracing/skylight_tracing.rb, spec/graphql/tracing/skylight_tracing_spec.rb, spec/support/skylight.rb
This will cause queries with the same name to be grouped together.
~~TODO: make this opt-in?~~, done, use `set_endpoint_name: true` at schema-level, and/or `context[:set_skylight_endpoint_name]` at query-level.
=> Support grouping by "endpoint" with skylight instrumentation

lib/graphql/schema/interface.rb, spec/graphql/schema/interface_spec.rb
When interfaces include other interfaces, their own interfaces are iterated over to extend each of their `DefinitionMethods`. This was happening in the reverse order than the usual Ruby object model.
Now `interfaces` is reversed when iterating to properly give precedence to interfaces higher in the chain.
This is another part of fixing behaviour described in #1674.
=> Fix method inheritance for interfaces

lib/graphql/schema/field.rb, spec/graphql/schema/field_spec.rb
To improve backwards compatibility I want to propose that we provide the option to yield the field to the field definition block if there is a block provided. 
Utilize `instance_exec` in place of `instance_eval` if the definition block has an arity of one, otherwise we will default to `instance_eval` which does not yield the field.
Improves compatibility with older versions.
Added a test to cover the case of yield the field.
=> Yield field for definition blocks with arity of one

lib/graphql/schema/argument.rb, spec/graphql/argument_spec.rb
To mirror the addition to `Field` in #1712.
To improve flexibility I want to propose that we provide the option to yield the argument to the argument definition block if there is a block provided. 
Utilize `instance_exec` in place of `instance_eval` if the definition block has an arity of one, otherwise we will default to `instance_eval` which does not yield the argument.
Improves flexibility!
Added a test to cover the case of yield the argument.
=> Yield argument for definition block with arity of one

Appraisals, Rakefile, gemfiles/rails_3.2.gemfile, gemfiles/rails_4.1.gemfile, gemfiles/rails_4.2.gemfile, gemfiles/rails_5.0.gemfile, gemfiles/rails_5.1.gemfile, gemfiles/rails_5.2.gemfile, gemfiles/without_rails.gemfile
Hello. I noticed that a system test task failed on Travis CI but the build was marked as "passed" on the CI. It does not seem to be an intended result. So I changed the Rakefile so the CI fails if the tests fail. Then, I fixed Capybara's version since Rails 5.1 depends on Capybara ~> 2.13.
* Before (an example of failing builds): https://travis-ci.org/rmosolgo/graphql-ruby/jobs/409088307
*  After: https://travis-ci.org/hibariya/graphql-ruby/jobs/409165615
=> Fix `test:system` for Rails 5.1

guides/relay/object_identification.md
Fixes an example, to use block `end` instead of `}`
=> Minor fix to end block in example

lib/graphql/schema/interface.rb, spec/graphql/schema/interface_spec.rb, spec/graphql/schema/object_spec.rb
This is effectively a revert of #1635.
When an Object Type would implement an Interface, the interface's `DefinitionMethods` were being extended.
However this causes unexpected ancestor chain issues when dealing with common methods (such as `to_graphql`) which are common to both interfaces and objects.
This simply removes this feature. Objects no longer extend the definition methods of the interfaces they implement.
Note: this is obviously a breaking change however I can't think of a better solution. This wasn't a core/fundamental feature of 1.8 either since it was introduced in 1.8.5 (and itself was technically a breaking change).
=> Revert extending interface methods onto Objects

lib/graphql/schema/object.rb, spec/graphql/schema/object_spec.rb
Ref: #1684
Right now an object type can use `implements` to "include" a plain Ruby module.
This adds a check to enforce that the module being implemented is an actual GraphQL interface module.
Note: this could possibly be a breaking change for some people, but I believe it's worth it? The other option for now is a deprecation/warning.
=> Only allow Objects to implement actual Interfaces

lib/graphql/schema.rb, lib/graphql/schema/list.rb, lib/graphql/schema/non_null.rb, lib/graphql/schema/wrapper.rb, spec/graphql/schema/list_spec.rb, spec/graphql/schema/non_null_spec.rb
Introduce `GraphQL::Schema::Wrapper` to move out some common code in `GraphQL::Schema::NonNull` and `GraphQL::Schema::List`.
Reduces code and DRY. Adds a better equality operator for wrapping types.
Not sure if you welcome the new class but thought it was a nice refactor! 😄
=> Refactor wrapping types to use new Wrapper class

lib/graphql/argument.rb, lib/graphql/input_object_type.rb, lib/graphql/query/variables.rb, spec/graphql/input_object_type_spec.rb
Given a schema like:
```graphql
input A {
b: Int = 42
}
input B {
a: A = {}
}
```
Prior to this change, constructing a `B` from defaults would result in a nil value for `a.b`, when instead it should have the value `42`. On this topic, [the spec says](http://facebook.github.io/graphql/June2018/#sec-Input-Objects):
> If a literal value is provided for an input object field, an entry in the coerced unordered map is given the result of coercing that value according to the input coercion rules for the type of that field.
Does it make sense to also call `input_field_defn.prepare` with default values? I haven't used that feature for anything yet.
@rmosolgo cc @jackychiu @michaelkipper
=> Coerce input field defaults to support nested default values

lib/graphql/schema/member/base_dsl_methods.rb, spec/graphql/schema/object_spec.rb
Create a `default_graphql_name` in `GraphQL::Schema::Member::BaseDSLMethods` method to be used in the base implementation of `graphql_name`. This will allow people to override just how default schema member name gets created without having to override the entire method.
Improves flexibility! 😃 
Add `default_graphql_name` and make use of it in `graphql_name`.
Is that a good place for my test to live?
=> Add default_graphql_name in BaseDSL methods

guides/type_definitions/interfaces.md
Noticed this when reading through documentation.
Now that interfaces are `modules` we can't use inheritance like it was previously indicated. Instead we must `include` the `BaseInterface` as indicated in the documentation prior to this.
=> Fix small issue in interface documentation

lib/graphql/schema/member/has_arguments.rb, spec/graphql/schema/field_spec.rb
Add an `add_argument` method to `GraphQL::Schema::Member::HasArguments`. This functionality is similar to how `GraphQL::Schema::Member::HasFields` exposes an `add_field` method. 
Improve consistency and flexibility. (ex. Arguments can now be added to a field outside a field definition)
Create the method `add_argument`, add a test and make use of the new method where applicable.
=> Add add_argument to GraphQL::Schema::Member::HasArguments

lib/graphql/argument.rb, lib/graphql/base_type.rb, lib/graphql/define/instance_definable.rb, lib/graphql/enum_type.rb, lib/graphql/field.rb, lib/graphql/query.rb, lib/graphql/relay/mutation.rb, lib/graphql/schema.rb, lib/graphql/schema/field.rb, lib/graphql/static_validation/validation_context.rb, lib/graphql/types/relay/base_connection.rb, spec/graphql/language/generation_spec.rb, spec/graphql/language/nodes_spec.rb, spec/graphql/schema/resolver_spec.rb, spec/graphql/subscriptions/serialize_spec.rb, spec/graphql/subscriptions_spec.rb, spec/support/global_id.rb, spec/support/lazy_helpers.rb
According to ruby's warning messages (run with `RUBYOPT=-w`), some method definitions were duplicate. I have removed them without changing existing behavior.
* removed some attribute names from `attr_*` or `def_delegators` since each of them has another definition
* added `undef` and `undef_method` to avoid warnings from ruby (related to #1256)
* removed `CustomPrinter` from toplevel
* moved multiple `GlobalIDUser` class definitions into one place
=> Remove duplicate method definitions

guides/schema/class_based_api.md
Because the branch no longer exists.
Fixes #1677.
=> [Guide] Fix link for included rake tasks

guides/mutations/mutation_authorization.md, lib/graphql/schema/resolver.rb, spec/graphql/schema/resolver_spec.rb
I'm trying this out in GitHub and tweaking things a bit. So far: 
- Add a `#object_from_id(type, id, ctx)` hook so that loading objects can be customized 
- Support lazy objects from that hook (promises)
- Remove `#validate_{arg}` hooks and replace them with a single `#authorized?(**inputs)` hook. This is a breaking change, but if you want to preserve the old behavior, you can implement authorized to do the same thing: 
```ruby 
def authorized?(inputs) 
inputs.each { |k, v|  public_send("validate_#{k}", v) } 
end 
```
=> Mutation auth improvements

lib/graphql/schema/wrapper.rb
Seems like I missed removing `extend Forwardable` in #1724.
Circling back here to remove it for good, sorry about that. 😃 
I included Forwardable in #1724 because I wanted to delegate some of the methods to base classes however after the discussion in that PR it made sense to not delegate and instead just reimplement the methods. Now that it's not being used it makes sense to get rid of it. 
Remove `extend Forwardable` from `GraphQL::Schema::Wrapper`.
=> Remove Forwardable from GraphQL::Schema::Wrapper

lib/generators/graphql/mutation_generator.rb, lib/generators/graphql/templates/base_enum.erb, lib/generators/graphql/templates/base_input_object.erb, lib/generators/graphql/templates/base_interface.erb, lib/generators/graphql/templates/base_object.erb, lib/generators/graphql/templates/base_union.erb, lib/generators/graphql/templates/enum.erb, lib/generators/graphql/templates/interface.erb, lib/generators/graphql/templates/loader.erb, lib/generators/graphql/templates/mutation.erb, lib/generators/graphql/templates/mutation_type.erb, lib/generators/graphql/templates/object.erb, lib/generators/graphql/templates/query_type.erb, lib/generators/graphql/templates/union.erb, spec/generators/graphql/enum_generator_spec.rb, spec/generators/graphql/install_generator_spec.rb, spec/generators/graphql/interface_generator_spec.rb, spec/generators/graphql/loader_generator_spec.rb, spec/generators/graphql/mutation_generator_spec.rb, spec/generators/graphql/object_generator_spec.rb, spec/generators/graphql/union_generator_spec.rb
To avoid confusion represented in #1591.
In Rails application, constant is resolved based on certain mechanism as
described in the [guide](https://guides.rubyonrails.org/v5.2/autoloading_and_reloading_constants.html#namespaces).
Essentially:
```
class Animal
end
class Animal::Dog
end
class Animal::Human
Dog # => NameError
end
```
This fails to lookup constant `Dog`
Whereas:
```
module Animal
class Dog
end
end
module Animal
class Human
Dog # => Animal::Dog
end
end
```
This works fine.
=> Nest under common namespace for better autoloading availability

guides/relay/object_identification.md
While following [this guide](http://graphql-ruby.org/relay/object_identification.html#node-field-find-by-uuid) verbatim, I ran into the following error:
```
GraphQL::Field was passed as the second argument, use the `field:` keyword for this instead.
/Users/Patrick/.gem/ruby/2.5.1/gems/graphql-1.8.6/lib/graphql/schema/field.rb:61:in `from_options'
/Users/Patrick/.gem/ruby/2.5.1/gems/graphql-1.8.6/lib/graphql/schema/member/has_fields.rb:52:in `field'
/Users/Patrick/Code/parsnip/app/graphql/types/query_type.rb:6:in `<class:QueryType>'
/Users/Patrick/Code/parsnip/app/graphql/types/query_type.rb:4:in `<module:Types>'
/Users/Patrick/Code/parsnip/app/graphql/types/query_type.rb:3:in `<main>'
...
```
I don't know when the docs got out of date, but it turns out that a `field: ` keyword is required …
=> Fix relay root-level node declaration syntax (in docs)

lib/graphql/schema/member/base_dsl_methods.rb
Small tweak to move the `NotImplementedError` into `default_graphql_name` based on @eapache suggestion, missed this in #1729.
Raise the error where it should be raised!
=> Move NotImplementedError out to default_graphql_name

guides/getting_started.md
As a new user of graphql, it never occurred to me that I needed to use camel case to query even when the ruby field is in snake case. I was stuck on this for much time...much...time...many...times.
Not sure your preference on which exact field to use but please take this as a seed of an idea.
=> Update to make life easier

lib/graphql/type_kinds.rb
Explicitly define type kind predicate methods instead of them defining them at execution.
Remove the `define_method` loop and instead define all the methods explicitly.
Makes for easier code search! 😃 
I often forget that methods like `enum?` exist and I think its largely because those methods were created during execution, because there aren't many methods and the number will likely not change its nice to just explicitly define them.
=> Explicitly define type kind predicate methods

guides/mutations/mutation_authorization.md, lib/graphql/schema/resolver.rb, spec/graphql/schema/resolver_spec.rb
As pointed out by @cainlevy in #1734 , the new mutation auth doesn't support errors-as-data very well, but it definitely _should_, because errors-as-data is nice. 
How to do it? I can think of a few implementations: 
- Somehow use the return value of `.authorized?` (this is how before-save callbacks used to work, if they returned `false`, then save was prevented. I think this was changed to [`throw(:abort)`](https://blog.bigbinary.com/2016/02/13/rails-5-does-not-halt-callback-chain-when-false-is-returned.html)
- Use `throw :early_return, response`. This has the advantage of being plain Ruby, but it's not a very familiar feature. Also, it halts program flow, which is convenient, since later code will be irrelevant. 
- Use a normal method, as shown here. It's abstract, which is nice, but …
=> Add a flow for returning data early from Mutation#authorized?

guides/guides.html, guides/language_tools/visitor.md, lib/graphql/compatibility/schema_parser_specification.rb, lib/graphql/language/document_from_schema_definition.rb, lib/graphql/language/nodes.rb, lib/graphql/language/visitor.rb, lib/graphql/static_validation/rules/no_definitions_are_present.rb, spec/graphql/language/nodes_spec.rb, spec/graphql/language/visitor_spec.rb
It would be nice to have a way to programmaticaly modify GraphQL ASTs, but we don't have one yet. I propose a way to do it using the class-based visitor on the `1.9-dev` branch. 
Goals: 
- Efficient
- Easy-to-use 
- Respects immutability of nodes 
So, this implementation will treat the AST as a persistent immutable data structure: 
- By default, the tree is only traversed; no modification or duplication 
- When a hook returns a new node, then: 
- the node's parent is shallow-copied; the copy is modified to include the new child 
- the copied parent is returned so that its parent may also be modified 
__TODO:__
- Lots of nodes need reorganization to support persistent copying, for example: 
- Implementing `.children_method_name` (I sure hope that each node type has only one possible name!) …
=> Manipulate AST with visitor

lib/graphql/schema/relay_classic_mutation.rb, lib/graphql/schema/resolver.rb, spec/graphql/schema/resolver_spec.rb
Oops, it was passing `client_mutation_id:` to authorized, which we want to hide from mutation code.
=> Don't pass client_mutation_id: to .authorized?

lib/graphql/schema/resolver.rb, spec/graphql/schema/relay_classic_mutation_spec.rb, spec/graphql/schema/resolver_spec.rb, spec/support/jazz.rb
This is really to support:
```ruby 
argument :id, ID, required: true, loads: Comment, as: :comment
```
Because otherwise, you end up with `id:` being a Comment, which makes no sense.
=> Let as: overrides loads: argument name

lib/graphql/schema/field.rb, lib/graphql/schema/field/connection_extension.rb, spec/integration/rails/graphql/relay/connection_resolve_spec.rb, spec/support/star_wars/schema.rb
Oops, a bug in #1758  which showed up when I tried GitHub on the latest master
=> Don't pass resolver objects to field extensions

guides/type_definitions/objects.md
=> fix doc: s/default/default_value/ for argument definitions

lib/graphql/enum_type.rb, spec/graphql/enum_type_spec.rb
Everything else in the schema does, and these should too. They don't
automatically because they don't inherit from BaseType, which they
potentially should, but that's a much larger change.
I couldn't get alias_method to work (something about how `name` is
defined dynamically through method_missing) so I defined the method
manually.
@rmosolgo cc @swalkinshaw there's a weird goose chase behind this one
=> Ensure enum values respond to graphql_name

guides/schema/class_based_api.md
Hey @rmosolgo, I was looking through the upgrade guide for the class-based API and was very surprised to see  a suggestion that the `.define` API would be outright removed in 1.x. I'd strongly suggest keeping a major removal/API change like that to a major version bump instead. I think as a downstream consumer of this gem I'd be quite surprised to see that happen in a minor version and the major version gives you a chance to celebrate the new change.
I've started you off here on the roadmap. 🙏
=> Suggest splitting off a 2.0

lib/graphql/execution/multiplex.rb, spec/graphql/execution/multiplex_spec.rb
If an exception not inheriting from StandardError was thrown in a
GraphQL mutation, then the rescue block added to fix #1072 in 8bf0039
would not have caught that exception. If such an exception was always
thrown, the query would have never been marked as resolved, and so the
schema resolver would have never terminated with certain instrumenting
gems that inspect `query.result`. This could have happened in
development if you made a syntax error inside a mutation, for example.
Rescuing from Exception fixes this. Although it is generally not advised
to rescue from Exception, it is probably okay in this case because we
immediately re-raise it.
=> Fix infinite resolution bug for Exception (#1803)

lib/graphql/schema/resolver.rb, spec/graphql/schema/relay_classic_mutation_spec.rb, spec/graphql/schema/resolver_spec.rb, spec/support/jazz.rb
Currently it is possible to have GraphQL Ruby automatically load objects for `ID` arguments, for example:
```ruby
argument :label_id, ID, required: true, loads: Label
```
In some cases, the argument will be a list of `ID`. It would be great if the `loads:` option worked in this case too, for example:
```ruby
argument :label_ids, [ID], required: true, loads: Label, as: :labels
```
I managed to do this by re-using the existing logic for `loads:`. I _think_ this is fine, but I'd love an extra pair of :eyes: in case I didn't think of something.
Another note, in the singular case, the `as:` is inferred by stripping `_id` off the original argument name. In the list case, this is a bit trickier as we'd have to pluralize the remainder, which would mean having to leverage something like …
=> Add support for array of IDs to `loads:` argument

guides/authorization/can_can_integration.md
It says `CanCan` instead of `CanCanIntegration` in the guide and it threw off my copy-paste game 😄
=> Fix typos in CanCan guide

lib/graphql/compatibility/execution_specification/specification_schema.rb
Just a quick fix that was marked in the codebase as `TODO:`
`Middleware that takes a next_middleware parameter is deprecated (GraphQL::Compatibility::ExecutionSpecification::SpecificationSchema::TestMiddleware); instead, accept a block and use yield.`
=> Fix middleware warning

lib/graphql/base_type.rb, lib/graphql/schema/field.rb, spec/graphql/analysis/analyze_query_spec.rb, spec/graphql/base_type_spec.rb, spec/graphql/enum_type_spec.rb, spec/graphql/execution/typecast_spec.rb, spec/graphql/field_spec.rb, spec/graphql/interface_type_spec.rb, spec/graphql/introspection/input_value_type_spec.rb, spec/graphql/object_type_spec.rb, spec/graphql/query/executor_spec.rb, spec/graphql/schema/interface_spec.rb, spec/graphql/schema/traversal_spec.rb, spec/graphql/schema/type_expression_spec.rb, spec/graphql/schema/validation_spec.rb, spec/graphql/union_type_spec.rb, spec/integration/rails/graphql/input_object_type_spec.rb, spec/integration/rails/graphql/query/variables_spec.rb, spec/integration/rails/graphql/schema_spec.rb, spec/support/dummy/data.rb, spec/support/dummy/schema.rb
This is a tradeoff in gem maintenance: 
- CON: we greatly _reduce_ our test coverage for `.define`-based schemas 
- PRO: we greatly _improve_ our test coverage for class-based schemas 
I want to use this schema to test the new interpreter, since this schema is used for testing _lots_ of runtime features. Before I can run the new interpreter on it, it has to be class-based."
Lots of the test changes involve adding `.graphql_definition` everywhere. I hope to drop lots of those tests in graphql-ruby 2.0, when `.define` will be gone altogther.
=> Migrate dummy schema to class-based 

lib/graphql/types/iso_8601_date_time.rb, spec/graphql/types/iso_8601_date_time_spec.rb
The result of `Time.zone.now.to_json` (Rails' datetime format)  differs from `GraphQL::Types::ISO8601`'s serialized one:
* Rails': `"2010-02-02T22:30:30.124-06:00"` (ISO8601 *with* miliseconds)
* GraphQL-Ruby's: `"2010-02-02T22:30:30-06:00"` (ISO8601 *without* milliseconds)
This incompatibility causes problems in my project :sob:, so I have monkey-patched to `GraphQL::Types::ISO8601` for now.
This PR provides a way to customize the precision of the serialized format just like [ActiveSupport::JSON::Encoding.time_precision](https://www.rubydoc.info/github/rails/rails/ActiveSupport/JSON/Encoding.time_precision).
Usage:
```ruby
GraphQL::Types::ISO8601.time_precision = ActiveSupport::JSON::Encoding.time_precision
```
No breaking change is introduced by the PR.
=> add GraphQL::Types::ISO8601DateTime.time_precision to customize time pricisions

lib/graphql/schema/field.rb
Previously this used `instance_exec` which sets `self` to the field instance.
This changes to `yield` which still executes within the context of the field instance (supporting the same functionality) but doesn't change `self`.
This is probably more relevant to our specific use case. We have resolve procs which call class methods on object type classes. As we're migrating more to use the gem directly, this is a blocker for us.
The irony being that we added this code in the first place 😂 
Note: this is technically a breaking change, but I (highly?) doubt it will affect anyone.
1. it's a fairly new feature
2. the common usage is still supported (since it yields the field instance)
3. no one else would have our use case of class methods on object classes?
cc @RobertWSaunders
=> Update how Schema::Field executes definition_block

lib/graphql/enum_type.rb, lib/graphql/input_object_type.rb, spec/graphql/input_object_type_spec.rb
This is a simple PR to solve: https://github.com/rmosolgo/graphql-ruby/issues/1826.  Basically it just falls back to the pre-existing behavior in case the lookup of default value in nested inputs fails as it does in the case of enum types.
=> Fall back to input_field_defn default value if coerce_input returns nil

guides/type_definitions/objects.md, lib/graphql/schema/field.rb, spec/graphql/schema/field_spec.rb, spec/support/jazz.rb
Before the 1.8 update you could use closures to pass information from a field to it's type. Now it's much more difficult (using `:method`).
Example from our codebase:
```ruby
class SomeType < GraphQL::Schema::Object
...
field generated_name, type, method: :resolver, extras: [:ast_node]
...
def resolver(:ast_node)
generated_name = parse_name(ast_node.name)
```
This pulled request would allow this:
```ruby
field generated_name, type, method: :resolver, extras: [:name]
...
def resolver(name:)
```
or even this:
```ruby
class SpecialField < GraphQL::Schema::Field
attr_reader :klass, :attribute
def initialize(*args, klass:, attribute:, **kwargs, &block)
@klass = klass
@attribute = attribute
...
end
...
class SomeType < GraphQL::Schema::Object
field_class SpecialField
field generated_name, type, …
```
=> Allow fields to pass additional parameters

lib/graphql/schema/resolver.rb, spec/graphql/schema/resolver_spec.rb
Fixes #1840 
If a nullable argument using `loads: ...` is provided a `null` value, we should passthrough the `nil` value to the resolver instead of trying to resolve it to an object.
=> Passthrough `null` values for arguments using `loads`

lib/graphql/relay/base_connection.rb, spec/integration/rails/graphql/relay/array_connection_spec.rb, spec/integration/rails/graphql/relay/base_connection_spec.rb
A problem I hit recently is that I could run a query with an invalid cursor and instead of getting an error response back, I'd get an exception. This branch rescues that exception ("ArgumentError: invalid base64") and raises an ExecutionError, which results in a normal error response from GraphQL explaining that the caller provided a bad cursor.
=> Raise execution error when trying to decode an invalid cursor

guides/development.md
This updates the documentation for how to run integration tests. Until I specified a gemfile using `BUNDLE_GEMFILE`, I got errors like "NameError: uninitialized constant StarWars::DATA".
=> Update docs for running integration tests

lib/graphql/query/context.rb, spec/graphql/query/context_spec.rb
It's sometimes useful to use `dig` to fetch deeply nested context values 
https://ruby-doc.org/core-2.3.0_preview1/Hash.html#method-i-dig
delegate `dig` to `@provided_values`
=> read context values using dig

lib/graphql/schema/field.rb, spec/graphql/schema/resolver_spec.rb
It appears like a regression was introduced in #1808.
Given the following code:
```ruby
field :hello, String, null: true,
extras: [:execution_errors, :path]
def hello(execution_errors:, path:)
p path
end
end
query Query
end
Schema.execute('{ alias: hello }')
```
Previously, `path` would return `["alias"]`.
As of v1.8.9, it returns `"Query.hello"`.
It seems like the issue is that `path` is obtaining its value from the field's `path` instead of `context.path`. I'm not sure if this is the most elegant way of fixing this so please let me know if you think there is a better way.
=> Regression in `extras: [:path]`

lib/graphql/schema/loader.rb, spec/graphql/schema/loader_spec.rb
Attempts to load schemas with argument default values that are lists of input objects failed with following exception:
```
/Users/jturkel/.rvm/gems/ruby-2.4.3/gems/graphql-1.8.10/lib/graphql/schema/traversal.rb:219:in `validate_type': Query is invalid: field "inventory" argument "ordering" default value [#<GraphQL::Language::Nodes::InputObject:0x00007fa3510db460 @line=1, @col=34, @filename=nil, @arguments=[#<GraphQL::Language::Nodes::Argument:0x00007fa3510dbc80 @line=1, @col=35, @filename=nil, @name="asc", @value="supplierPartNumber">]>] is not valid for type [orderingInput] (undefined method `reduce' for #<GraphQL::Language::Nodes::InputObject:0x00007fa3510db460>) (GraphQL::Schema::InvalidTypeError)
from /Users/jturkel/.rvm/gems/ruby-2.4.3/gems/graphql-1.8.10/lib/graphql/schema/traversal. …
```
=> Loader support for argument default values that are lists of input objects

Rakefile, benchmark/run.rb, lib/graphql/execution/interpreter/hash_response.rb, lib/graphql/execution/interpreter/runtime.rb, lib/graphql/schema/member/has_arguments.rb, lib/graphql/schema/member/has_fields.rb
I don't want to fuss over this too much, because the application benchmarks might be different from isolated ones, but I thought I'd look for low-hanging fruit now. 
I added a benchmark based on #861, here's the initial result: 
```
1.000  i/100ms
1.704  (± 0.0%) i/s -      9.000  in   5.286738s
```
<details>
<summary>Method calls</summary>
<pre>
Thread ID: 70366903138220
Fiber ID: 70366933287300
Total: 2.387865
%self      total      self      wait     child     calls  name
4.53      0.108     0.108     0.000     0.000   528057   Kernel#is_a?
called from:
GraphQL::Query#initialize …
=> Low hanging fruit in interpreter 

lib/graphql/execution/instrumentation.rb, lib/graphql/execution/multiplex.rb, lib/graphql/query/result.rb, spec/graphql/execution/instrumentation_spec.rb
This allows you to halt a query with errors by raising GraphQL::ExecutionError in before_query
=> Rescue GraphQL::ExecutionErrors raised during before_query hooks

lib/graphql/language/nodes.rb, spec/graphql/language/nodes_spec.rb
Found while updating graphql-client
=> Fix cache busting when duping nodes

lib/graphql/schema/printer.rb, spec/graphql/schema/printer_spec.rb
Fixes a very old regression in `print_type`. Right now it only handles
object types and breaks on anything else.
This updates it to use `build_type_definition_node` which detects the
type kind and works as expected with every kind.
=> Fix type printing in Schema printer

lib/graphql/static_validation/rules/fields_will_merge.rb, spec/graphql/static_validation/rules/fields_will_merge_spec.rb
Previously, it was assumed that to maybe-conflicting nodes would have equally-deep `parents` arrays. But this is sometimes not true, for example, in: 
```graphql 
{
... on Pet { 
... on Dog {
x 
}
}
... on Cat {
x: y 
}
}
```
Those are _not_ conflicting, but because their `parents` arrays were mismatched lengths, the method returned `false` (in the fallback case). 
When I changed the method to support any depth of either array (via a double-nested `#each`), there was the problem that those arrays also included the _owner_ type of the field. The presence of the owner type would wrongly cause the method to return `true`. So I refactored the code to pass `owner_type:` separately. 
Now, `parents` is usually an array with one entry, but in the case of multiply-scoped fields like the one above, …
=> FieldsWillMerge: keep owner_type separate from static scoping; support unbalanced static scopes 

graphql.gemspec, guides/development.md, spec/spec_helper.rb
Having had some RSI issues in the past, I like to try to keep my typing as minimial as possible while developing, and the current way to run specs is a bit verbose for my liking. Would it be OK to add the m gem to make this process easier?
=> Add m gem for easier test running

javascript_client/subscriptions/PusherLink.js
Without this, you need to explicitly transpile the node module contents.
=> Pusher: use require and module.exports instead of import/export

guides/javascript_client/apollo_subscriptions.md
The current documentation did not indicate where PusherLink comes from (i.e. not clear if it is part of `apollo` or part of `graphql-ruby-client`. This documents that it is part of `graphql-ruby-client` (and the path for import).
=> Document import of PusherLink for Apollo

lib/graphql/execution/lookahead.rb, lib/graphql/schema/field.rb, spec/graphql/execution/lookahead_spec.rb, spec/graphql/schema/field_spec.rb
This PR adds the ability to get all of the selections from a Lookahead. I decided to keep the implementation simple by just re-using the `selection` method instead of refactoring, let me know if that's alright :smile:
Continuation of https://github.com/rmosolgo/graphql-ruby/pull/1894
=> Add GraphQL::Execution::Lookahead#selections

lib/graphql/query.rb, spec/graphql/execution/lookahead_spec.rb
Makes it easier to look at root level fields, for example in `before_query`.
=> Add Query#lookahead

lib/graphql/schema/relay_classic_mutation.rb, spec/graphql/schema/relay_classic_mutation_spec.rb, spec/support/jazz.rb
Oops, `extras [...]` didn't work on relay classic mutations.
=> Fix RelayClassicMutation extras on interpreter

guides/authorization/authorization.md
The usage of non-library code in examples is confusing to beginners and should be avoided.
=> Remove confusing non-relevant example

guides/queries/tracing.md
Consistent with the other examples in the `tracing` documentation.
=> [Documentation] Use parenthesis for consistency

lib/graphql/tracing/new_relic_tracing.rb, lib/graphql/tracing/skylight_tracing.rb, spec/graphql/tracing/new_relic_tracing_spec.rb, spec/graphql/tracing/skylight_tracing_spec.rb, spec/support/new_relic.rb, spec/support/skylight.rb
The New Relic and Skylight subclasses of `GraphQL::Tracing::PlatformTracing` weren't plumbing through superclass options.
=> Fix scalar tracing in NewRelic and Skylight instrumentation

lib/graphql/execution/interpreter/runtime.rb, spec/graphql/execution/lookahead_spec.rb
`extras: [:lookahead]` wasn't working quite right, because it was being delegated to `Query::Context#lookahead` instead of being injected by the runtime.
=> Support lookahead in interpreter

lib/graphql/query/context.rb, spec/graphql/query/context_spec.rb
Right now extending of fields via something like
```ruby
module ExtendedField
def initialize(*args, custom_key:, **kwargs, &block)
…
super(*args, **kwargs, &block)
end
end
```
because sometimes context is passed as the second argument and it
ends up in args instead of kwargs.
Fixes #1821
=> Add GraphQL::Query::Context#to_hash to allow splatting

lib/graphql/schema/member/build_type.rb, spec/graphql/schema/member/build_type_spec.rb, spec/support/jazz.rb
Currently string arguments passed to a type definition (such as `field :user, "Types::UserType", null: true`) are resolved using a basic `Object.const_get` call. This is prone to autoloading issues, particularly in development with classes down several module levels (e.g., `Types::User::Foo::BarType` where `Foo` is also a type).
Rails' `ActiveSupport::Inflector.constantize` has a few workarounds built-in, which this PR grifts in `BuildType#parse_type` for more robust string-to-constant resolution, without assuming the project has `String.constantize` available.
A more complex solution could be allowing a custom string-to-constant resolver as an option on the schema, but that seemed like overkill. On the other hand a simpler solution could be checking that the type string …
=> Improve field type string-to-constant resolution

lib/graphql/execution/interpreter/runtime.rb, spec/graphql/execution/interpreter_spec.rb
The problem was that `.non_null?` information was left behind when unwrapping them in `continue_field`. So we should retain that value when resolving the field, that's why I added a new argument which can be set to `true` when unwrapping a non-null type.
=> Fix non-null abstract fields that return nil

lib/graphql/execution/interpreter/runtime.rb, spec/graphql/execution/interpreter_spec.rb
You can get this information injected into field methods which is definitely the best way to get it. But sometimes you need it in places that _aren't_ field methods. So, I'll write them into this little bit of context so they can be read elsewhere.
=> Put runtime info in mutable context, too

lib/graphql/execution/interpreter/runtime.rb, lib/graphql/schema/field.rb, lib/graphql/schema/member/base_dsl_methods.rb, lib/graphql/schema/member/has_fields.rb
=> Interpreter performance

lib/graphql/execution/interpreter/runtime.rb, spec/graphql/execution/interpreter_spec.rb
Wow, I put a very bad assumption in the code, and it took me two days to find it as the cause of a bug in our app. But, here you have it!
(Turns out, in a list, not all members are the same type as the first member 😩 😩 😩 )
=> Interpreter type at path fix

lib/graphql/execution/interpreter.rb, lib/graphql/query.rb, lib/graphql/query/context.rb, lib/graphql/schema.rb, lib/graphql/static_validation.rb, lib/graphql/static_validation/base_visitor.rb, lib/graphql/static_validation/interpreter_visitor.rb, lib/graphql/static_validation/validator.rb, spec/graphql/analysis/ast_spec.rb, spec/graphql/execution/interpreter_spec.rb, spec/graphql/schema/warden_spec.rb, spec/support/jazz.rb, spec/support/lazy_helpers.rb
We have this alternative path that doesn't require `irep_node`s, so let's see if we can skip building them altogether (which is the goal). 
This is a bit different take than #1918 , because you have to explicitly opt into _both_ (but this is kind of good, since you can adopt them separately).
=> Skip rewrite when interpreter is enabled

javascript_client/subscriptions/createAblyHandler.js
This avoids warnings when using an Ably "Realtime" client instance
that uses "identified" authentication.
=> Work better with identified Ably client

lib/graphql/schema.rb, spec/integration/rails/graphql/schema_spec.rb
This allows you to pass multiple error types into `rescue_from`'s in your schema, instead of just one:
``` ruby 
rescue_from(ActiveRecord::RecordInvalid, ActiveModel::ValidationError) { |e| "Validation failed." }
end
```
* the underlying `RescueMiddleware#rescue_from` already accepts multiple error classes
* would be nice to follow the same signature as Rails `rescue_from`, which accepts multiple errors
=> Allow multiple errors as args to Schema.rescue_from.

lib/graphql/schema/build_from_definition.rb
The current error message made me feel like there was no way that I could make an executable schema that handles interfaces.  I forgot that I implemented this myself partially. Hopefully this error message clarifies it a little.
- Make more clear error message
=> Clarify error message on build from definition

guides/queries/multiplex.md
See issue #1948 
Adds a tip to the documentation that could help resolve confusion with query batching and Apollo Client.
=> add tip to documentation

spec/graphql/schema/field_spec.rb, spec/support/jazz.rb
Copies #1979 onto 1.9-dev and shows that it's fixed by #1961
=> 1.9 hash key schema fix

guides/fields/arguments.md
The current documentation suggests that returning a
GraphQL::ExecutionError from an argument's prepare function is valid,
but you must actually raise the GraphQL::ExecutionError to achieve the
desired behavior.
=> Clarify argument prepare documentation

Gemfile
I got below error message.
```
Configuration file: /Users/technuma/gems/graphql-ruby/guides/_config.yml                                                                                                                                Dependency Error: Yikes! It looks like you don't have jekyll-redirect-from or one of its dependencies installed. In order to use Jekyll as currently configured, you'll need to install this gem. The full
error message from Ruby is: 'cannot load such file -- jekyll-redirect-from' If you run into trouble, you can find helpful resources at https://jekyllrb.com/help/! 
rake aborted! 
```
=> add jekyll-redirect-from to Gemfile for fixing 'bundle exec rake site:serve'

lib/graphql/static_validation/rules/argument_literals_are_compatible_error.rb, lib/graphql/static_validation/rules/argument_names_are_unique_error.rb, lib/graphql/static_validation/rules/arguments_are_defined_error.rb, lib/graphql/static_validation/rules/directives_are_defined_error.rb, lib/graphql/static_validation/rules/directives_are_in_valid_locations_error.rb, lib/graphql/static_validation/rules/fields_are_defined_on_type_error.rb, lib/graphql/static_validation/rules/fields_have_appropriate_selections_error.rb, lib/graphql/static_validation/rules/fields_will_merge_error.rb, lib/graphql/static_validation/rules/fragment_names_are_unique_error.rb, lib/graphql/static_validation/rules/fragment_spreads_are_possible_error.rb, lib/graphql/static_validation/rules/fragment_types_exist_error.rb, lib/graphql/static_validation/rules/fragments_are_finite_error.rb, lib/graphql/static_validation/rules/fragments_are_named_error.rb, lib/graphql/static_validation/rules/fragments_are_on_composite_types_error.rb, lib/graphql/static_validation/rules/fragments_are_used_error.rb, lib/graphql/static_validation/rules/mutation_root_exists_error.rb, lib/graphql/static_validation/rules/no_definitions_are_present_error.rb, lib/graphql/static_validation/rules/operation_names_are_valid_error.rb, lib/graphql/static_validation/rules/required_arguments_are_present_error.rb, lib/graphql/static_validation/rules/subscription_root_exists_error.rb, lib/graphql/static_validation/rules/unique_directives_per_location_error.rb, lib/graphql/static_validation/rules/variable_default_values_are_correctly_typed_error.rb, lib/graphql/static_validation/rules/variable_names_are_unique_error.rb, lib/graphql/static_validation/rules/variable_usages_are_allowed_error.rb, lib/graphql/static_validation/rules/variables_are_input_types_error.rb, lib/graphql/static_validation/rules/variables_are_used_and_defined_error.rb
This allows better reporting of codes without the need to use `to_h`. It's also better for subclasses as they can modify if they need to. Which for fine grained reporting they would want to.
I'm sure I had good reasons to make this private originally, but use cases now show this would be a much better solution.
=> Allow code to be accessed outside of the errors

lib/graphql/schema/enum_value.rb, spec/graphql/schema/enum_spec.rb, spec/support/jazz.rb
Hi there,
I don't know if it's a feature or a bug, but `false` used to be an accepted `:value` argument in enum values, and didn't work when I switched to the latest 1.9.0.pre1 build and the class based schema.
This PR just allows `false` as an enum custom ruby value :
```ruby
class Family < BaseEnum
description "Groups of musical instruments"
value "SILENCE", "Makes no sound", value: false
end
```
I added an assertion in the test that seemed right to me.
I'm available to update the PR code if needed !
Thanks
=> allow using false as enum values :value argument

lib/graphql/language/nodes.rb, lib/graphql/language/parser.rb, lib/graphql/language/parser.y, spec/graphql/schema/build_from_definition_spec.rb
This is so, if you parse a schema file, then want to point back to that file for where types were defined, you can get the _right_ line number.
cc @cjoudrey
=> Add ast_node.definition_line for build_from_definition

lib/graphql/language/visitor.rb
These arrays can really add up. When I designed this API, I didn't know that `return a,b` makes an Array 😖
=> Reduce arrays when we have throw-away return values

lib/graphql/execution/interpreter/hash_response.rb, lib/graphql/execution/lookahead.rb, lib/graphql/internal_representation/rewrite.rb, lib/graphql/language/parser.rb, lib/graphql/language/parser.y, lib/graphql/language/printer.rb, lib/graphql/language/visitor.rb, lib/graphql/query.rb, lib/graphql/query/arguments_cache.rb, lib/graphql/query/validation_pipeline.rb, lib/graphql/schema/field.rb, lib/graphql/schema/mutation.rb, lib/graphql/static_validation/base_visitor.rb, lib/graphql/static_validation/definition_dependencies.rb, lib/graphql/static_validation/literal_validator.rb, lib/graphql/static_validation/rules/fields_have_appropriate_selections.rb, lib/graphql/static_validation/rules/fields_will_merge.rb, lib/graphql/static_validation/validator.rb
Enumerable#none? was being used without a block to check if enumerables were empty, even though its behaviour is documented as
> If the block is not given, none? will return true only if none of the collection members is true.
so `Enumerable#none?` should only be used if this is actually the behaviour we want.  A comment in the code (`if path.size == 0 # faster than #none?`) both shows that this is significant to performance and that `none?` was being used when `empty?` was more appropriate.
Let me know if any of the replaced `none?` calls were actually needed to handle falsey values.  If so, then the tests should reflect this.
=> performance: Replace use of Enumerable#none? without a block with empty?

Appraisals, gemfiles/rails_3.2.gemfile, gemfiles/rails_4.1.gemfile, gemfiles/rails_4.2.gemfile, gemfiles/rails_5.0.gemfile, gemfiles/rails_5.1.gemfile, gemfiles/rails_5.2.gemfile, lib/graphql/schema/field.rb, lib/graphql/types/relay/node_field.rb, lib/graphql/types/relay/nodes_field.rb, spec/graphql/execution/interpreter_spec.rb
Add a warning for legacy nodes fields  but try to support it. Improve docs. 
closes #2082
=> Better node field compat with interpreter

guides/pro/authorization.md
Before: `GraphQL::Pro` integrates has out-of-the-box
After: `GraphQL::Pro` integrates out-of-the-box
=> Fix grammar error

guides/type_definitions/field_extensions.md, lib/graphql/schema/field.rb, spec/graphql/schema/field_extension_spec.rb
Oops, previously an extension could _access_ but not _modify_ a user-returned Promise. Now it can.
=> Field extensions access the resolver's return value

lib/graphql/analysis/ast/visitor.rb, spec/graphql/analysis/ast_spec.rb
The AST visitor is a special case visitor that only visits the selected operation of a query (what will actually be ran), which emulates was the Internal Representation used to do. The irep also took care of queries with no selected operations, which was missing here.
This PR returns early when no @document is present for the visitor (when there was no selected operation on the query)
=> Handle visitor when no operation is selected

lib/graphql/query/arguments.rb, spec/integration/rails/graphql/relay/mutation_spec.rb
`GraphQL::Schema::InputObject` instances are not unwrapped in `GraphQL::Query::Arguments`
Without a change it produces the following value instead of `hash`. 
```
#<#<Class:0x00007f925e6910c0>:0x00007f9266bc45f8 @context=#<Query::Context ...>, @arguments=#<#<Class:0x00007f9266b3f010>:0x00007f9266bc4580 @argument_values={"something"=>#<GraphQL::Query::Arguments::ArgumentValue:0x00007f9266bc4490 @key="something", @value="string", @definition=#<GraphQL::Argument:0x00007f925e690800 @prepare_proc=GraphQL::Argument::DefaultPrepare, @name="something", @clean_type=String, @dirty_type=#<Proc:0x00007f925e6907b0@/Users/evgeniydemin/RubymineProjects/graphql-ruby/lib/graphql/schema/argument.rb:88 (lambda)>, @description=nil, @metadata={:type_class=>#<GraphQL::Schema::Argument:0x00007f925e690d28 …
```
=> Fix unwrapping of InputObject

lib/graphql/static_validation/rules/argument_literals_are_compatible.rb, spec/graphql/static_validation/rules/argument_literals_are_compatible_spec.rb
Lists in GraphQL can omit the square brackets if there's only one item but the validation code was assuming it would be an array.
This coerces the node's `value` to ensure it is an array.
Note: I figured there might be a more proper fix for this in a different place but it can't be in the parser since there's no knowledge of the argument's type (correct me if I'm wrong). Is there another place I'm not thinking of?
This is also branched off of `v1.8.13`. If this is acceptable, could we backport and do a new 1.8.14 release? (since master is on 1.9 now)
=> Fix #2085 - Ensure lists are arrays

lib/graphql/execution/interpreter/resolve.rb, lib/graphql/execution/interpreter/runtime.rb, spec/graphql/execution/interpreter_spec.rb
Oops, make sure that mutation root selections are evaluated in sequence, so that each root field and its subselections are evaluated _before_ proceeding to the next mutation. (Otherwise the reads that follow a mutation might not reflect the state that the mutation had just created!)
=> Interpreter: Sequential mutation root fields

guides/type_definitions/field_extensions.md, lib/graphql/schema/field.rb, lib/graphql/schema/field/connection_extension.rb, lib/graphql/schema/field_extension.rb, spec/graphql/schema/field_extension_spec.rb
Renamed to reflect it's new role returning a value for execution (since #2092), also update docs
=> Rename FieldExtension#before_resolve -> FieldExtension#resolve

CHANGELOG.md
Fixed a typo in the contributing guides.
=> Fix typo compat -> compatibility[ci skip] 

lib/graphql/query/arguments.rb, spec/integration/rails/graphql/relay/mutation_spec.rb
This is a copy of https://github.com/rmosolgo/graphql-ruby/pull/2094 for `1.8.x` branch.
`GraphQL::Schema::InputObject` instances are not unwrapped in `GraphQL::Query::Arguments`
Without a change it produces the following value instead of `hash`.
```
#<#<Class:0x00007f925e6910c0>:0x00007f9266bc45f8 @context=#<Query::Context ...>, @arguments=#<#<Class:0x00007f9266b3f010>:0x00007f9266bc4580 @argument_values={"something"=>#<GraphQL::Query::Arguments::ArgumentValue:0x00007f9266bc4490 @key="something", @value="string", @definition=#<GraphQL::Argument:0x00007f925e690800 @prepare_proc=GraphQL::Argument::DefaultPrepare, @name="something", @clean_type=String, @dirty_type=#<Proc:0x00007f925e6907b0@/Users/evgeniydemin/RubymineProjects/graphql-ruby/lib/graphql/schema/argument.rb:88 (lambda)>, …
```
=> Fix unwrapping the input with InputObject

lib/graphql/schema/resolver.rb, spec/graphql/schema/resolver_spec.rb
=> Correctly pass loads: errors to the resolver's handler

lib/graphql/schema.rb, spec/graphql/execution/lazy_spec.rb
Try again to fix #1867 , cherry-picking a commit from 1.9 (38148d1c81076e011202b307c1879aaad84e6da0)
=> [1.8] Fix direct calls to .sync_lazy

lib/graphql/schema/field.rb, spec/graphql/schema/member/scoped_spec.rb
Fixes #2114 
Interestingly, support for `extensions:` with legacy resolve procs was already _halfway_ there. It just had to be ported to the other kind of resolution.
=> Support extensions with resolve procs

lib/graphql/schema/field/scope_extension.rb, spec/graphql/schema/member/scoped_spec.rb
When a field returns `nil`, don't try to apply a scope to it.
Fixes #2129
=> Fix scoping nil

lib/graphql/subscriptions.rb
See: #1882 
There's a bug when attempting to assign the field, it's using the hard-coded `Subscription` string instead of pulling the subscription from the schema.
This fixes it.
=> Fix bug in subscriptions#trigger

.rubocop.yml, lib/graphql/analysis/ast/max_query_complexity.rb, lib/graphql/analysis/ast/query_complexity.rb
AST::QueryComplexity has two `#result` methods so this PR fixes it.
=> fix duplicate method in G::A::A::QueryComplexity

lib/graphql/query.rb, spec/graphql/subscriptions_spec.rb
Currently, subscriptions don't work (at least with `ActionCable`) if you're passing in a `document` rather than the explicit query string. Eg. we've overridden `execute` on our schema to look something like this:
```ruby
def execute(query_string, **kwargs)
document = GraphQL.parse(query_string)
super(nil, document: document, **kwargs)
end
```
This works great until you try to pull in subscriptions, which will start (somewhat quietly) failing with a message saying something to the effect of "query string not present". Further research pointed me to this:
https://github.com/rmosolgo/graphql-ruby/blob/7fc54bf322ed9cde9db594c519ae41539d41b33b/lib/graphql/subscriptions/action_cable_subscriptions.rb#L128-L136
Where the relevant code is the call to `query.query_string`, which if you don't pass …
=> Get query string from document if it wasn't passed in explicitly to `execute`

lib/graphql/execution/interpreter/runtime.rb, lib/graphql/tracing.rb, lib/graphql/tracing/platform_tracing.rb, spec/graphql/tracing/new_relic_tracing_spec.rb
Fixes #2153  
The problem is, not _all_ fields have `.owner`s. Some fields are built before the owner is available (ok, probably just `Types::Relay::Node{s}Field`). 
So, we can get the owner from here. Also, I wouldn't be surprised if mutation fields had the wrong owner, since those use `add_field` too. This will fix the situation here, but add_field might need more work down the line.
=> Thread `owner:` through field tracing

lib/graphql/query/arguments.rb, spec/graphql/schema/argument_spec.rb
Prevent argument names like the ones below from overwriting existing methods on `GraphQL::Query::Arguments`.
```ruby
field :field, String, null: false do
argument :to_h, String
argument :keys, String
end
```
This prevents errors like this:
> NoMethodError: undefined method `any?' for nil:NilClass
>    /home/gabrielx/.rvm/rubies/ruby-2.5.3/lib/ruby/2.5.0/forwardable.rb:227:in `any?'
>    /home/gabrielx/projects/oss/graphql-ruby/lib/graphql/schema/field.rb:573:in `to_ruby_args'
And this:
> NoMethodError: undefined method `key?' for nil:NilClass
>    /home/gabrielx/projects/oss/graphql-ruby/lib/graphql/schema/field.rb:579:in `block in to_ruby_args'
>    /home/gabrielx/projects/oss/graphql-ruby/lib/graphql/schema/field.rb:577:in `each'
=> Prevent argument names from overwriting Arguments methods

lib/graphql/static_validation/base_visitor.rb, spec/graphql/static_validation/rules/argument_literals_are_compatible_spec.rb, spec/graphql/static_validation/rules/arguments_are_defined_spec.rb, spec/graphql/static_validation/rules/required_input_object_attributes_are_present_spec.rb
Fixes #2160 
`is_list = @argument_definitions.last&.type&.list? == true` feels a bit smelly, is there a more idiomatic way to achieve the same result?
=> Include array indices in error paths

javascript_client/subscriptions/ActionCableLink.js
We ran into an issue where Apollo is not notified when sending bad queries that return errors but no data.
=> Fix ActionCableLink when there are errors but no data

javascript_client/sync/prepareRelay.js
Relay compilers generated files exports changed from
```
module.exports = { ..., name }
```
to
```
module.exports = { ..., params: { name } }
````
=> Relay 2.0.0 support

guides/queries/tracing.md, lib/graphql/tracing/data_dog_tracing.rb
Datadog offers a trace search and analytics feature, which can make it easy to find and analyze measurements made by the tracing in GraphQL.
This pull request adds an `event_sample_rate` tag, to the span, if configured & available, so the trace will be sampled and indexed for use in search and analytics.
GraphQL users implementing Datadog's `ddtrace` gem version >= 0.20.0 will see the benefit of this new feature, while others using older versions of `ddtrace` will remain backwards compatible.
=> Add analytics tag to Datadog tracing

lib/graphql/schema/field_extension.rb, spec/graphql/schema/field_extension_spec.rb
with updated tests, though I am not sure it's the good way to test it
related ticket : https://github.com/rmosolgo/graphql-ruby/issues/2182
=> provide empty hash as default option for field resolvers

lib/graphql/subscriptions/action_cable_subscriptions.rb
A simple typo that leads to memory leaks!
=> Doc: fix ActionCableSubscriptions channel example

lib/graphql/backtrace/table.rb, lib/graphql/language/document_from_schema_definition.rb, lib/graphql/schema.rb, lib/graphql/schema/argument.rb, lib/graphql/schema/build_from_definition.rb, lib/graphql/schema/build_from_definition/resolve_map.rb, lib/graphql/schema/build_from_definition/resolve_map/default_resolve.rb, lib/graphql/schema/directive.rb, lib/graphql/schema/enum.rb, lib/graphql/schema/enum_value.rb, lib/graphql/schema/field.rb, lib/graphql/schema/input_object.rb, lib/graphql/schema/interface.rb, lib/graphql/schema/member.rb, lib/graphql/schema/member/build_type.rb, lib/graphql/schema/member/has_ast_node.rb, lib/graphql/schema/member/has_fields.rb, lib/graphql/schema/object.rb, lib/graphql/schema/scalar.rb, lib/graphql/schema/type_expression.rb, lib/graphql/schema/union.rb, lib/graphql/schema/validation.rb, spec/graphql/schema/build_from_definition_spec.rb, spec/graphql/schema/warden_spec.rb, spec/integration/rails/graphql/schema_spec.rb, spec/support/error_bubbling_helpers.rb
This is a pretty big change for anyone using `.from_definition` to build their schemas. Now, `.from_definition` builds a class-based schema out of dynamically-created, anonymous classes. 
That means, at _least_, that the `ctx` passed into resolvers will be a `GraphQL::Query::Context` instead of a `GraphQL::Query::Context::FieldResolutionContext`. Resolvers won't have access to metadata anymore. Maybe we'll need a followup to somehow support `extras`.
=> [1.10] Schema.build_from_definition should make classes

lib/graphql/execution/lookahead.rb
Support was added in https://github.com/rmosolgo/graphql-ruby/pull/2068
=> Update Lookahead docs: remove fragment note

lib/graphql/integer_encoding_error.rb, lib/graphql/types.rb, lib/graphql/types/big_int.rb, lib/graphql/types/int.rb, spec/graphql/types/big_int_spec.rb
Follow up for #2101 , for out-of-the-box support for large values.
=> Add Types::BigInt

lib/graphql/language/token.rb, lib/graphql/query/arguments.rb, lib/graphql/schema/argument.rb, lib/graphql/schema/field.rb
While memory profiling our application, I noticed a lot of duplicated strings being help by graphql structs:
```
Retained String Report
1600  "userErrors"
391  /tmp/bundle/ruby/2.5.0/gems/graphql-1.9.4/lib/graphql/schema/member/build_type.rb:120
391  /tmp/bundle/ruby/2.5.0/gems/graphql-1.9.4/lib/graphql/schema/member/has_fields.rb:45
391  /tmp/bundle/ruby/2.5.0/gems/graphql-1.9.4/lib/graphql/schema/traversal.rb:206
390  /tmp/bundle/ruby/2.5.0/gems/graphql-1.9.4/lib/graphql/schema/object.rb:123
25  /tmp/bundle/ruby/2.5.0/gems/graphql-1.9.4/lib/graphql/language/lexer.rb:1386
9  /tmp/bundle/ruby/2.5.0/gems/graphql-client-0.14.0/lib/graphql/client/schema/object_type.rb:57
1  /tmp/bundle/ruby/2.5.0/bundler/gems/json-b5f423ccf08f/lib/json/common.rb:155
1 …
```
=> Use String#-@ in key places to reduce string duplications

lib/graphql/language/parser.rb, lib/graphql/language/parser.y, spec/graphql/language/parser_spec.rb
I use `GraphQL.parse()` to prepare compiled GraphQL documents, and found that it raises NoMethoderror for `nil` by `query_string.unpack("c*")`.
I think it should raise `GraphQL::ParseError` for such cases. What do you think of it?
=> raise ParseError for GraphQL.parse(nil)

guides/queries/tracing.md
In `GraphQL::Tracing::DataDogTracing`, we fetch the option `:service`
https://github.com/rmosolgo/graphql-ruby/blob/master/lib/graphql/tracing/data_dog_tracing.rb#L42
However, the docs currently [incorrectly] specify that the param is named `:service_name`.
I've updated the docs to be accurate!
Before:
https://github.com/rmosolgo/graphql-ruby/blob/master/guides/queries/tracing.md#datadog
After:
https://github.com/rmosolgo/graphql-ruby/blob/564b4f51046118a13571b4f3c9dbf0f2241b7486/guides/queries/tracing.md#datadog
(note that the example in the getting started guide is correct. https://github.com/DataDog/dd-trace-rb/blob/master/docs/GettingStarted.md#graphql)
=> [Documentation] Naming Fix - DataDog Tracing Docs

lib/graphql/query/variable_validation_error.rb, spec/graphql/query/executor_spec.rb, spec/graphql/schema/warden_spec.rb
When a GraphQL mutation gets invalid input, we raise an error with a message like
```
Variable input of type <InputType>! was provided invalid value
```
Reproducing these issues is not always obvious because which field was
invalid is not clear.
This change updates the error message to include the path to the invalid
field when it's present. The message now looks like:
```
Variable input of type <InputType>! was provided invalid value for field foo
```
Or
```
Variable input of type <InputType>! was provided invalid value for field 0.foo
```
if the field was in an array field.
There's likely some refactorings to be done here so I'm very open to
feedback. Thank you!
=> Add more context to input validation error message

lib/graphql/schema/field.rb, spec/graphql/function_spec.rb, spec/graphql/schema/object_spec.rb
This PR fixes an issue where `GraphQL::Function` stopped working for connections after v1.9.0, also added additional tests to cover `GraphQL::Function`
reference https://github.com/rmosolgo/graphql-ruby/issues/2223
=> GraphQL::Schema::Field#scoped? checking presence of return type

lib/graphql/execution/execute.rb, lib/graphql/schema/field.rb, lib/graphql/schema/object.rb, lib/graphql/unauthorized_field_error.rb, spec/graphql/authorization_spec.rb
This allows to extend the use of `authorized?` in resolvers and objects by forwarding `UnauthorizedFieldError` and `UnauthorizedError` to `unauthorized_field` and `unauthorized_object` respectively.
Coming from #2157
=> Forwarding field and object unauthorized errors

lib/graphql/types/relay/base_edge.rb, spec/graphql/schema/introspection_system_spec.rb, spec/support/non_nullable_dummy.rb
As discussed in the issue #1217, nullable requires extra code in typed languages, so it is important to have a way to avoid it. I submitted this PR because our private project ran into that problem.
=> Add null option to node_type of Relay::BaseEdge

lib/graphql/schema/relay_classic_mutation.rb, spec/graphql/schema/relay_classic_mutation_spec.rb, spec/support/jazz.rb
The interpreter runtime is recursively unwrapping inputs to `GraphQL::Schema::RelayClassicMutation` which is inconsistent with the old runtime. I'm assuming this was unintentional (at least it wasn't documented in the list of incompatibilities 😄) so this PR updates`GraphQL::Schema::RelayClassicMutation`to only unwrap the the top level of the input when using the interpreter.
=> Interpreter shouldn't recursively unwrap RelayClassicMutation inputs

lib/graphql/execution/interpreter/runtime.rb, lib/graphql/tracing.rb
This adds the current `GraphQL::Query` to tracing events for `execute_field` and `execute_field_lazy` when running with the interpreter which is useful for accessing the query, query context, etc. (see #2167 for one example use case). With the old runtime this information is available via the `context` key which has a `GraphQL::Query::Context::FieldResolutionContext` instance.
=> Include query in interpreter tracing events for execute_field and execute_field_lazy

lib/graphql/schema/validation.rb
While memory profiling our application boot I noticed an impressive amount of allocations coming from the `Validation.validate` method:
```
allocated objects by location
...
713390  /tmp/bundle/ruby/2.5.0/gems/graphql-1.9.4/lib/graphql/schema/validation.rb:16
```
700k allocations is quite a lot for a method that simply iterate over a constant hash. The cause is the many array concatenations inside the first `reduce`
By rewriting the method in a more imperative way it no longer allocated anything.
@rmosolgo
=> Reduce allocations in Schema::Validation.validate()

lib/graphql/query/arguments.rb
While memory profiling our application boot I noticed an important amount of allocations commit from `arguments.rb`:
```
allocated memory by location
...
16.51 MB  /tmp/bundle/ruby/2.5.0/gems/graphql-1.9.4/lib/graphql/query/arguments.rb:22
...
12.18 MB  /tmp/bundle/ruby/2.5.0/gems/graphql-1.9.4/lib/graphql/query/arguments.rb:13
```
Line 22 is the `Class.new()`, I can't do much about it, however for line 3 I think they can easily be avoided.
`Module#instance_methods` instantiate a new array on each call, and since `Object.instance_methods` is quite big on an empty Rails app, it can quickly amount to an important amount.
Since we access that array to do a lookup, `Module#method_defined?` is a much better replacement. First it doesn't allocate an array, …
=> Reduce memory allocations in Arguments.construct_arguments_class

guides/authorization/authorization.md, guides/mutations/mutation_authorization.md, lib/graphql/schema.rb, spec/integration/rails/graphql/schema_spec.rb, spec/support/dummy/schema.rb
This resolves #2251. Discussion on the issue is over there. 
- Documentation improvements to resolve #2231 
Allows `.validate` to accept a `context:` hash argument. 
This is passed to Query#initialize and in the function and the rest of the machinery should work as expected.
- Documentation on the context args?
- Test is a little indirect 
- Not sure if I ran all the tests correctly, assuming there's a PR CI
=> Add the ability to pass in context on Schema.validate

lib/graphql/schema/rescue_middleware.rb, spec/graphql/query/executor_spec.rb, spec/graphql/schema/rescue_middleware_spec.rb
Hi there. 
First of all this gem is AWESOME. Really appreciate the hard work you guys put in.
So let's get right into the topic. We are using `rescue_from` in our schema class like this↓ as a safety net to make sure responses are always in the same form.
```ruby
class SomeSchema < GraphQL::Schema
rescue_from(StandardError) { 'INTERNAL_SERVER_ERROR' }
...
end
```
But we are using `extensions` entry to expand error responses in other fields.
So in order to get every error forms together we started to think that we need to be able to expand an error form with `extensions` entry in `rescue_from` method too like this↓
```ruby
class SomeSchema < GraphQL::Schema
rescue_from(StandardError) { GraphQL::ExecutionError.new('internal server error', extensions: { code: 'INTERNAL_SERVER_ERROR' }) }
... …
```
=> extend GraphQL::Schema::RescueMiddleware#attempt_rescue

lib/graphql/introspection/input_value_type.rb, spec/graphql/introspection/input_value_type_spec.rb
Fixes the introspection payload for default values where the type is a list of enums.
Example of issue:
```
{
"name": "affiliations",
"description": "Array of viewer's affiliation options for repositories returned from the connection. For example, OWNER will include only repositories that the current viewer owns.",
"type": {
"kind": "LIST",
"name": null,
"ofType": {
"kind": "ENUM",
"name": "RepositoryAffiliation",
"ofType": null
}
},
"defaultValue": "[\"OWNER\", \"COLLABORATOR\"]"
},
```
However:
> defaultValue may return a String encoding (using the GraphQL language) of the default value.
(https://graphql.github.io/graphql-spec/June2018/#sec-The-__InputValue-Type)
This was fixed a while ago for enum values, but the list edge case remained.
=> Fix list enum default values in introspection

lib/graphql/execution/lookahead.rb, spec/graphql/execution/lookahead_spec.rb
`Lookahead#selections` wasn't very suitable for iterating over selections that had arguments or type conditional selections, since it neither exposed these on the returned lookahead objects nor even consider these aspects when trying to merge duplicate selections.
This PR changes `Lookahead#selections` to no longer be based on `Lookahead#selection`, since that was searching for selections with the same name without considering aliases or whether selections type conditional.  It also seemed like a performance concern, since `Lookahead#selections` was calling `Lookahead#selection` for each selection, which would then do a nested iteration over all the selections, which unnecessarily increased the time complexity of `Lookahead#selections`.  Instead, I extracted out the argument matching into …
=> Avoid merging distinct aliased selections in Lookahead

javascript_client/sync/__tests__/generateClientTest.js, javascript_client/sync/generateClient.js, javascript_client/sync/index.js, javascript_client/sync/prepareProject.js
Hey @rmosolgo Happy Friday. I believe this is a typo. 
I finally got to using the `generateClient` function you exposed in https://github.com/rmosolgo/graphql-ruby/pull/1941 and noticed that in one place, there's a reference to `options.clientName` but it seems to be passed as `options.client` and documented as such. 
Btw, the `generateClient` function works brilliantly. 
Just additional context for posterity:
- The sync generates `operation-store-client.js` which has to be consumed by the Apollo client. 
- I'd like to make a webpack plugin to sync queries whenever a `.graphql` file changes in development. So the dev keeps making changes and keeps using persisted queries even in dev. We have this working with a custom webpack script.  
- The hard part is that since the sync task writes to …
=> Typo in referencing an option

guides/queries/complexity_and_depth.md
This recently bit me as I added a `max_complexity` restriction to my schema and my introspection queries began failing.
My assumption that fields are all scored as complexity "1" by default is based on the code here: https://github.com/rmosolgo/graphql-ruby/blob/a9f334b171a6caaa64bac683f54cedea76d91b28/lib/graphql/schema/resolver.rb#L233
=> [Docs] Add note about default complexity.

guides/related_projects.md
I wrote a blog post a while back which goes over how to parallelize the execution of graphql-ruby resolvers by utilizing the concurrent-ruby library's Future class. It took a few tries to finally figure out how to get this to work, so I think it would be valuable for others in the same situation looking for a speed boost.
Let me know what you think! 😄
=> Add link to blog post on parallel resolvers

lib/graphql/query/context.rb
- reduce the hash allocations by using positional arguments instead of keyword arguments
The object allocations were measured with the allocation_tracer gem and ruby 2.5.0.
This reduces the memory allocated by our application by 100 MB when the response contains a large number of objects (16K in our case).
=> Reduce memory and allocations

.rubocop.yml, Rakefile, graphql.gemspec, guides/_plugins/api_doc.rb, lib/graphql/static_validation/base_visitor.rb, spec/graphql/execution/lookahead_spec.rb
Oops, Travis started installing Bundler 2 (which requires Ruby 2.3+) by default, and I really couldn't figure out how to run Bundler 1 instead, so I bumped the CI Ruby versions to 2.3+. But there's no reason we can't support Ruby 2.2, except that since we didn't have CI, some incompatible syntax was introduced. 
I decreased the Rubocop Ruby version which found the error in #2235 and a couple others.
=> Support ruby 2.2

.travis.yml, Gemfile, lib/graphql.rb, lib/graphql/language/token.rb, lib/graphql/query/arguments.rb, lib/graphql/schema/argument.rb, lib/graphql/schema/field.rb
Oops, I intend to support Ruby 2.2, but this was breaking it. (The real problem is, I can't figure out how to run Ruby 2.2 on Travis CI.) I ran Ruby 2.2 locally and it passed after these changes. 
```
~/code/graphql-ruby $ ruby -v
ruby 2.2.8p477 (2017-09-14 revision 59906) [x86_64-darwin16]
~/code/graphql-ruby $ be rake test
1381 tests, 5871 assertions, 0 failures, 0 errors, 0 skips
```
=> Backport String#-@ for Ruby 2.2

lib/graphql/execution/multiplex.rb, spec/graphql/execution/multiplex_spec.rb
Seems like `multiplex` does not support `GraphQL::Analysis::AST::MaxQueryComplexity`, it's only automatically add `GraphQL::Analysis::MaxQueryComplexity`:
https://github.com/rmosolgo/graphql-ruby/blob/85554e8f1c9bfa499fe14a912b92de8c83d99932/lib/graphql/execution/multiplex.rb#L177-L179
Failed test `TESTING_INTERPRETER=yes bundle exec rake test TEST=spec/graphql/execution/multiplex_spec.rb`:
```
Error:
GraphQL::Execution::Multiplex::max_complexity#test_0001_can successfully calculate complexity:
NoMethodError: undefined method `new' for #<GraphQL::Analysis::MaxQueryComplexity:0x00005638555aba20>
/media/sf_Ruby/!Other/graphql-ruby/lib/graphql/analysis/ast.rb:29:in `block in analyze_multiplex'
/media/sf_Ruby/!Other/graphql-ruby/lib/graphql/analysis/ast.rb:29:in `map' …
```
=> Support `max_complexity` AST analysis in multiplex 

lib/generators/graphql/install_generator.rb, lib/generators/graphql/templates/base_field.erb, lib/graphql/version.rb
In the documentation for Mutation Classes in 1.9.3 it specifies that you should build a Base Mutation.
https://graphql-ruby.org/mutations/mutation_classes.html#example-mutation-class
In the example mutation class it specifies:
field_class Types::BaseField
My install of graphql-ruby did not create a Types::BaseField at types/base_field.rb.
Therefore it throws an error when attempting to load graphiql:
```
uninitialized constant Types::BaseField
Did you mean?  Types::BaseInterface
```
The answer is no, no I did not.
The fix is to add the base_field.rb in the types/ directory.  This should be auto generated.  This patch makes it so.
```
module Types
class BaseField < GraphQL::Schema::Field
def resolve_field(obj, args, ctx)
resolve(obj, args, ctx)
end
end
end
```
=> Autogenerate base_field.rb

.travis.yml, spec/graphql/internal_representation/rewrite_spec.rb
This one obscure test fails. Nobody has ever reported a bug, so let's just skip it. It'll be removed in GraphQL-Ruby 2.0 anyways.
Fixes #1295
=> Test on Ruby 2.6

lib/graphql/analysis/ast/visitor.rb, spec/graphql/analysis/ast_spec.rb
Closes #2217 
Changes `argument_definition` to return the current argument definition and adds `previous_argument_definition`.
@rmosolgo I'm guessing this is what you had in mind?
cc @xuorig
=> Update AST visitor argument definition methods

guides/schema/introspection.md, lib/graphql/schema.rb, lib/graphql/schema/introspection_system.rb, spec/graphql/schema/introspection_system_spec.rb, spec/integration/rails/graphql/schema_spec.rb, spec/support/jazz.rb
That might be helpful to turn off introspection entry points, especially in the production environments. The shortest way to do it I found (given the fact that we don't have any custom entry points):
```ruby
if Rails.env.production?
introspection(Module.new do
class EntryPoints < GraphQL::Introspection::EntryPoints
def self.authorized?(*)
false
end
end
end)
end
end
```
It looks a little bit verbose and does not hide entry points from the schema, just restricts the access. I've added a shorthand method `#disable_introspection_entry_points` which allows to skip generating entry points:
```ruby
disable_introspection_entry_points Rails.env.production?
end
```
=> Add method for disabling introspection entrypoints

javascript_client/package.json, javascript_client/yarn.lock
Have been getting warnings after upgrading graphql.
`warning "graphql-ruby-client > apollo-link@1.0.5" has incorrect peer dependency "graphql@^0.11.3".`
Of the client side changes only the graphql package has breaking changes and none of them should effect this.
Associated change logs:
graphql: https://github.com/graphql/graphql-js/releases
apollo-link: https://github.com/apollographql/apollo-link/blob/master/packages/apollo-link/CHANGELOG.md
glob: https://github.com/isaacs/node-glob/blob/master/changelog.md (though they dont seem to document patch updates)
dev dependencies:
jest: https://github.com/facebook/jest/blob/master/CHANGELOG.md
nock: https://github.com/nock/nock/releases?after=v10.0.5
=> upgrade js packages

lib/graphql/schema/subscription.rb, spec/graphql/schema/subscription_spec.rb
As of now, if you want to make a scoped subscription using the new `Subscription` class, the only way to do so is the following:
```ruby
class MySubscription < BaseSubscription
...
end
```
```ruby
class SubscriptionType < GraphQL::Schema::BaseObject
field :my_subscription, subscription: MySubscription, subscription_scope: :current_user_id
end
```
My proposal is to add a `subscription_scope` method to the `Subscription` class so that all the options for the subscription can be defined within the class itself (more like the `Query` or `Mutation` class definitions). Using this change, the same example would become
```ruby
class MySubscription < BaseSubscription
...
subscription_scope :current_user_id
end
```
```ruby
class SubscriptionType < GraphQL::Schema::BaseObject
field :my_subscription, …
```
=> Add `subscription_scope` method to `Subscription` class

guides/relay/object_identification.md, spec/integration/mongoid/star_trek/schema.rb, spec/support/star_wars/schema.rb
In [Integration testing guide](https://github.com/rmosolgo/graphql-ruby/blame/d491c1722f4920b346f4f807ed02878e834a7fa7/guides/testing/integration_tests.md#L56), I found `MySchema.id_from_object(post, Types::Post, {}))`  which was exactly what I needed in a mutation integration test. 
(I had to use the blame view to get line highlighting on Markdown files)
But it seems that normally `.id_from_object` receives a type_definition(`SomeType.graphql_definition`) instead of the type class (`SomeType < BaseObject`)
Subtle difference: 
```ruby
SomeType.name # "My::Module::Namespace::SomeType"
SomeType.graphql_definition.name # "Some"
```
In the former case, it's a bit iffy that because the fully qualified name leaks into the IDs vs the GraphQL type name, which is usually already exposed.
I saw two …
=> Use #graphql_name over name in case a Type class is given

readme.md
Diving into the graphql-ruby library was a bit frustrating because the "Getting Started" link in the readme didn't go to the Getting Started page on the website, but to the home page. 
Eventually I found it, but maybe this will save others the trouble.
=> Correct link to Getting Started from readme.md

guides/pro/authorization.md
In this pull request, I changed the documentation examples to class-based syntax since the block definition syntax is deprecated.
=> Change Authorization doc examples to class based syntax

lib/graphql/schema/input_object.rb, spec/graphql/schema/input_object_spec.rb, spec/integration/rails/graphql/input_object_spec.rb
This is a continuation of https://github.com/rmosolgo/graphql-ruby/pull/2313. I accidentally deleted the fork so a new PR is needed :smiley_cat:. 
I've used the `#to_hash` approach here to be consistent with an accepted PR https://github.com/rmosolgo/graphql-ruby/pull/1955 that implements `#to_hash` in context. 
- You can call `input_object.to_json` now without a stack too deep error. 
- You can also splat input objects to get their hashes
=> Implement #to_hash so input objects can be serialized/splatted

lib/graphql/relay/array_connection.rb, spec/integration/rails/graphql/relay/array_connection_spec.rb
The cursors for the items for ArrayConnection are generated by a 1 based index. (Index of origin is 1, not zero). 
However, when we compute the value for `has_next_page`, we were considering that it's a zero-based index. 
So it would return incorrect `hasNextPage` when the `before` cursor belongs to the last element int the array. 
I wrote a spec which would fail on the master branch because of this error. 
https://github.com/rmosolgo/graphql-ruby/blob/bb70bd88988d5cdf66dc7aea7427eca91274de04/spec/integration/rails/graphql/relay/array_connection_spec.rb#L293-L306
When computing `has_next_page` value, consider the array to be based 1.
=> Fix incorrect hasNextPage value when the last cursor belongs to the last element in the array

lib/graphql/query.rb, spec/graphql/execution/instrumentation_spec.rb
Oops, a recent change broke the way that GraphQL-Pro's operation store interacts with runtime 🤦‍♂ . Should have had a test like this from the start!
=> Fix late query string assignment

lib/graphql/schema/argument.rb, lib/graphql/schema/input_object.rb, lib/graphql/schema/member/has_arguments.rb, lib/graphql/schema/resolver.rb, spec/graphql/schema/resolver_spec.rb
Oops, resolver arguments that used `loads:` didn't actually have a value in `@loads`.
=> Fix resolver loads

lib/graphql/argument.rb, lib/graphql/compatibility/lazy_execution_specification/lazy_schema.rb, lib/graphql/query/arguments.rb, lib/graphql/schema/argument.rb, lib/graphql/schema/build_from_definition.rb, lib/graphql/schema/loader.rb, spec/graphql/schema/argument_spec.rb, spec/graphql/schema/build_from_definition_spec.rb, spec/graphql/schema/input_object_spec.rb, spec/graphql/schema/loader_spec.rb, spec/support/dummy/schema.rb, spec/support/lazy_helpers.rb
Oops, we added a warning but no way to quiet it when it wasn't necessary. Fixes #2358
=> Add method_access: false to suppress warning about argument name

lib/graphql/schema/member/has_fields.rb, spec/graphql/schema/object_spec.rb
Help people do the right thing when a `field` conflicts with an important method name. 
Also, make it possible to dismiss the warning somehow :P 
Fixes #1648 
Fixes #1320
=> Warn for field names that conflict; include suggestion for name override

lib/graphql/schema/field.rb, lib/graphql/schema/resolver.rb, spec/graphql/schema/resolver_spec.rb
This code was moved from GraphQL-Pro to here because it's generally relevant, and besides, we can simplify `Field#authorized?` if we know that resolver classes do their own argument authorization. 
There's some chance this could be disruptive _if_: 
- Someone is using `loads:`
- Someone _doesn't want_ their loaded argument objects to be authorized automatically. (Previously they weren't, now they are.) 
I think this is a good improvement in any case, but maybe it could be pushed to 1.10 if it seems too disruptive. 
Fixes #2367 (which was worked around by the author)
=> When using a resolver, don't re-authorize arguments

Rakefile, lib/graphql/language/lexer.rb, lib/graphql/language/lexer.rl, spec/graphql/language/lexer_spec.rb
This is an attempt to resolve https://github.com/rmosolgo/graphql-ruby/issues/2373. 
```ruby
GraphQL.parse('{ t(x: """"""X"""""")}') # NoMethodError (undefined method `empty?' for nil:NilClass)
```
During the lexing phase, `""""""x""""""` will actually be read as: 
```ruby
GraphQL::Language::Lexer.tokenize('""""""x""""""')
=> [(STRING "" [1:1]), (IDENTIFIER "x" [1:7]), (STRING "" [1:8])] 
```
That brings us to the underlying problem.
```ruby
GraphQL::Language::Lexer.tokenize('"""""") # empty block string
NoMethodError: undefined method `empty?' for nil:NilClass
```
The fix is not to do extra processing when dealing with an empty block string.
=> Parse empty block strings correctly

lib/graphql/schema.rb, lib/graphql/schema/find_inherited_value.rb, lib/graphql/schema/member/base_dsl_methods.rb, lib/graphql/schema/member/relay_shortcuts.rb, lib/graphql/schema/resolver/has_payload_type.rb, lib/graphql/schema/subscription.rb, spec/graphql/analysis/analyze_query_spec.rb, spec/graphql/analysis/ast/max_query_complexity_spec.rb, spec/graphql/analysis/ast/max_query_depth_spec.rb, spec/graphql/analysis/max_query_complexity_spec.rb, spec/graphql/analysis/max_query_depth_spec.rb, spec/graphql/schema/catchall_middleware_spec.rb, spec/graphql/schema_spec.rb
This is a first stab at support for inheriting `GraphQL::Schema` settings (i.e. fixing #1627) e.g.
```ruby
class BaseSchema < GraphQL::Schema
use GraphQL::Tracing::NewRelicTracing
use GraphQL::Execution::Interpreter
use GraphQL::Analysis::AST
max_complexity 5000
end
class ServiceSchema < BaseSchema
end
class AdminSchema < BaseSchema
end
```
I took a pretty naive approach to the implementation and just leveraged the existing `find_inherited_method` method from`GraphQL::Schema::Member::BaseDSLMethods` to walk up the superclass chain looking for non-null setting values. It's a bit tedious and it's error prone as new settings are added but it works. There appears to be more generic frameworks for defining inheritable settings in `GraphQL::Schema::Member::AcceptsDefinition` and …
=> Schema class inheritance support

Rakefile, lib/graphql/language/lexer.rb, lib/graphql/language/lexer.rl, spec/graphql/language/lexer_spec.rb
@swalkinshaw @rmosolgo Found another one, though I'm a little less confident that my solution here is correct.
A string constant that is validly encoded initially, and also passes the `VALID_STRING` regex, can end up invalidly encoded after passing through `replace_escaped_characters_in_place`.
This PR just does a second check for `valid_encoding?` after that call, but potentially the real fix belongs in the `VALID_STRING` regex or the crazy mess that is `replace_escaped_characters_in_place`?
=> Fix another mishandling of unicode in the lexer

guides/development.md, lib/graphql/analysis/ast/query_complexity.rb, lib/graphql/analysis/ast/visitor.rb, lib/graphql/language/lexer.rb, lib/graphql/language/lexer.rl
When profiling some common queries in our application I noticed a large amount of memory was being allocated by the analysis process. The graphql gem allocated 713,654 bytes during the execution of the query with the top 5 allocations by file being:
```
257032  /Users/jturkel/.rvm/gems/ruby-2.6.3@dandelion/gems/graphql-1.9.6/lib/graphql/language/lexer.rb
110094  /Users/jturkel/.rvm/gems/ruby-2.6.3@dandelion/gems/graphql-1.9.6/lib/graphql/analysis/ast/query_complexity.rb
85112  /Users/jturkel/.rvm/gems/ruby-2.6.3@dandelion/gems/graphql-1.9.6/lib/graphql/language/nodes.rb
79456  parser.y
48400  /Users/jturkel/.rvm/gems/ruby-2.6.3@dandelion/gems/graphql-1.9.6/lib/graphql/static_validation/rules/fields_will_merge.rb
```
The worst offenders in lib/graphql/analysis/ast/query_complexity.rb were: …
=> Optimize complexity analysis memory usage

lib/graphql/static_validation/rules/required_arguments_are_present.rb, spec/graphql/static_validation/rules/required_arguments_are_present_spec.rb
If an argument is required, but not `visible?`, it should not cause an error for the query, because it _doesn't exist_ for the current query. 
Fixes #2392 and Fixes #1439
=> Fix error when required args are not visible

lib/graphql/schema/build_from_definition.rb, lib/graphql/schema/field.rb, lib/graphql/schema/member/has_fields.rb, spec/graphql/schema/object_spec.rb
It's nice to have warnings when things might go wrong. It's also nice to _not_ have warnings when nothing's going wrong 😬 
This test didn't fail on master, so I'm PR-ing 1.10-dev. I think it's because I ported `build_from_definition` on this branch.
=> Don't warn about field name conflicts when parsing a schema from SDL

lib/graphql/language/nodes.rb
Diff between the benchmarks with and without caching:
Query & validation:
```
--- a/no_cache
+++ b/cache
@@ -1,31 +1,31 @@
query     2.000  i/100ms
-               query     22.086  (± 4.5%) i/s -    110.000  in   5.003548s
+               query     22.323  (± 4.5%) i/s -    112.000  in   5.036334s
validate - introspection
-                        53.000  i/100ms
+                        56.000  i/100ms
validate - abstract fragments
-                       108.000  i/100ms
+                       112.000  i/100ms
validate - abstract fragments 2
-                        59.000  i/100ms
+                        60.000  i/100ms
validate - big …
```
=> Memoize generated GraphQL query strings

lib/graphql/schema.rb, spec/graphql/schema_spec.rb
I think a `.define`-based schema will choke if the root types are class-based.
=> Normalize root types when using define/class

lib/graphql/tracing/platform_tracing.rb
Profiling of some of our queries showed we were spending a decent amount of time and allocating a fair amount of memory generating field trace keys. Caching this information within the scope of a query execution shaved 5.8% off of our query latency and saved 1MB in memory allocations.
=> Avoid recomputation of field keys during tracing

guides/_plugins/api_doc.rb
=> Remove indentation from heredoc so markdown doesn't treat it like code

lib/graphql/schema.rb, spec/graphql/schema/printer_spec.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/2301
This will be fixed better in 1.10 when the class has its own AST node since it's built directly.
=> fix printing schema classes

lib/graphql/query.rb, spec/graphql/analysis/ast/max_query_complexity_spec.rb, spec/graphql/analysis/ast/max_query_depth_spec.rb, spec/graphql/analysis/max_query_complexity_spec.rb, spec/graphql/analysis/max_query_depth_spec.rb, spec/graphql/query_spec.rb
The [doc](https://graphql-ruby.org/queries/complexity_and_depth) states that passing an explicit `max_complexity` or `max_depth` of nil will disable any schema level settings for `max_complexity` or `max_depth` but that wasn't working. This should fix that :)
I also fixed a problem with my changes in #2384 invoking `GraphQL::Schema.max_depth=(new_value)` rather than `GraphQL::Schema.max_depth(new_value = nil)` and a similar problem for `max_complexity`.
=> Fix disabling of max_complexity and max_depth during query execution

lib/graphql/language/nodes.rb
I like it better when objects don't set internal state on other objects, so in these patches I've moved around the instance variable manipulation so that it's done inside the object rather than being done from the outside.
=> Just a couple clean-ups wrt ivars

lib/graphql/schema/member/has_fields.rb, spec/graphql/schema/object_spec.rb
For field definitions change how conflicting field names are checked. Instead of checking the `resolver_method`, check the field name directly using `original_name`.
With this change, you should be able to write the following:
```ruby
field :value, SomeType, null: false, resolver_method: :object # pass the object through no warning
field :object, SomeType, null: false, resolver_method: :resolve_object # override no warning
field :object, String, null: true, resolver_method: :object # warning because original_name and resolver_method match
field :object, SomeType, null: false # warning because object is conflicting field name
```
The gem, specifically in `has_fields.rb`, performs a check for every field being added to the schema to ensure that the field name does not conflict with some …
=> Make conflicting field name check use :original_name instead of :resolver_method

lib/graphql/coercion_error.rb, lib/graphql/static_validation/rules/argument_literals_are_compatible.rb, lib/graphql/static_validation/rules/argument_literals_are_compatible_error.rb, spec/graphql/static_validation/rules/argument_literals_are_compatible_spec.rb
The idea of Custom Scalars is great. 
In `raise GraphQL::CoercionError` used when the data is not correct, it seems better to be able to return optional keys and values to the client with `extensions`.
PR with reference to https://github.com/rmosolgo/graphql-ruby/issues/1621.
=> Add extensions in CoercionError

guides/fields/resolvers.md
I have tried using the example included, and get the error `undefined method 'argument' for Types::QueryType:Class`. After some investigation, the correct way seems to be to pass `self` to the block as a parameter.
=> Correct the example for using 'a class method to generate fields'

lib/graphql/analysis/ast/query_depth.rb, lib/graphql/analysis/query_depth.rb, spec/graphql/analysis/ast/max_query_depth_spec.rb, spec/graphql/introspection/directive_type_spec.rb, spec/graphql/introspection/introspection_query_spec.rb
According to a Slack conversation with @rmosolgo , the exclusion of introspective fields from query depth calculation may be a bug. 
This PR removes that exclusion so all fields are included in the query depth calculation. 
I am happy for it also to be conditional -ie. passing something like `include_all_fields: true` invokes this behaviour and the current behaviour (filtering out introspective fields) remains the default to ensure it doesn't unreasonably break functionality.
Please feel free to edit/comment.
=> Include introspective fields in query depth calculations

lib/graphql/introspection/input_value_type.rb, spec/graphql/introspection/input_value_type_spec.rb, spec/graphql/introspection/type_type_spec.rb, spec/graphql/schema/input_object_spec.rb
Previously, default values with enums were being (wrongly) quoted, like 
```
{a:"A", b:"B"}
```
Now, they're unquoted (like GraphQL enums), with some space: 
```
{a: A, b: B}
```
(Which is spec-compliant!)
=> Properly serialize enum default values of input objects

lib/graphql/static_validation/literal_validator.rb, lib/graphql/static_validation/rules/argument_literals_are_compatible.rb, spec/graphql/schema/list_spec.rb
Oops, our detection for errors from inner nodes wasn't handling non-nulls properly. 
fixes #2428
=> fix list validation error handling

lib/graphql/schema/field.rb, spec/graphql/schema/field_extension_spec.rb
Currently its only possible to specify one extension with options when using the `extensions` kwarg in a field and it has to be the *last* extension specified.
This improves handling of `extension` and allows for a mix of extension classes and extensions with options which no longer have to come last.
=> Make extensions kwarg on field on more flexible

graphql.gemspec
This results in `spec` being bundled in the packaged gem resulting in
larger filesizes. Removing these will make downloads more efficient!
ref: https://github.com/rubygems/rubygems/issues/735
This also uses require_relative instead of mangling the LOAD_PATH
which hasn't been necessary for a long time.
=> Remove test_files from gemspec

lib/graphql/analysis/ast/query_complexity.rb, lib/graphql/analysis/ast/query_depth.rb, lib/graphql/analysis/ast/visitor.rb, spec/graphql/analysis/ast/field_usage_spec.rb, spec/graphql/analysis/ast/max_query_complexity_spec.rb
This changes `GraphQL::Analysis::AST::Visitor` to automatically visit fragment spreads inline to fix #2419. It's an alternative to #2421 that avoids forking visitors for each analyzer when visiting fragment spreads. As part of this I made `GraphQL::Analysis::AST::Visitor#enter_fragment_spread_inline` and `GraphQL::Analysis::AST::Visitor#leave_fragment_spread_inline` private since they can cause an analyzer to screw up the iteration for other analyzers. I left the `fragment_spread` callbacks in `GraphQL::Analysis::AST::Analyzer` to be consistent with the `inline_fragment` callbacks but I'm not sure when these would actually be useful. This is hopefully a minimal change to fix #2419 which is a pretty unfortunate regression.
=> Automatically inline fragment spreads during AST visits

guides/queries/ast_analysis.md, lib/graphql/analysis/ast/analyzer.rb
Since https://github.com/rmosolgo/graphql-ruby/pull/2463/ we inline fragment spreads automatically in AST visits. As such, the example in the docs is no longer correct and would cause an error because `enter_fragment_spread_inline` and `leave_fragment_spread_inline` are now private methods on the `GraphQL::Analysis::AST::Visitor` class. So this updates that example in the docs to be correct.
In addition to that, I noticed in the [docs](https://graphql-ruby.org/api-doc/1.9.12/GraphQL/Analysis/AST/Analyzer) for `GraphQL::Analysis::AST::Analyzer` that `build_visitor_hooks` had a message to not use it, I think we should make it a private method and update the docs to be more clear.
=> Fix AST analysis documentation

lib/generators/graphql/templates/base_interface.erb, lib/generators/graphql/templates/base_object.erb, spec/integration/rails/generators/graphql/install_generator_spec.rb
When running `rails g graphql:install` to setup Rails integration, make sure that `Types::BaseObject` and `Types::BaseInterface` set their field class to the generated `Types::BaseField`. (Similarly to how various templates call `argument_class`.)
=> Use Types::BaseField in appropriate rails base templates

guides/getting_started.md
Result of executing the command `rails g graphql:object Post title:String rating:Int comments:[Comment]`  with reference to the [document](https://graphql-ruby.org/getting_started), graphql-ruby generate below code.
```ruby
module Types
class PostType < Types::BaseObject
end
end
```
Current [document](https://graphql-ruby.org/getting_started#declare-types) differ generated file.
```ruby
class Types::PostType < Types::BaseObject
　# ...
end
```
Improve getting started document.
@bary822 commited [code](https://github.com/rmosolgo/graphql-ruby/commit/7279b5fc113627e4d01a6b0f39c0c520c69bd744#diff-a6f0315311fb9167ede5428eb5a574d3), to solve the issue of https://github.com/rmosolgo/graphql-ruby/issues/1591 .
```
$ cat Gemfile.lock | grep graphql
graphql (1.9.12)
```
=> Getting Started page is not followed new version template generator.

guides/type_definitions/scalars.md, lib/graphql/types/iso_8601_date.rb, lib/graphql/types/iso_8601_date_time.rb, spec/graphql/types/iso_8601_date_spec.rb, spec/graphql/types/iso_8601_date_time_spec.rb
I've figured out that `ISO8601DateTime` handles `Date` objects in a funny way – it fails with `ArgumentError` (because `Date#iso8601` does not accept any arguments), but from the controller:
```ruby
ArgumentError (wrong number of arguments (given 1, expected 0)):
app/controllers/graphql_controller.rb:10:in `execute'
...
```
When I figured out what's going on, I've written my own implementation for `Date` and decided to open up this PR – the idea is that now `ISO8601DateTime` can accept `Date` too. There are another options of what we can do here: I can write a separate scalar type for Dates or just fix the docs to make it clear that the current type doesn't work with dates. What do you think of it?
=> Make ISO8601DateTime work with Date

lib/graphql/analysis/ast.rb
The directive already appears higher in the file, so it is unnecessary here. Moreover, it is ignored if any tokens have been seen in the file before the directive is encountered.
=> Remove errant frozen_string_literal directive.

guides/errors/execution_errors.md
Since the current URL is old and redirected to the top page, the path and anchor does not work, so fix the URL.
=> Fix URL in docs

lib/graphql/query.rb, spec/graphql/query_spec.rb
Calling `query.result` in an instrumentation `after_query` hook results in an infinite recursion if the query fails with an exception. See this [gist](https://gist.github.com/jturkel/bf40ba28ccf7a5686136a92590312894) which demonstrates the problem and generates the following stacktrace:
```
SystemStackError: stack level too deep:
```
The query is going to fail no mater what but the `SystemStackError` masks the underlying problem making these bugs hard to fix. This PR adds a `GraphQL::Query#executed?` method so instrumentation can guard against the problem without reaching into `GraphQL::Query` instance variables. Alternatively we could stop invoking `after_query` hooks if the query fails with an exception but that might break instrumentation assumptions about always calling `after_query` …
=> Add GraphQL::Query#executed? method

lib/graphql/types/iso_8601_date.rb
I just thought that `created_at`, which is probably in 100% of the apps a DateTime rather than Date, would be slightly misleading, so I changed it to something else.
=> Change misleading field name [ci skip]

lib/graphql/language/visitor.rb
`apply_hooks` is an extremely hot method.  `inject` allocates an object
to keep track of the memo used for the "fold" operation.  We don't
really need a fold operation in this case, so I converted it to an
`each`.  This kills two birds with one stone in that:
1. There are zero allocations
2. We actually short circuit iteration if `SKIP` is returned
The previous code would loop through all elements every time, even if
one of them returned `SKIP` and the subsequent procs would no longer be
called.
This patch decreases our boot time allocations by about 10 million (or 23%):
```
[aaron@tc-lan-adapter ~/g/github (master)]$ env FASTDEV=1 bin/rails r 'p GC.stat(:total_allocated_objects)' ^ /dev/null
42948624
[aaron@tc-lan-adapter ~/g/github (master)]$ env FASTDEV=1 bin/rails r 'p …
```
=> Reduce allocations in `apply_hooks`

lib/graphql/language/visitor.rb
Similar to #2451
The visitor code is run a lot. Previously we could call `begin_visit`/`end_visit` even if there was no visitor configured for the class, this would end up allocating an empty NodeVisitor (3 objects) and inserting it into the hash.
Skipping all this should reduce allocations and avoiding the hash insertions and extra method calls should be faster.
Versus #2451, this reduces another 1.5 million allocations from our app boot (about 4%).
=> Skip visitor hooks entirely if possible

lib/graphql/scalar_type.rb, spec/graphql/float_type_spec.rb, spec/graphql/id_type_spec.rb, spec/graphql/static_validation/rules/argument_literals_are_compatible_spec.rb
Happy Hacktoberfest 🎃 ! This resolves #2371. 
In general, it seems that we allow raw enum values to be coerced into strings, code below. 
```ruby
def raw_coercion_input(value)
if value.is_a?(GraphQL::Language::Nodes::InputObject)
value.to_h
elsif value.is_a?(Array)
value.map { |element| raw_coercion_input(element) }
elsif value.is_a?(GraphQL::Language::Nodes::Enum)
value.name
else
value
end
end
```
This means that enum's value (#name) will be taken as a `string` to go through input coercion. But it seems that enums are not scalars, neither string or number from the spec. 
Hence I attempted a solution to reject enums as scalars. 
During validation, this returns errors such as the below: 
```ruby
"message"=>"Argument 'id' on Field 'milk' has an invalid value. Expected type 'ID!'.", …
```
=> Disallow casting of Enums into scalar values

guides/testing/integration_tests.md
In the last example on [this doc page](https://graphql-ruby.org/testing/integration_tests.html#testing-transport-level-behaviors), the http header name used for the token is incorrect.
"Authentication" should be "Authorization"
=> Correct http header in example

lib/graphql/execution/interpreter/runtime.rb, spec/graphql/execution/errors_spec.rb
Fixes #2523 
Oops, there was an unhandled scenario. The eager-resolver code already had its error handling arranged like this, but I guess I missed this spot!
=> Fix errors that are re-raised after lazy fields

lib/graphql/subscriptions/action_cable_subscriptions.rb, lib/graphql/subscriptions/instrumentation.rb, spec/graphql/subscriptions_spec.rb
Use the returned value of subscription root fields, even with the old runtime. 
Previously, the return value was ignored. (But raised errors were acknowledged.) Now, a returned value may be used. (Although `nil` might not, I'm not exactly sure what case that is.)
Closes #2294 
Closes #2145 
Closes #2319 
Closes #2261
=> Use returned value of subscription field (breaking) 

guides/schema/class_based_api.md, guides/schema/introspection.md, guides/schema/lazy_execution.md, guides/schema/limiting_visibility.md, guides/schema/root_types.md
Was going through the Guides with a colleague and the Class-based API guide made it sound like it's a new feature where it's actually the new norm now. 
Suggesting to rename it as the migration guide and put it at the bottom of the page. 
The thought is that it remains available for people who are still using the define DSL but does not confuse people who are new to graphql-ruby.
=> Guides: Repurpose class API guide 

guides/related_projects.md
`graphql_rails` allows to build graphql types using already known patters from Rails: models, controllers, routers and etc.
Project is quite stable: it is maintained for more then a year and had 18 releases so far. 
I hope that's enough to treat this project as `related` and to mention it in "related projects" :)
=> Docs: add link to `graphql_rails` in related projects

lib/generators/graphql/templates/graphql_controller.erb, spec/integration/rails/generators/graphql/install_generator_spec.rb
This change allows for outside API access (say, from a mobile app) while continuing to have protections against CSRF attacks.
Essentially, if the request comes from outside of the current domain, it'll nullify the session. This means that you'll have to get the current_user or other session data some other way (usually a token on the request), which is safer than just checking your current browsing session.
See more here: https://marcgg.com/blog/2016/08/22/csrf-rails/
=> Add nullify session CSRF protection

lib/graphql/schema/build_from_definition.rb, lib/graphql/schema/printer.rb, lib/graphql/schema/validation.rb, spec/graphql/authorization_spec.rb, spec/graphql/schema/build_from_definition_spec.rb, spec/graphql/schema/member/accepts_definition_spec.rb, spec/graphql/schema/traversal_spec.rb, spec/graphql/schema/validation_spec.rb, spec/graphql/schema_spec.rb, spec/graphql/types/relay/base_edge_spec.rb
Closes https://github.com/rmosolgo/graphql-ruby/issues/2461
See the above issue for background, expected vs. actual, and repro steps.
This PR. I think we should not only ensure schema.query is defined, but that it has at least one fields defined on it.
```ruby
schema_doc = "type Query { }"
GraphQL::Schema.from_definition(schema_doc) # 💥"Schema definition Query type must define at least one field."
```
~This change, however, conflicts with an existing test case that now fails: https://github.com/chrisbutcher/graphql-ruby/blob/error-when-query-defined-but-empty/spec/graphql/schema/build_from_definition_spec.rb#L723-L730~
~I may be missing some important context on why `it 'supports empty types'`, or maybe this is just outdated and a case that this gem shouldn't support any longer.~
edit: …
=> Treat defined but empty schema.query type as invalid

lib/graphql/query/arguments.rb, spec/graphql/schema/field_spec.rb
I really don't know how this was introduced. But apparently we've been generating code like this, and it should still work, one way or another. 
Fixes #2537
=> Fix args compatibility in 1.9.13

lib/generators/graphql/templates/schema.erb, lib/graphql.rb, lib/graphql/analysis/ast/analyzer.rb, lib/graphql/base_type.rb, lib/graphql/function.rb, lib/graphql/language/document_from_schema_definition.rb, lib/graphql/language/nodes.rb, lib/graphql/relay/base_connection.rb, lib/graphql/schema.rb, lib/graphql/schema/build_from_definition.rb, lib/graphql/schema/directive/feature.rb, lib/graphql/schema/field.rb, lib/graphql/schema/loader.rb, lib/graphql/schema/member/base_dsl_methods.rb, lib/graphql/schema/member/type_system_helpers.rb, lib/graphql/schema/resolver.rb, lib/graphql/schema/wrapper.rb, lib/graphql/subscriptions.rb, lib/graphql/upgrader/member.rb, spec/graphql/authorization_spec.rb, spec/graphql/function_spec.rb, spec/graphql/schema/object_spec.rb, spec/graphql/schema/validation_spec.rb, spec/integration/rails/generators/graphql/install_generator_spec.rb, spec/integration/rails/graphql/schema_spec.rb
=> Issue#2067 Replace NotImplementedError with RequiredImplementationMissingError
