- lib/graph_ql/types/id_type.rb
- lib/graph_ql/types/type_definer.rb
- lib/graphql.rb
- spec/graph_ql/introspection/schema_type_spec.rb
- spec/graph_ql/introspection/type_type_spec.rb
- spec/graph_ql/query_spec.rb
- spec/graph_ql/schema/type_reducer_spec.rb
- spec/graph_ql/types/scalar_type_spec.rb
- spec/support/dummy_app.rb
Ref: http://facebook.github.io/graphql/#sec-ID
> Add ID type as per the GraphQL spec

- lib/graphql/query/serial_execution/selection_resolution.rb
- spec/graphql/introspection/schema_type_spec.rb
- spec/graphql/query_spec.rb
- spec/support/dairy_app.rb
- spec/support/dairy_data.rb
resolves https://github.com/rmosolgo/graphql-ruby/issues/29
> deep merge fragments in order to avoid dropping keys

- lib/graphql/schema/type_reducer.rb
- spec/graphql/schema/type_reducer_spec.rb
r? @rmosolgo 
Fortunately GraphiQL does introspection validation, I discovered this while trying to get it running on my schema.
> Add InputObject fields to type reducer

- lib/graphql/language/transform.rb
- spec/graphql/language/transform_spec.rb
> fix(Transform) handle empty input objects

- .travis.yml
- lib/graphql/language/transform.rb
- spec/graphql/interface_type_spec.rb
[Rubinius](http://rubinius.com/) currently doesn't support refinements so made a little change to use a constant Proc instead of a Monkey Patch/Refinement
> Add rubinius support

- readme.md
Hi @rmosolgo 
Compiled links to a few tutorials from the internet and updated the Readme.
Please review and merge!
> Add getting started tutorials links to readme

- lib/graphql/definition_helpers/defined_by_config.rb
- lib/graphql/field.rb
- spec/graphql/field_spec.rb
- spec/graphql/object_type_spec.rb
> feat(Field) expose property and respond to changes

- lib/graphql/query/serial_execution/selection_resolution.rb
Extracted the flattening and merging of selections into it's own method, used by both `result` and `flatten_fragment` methods. Also changed a few style things, let me know if you disagree with them :)
> Extract flatten and merge into own method

- lib/graphql/define/assign_object_field.rb
- lib/graphql/directive.rb
- lib/graphql/introspection/directive_type.rb
- spec/graphql/introspection/directive_type_spec.rb
- spec/graphql/schema/printer_spec.rb
Oops, removing them altogether broke some versions of GraphiQL!
> fix(Directive) add previous introspection fields as deprecated

- lib/graphql/boolean_type.rb
- lib/graphql/float_type.rb
- lib/graphql/id_type.rb
- lib/graphql/int_type.rb
- lib/graphql/string_type.rb
Pretty much what the title says.
> Add documentation for the scalar types

- lib/graphql/analysis/query_depth.rb
It's minor, but this tripped me up earlier. 😅
> Update comment documentation

- spec/graphql/interface_type_spec.rb
- spec/graphql/introspection/type_type_spec.rb
- spec/graphql/object_type_spec.rb
- spec/graphql/schema/reduce_types_spec.rb
- spec/graphql/union_type_spec.rb
- spec/support/dairy_app.rb
Check if fragments between composite types work right or not
> fix(Typecast) add end-to-end test for interface-to-interface casting

- guides/relay.md
Add reference to the doc for #213 
Is this good enough?
> Document passing field to connection class and creating relation object

- lib/graphql.rb
- lib/graphql/argument.rb
- lib/graphql/define.rb
- lib/graphql/directive.rb
- lib/graphql/enum_type.rb
- lib/graphql/field.rb
- lib/graphql/field/resolve.rb
- lib/graphql/input_object_type.rb
- lib/graphql/interface_type.rb
- lib/graphql/list_type.rb
- lib/graphql/non_null_type.rb
- lib/graphql/object_type.rb
- lib/graphql/query/arguments.rb
- lib/graphql/scalar_type.rb
- lib/graphql/union_type.rb
Lots of doc improvements. I wanna make a website, but I gotta have some good content first 😅
> Type guides

- lib/graphql/relay/global_node_identification.rb
- lib/graphql/schema.rb
- spec/graphql/relay/global_node_identification_spec.rb
Oops, I thought I tested this by updating the code, then updating the tests, but apparently something got mixed up! I was struggling with the proper arity for this function and I see I missed some spots after figuring out it should be 2.
> fix(type_from_object) correctly support deprecated type resolution

- lib/graphql/language/generation.rb
- lib/graphql/language/nodes.rb
- lib/graphql/language/token.rb
> doc(GraphQL::Language) add documentation for ast node classes

- lib/graphql/static_validation/rules/fields_will_merge.rb
- spec/graphql/static_validation/rules/fragments_are_finite_spec.rb
- spec/graphql/static_validation/validator_spec.rb
Attempt number 2 at #257 
This is why `StaticValidation` needs a rewrite 😖
> fix(FieldsWillMerge) detect infinite spreads when checking mergeablility

- lib/graphql/static_validation/rules/variables_are_input_types.rb
- spec/graphql/static_validation/rules/variables_are_input_types_spec.rb
> fix(StaticValidation) handle unknown variable types

- lib/graphql/query/serial_execution/field_resolution.rb
- lib/graphql/schema.rb
Save the rainforest, etc. Middleware is pretty slow.
```ruby 
require "benchmark/ips"
require "graphql"
require "support/dairy_app"
query = GraphQL::Introspection::INTROSPECTION_QUERY
Benchmark.ips do |x|
x.report("without empty middleware") { DummySchema.execute(query) }
x.report("with empty middleware") { DummyWithRescueSchema.execute(query) }
x.compare!
end
```
```
~/code/graphql $ ruby -Ilib -Ispec middleware_benchmark.rb
without empty middleware
3.000  i/100ms
with empty middleware
2.000  i/100ms
without empty middleware
37.813  (±10.6%) i/s -    186.000  in   5.014397s
with empty middleware
21.016  (±23.8%) i/s -    100.000  in   5.036850s
Comparison:
without empty middleware: …
```
> refactor(Schema) only add the RescueMiddleware if it's being used

- lib/graphql/relay/relation_connection.rb
- spec/graphql/relay/relation_connection_spec.rb
Provide a more descriptive error for cases like #311
> fix(RelationConnection) raise when the edge isn't found

- lib/graphql/static_validation/rules/fragments_are_finite.rb
- spec/graphql/static_validation/rules/fragments_are_finite_spec.rb
Fixes #329
yet another reason we need unified state management for validation as WIP in #268
> fix(FragmentsAreFinite) handle undefined fragment usage

- readme.md
- Removed a parenthesis which broke the link
> Fix website link in README

- spec/graphql/relay/relation_connection_spec.rb
Trying to fix #302 ... first step, test failure :)
> Add failing test for relation connection on Rails 3

- lib/graphql/query/serial_execution/field_resolution.rb
- spec/graphql/schema/timeout_middleware_spec.rb
> fix(Middleware) add ast_node and irep_node to query context for middlewares

- lib/graphql/relay/base_connection.rb
- lib/graphql/relay/mutation.rb
- lib/graphql/schema.rb
- lib/graphql/unresolved_type_error.rb
- spec/graphql/query/serial_execution/value_resolution_spec.rb
Remove some things that have been deprecated for a little while
> refactor(lib) remove some deprecated methods

- lib/graphql/enum_type.rb
- spec/graphql/enum_type_spec.rb
- spec/graphql/introspection/type_type_spec.rb
- spec/support/dairy_app.rb
Add documentation how to use enum types defined with ActiveRecord::Enum.
> Change documentation enum_type to include ActiveRecord::Base

- guides/related_projects.md
Hello! Thanks for the great library. I've been building a GraphQL Sinatra example this weekend and have really enjoyed working with it.
I thought it might be useful for other people, so I've added a link to my example in the docs underneath your Rails one.
> Add Sinatra example to docs

- lib/graphql/language/lexer.rb
- lib/graphql/language/lexer.rl
- spec/graphql/language/lexer_spec.rb
Oops, this was previously not threadsafe! Fortunately it's only used for schema parsing, which I doubt people are doing on multiple threads 😬
> fix(lexer) don't preserve state between runs

- lib/graphql/query/arguments.rb
- spec/graphql/query/variables_spec.rb
Oops, it would keep trying to wrap `nil`, which eventually made a NoMethodError 😖 
Fixes #408
> fix(Argument#wrap_value) don't keep wrapping nil

- lib/graphql/relay/connection_field.rb
- spec/graphql/field_spec.rb
- spec/graphql/relay/connection_field_spec.rb
> fix(ConnectionField) use redefine to capture connection behaviors

- guides/schema/configuration_options.md
- lib/graphql/compatibility/execution_specification/specification_schema.rb
- lib/graphql/execution/execute.rb
- lib/graphql/query/context.rb
- lib/graphql/query/serial_execution/field_resolution.rb
- lib/graphql/schema.rb
- lib/graphql/schema/catchall_middleware.rb
- lib/graphql/schema/middleware_chain.rb
- lib/graphql/schema/rescue_middleware.rb
- lib/graphql/schema/timeout_middleware.rb
- lib/graphql/schema/warden.rb
- spec/graphql/schema/middleware_chain_spec.rb
- spec/graphql/schema/rescue_middleware_spec.rb
- spec/graphql/schema_spec.rb
This is a work in progress to try to optimize query execution. For the schema in my app, this eliminates about 73k object allocations for the introspection query.
> Optimize Query Execution

- guides/relay/object_identification.md
> Fix uuid documentation

- lib/graphql/language/nodes.rb
- lib/graphql/query/variables.rb
- spec/graphql/query/variables_spec.rb
- spec/graphql/query_spec.rb
> fix(Query::Variables) don't assign nil for absent variables

- lib/graphql/query.rb
- spec/graphql/schema/warden_spec.rb
If you specify a default_mask, it's ignored when you pass a query mask. But they should add together. (eg, GraphQL::Pro's authorization uses default_mask. You should be able to lay another mask on top of that one without ignoring it.)
> fix(Query) default_mask and query mask are additive

- guides/schema/limiting_visibility.md
> docs(filters) improve schema filtering documentation

- lib/graphql/input_object_type.rb
- lib/graphql/query/literal_input.rb
- spec/graphql/query/variables_spec.rb
I tried to fix #472  with #479 but didn't go deep enough. 
There was a lot of bad code here 😬 I mean, it just wasn't checking for the presence of the variable.
> Fix argument presence/absence again

- lib/graphql/relay/relation_connection.rb
- spec/graphql/relay/array_connection_spec.rb
- spec/graphql/relay/relation_connection_spec.rb
Hey @rmosolgo ,
Here's my PR: 
I added a couple of tests and included them into a separate commit, please have a look at them, if they are needed or not - you can exclude that commit.
Regards,
Alex
> Fix negative offset

- guides/related_projects.md
- readme.md
I have corrected the URL for the screencast link in the related projects file. Please merge.
> Correct URL

- guides/schema/types_and_fields.md
There's not really any examples on how to add a mutation root and basic mutations on the website. (Only Relay AFAIK).
This adds a simple example on how to do so!
> Docs on mutations

- spec/graphql/execution/execute_spec.rb
Proposing complementary specs for #575. 
I'm not aware whether or not this is already tested on other specs, but I thought it could lbe nice to ensure we're not messing with the other behavior. I also took the liberty of updating some spec descriptions that were created when we were still diagnosing the issue.
> Additional specs for #575 (complementary case)

- Rakefile
- benchmark/run.rb
- graphql.gemspec
This is the profile I've been using locally. I can't claim it's the most scientific in the world, but I'd like to get the ball rolling in this area!
It's nice to use this way:
```
$ bundle exec rake bench:profile > before.txt 
$ bundle exec rake bench:profile > after.txt 
```
> feat(Benchmark) add profile task

- guides/relay/mutations.md
Updates the Relay mutation docs so that it goes into a little more detail about the fields that certain Relay mutations expect, and updates the comment mutation example so that it uses the new `GraphQL::Relay::RangeAdd` API.
> Update Relay mutation docs for new RangeAdd method

- guides/schema/generators.md
- lib/generators/graphql/enum_generator.rb
- lib/generators/graphql/templates/enum.erb
- spec/generators/graphql/enum_generator_spec.rb
> feat(EnumGenerator) add enum generator

- lib/graphql/relay/connection_resolve.rb
- spec/graphql/relay/connection_resolve_spec.rb
- spec/graphql/relay/connection_type_spec.rb
- spec/support/star_wars/schema.rb
Oops, connection resolve functions should be allowed to return execution errors, too!
Fixes #591
> fix(Connection) support ExecutionError from Connection resolves

- lib/graphql/static_validation/all_rules.rb
- lib/graphql/static_validation/rules/fragment_names_are_unique.rb
- spec/graphql/static_validation/rules/fragment_names_are_unique_spec.rb
oops, this was missing https://facebook.github.io/graphql/#sec-Fragment-Name-Uniqueness
> fix(StaticValidation) assert fragment names are unique

- lib/graphql/internal_representation/node.rb
- lib/graphql/internal_representation/rewrite.rb
- spec/graphql/internal_representation/rewrite_spec.rb
oops, I removed this API unwittingly in #512 
cc @gjtorikian
> fix(InternalRepresentation#Node) add reference to parent node

- lib/graphql/query/variables.rb
- lib/graphql/schema/type_expression.rb
- lib/graphql/static_validation/rules/variable_default_values_are_correctly_typed.rb
- lib/graphql/static_validation/rules/variable_usages_are_allowed.rb
- spec/graphql/static_validation/rules/variable_default_values_are_correctly_typed_spec.rb
- spec/graphql/static_validation/rules/variables_are_input_types_spec.rb
Fixes #626 and another error when you provide a default value but the type condition is not found.
> fix(Schema.type_from_ast) allow returning nil

- guides/related_projects.md
We can use this section to add talks about graphql-ruby.
> Add presentations section

- .travis.yml
- Gemfile
- gemfiles/rails_3.2.gemfile
- gemfiles/rails_4.1.gemfile
- gemfiles/rails_4.2.gemfile
- gemfiles/rails_5.0.gemfile
- graphql.gemspec
- spec/spec_helper.rb
- spec/support/star_wars/data.rb
This pull requests enables JRuby for all tests on Travis
> Run tests on JRuby

- lib/graphql/language/parser.rb
- lib/graphql/language/parser.y
- lib/graphql/query.rb
- lib/graphql/static_validation/all_rules.rb
- lib/graphql/static_validation/rules/no_definitions_are_present.rb
- spec/graphql/query_spec.rb
- spec/graphql/static_validation/rules/no_definitions_are_present_spec.rb
Previously this :boom:ed the application, boo hiss
> fix(Query) validate incoming query isn't a schema definition

- lib/graphql/function.rb
- spec/graphql/function_spec.rb
See https://github.com/rmosolgo/graphql-ruby/issues/653#issuecomment-291553315
> Provides shorthand access to GraphQL's built-in types within function classes

- lib/graphql.rb
- lib/graphql/string_type.rb
- spec/graphql/string_type_spec.rb
Aims to close https://github.com/rmosolgo/graphql-ruby/issues/657!
> Raise on UTF-8 encoding error

- lib/graphql/rake_task.rb
- lib/graphql/schema.rb
- spec/graphql/rake_task_spec.rb
- spec/graphql/schema_spec.rb
- spec/spec_helper.rb
> feat(RakeTask) add tasks for dumping the schema

- .travis.yml
- gemfiles/rails_5.1.gemfile
I add Rail5.1 gemfile to .travis.yml.
> add Rails5.1 to CI

- lib/graphql/query/arguments.rb
- spec/graphql/query/arguments_spec.rb
If an argument has an alias from `as:`, apply it for `#to_h`, `#each` and `#keys`.
Fixes #684 
Fixes #698, kinda. (It won't actually fix that middleware.)
> fix(Arguments#to_h) apply as: names for to_h, return string keys from to_h

- lib/graphql/relay/mutation/instrumentation.rb
- lib/graphql/relay/mutation/resolve.rb
- spec/graphql/relay/mutation_spec.rb
- spec/support/star_wars/schema.rb
There was no test for this and it changed 1.5.7 -> 1.5.8
> fix(Relay::Mutation) handle errors raised in resolve function

- lib/graphql/execution/multiplex.rb
- spec/graphql/execution/multiplex_spec.rb
- spec/graphql/schema_spec.rb
- spec/support/lazy_helpers.rb
> refactor(Instrumentation) call before_/after_ hooks as a stack

- lib/graphql/enum_type.rb
LanguageType is not mentioned should be LanguageEnum
> Enum types documentation fix

- lib/graphql/schema/rescue_middleware.rb
- spec/graphql/schema/rescue_middleware_spec.rb
> Allow rescue_from and remove_handler to take multiple error classes

- guides/getting_started.md
GraphQL.js is a library based on simple HTTP request.
> Add GraphQL.js client to getting started page. 😇

- lib/graphql.rb
- lib/graphql/analysis/query_complexity.rb
- lib/graphql/execution/lazy.rb
- lib/graphql/execution/lazy/lazy_method_map.rb
- lib/graphql/execution/lazy/resolve.rb
- lib/graphql/internal_representation/node.rb
- lib/graphql/non_null_type.rb
- lib/graphql/query.rb
- lib/graphql/query/arguments.rb
- lib/graphql/query/arguments_cache.rb
- lib/graphql/query/context.rb
- lib/graphql/query/null_context.rb
- lib/graphql/query/variables.rb
- lib/graphql/relay/base_connection.rb
- lib/graphql/schema/middleware_chain.rb
- lib/graphql/schema/type_map.rb
- lib/graphql/static_validation/definition_dependencies.rb
- lib/graphql/static_validation/validation_context.rb
Taking another look for serious offenders, this time with https://github.com/SamSaffron/memory_profiler
> Perf improvements

- lib/graphql/execution/multiplex.rb
- spec/graphql/query_spec.rb
Oops, I want to run one query as a special case of multiplex. It should be covered by multiplex instrumentation. This fixes that!
> Fix(Schema#execute) run instrumentation for single, legacy query

- spec/generators/graphql/install_generator_spec.rb
Almost not PR worthy, but while debugging the issues on #773 I stumbled upon this minor improvement.
> Simplifies the test setup a tiny bit

- guides/fields/limits.md
Cap limit using prepare function instead of in the resolve body.
> Use prepare function to cap limit

- Rakefile
- benchmark/run.rb
- guides/development.md
- readme.md
This documents some parts of developing graphql-ruby, I hope it will help new folks get accustomed to the setup!
cc @esjee
> Add development guide

- lib/generators/graphql/core.rb
- lib/generators/graphql/install_generator.rb
- lib/generators/graphql/mutation_generator.rb
- lib/generators/graphql/templates/mutation.erb
- lib/generators/graphql/templates/mutation_type.erb
- lib/generators/graphql/templates/schema.erb
- spec/generators/graphql/install_generator_spec.rb
- spec/generators/graphql/mutation_generator_spec.rb
Work from #773, plus @Willianvdv 's fixes. 
@Willianvdv, do you mind my including your work here?
> Improved mutation generator

- lib/graphql/static_validation/rules/variable_usages_are_allowed.rb
- spec/graphql/static_validation/rules/variable_usages_are_allowed_spec.rb
See https://github.com/rmosolgo/graphql-ruby/pull/823 for more info
Just creating a new PR to get it to run on Travis!
> Fix list variable validation

- lib/graphql/enum_type.rb
- spec/graphql/enum_type_spec.rb
Had trouble finding which enum had the problem :)
cc @swalkinshaw
> Print Enum name when raising duplicate value error.

- Rakefile
- guides/pro/installation.md
- lib/graphql/rake_task.rb
- lib/graphql/rake_task/validate.rb
Automate the task of verifying the downloads
> feat(RakeTask) add graphql:pro:validate

- Guardfile
- guides/development.md
- lib/graphql/query/arguments_cache.rb
- lib/graphql/query/executor.rb
this will make my life easier :)
> feat(Guard) add test_via: pragma to run other tests

- guides/_layouts/guide.html
- guides/css/main.scss
`experimental: true` in frontmatter will render: 
I'm hoping to use this for subscriptions and new schema definition so that I can release them before they are _perfect_ 😬
> feat(site) add experimental header

- lib/graphql/relay/relation_connection.rb
> Check if ActiveRecord::Relation is defined

- lib/graphql/static_validation/rules/variable_usages_are_allowed.rb
- spec/graphql/static_validation/rules/variable_usages_are_allowed_spec.rb
Fix https://github.com/rmosolgo/graphql-ruby/issues/878
> fix(VariableUsagesAreAllowed) a required variable inside a literal list satisfies [T!]

- lib/graphql/non_null_type.rb
- lib/graphql/static_validation/rules/variable_usages_are_allowed.rb
- spec/graphql/object_type_spec.rb
> Do not allow double non-null constraints

- lib/graphql/enum_type.rb
- spec/graphql/enum_type_spec.rb
> Validate enum names

- guides/queries/error_handling.md
It wasn't listed in any of the sections due to missing metadata.
> Make sure error handling guide shows up

- lib/graphql/schema/traversal.rb
- spec/graphql/schema/traversal_spec.rb
Noticed this while working on visibility: Types may be discovered through Directive arguments.
WDYT @rmosolgo ?
> Find types from directives

- guides/queries/backtrace_annotations.md
- lib/graphql/backtrace/traced_error.rb
- spec/graphql/backtrace_spec.rb
> feat(GraphQL::Backtrace) include the cause backtrace in the message; update docs

- guides/development.md
This has been in my head for a while but I think it's valuable to write it down!
> doc(VERSION) document the version policy

- guides/queries/multiplex.md
In Slack there were a few questions about using Apollo batching with GraphQL-Ruby. 
I _believe_ Apollo batching is the most common use case of multiplexing, so maybe adding an example of how to handle these batches would be a nice addition to the documentation.
> Add Apollo Query Batching example to Multiplexing docs

- lib/graphql/subscriptions.rb
- spec/graphql/subscriptions_spec.rb
> fix(Subscriptions) accept symbol args hash

- guides/faq.md
added doc in #992
wasn't sure what category it belonged in so made a new FAQ page ?
Tested locally using `bundle exec rake site:serve `
> added FAQ doc page to have tips such as the question in #992

- javascript_client/subscriptions/__tests__/createActionCableHandlerTest.js
- javascript_client/subscriptions/createActionCableHandler.js
This also adds a simple test to ensure the plumbing is correct
> Fix returned disposal function in createActionHandler

- lib/graphql/subscriptions.rb
- lib/graphql/subscriptions/action_cable_subscriptions.rb
- spec/graphql/subscriptions_spec.rb
This is a nice thing for other subscription transports, also fixing a typo found in #1038
> Add Subscriptions#build_id

- lib/graphql/subscriptions/serialize.rb
- spec/graphql/subscriptions/serialize_spec.rb
> Serialize GlobalID::Identification recursively in Array/Hash

- Appraisals
- gemfiles/without_rails.gemfile
- spec/graphql/subscriptions_spec.rb
GlobalID does not dependency Rails.
> Doesn't need check rails installed for GlobalID

- guides/queries/error_handling.md
It took me a while to get this setup properly for a production app. The doc seems to recommend doing things per resolver, which is tedious and problematic for most production scenarios. 
It's strange that `RescueFrom` wants a class to rescue from, seems like an unnecessary pattern because you typically handle exceptions in that rescue block, why would you want to declare in two places what that exception is? So I removed that option and documented how you can handle just about anything there with some useful examples for ActiveRecord.
Finally, graphql-errors does a great job at wrapping it in a schema. Don't know if that's ok since this is a library on top of this library, but seems like a useful link and that's what we ended up using.
> Better error handling documentation linking to graphql-errors gem.

- lib/graphql/execution/multiplex.rb
- lib/graphql/query.rb
- spec/graphql/execution/multiplex_spec.rb
> Mark queries as @executed when unhandled errors are raised

- lib/graphql/language/parser.rb
- lib/graphql/language/parser.y
- spec/graphql/enum_type_spec.rb
- spec/graphql/relay/mutation_spec.rb
No idea _why_ these started failing this way, but this makes 'em pass
> Fix jruby tests

- lib/graphql/relay/relation_connection.rb
- spec/graphql/relay/relation_connection_spec.rb
- spec/support/star_wars/data.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/1016
> fix(RelationConnection) avoid unneeded query on Sequel

- .travis.yml
JRuby has been failing on master for some odd reason, maybe it's due for another shaking-up.
> Test JRuby on Rails 5.1

- lib/graphql/subscriptions/action_cable_subscriptions.rb
- spec/dummy/app/channels/graphql_channel.rb
- spec/dummy/test/system/action_cable_subscription_test.rb
This allows us to use our own serializer for action cable subscriptions.
I can't find a good way to test this.
> Pluggable action cable serializer

- lib/graphql/language/lexer.rb
- lib/graphql/language/lexer.rl
- lib/graphql/language/token.rb
- spec/graphql/language/lexer_spec.rb
Fixes #1132 
Closing quotes were not handled correctly for column numbers, I think this is more like it!
> Fix string tokens

- guides/schema/class_based_api.md
- spec/graphql/tracing/platform_tracing_spec.rb
Thanks to people who tried it out and found holes in the docs, hopefully these will help out a bit 😬  !
> More 1.8 docs

- lib/graphql/object_type.rb
Very nit picky and non urgent change, just stumbled upon it 🤷‍♂️
> Fix documentation on `ObjectType.mutation`

- guides/related_projects.md
Hello.
I just want to share one more useful library :).
> Add apollo_upload_server-ruby to related projects list.

- lib/graphql/schema/field/dynamic_resolve.rb
- spec/graphql/schema/object_spec.rb
- spec/support/jazz.rb
So, if the object is a hash, it'll Just Work :tm:
> [1.8] Try string and symbol hash keys

- lib/graphql/upgrader/member.rb
- spec/fixtures/upgrader/blame_range.original.rb
- spec/fixtures/upgrader/blame_range.transformed.rb
- spec/fixtures/upgrader/type_x.original.rb
- spec/fixtures/upgrader/type_x.transformed.rb
- spec/graphql/upgrader/member_spec.rb
I'm continuing to run this on our code and here some improvements that I've found
> [1.8] More upgrader tweaks

- .codeclimate.yml
- see https://docs.codeclimate.com/docs/advanced-configuration
Or, more exactly: https://docs.codeclimate.com/docs/advanced-configuration#section-analysis-configuration-versions
> CodeClimate v2 configuration

- lib/graphql/define/assign_global_id_field.rb
- lib/graphql/relay/node.rb
- lib/graphql/schema/object.rb
- spec/graphql/relay/node_spec.rb
oops, these could be different, but I think they were meant to be the same.
> fix(Relay::Node) use consistent description for id fields

- lib/graphql/upgrader/member.rb
- spec/fixtures/upgrader/account.original.rb
- spec/fixtures/upgrader/account.transformed.rb
- spec/fixtures/upgrader/date_time.original.rb
- spec/fixtures/upgrader/date_time.transformed.rb
- spec/fixtures/upgrader/gist_order_field.original.rb
- spec/fixtures/upgrader/gist_order_field.transformed.rb
- spec/fixtures/upgrader/release_order.original.rb
- spec/fixtures/upgrader/release_order.transformed.rb
- spec/fixtures/upgrader/subscribable.original.rb
- spec/fixtures/upgrader/subscribable.transformed.rb
- spec/graphql/upgrader/member_spec.rb
I'm working on these parts of the GitHub schema, so these made it work.
> [1.8] Upgrade unions, scalars and input objects

- lib/graphql/schema.rb
- lib/graphql/schema/enum.rb
- lib/graphql/schema/enum_value.rb
- spec/graphql/schema/enum_spec.rb
- spec/support/jazz.rb
Oops, I overlooked this, but discovered it when trying to upgrade GitHub's code
> [1.8] customizing enum values

- lib/graphql/internal_representation/node.rb
Oops, I was a bit off in #1277
> NoTypedChildren should return a Hash, not Array

- lib/graphql/schema/argument.rb
- lib/graphql/schema/field.rb
- spec/graphql/schema/input_object_spec.rb
- spec/support/jazz.rb
- spec/support/star_wars/schema.rb
As pointed out by @swalkinshaw in #1274 , this would be a bit more consistent with other APIs which accept either position or keyword
> [1.8] Argument description: kwarg

- guides/queries/tracing.md
Ok, so that happened way faster than I expected 🙂 
Adds documentation for the already-added Datadog tracing. 🎉
> Add Guides for Datadog Tracing

- lib/graphql/schema/member/has_fields.rb
- lib/graphql/schema/object.rb
- spec/graphql/schema/interface_spec.rb
https://github.com/rmosolgo/graphql-ruby/issues/1298
> [1.8] Add support for global_field_id in interface

- lib/graphql/upgrader/member.rb
- spec/fixtures/upgrader/starrable.original.rb
- spec/fixtures/upgrader/starrable.transformed.rb
- spec/fixtures/upgrader/subscribable.transformed.rb
> [1.8] Properly migrate interface resolve functions

- guides/type_definitions/objects.md
- lib/graphql/query/context.rb
- spec/graphql/schema/field_spec.rb
- spec/support/jazz.rb
> Add extras: :execution_errors for adding errors in class-based fields

- lib/graphql/schema/argument.rb
- lib/graphql/schema/enum.rb
- lib/graphql/schema/enum_value.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/input_object.rb
- lib/graphql/schema/member/has_fields.rb
- lib/graphql/schema/object.rb
- spec/graphql/schema/enum_spec.rb
- spec/graphql/schema/field_spec.rb
- spec/graphql/schema/input_object_spec.rb
Fixes #1309 
I've added this for debugging a bunch, and with the old API, we often wish we had this. So let's add it :)
> [1.8] Add #owner method to schema objects

- lib/graphql/subscriptions/action_cable_subscriptions.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/1368
> Fix example code to return correct nil data in result.

- gemfiles/rails_5.1.gemfile
- lib/graphql/schema.rb
- spec/dummy/app/channels/graphql_channel.rb
Oops, this needs to be delegated for now
Fixes #1388
> Fix subscriptions for class-based schemas

- guides/type_definitions/lists.md
A bit of docs based on conversation at #1395
> Add docs for list nullability combinations

- guides/javascript_client/apollo_subscriptions.md
- javascript_client/subscriptions/PusherLink.js
Add support for pusher subscriptions + apollo 2. Not really sure how to do a full end-to-end test (or, at least it's too intimidating to do it!)
> Add PusherLink for Apollo 2

- lib/graphql/subscriptions.rb
- spec/graphql/subscriptions_spec.rb
I hope this will make onboarding with subscriptions easier: 
- `event_name` may be a symbol; if it is underscore-cased, try camelizing it to find the matching field 
- `args` may be symbol and/or underscore cased 
- `args` will be checked against the schema to make sure they're matched 
This removes some of the finickiness of the API, making it more accepting of input while also adding more evident failures when input can't be handled.
> Subscriptions: handle underscored symbols; validate args

- lib/graphql/schema/member/has_arguments.rb
- spec/graphql/schema/input_object_spec.rb
> Fix InputObject argument inheritance

- lib/graphql/upgrader/member.rb
- spec/fixtures/upgrader/photo.original.rb
- spec/fixtures/upgrader/photo.transformed.rb
Related to the issue: https://github.com/rmosolgo/graphql-ruby/issues/1445
> Parentheses are breaking upgrader

- lib/graphql/schema/member/base_dsl_methods.rb
- spec/graphql/schema/object_spec.rb
> Raise undefined `.graphql_name` in anonymous class

- lib/graphql/schema/argument.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/input_object.rb
- lib/graphql/schema/mutation.rb
- lib/graphql/schema/relay_classic_mutation.rb
- spec/graphql/schema/argument_spec.rb
- spec/graphql/schema/input_object_spec.rb
- spec/graphql/schema/mutation_spec.rb
- spec/support/jazz.rb
> Support prepare: and as: in class-based arguments

- lib/graphql/upgrader/member.rb
- spec/fixtures/upgrader/blame_range.transformed.rb
- spec/fixtures/upgrader/delete_project.transformed.rb
- spec/fixtures/upgrader/increment_count.transformed.rb
- spec/fixtures/upgrader/photo.transformed.rb
- spec/fixtures/upgrader/starrable.transformed.rb
- spec/fixtures/upgrader/subscribable.transformed.rb
- spec/fixtures/upgrader/type_x.transformed.rb
- spec/graphql/upgrader/member_spec.rb
ref https://github.com/rmosolgo/graphql-ruby/issues/1526
> Use object/context method instead of @object/@context

- lib/graphql/schema/relay_classic_mutation.rb
- spec/graphql/schema/mutation_spec.rb
- spec/graphql/schema/relay_classic_mutation_spec.rb
- spec/support/jazz.rb
> Use a default empty hash if no arguments supplied

- guides/type_definitions/objects.md
As per [this comment](https://github.com/rmosolgo/graphql-ruby/pull/1300#issuecomment-396933931).
> Add Example For Overriding Default Object Field Parameters

- lib/graphql/execution/execute.rb
- lib/graphql/schema/member/instrumentation.rb
- spec/graphql/authorization_spec.rb
- spec/graphql/execution_error_spec.rb
Another bug discovered with `integrated-auth`.
> Fix lists of abstract type with promises

- guides/queries/tracing.md
- lib/graphql/tracing.rb
Minor issue with an easy workaround, just makes slightly easier for the user
> Fix require in tracing.rb

- lib/generators/graphql/mutation_generator.rb
- spec/generators/graphql/mutation_generator_spec.rb
I fixed #1629. I suppose this fix is not perfect, but works correctly in most cases.
> Improve the mutation generator

- lib/graphql/schema/interface.rb
- lib/graphql/schema/member.rb
- lib/graphql/schema/member/relay_shortcuts.rb
- lib/graphql/types/relay/base_connection.rb
- lib/graphql/types/relay/base_edge.rb
- spec/graphql/authorization_spec.rb
- spec/graphql/relay/connection_instrumentation_spec.rb
- spec/support/star_trek/schema.rb
- spec/support/star_wars/schema.rb
> Use class-based types for .edge_type and .connection_type

- lib/graphql/schema/field.rb
Hello. I noticed some code need to be fixed while investigating #1256. I will explain them in line comments below.
> Some fixes for GraphQL::Schema::Field#initialize

- lib/graphql/execution/instrumentation.rb
We're seeing very deep call stacks from `call_hooks` in production.
This commit just changes the `call_hooks` method to be iterative rather
than recursive so that we don't have to build such a large stack when
executing instrumentation hooks.
@rmosolgo if you check the flame graphs in production, you should be able to see these calls (I just didn't want to post the graph here).  The problem is that our stacks can get to `instrumenters.length * queries.length` or basically n^2.  This change reduces it to `queries.length * 2`.  I think we can change `each_query_call_hooks` to be iterative rather than recursive, but I haven't cracked that yet.
Thanks!
> Change `call_hooks` to be iterative rather than recursive

- guides/related_projects.md
Adds new gem (https://github.com/Shopify/graphql-metrics) to the list of related projects :)
@rmosolgo
> Add graphql-metrics to related projects list

- lib/graphql/schema/argument.rb
- lib/graphql/schema/enum_value.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/interface.rb
- lib/graphql/schema/member.rb
- lib/graphql/schema/member/base_dsl_methods.rb
- lib/graphql/schema/member/has_path.rb
- lib/graphql/schema/resolver.rb
- spec/graphql/schema/argument_spec.rb
- spec/graphql/schema/enum_spec.rb
- spec/graphql/schema/enum_value_spec.rb
- spec/graphql/schema/field_spec.rb
- spec/graphql/schema/input_object_spec.rb
- spec/graphql/schema/interface_spec.rb
- spec/graphql/schema/object_spec.rb
- spec/graphql/schema/resolver_spec.rb
- spec/graphql/schema/scalar_spec.rb
- spec/graphql/schema/union_spec.rb
I've done stuff like this locally a lot, it would be nice to have something built-in
> Add .path method to schema members for debugging

- lib/graphql/language/nodes.rb
- spec/graphql/language/visitor_spec.rb
Oops, some definitions were missing.
> Fix modifying fragment spreads with visitor

- guides/schema/generators.md
- lib/generators/graphql/install_generator.rb
- lib/generators/graphql/scalar_generator.rb
- lib/generators/graphql/templates/base_scalar.erb
- lib/generators/graphql/templates/scalar.erb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
- spec/integration/rails/generators/graphql/scalar_generator_spec.rb
Hello. I added a generator for scalar types for convenience.
> Add scalar type generator

- javascript_client/subscriptions/ActionCableLink.js
* Added `connectionParams`
const wsLink = new ActionCableLink({
cable,
connectionParams: {
// e.g. token: string_token
}
})
Inspiration: [subscriptions-transport-ws](https://github.com/apollographql/subscriptions-transport-ws)
> [JS] ActionCableLink connection params

- guides/relay/object_identification.md
- Reference the correct variable name in `object_from_id`
- Capitalize `GraphQL::Schema::Object` class
> Minor edits in relay/object_identification.md guide

- guides/index.html
The Kickstarter Engineering team loves the GraphQL-Ruby gem (and we use it in production on our site extensively!) so we added ourselves to your list of users. Let us know know if this is an issue. ❤️
> Added Kickstarter to the list of gem users ❤️

- guides/queries/tracing.md
- lib/graphql/tracing.rb
- lib/graphql/tracing/active_support_notifications_tracing.rb
This was removed in ac35acef2ecb97a767605957493d3aefbcb6ce5c
> Remove outdated comments about AS::Notifications

- lib/graphql/language/nodes.rb
- spec/graphql/language/visitor_spec.rb
- spec/graphql/static_validation/rules/variables_are_used_and_defined_spec.rb
Oops, updating an SDL AST with the new visitor was never tested!
> Fix Visitor updating SDL

- guides/type_definitions/extensions.md
This adds documentation on how to override base connection and edge types.
> Added connection base class override

- guides/type_definitions/interfaces.md
Regarding #1597 I thought it might help to add this hint to the guide about interfaces.
Thank you for this gem! :heart_eyes_cat:
> Add documentation about `implements` to implement interface types

- javascript_client/sync/generateClient.js
- javascript_client/sync/sendPayload.js
Spotted some unused `require`s while reading the code in the JS client. Thought removing it will make it easier for future readers
> Remove unused requires

- javascript_client/subscriptions/createAblyHandler.js
- javascript_client/subscriptions/createHandler.js
> add relay-modern subscription handler for ably (fixes #1975)

- guides/type_definitions/unions.md
> Update Union Documentation

- lib/graphql/schema/field.rb
This reverts commit 843a7bc3ad62b92e37a729222473b50ab423c0b3.
> Revert "Remove needless nil check"

- guides/getting_started.md
I updated Getting Started like following image
> update sample code at getting started

- javascript_client/subscriptions/PusherLink.js
Oops, proper `.unsubscribe()` calls weren't supported in PusherLink the way they were in the old Apollo 1.0 `PusherSubscriber`. 
Now I've implemented it properly, with cues from Apollo's websocket support: 
- The link returns an observable: https://github.com/apollographql/apollo-link/blob/2db1b296c2966cf325f59668ff46c495de5b160d/packages/apollo-link-ws/src/webSocketLink.ts#L50
- The subscription client makes a [fake observable](https://github.com/apollographql/subscriptions-transport-ws/blob/34d503a6cef99efaffb35dae6a816ab898440565/src/client.ts#L178-L181) whose `.subscribe()` [returns an `.unsubscribe()` object](https://github.com/apollographql/subscriptions-transport-ws/blob/34d503a6cef99efaffb35dae6a816ab898440565/src/client.ts#L205-L213) 
It seems a bit fishy to duck-type an …
> Update PusherLink for application unsubscribes

- lib/graphql/language/lexer.rb
- lib/graphql/language/lexer.rl
- spec/graphql/language/lexer_spec.rb
> Fix block string line counting

- lib/graphql/execution/lookahead.rb
- spec/graphql/execution/lookahead_spec.rb
> Fix lookahead with typed fragments

- lib/graphql/query/variable_validation_error.rb
- spec/graphql/query/executor_spec.rb
- spec/graphql/query_spec.rb
Opening the PR tp check CI. I also want to check which branch you want this merging to @rmosolgo 👍 🙇‍♀️
> Ensure variable validation errors meet GraphQL spec

- javascript_client/__tests__/__snapshots__/syncTest.js.snap
- javascript_client/__tests__/syncTest.js
- javascript_client/cli.js
- javascript_client/sync/generateClient.js
- javascript_client/sync/index.js
Trying to make it easier to debug stuff like #2074
> Add --verbose option to sync

- guides/queries/interpreter.md
Update the doc with the migration path we settled on, cc @swalkinshaw who had asked about this earlier.
> Update analyzer migration docs

- lib/graphql/execution/execute.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/schema.rb
- lib/graphql/schema/member/instrumentation.rb
- lib/graphql/schema/resolver.rb
- spec/support/jazz.rb
> Support lazy values from .resolve_type hooks

- lib/graphql/schema.rb
- spec/graphql/execution/lazy_spec.rb
Derp, #2112 was into _master_, not 1.8.x. Trying again to fix #1867
> Lazy yield bug 1.8

- lib/graphql/unauthorized_error.rb
- spec/graphql/authorization_spec.rb
> Support returning false from Query.authorized?

- lib/graphql/tracing/platform_tracing.rb
- spec/graphql/tracing/platform_tracing_spec.rb
> Fix platform_tracing with Interpreter & introspection

- lib/graphql/schema/subscription.rb
- spec/graphql/schema/subscription_spec.rb
> Fix subscribe hook with no args

- lib/graphql/static_validation/rules/required_input_object_attributes_are_present.rb
- spec/graphql/static_validation/rules/required_input_object_attributes_are_present_spec.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/2109
> Correct static validation of nested InputObjects

- guides/_layouts/guide.html
- guides/fields/arguments.md
- guides/fields/resolvers.md
- guides/mutations/mutation_classes.md
- guides/mutations/mutation_root.md
- guides/schema/class_based_api.md
- guides/schema/definition.md
- guides/schema/introspection.md
- guides/type_definitions/directives.md
- guides/type_definitions/enums.md
- guides/type_definitions/extensions.md
- guides/type_definitions/field_extensions.md
- guides/type_definitions/input_objects.md
- guides/type_definitions/interfaces.md
- guides/type_definitions/lists.md
- guides/type_definitions/non_nulls.md
- guides/type_definitions/objects.md
- guides/type_definitions/scalars.md
- guides/type_definitions/unions.md
> Removed blue notice bar which prompts about New class based API

- lib/graphql/language/visitor.rb
- spec/graphql/language/visitor_spec.rb
Fixes #2148 
This one took a while to reproduce properly 🤔 
Let me know if you have any questions, comments, or concerns!
> Handle non-node arrays

- guides/fields/introduction.md
It's not clear what current docs tell.
> Improve wording for override camelize

- guides/related_projects.md
Hi @rmosolgo really thank you for your awesome work and this gem.
I added the **Tutorials** sections to your guide.
> Add Tutorials sections to related_projects.md

- lib/graphql/analysis/ast/field_usage.rb
Minor thing since the arguments weren't used but still 🎉
> Fix FieldUsage analyzer method args

- lib/graphql/language/visitor.rb
This seems to be a minor typo in the docs.
> Fix typo in docs

- lib/graphql/schema/argument.rb
- lib/graphql/schema/input_object.rb
- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/schema/resolver.rb
- spec/graphql/schema/input_object_spec.rb
Fixes #2280 
The `loads:` implementation should apply to key lookup on input objects, too!
> Input object loads bug

- lib/graphql/types/relay/base_edge.rb
- spec/integration/mongoid/star_trek/schema.rb
- spec/support/star_wars/schema.rb
Not 100% sure if this is the right solution, but the tests seem to pass locally.  Fixes #2221 (tested fork against my app)
> Use `default_graphql_name` for BaseEdge edges

- lib/graphql/upgrader/member.rb
- spec/fixtures/upgrader/mutation.original.rb
- spec/fixtures/upgrader/mutation.transformed.rb
fix #1665
Convert a mutation file from
```ruby
module ActivityMutations
Create = GraphQL::Relay::Mutation.define do
name 'CreateActivity'
input_field :name, types.String
input_field :start_at, DateTimeType
input_field :end_at, DateTimeType
input_field :address_codes, types[types.String]
resolve ->(_obj, inputs, _ctx) {
activity = Shundao::Activity.new(inputs.to_h)
if activity.save
{ activity: activity }
else
{ error: activity }
end
}
end
Update = GraphQL::Relay::Mutation.define do
name 'UpdateActivity'
input_field :id, !types.ID
input_field :name, types.String
input_field :start_at, DateTimeType
input_field :end_at, DateTimeType
input_field :address_codes, types[types.String]
input_field :is_active, types.Boolean
return_field :activity, ActivityType
return_field :error, ErrorType
resolve …
```
> Correct transforming multiple mutations in one file (#1665)

- guides/relay/connections.md
I wanted to explicitly describe where to use the connections arguments
> Doc: use object to perform query with connections arguments

- guides/fields/limits.md
I think the field type should be a list. Am I missing something?
> Make items type a list

- lib/generators/graphql/install_generator.rb
- lib/generators/graphql/templates/base_argument.erb
- lib/generators/graphql/templates/base_field.erb
- lib/generators/graphql/templates/base_input_object.erb
- lib/graphql/schema/member/has_fields.rb
- spec/graphql/schema/object_spec.rb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
It's always handy to have this, better just generate it. 
closes #2215
> Generate BaseArgument during install

- .travis.yml
> Update travis xvfb build

- lib/graphql/analysis/ast/query_depth.rb
The comments should match the instructions at https://graphql-ruby.org/queries/ast_analysis.html
> Fix incomplete docs in comments

- lib/graphql/types/int.rb
- spec/graphql/int_type_spec.rb
- spec/graphql/query_spec.rb
- spec/graphql/static_validation/rules/variable_default_values_are_correctly_typed_spec.rb
- spec/integration/rails/graphql/input_object_type_spec.rb
Closes #2259
Raise an error if an Integer argument receives a Float.
> Fix Int/Float typecast issue.

- guides/schema/class_based_api.md
Related to https://github.com/rmosolgo/graphql-ruby/issues/2034
We might want to add a note about this somewhere else but I think it is super important for people that are converting to the class based API so that they are not surprised with request timeouts like me 😅
> Add heads up about deferred schema initialization

- lib/graphql/schema/field.rb
- spec/graphql/schema/field_spec.rb
Closes https://github.com/rmosolgo/graphql-ruby/issues/2440
WIP for initial review of approach taken. cc: @rmosolgo @swalkinshaw
> Add `extras` setter to GraphQL::Schema::Field

- lib/graphql/static_validation/rules/fields_will_merge.rb
- spec/graphql/static_validation/rules/fields_will_merge_spec.rb
> Fix enum argument conflict

- guides/fields/resolvers.md
Fixes https://github.com/rmosolgo/graphql-ruby/issues/2366
I encountered basically the same issue as above, and also solved it by expressing the type as a string.
To avoid having to hunt through issues or tickets, it would be nice if this was in the guide for resolvers.
> Update guide around nesting resolvers of same type

- lib/graphql/schema/relay_classic_mutation.rb
- spec/graphql/schema/relay_classic_mutation_spec.rb
- spec/support/jazz.rb
Oops, if you add an extra and then try to remove it in the base class, it didn't quite work right.
> Fix stripping extras in relay classic mutation

- lib/graphql/schema/validation.rb
- spec/graphql/schema/validation_spec.rb
Follow up on #2462 , closes #1923
> Also require at least one argument for input objects

- lib/generators/graphql/templates/graphql_controller.erb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
> Comment out protect from forgery code, let the consumer opt in

- lib/graphql/static_validation/definition_dependencies.rb
- spec/graphql/static_validation/rules/fragment_names_are_unique_spec.rb
- spec/graphql/static_validation/rules/fragments_are_finite_spec.rb
> Fix duplicate, self-referencing fragment

- lib/graphql/schema/member/instrumentation.rb
- spec/graphql/schema/mutation_spec.rb
- spec/support/jazz.rb
Looking to address the issue described: [2566](https://github.com/rmosolgo/graphql-ruby/issues/2566)
> Account for list of errors when performing field instrumentation.

- guides/relay/object_identification.md
Update Relay Node Field from legacy-style to new-style
https://github.com/rmosolgo/graphql-ruby/blob/d31d378c56d3c4a652ef42a2b0ae0d2d4736622d/lib/graphql/types/relay/node_field.rb#L9
https://github.com/rmosolgo/graphql-ruby/blob/d31d378c56d3c4a652ef42a2b0ae0d2d4736622d/lib/graphql/types/relay/nodes_field.rb#L9
> Update Relay object indentification doc

- lib/graphql/schema/argument.rb
- lib/graphql/schema/field.rb
Trying to cut down a bit more on the memory footprint of a booted schema.
> Reduce schema allocations

- lib/graphql/schema/list.rb
- spec/graphql/schema/list_spec.rb
`Array(...)` wasn't doing the right coercion. (The old `ListType` didn't use `Array(...)` either, now I know why!) 
Fixes #2652
> Fix single item list

- lib/graphql/define/defined_object_proxy.rb
- lib/graphql/define/instance_definable.rb
- lib/graphql/schema.rb
- lib/graphql/schema/build_from_definition.rb
- lib/graphql/schema/loader.rb
- lib/graphql/schema/subscription.rb
- lib/graphql/subscriptions.rb
- spec/graphql/authorization_spec.rb
- spec/graphql/define/assign_argument_spec.rb
- spec/graphql/execution/multiplex_spec.rb
- spec/graphql/query/context_spec.rb
- spec/graphql/schema/resolver_spec.rb
- spec/graphql/schema/subscription_spec.rb
- spec/graphql/schema/warden_spec.rb
- spec/integration/rails/data.rb
- spec/integration/rails/graphql/relay/array_connection_spec.rb
- spec/integration/rails/graphql/relay/mutation_spec.rb
- spec/integration/rails/graphql/relay/page_info_spec.rb
- spec/integration/rails/graphql/relay/relation_connection_spec.rb
- spec/support/star_wars/schema.rb
I think this is the last of the Ruby 2.7 work. 
Fixes #2650
> Fix Ruby 2.7 warnings

- lib/graphql/schema/list.rb
- spec/graphql/schema/list_spec.rb
Oops, fixing a spot I missed in #2667
> Don't coerce nil into a list of [nil]

- lib/graphql/pagination/relation_connection.rb
- spec/graphql/pagination/active_record_relation_connection_spec.rb
Fixes #2695 
I oversimplified the new implementation 😅  I think it's as good as the old one, now.
> More efficient pageInfo in new connections

- lib/graphql/query/variables.rb
- lib/graphql/schema/input_object.rb
- spec/graphql/schema/input_object_spec.rb
fixes #2686 
can't figure out where to add a regression test to cover this, but this is working and resolves the issue
> Fix passing null for a nested input

- lib/graphql/analysis/ast/query_complexity.rb
- spec/graphql/analysis/ast/query_complexity_spec.rb
Demonstrates https://github.com/rmosolgo/graphql-ruby/issues/2589
> Make complexity analyzer correctly handle re-entering selections

- spec/graphql/tracing/platform_tracing_spec.rb
> Test tracing during Query#result

- .rubocop.yml
- cop/no_focus_cop.rb
- lib/graphql/field.rb
- lib/graphql/language/nodes.rb
- lib/graphql/language/parser.rb
- lib/graphql/language/parser.y
- lib/graphql/schema.rb
- lib/graphql/schema/enum.rb
- lib/graphql/schema/member/base_dsl_methods.rb
- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/schema/member/has_ast_node.rb
- lib/graphql/schema/member/has_fields.rb
- lib/graphql/schema/resolver/has_payload_type.rb
- lib/graphql/static_validation/rules/variable_default_values_are_correctly_typed.rb
- spec/graphql/language/document_from_schema_definition_spec.rb
This reduces the warnings generated by Rspec to include only warnings from generated code. I tried `rubocop -a` on those files, but they still emitted warnings after that. 
```
~/code/graphql-ruby $ ruby -Ilib warnings.rb
/Users/rmosolgo/code/graphql-ruby/lib/graphql/language/lexer.rb:252: warning: mismatched indentations at 'end' with 'case' at 236
/Users/rmosolgo/code/graphql-ruby/lib/graphql/language/lexer.rb:261: warning: mismatched indentations at 'else' with 'if' at 258
/Users/rmosolgo/code/graphql-ruby/lib/graphql/language/lexer.rb:268: warning: mismatched indentations at 'else' with 'if' at 255
/Users/rmosolgo/code/graphql-ruby/lib/graphql/language/lexer.rb:276: warning: mismatched indentations at 'end' with 'begin' at 235 …
```
> Tidy up some code to quiet down Rspec's warnings

- guides/javascript_client/apollo_subscriptions.md
- guides/javascript_client/overview.md
- guides/javascript_client/relay_subscriptions.md
- javascript_client/package.json
- javascript_client/src/__tests__/indexTest.ts
- javascript_client/src/index.ts
- javascript_client/src/sync/sendPayload.ts
fixes #2673 
fixes #2756 
fixes #2753
> Add root-level imports to js client, improve body handling

- .github/workflows/api_docs.yaml
- .github/workflows/website.yaml
- guides/_tasks/site.rb
I'm hoping to automate the pipeline for publishing graphql-ruby.org. 
Fixes #2132
> Publish with actions

- lib/graphql/schema.rb
- spec/graphql/schema_spec.rb
Add the path to improve the error message
> Improve error when schema finds a duplicate type

- CHANGELOG.md
> add entry about custom scalar changes

- javascript_client/package.json
> [JavaScript Client] Fix module not found TypeScript Error

- guides/relay/object_identification.md
This fixes the documentation to avoid https://github.com/rmosolgo/graphql-ruby/issues/2724
> Correct the interface required to implement Node.

- lib/graphql/execution/lookahead.rb
- spec/graphql/execution/lookahead_spec.rb
A chance to dry up a lot of code here. 
Fixes #2809 by removing the problematic call altogether.
> Use Query#arguments_for in Lookahead#arguments

- lib/graphql/schema/member/has_arguments.rb
- spec/graphql/schema/argument_spec.rb
- spec/support/jazz.rb
Previously, it would try to load an object using `nil`.
Fixes #2760
> Fix loads with require: false and nil ID

- lib/graphql/pagination/connection.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/field/connection_extension.rb
- spec/support/connection_assertions.rb
`max_page_size: nil` is supposed to allow unbounded results. 
Fixes #2840
> Fix nil override for max_page_size

- lib/graphql/rake_task.rb
> Make rake task properly detect Rails environment task

- lib/graphql/schema/list.rb
- lib/graphql/schema/non_null.rb
- spec/graphql/schema/non_null_spec.rb
> Fix field type description on List and NonNull

- lib/graphql/schema/loader.rb
- spec/graphql/schema/loader_spec.rb
Migrating from `.define` to class-based schema -- it _should_ all work the same!
> Build classes when generating schema from introspection

- lib/graphql/schema.rb
> Fix memory leak in legacy runtime possible types lookup

- spec/graphql/schema/object_spec.rb
Caught a spelling mistake in my most recent PR :(
> Fixed superclases -> superclasses

- lib/graphql/schema/resolver.rb
RubyMine keeps complaining about wrong types when I pass an Array
> change Resolver#type function's YARD

- lib/graphql/schema/field.rb
- spec/graphql/schema/field_spec.rb
As discussed here https://github.com/Shopify/graphql-metrics/pull/23#discussion_r410414264
> Expose GraphQL::Schema::Field.introspection?

- guides/schema/root_types.md
Update documentation of RootTypes https://github.com/rmosolgo/graphql-ruby/issues/2907
> Update example for root_types documentation

- lib/graphql/subscriptions/action_cable_subscriptions.rb
it took me a week to figure out that the `async` adapter will not work correctly from background jobs or the rails console :/
> update docs to suggest _not_ using the async activejob adapter

- lib/graphql/types/iso_8601_date.rb
- lib/graphql/types/iso_8601_date_time.rb
- spec/graphql/types/iso_8601_date_spec.rb
- spec/graphql/types/iso_8601_date_time_spec.rb
> Fix array input to Date/DateTime types

- lib/graphql/schema/field.rb
- spec/graphql/authorization_spec.rb
In our project, we rely on https://github.com/Shopify/graphql-batch gem, the result of each call is a `Promise`. 
There are such cases that in order to check if the current user is authorized to fetch a certain field, there is a need to perform DB query via https://github.com/Shopify/graphql-batch to check if the current user is an owner of the object. Example:
```
class BaseField 
def authorized?(obj, context)
RecordLoader.for(Assignment).load(object.assigment_id).then do |assigment|
assigment.owner_id == context[:current_user].id
end
end
end
```
Because field level authorization does not support lazy values(aka promises) we always get `true`(as promise are truthy object) for such cases. This PR changes the behavior of `GraphQL::Schema::Field#resolve` method to allow …
> feat: support lazy field level authorization

- lib/graphql/subscriptions/subscription_root.rb
- spec/graphql/schema/subscription_spec.rb
> Fix subscription with extras

- lib/graphql/types/iso_8601_date_time.rb
- spec/graphql/types/iso_8601_date_time_spec.rb
Fixes #2988 
cc @bdewater just fyi, since you were working around here recently
> Fix DateTime type to handle dates without times

- lib/graphql/tracing.rb
- lib/graphql/tracing/platform_tracing.rb
- lib/graphql/tracing/statsd_tracing.rb
- spec/graphql/tracing/statsd_tracing_spec.rb
Ported from GraphQL::Pro::Monitoring
> Add Statsd tracing

- lib/graphql/schema.rb
- lib/graphql/schema/union.rb
- spec/graphql/schema/union_spec.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/3018
> Make sure that interfaces aren't added as possible_types of unions

- lib/graphql/schema/input_object.rb
- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/schema/warden.rb
- spec/graphql/query/executor_spec.rb
Same as https://github.com/rmosolgo/graphql-ruby/pull/2985 but on master/1.11
> Only check used input arguments visibility [for 1.11.x]

- lib/graphql/directive.rb
- lib/graphql/field.rb
- lib/graphql/input_object_type.rb
- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/static_validation/literal_validator.rb
- lib/graphql/static_validation/rules/arguments_are_defined.rb
- lib/graphql/static_validation/rules/required_arguments_are_present.rb
- lib/graphql/static_validation/rules/required_input_object_attributes_are_present.rb
Same as https://github.com/rmosolgo/graphql-ruby/pull/3000 but for master/1.11.
~Based on https://github.com/rmosolgo/graphql-ruby/pull/3030 so I'll update once that's merged.~
> Fix visible calls in static validation [for 1.11.x]

- lib/graphql/language/nodes.rb
- spec/graphql/language/visitor_spec.rb
> Support renaming variable identfiers

- lib/graphql/subscriptions/action_cable_subscriptions.rb
- spec/graphql/subscriptions/action_cable_subscriptions_spec.rb
> Fix trigger from unsubscribed ActionCable channel

- guides/schema/sdl.md
- lib/graphql/schema/build_from_definition/resolve_map.rb
A lot of folks have found this feature by source diving, and it's really nifty, no reason not to give it a decent guide. 
Fixes #2813
> Document building a schema from SDL string

- lib/graphql/schema/field/connection_extension.rb
- spec/graphql/schema/member/scoped_spec.rb
The connection extension choked on promises, now it waits for them. 
Fixes #2747
> Fix connection wrappers on lazy lists

- guides/type_definitions/directives.md
Add docs for custom directive name, includes commits from #2870
> Directive graphql name

- guides/type_definitions/directives.md
This wasn't documented and I had to dig into the source code to find it.
I tried to follow the style of the rest of the documentation, but feel free to edit however best reflects what you would want.
> Document `graphql_name` configuration for custom directives.

- lib/generators/graphql/templates/union.erb
- spec/integration/rails/generators/graphql/union_generator_spec.rb
> Update union type generator

- lib/graphql/schema/argument.rb
- spec/graphql/schema/argument_spec.rb
This is a downside of losing `Schema.define { ... }` -- it had a "validate" step that checked for things like this. Best thing would be to copy the specs for that, update the fixtures to a class-based schema, then make them all pass (with new assertions, etc) to make sure every case is covered. 
But for now:
fixes #3119
> Assert valid input types when adding arguments to schema

- lib/graphql/schema.rb
- spec/graphql/analysis/ast/max_query_depth_spec.rb
Oops, I fixed this before (#3107), but I didn't put the error in somewhere that would come back in the response. My bad for not doing a full end-to-end test!
Fixes #3127
> Make sure stack error comes back in response

- guides/type_definitions/field_extensions.md
Pretty sure this is what was meant here..
> fix variable name in code snippet example

- lib/graphql/backtrace/tracer.rb
- spec/graphql/backtrace_spec.rb
Oops, this code was never updated for the new runtime! 
Fixes #3026
> Fix Backtrace on Interpreter

- lib/graphql/execution/interpreter.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/query/context.rb
- spec/graphql/execution/interpreter_spec.rb
Make a bunch of runtime info generally available. 
Fixes #3085
> Set intepreter current_... values in Query context

- spec/dummy/app/channels/graphql_channel.rb
- spec/dummy/app/views/pages/show.html
- spec/dummy/test/system/action_cable_subscription_test.rb
Sadly, I don't actually have a plan to fix the test. 
But I've been hacking on it, trying to understand _why_ it fails on CI, and I'm gonna figure this out one way or another!
> Fix ActionCable integration test

- guides/development.md
I just stepped upon these little annoyance while working on another PR.
> Minor development.md improvements

- guides/testing/integration_tests.md
Small change, but figured I would put up PR while reading testing documentation.
> Grammar fix

- lib/graphql/types/relay/base_connection.rb
- lib/graphql/types/relay/base_edge.rb
- spec/graphql/types/relay/base_connection_spec.rb
> Fix generated fields for types ending in Connection

- guides/related_projects.md
Added three more gems and one article on avoiding N+1s
> Add more related projects

- lib/graphql/dataloader.rb
- lib/graphql/dataloader/null_dataloader.rb
- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/dataloader_spec.rb
Oops, a very simple case was not covered by the current tests and implementation 🤦 
Fixes #3293
> Support multiple selections with Dataloader

- benchmark/batch_loading.rb
- benchmark/run.rb
- lib/graphql/dataloader.rb
- lib/graphql/dataloader/null_dataloader.rb
- lib/graphql/dataloader/source.rb
- lib/graphql/execution/interpreter.rb
- lib/graphql/execution/interpreter/resolve.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/execution/multiplex.rb
- spec/graphql/dataloader_spec.rb
- spec/graphql/execution_error_spec.rb
I thought this was going to be a little fix, but it turned out to be a total rebuild of the dataloader. 
Its path tracking was naive and failed in the case described in #3308. Rebuilding it as a general queue worker was fine, but then it didn't play nice with lazy_resolve. 
TODO: 
- All that matters is performance in the default case
Fixes #3308
--------------
Profiling info: this increases the memory consumption by 6% in the Dataloader case, but reduces memory in the GraphQL-Batch and No Batch case. Curiously, I'm getting reliably _faster_ times for all three cases. Maybe those ivar writes made the difference -- they would have been slower, but less memory intensive 🤷 . I'll take it!
<details>
<summary>BEFORE profile</summary>
<p>
``` …
```
> Rebuild dataloader

- gemfiles/rails_master.gemfile
- lib/generators/graphql/install_generator.rb
- lib/generators/graphql/relay.rb
- lib/generators/graphql/relay_generator.rb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
Looks like the handling of `generate(...)` changed on Rails master, so update our tests to ... not break.
> Fix rails tests

- .github/workflows/ci.yaml
- gemfiles/rails_6.1.gemfile
- lib/graphql/backtrace/tracer.rb
- lib/graphql/object_type.rb
- spec/graphql/backtrace_spec.rb
- spec/integration/rails/graphql/query/variables_spec.rb
> Fix static validation when backtrace is enabled

- lib/graphql/schema/field.rb
> Add connections extension before other extensions to make sure it grabs the original arguments

- guides/dataloader/adopting.md
I couldn't just ignore such an e-gregious error 😄
> remove errant letter "e"

- .gitignore
- guides/javascript_client/apollo_subscriptions.md
- guides/javascript_client/relay_subscriptions.md
- javascript_client/CHANGELOG.md
- javascript_client/jest.config.js
- javascript_client/package.json
- javascript_client/src/__tests__/cliTest.ts
- javascript_client/src/__tests__/indexTest.ts
- javascript_client/src/index.ts
- javascript_client/src/subscriptions/createRelaySubscriptionHandler.ts
- javascript_client/tsconfig.json
> Remove dist/ from ts build, update docs

- lib/graphql/dataloader.rb
- spec/graphql/dataloader_spec.rb
Fixes #3331. Let me know if I should change something. 🙂
> Dataloader passes along throws

- lib/graphql/schema.rb
> Skip possible_type filtering for non-interface types

- lib/graphql/schema/resolver.rb
- spec/graphql/schema/resolver_spec.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/3257
> Support max_page_size config in resolver classes, fixes #3257

- lib/graphql/backtrace/tracer.rb
- spec/graphql/backtrace_spec.rb
> Fix backtrace multiplex tracing without execute

- lib/generators/graphql/install_generator.rb
- lib/generators/graphql/loader_generator.rb
- lib/generators/graphql/mutation_generator.rb
- lib/generators/graphql/relay_generator.rb
- lib/generators/graphql/type_generator.rb
- spec/integration/mongoid/spec_helper.rb
- spec/integration/rails/generators/graphql/mutation_generator_spec.rb
- spec/integration/rails/generators/graphql/relay_generator_spec.rb
- spec/spec_helper.rb
I don't have a clue why Generators suddenly started to fail loading. I'll see if I can get the build passing again.
> Try to fix generators loading and warnings

- guides/development.md
> Remove docs for m

- lib/graphql/types/relay/connection_behaviors.rb
- spec/graphql/types/relay/base_connection_spec.rb
> added option to make edges non-nullable

- javascript_client/package.json
- lib/graphql/query.rb
- spec/graphql/tracing/platform_tracing_spec.rb
> Tracing: consistent sequence of events for Query#result

- javascript_client/package.json
As discussed [here](https://github.com/rmosolgo/graphql-ruby/pull/3391) 😃
> Move graphql and @apollo/client to peerDeps

- guides/fields/introduction.md
Hi there, I was trying to understand how to customize and extend field resolution behavior. It took me a few hops to understand where / how to properly do so! I was wondering if I could attach a link to registering fields with `field_class` behavior.
> [README] Update Field Resolution readme

- lib/graphql/static_validation/rules/fields_will_merge.rb
- spec/graphql/static_validation/rules/fields_will_merge_spec.rb
> Fix fields-will-merge for fields that return unions and have spreads on mutually exclusive interfaces

- lib/generators/graphql/install_generator.rb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/3273
> Don't re-add graphiql-rails when installed twice

- javascript_client/src/subscriptions/ActionCableLink.ts
- javascript_client/src/subscriptions/__tests__/ActionCableLinkTest.ts
I've applied my suggestion from https://github.com/rmosolgo/graphql-ruby/issues/3468 and filled in specs related to the change.
Few additional questions:
1. There's nothing in guides about connectionParams - should I fill them in on this MR or is it OK if it stays undocumented?
2. I see there's `prettier` in package.json but it looks unconfigured(`prettierrc.json` is missing)
Resolves #3468
> ActionCableLink accepts connectionParams as func where operation is first argument

- lib/graphql/rake_task.rb
- spec/graphql/rake_task_spec.rb
> Add a newline to rake task output

- lib/graphql/subscriptions/serialize.rb
- spec/graphql/subscriptions/serialize_spec.rb
- spec/support/global_id.rb
> Use locate_many for arrays of global_ids

- lib/graphql/schema/resolver.rb
- spec/graphql/schema/resolver_spec.rb
> Don't override inherited load_ argument methods

- guides/getting_started.md
Added instructions in [Getting Started](https://graphql-ruby.org/getting_started.html) section, making it consistent with [README of the repository](https://github.com/rmosolgo/graphql-ruby/blob/master/readme.md).
> [Doc] Update getting_started.md

- lib/graphql/schema/resolver.rb
- spec/graphql/schema/resolver_spec.rb
> Inherit extensions in resolvers

- lib/graphql/dataloader.rb
The complexity here was trying to tell me something...
> Dataloader sources: Use a queue instead of a stack

- guides/queries/interpreter.md
- lib/graphql/types/relay/has_node_field.rb
- lib/graphql/types/relay/has_nodes_field.rb
- lib/graphql/types/relay/node_field.rb
- lib/graphql/types/relay/nodes_field.rb
- spec/graphql/types/relay/has_node_field_spec.rb
> Add the right owner for node(s) field, update docs

- lib/graphql/schema/resolver.rb
- spec/graphql/schema/resolver_spec.rb
> Don't pass frozen array of extensions

- lib/graphql/execution/interpreter/runtime.rb
Fixes #3512 
cc @eapache  since we talked about improving this a bit. I feel like I'm still missing something -- why did it need the `.graphql_parent.graphql_dead` check? Gotta figure that out 👀
> Recursively set graphql_dead so that checking is faster

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/schema/directive_spec.rb
> Handle errors from directive args

- lib/graphql/backtrace/tracer.rb
- spec/graphql/backtrace_spec.rb
> Fix backtrace with multiplex

- lib/graphql/types/big_int.rb
- spec/graphql/types/big_int_spec.rb
> Ensures numbers are parsed with base 10 in BigInt - Issue #3585

- guides/javascript_client/relay_subscriptions.md
- javascript_client/package.json
- javascript_client/src/subscriptions/__tests__/createRelaySubscriptionHandlerTest.ts
- javascript_client/src/subscriptions/createRelaySubscriptionHandler.ts
> Relay 11 fix, remove request as a dependency

- guides/authorization/authorization.md
Due to the error, this must be looks like this change
> Fix for syntax error in doc

- lib/graphql/integer_encoding_error.rb
- lib/graphql/string_encoding_error.rb
- lib/graphql/types/int.rb
- lib/graphql/types/string.rb
- spec/graphql/introspection/schema_type_spec.rb
- spec/graphql/types/int_spec.rb
- spec/graphql/types/string_spec.rb
- spec/support/dummy/schema.rb
Fixes #3693 
Add some location info to these errors to make them easier to fix out-of-the-box.
> Add field name and path to encoding errors

- guides/errors/overview.md
- lib/graphql/query/validation_pipeline.rb
- spec/graphql/query_spec.rb
Cherry-picking #3690 to master
> Validate max errors fix

- guides/mutations/mutation_classes.md
- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/schema/resolver.rb
- lib/graphql/unauthorized_error.rb
- spec/graphql/schema/resolver_spec.rb
> Add Resolver#unauthorized_object

- lib/graphql/dataloader/source.rb
- spec/graphql/dataloader/source_spec.rb
- spec/graphql/dataloader_spec.rb
> Tell Sources to wait when one dataloader.yield didn't finish the load

- guides/schema/definition.md
- guides/schema/object_identification.md
- lib/generators/graphql/relay.rb
- lib/generators/graphql/templates/schema.erb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
I think this is the best way to address a couple issues:
- Recommend a better UUID implementation in the docs and generators 
- Recommend a better type_error implementation in the generator 
Fixes https://github.com/rmosolgo/graphql-ruby/pull/2106
Fixes https://github.com/rmosolgo/graphql-ruby/pull/3681
> Improve uuid and type_error implementations in the Rails generator and docs

- lib/generators/graphql/object_generator.rb
I found this behaviour to be surprising. This PR includes an additional line to clarify the behaviour for existing active record models.
I'm happy to contribute more documentation improvements if it's needed. Thanks for the great Gem. 😄
> Update generator description to document AR behaviour

- lib/graphql/schema/validator/format_validator.rb
- spec/graphql/schema/validator/format_validator_spec.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/3723
> Fix allow_blank: true with format: /.../

- lib/generators/graphql/templates/schema.erb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
Oops, I implemented the wrong thing in #3710 🤦
> Fix generated type_error hook signature

- lib/graphql/schema/field.rb
- spec/graphql/schema/relay_classic_mutation_spec.rb
> Call authorized on args from input_object_class, input_type too

- lib/graphql/schema/validator.rb
- lib/graphql/schema/validator/length_validator.rb
- spec/graphql/schema/validator/length_validator_spec.rb
> Fix validates: { length: ... }, allow_blank: false

- lib/generators/graphql/core.rb
- lib/generators/graphql/install_generator.rb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
> Fix rails destroy graphql:install

- Rakefile
- benchmark/run.rb
- lib/graphql/language/nodes.rb
- lib/graphql/static_validation/rules/fields_will_merge.rb
- lib/graphql/static_validation/rules/required_arguments_are_present.rb
> Validation perf from 1.12

- guides/index.html
[Chime](https://www.chime.com/) is a big user and fan of the graphql-ruby gem. We appreciate the support from you, Robert (from answering all my questions and past issues concerning class-based migrations 💚 ), and the graphQL community and would like to add our name onto this list 🙂
> 📝   Add Chime to index page

- guides/queries/response_extensions.md
- lib/graphql/execution/multiplex.rb
- lib/graphql/query/context.rb
- spec/graphql/query/context_spec.rb
> Add context.response_extensions[...] = ... for adding extensions to the response

- lib/graphql/types/relay/node_field.rb
- lib/graphql/types/relay/nodes_field.rb
- spec/graphql/execution/interpreter_spec.rb
- spec/graphql/tracing/new_relic_tracing_spec.rb
- spec/graphql/tracing/scout_tracing_spec.rb
- spec/integration/mongoid/star_trek/schema.rb
- spec/integration/rails/graphql/schema_spec.rb
- spec/support/star_wars/schema.rb
Point users to the new alternative. Fixes #3788
> Deprecate NodeField and NodesField

- lib/graphql/schema/field.rb
- spec/graphql/schema/field_spec.rb
> Better field parameter error

- spec/integration/rails/generators/graphql/mutation_generator_spec.rb
- spec/integration/rails/generators/graphql/relay_generator_spec.rb
- spec/spec_helper.rb
It's been broken for a long time ... I thought a Rails 7 release would fix it, but it didn't, so I'm trying again 😩
> Try to fix Rails 7 build

- lib/graphql/analysis/ast/field_usage.rb
- spec/graphql/analysis/ast/field_usage_spec.rb
> FieldUsage: don't visit arguments when prepare raises an error

- lib/graphql/analysis/ast/field_usage.rb
- spec/graphql/analysis/ast/field_usage_spec.rb
Same as #3794 , but for 1.12.x
Fixes #3789
> 1.12 field usage fix

- guides/authorization/can_can_integration.md
Fixes https://github.com/rmosolgo/graphql-ruby/issues/3809
> Remove `end` token in code block example, fixing typo

- lib/graphql/schema.rb
- lib/graphql/static_validation/all_rules.rb
- lib/graphql/static_validation/rules/query_root_exists.rb
- lib/graphql/static_validation/rules/query_root_exists_error.rb
- spec/graphql/query_spec.rb
- spec/graphql/schema_spec.rb
I tried to find how these could be raised, but I was only able to track down one situation (I'm sure there are more). So I improved the error message, too. 
Fixes #3771
> Fix field error when query(...) isn't configured

- guides/fields/arguments.md
- lib/graphql/schema/argument.rb
- lib/graphql/schema/validator/required_validator.rb
- spec/graphql/schema/argument_spec.rb
- spec/graphql/schema/validator/required_validator_spec.rb
> Add a validator for requiring an argument to be passed, even if it's null

- lib/graphql/pagination/relation_connection.rb
- spec/support/connection_assertions.rb
> Fix application of limit on unbounded relations

- lib/graphql/tracing/active_support_notifications_tracing.rb
> Fix bug requiring if ActiveSupport only partially required

- lib/graphql/types/relay/node_field.rb
- lib/graphql/types/relay/nodes_field.rb
- spec/graphql/types/relay/has_node_field_spec.rb
> Fix crash on NodeField

- lib/graphql/pagination/relation_connection.rb
- spec/graphql/pagination/active_record_relation_connection_spec.rb
- spec/support/connection_assertions.rb
Oops, there were some bugs in this implementation and it wasn't tested 😖 
Fixes #3843
> Fix RelationConnections when relation already has offset

- spec/artifacts/coverage.txt
- spec/artifacts/memory.txt
Hmmm... why did this change...
> Update artifacts (automatic)

- lib/graphql/introspection.rb
- lib/graphql/introspection/directive_location_enum.rb
- lib/graphql/introspection/directive_type.rb
- lib/graphql/introspection/schema_type.rb
- lib/graphql/introspection/type_type.rb
- lib/graphql/schema.rb
- lib/graphql/schema/directive.rb
- lib/graphql/schema/loader.rb
- lib/graphql/schema/scalar.rb
- spec/graphql/introspection/directive_type_spec.rb
- spec/graphql/introspection/schema_type_spec.rb
- spec/graphql/introspection/type_type_spec.rb
- spec/graphql/schema/loader_spec.rb
- spec/graphql/schema/printer_spec.rb
- spec/support/dummy/schema.rb
Fixes #3757 
Riffing on https://github.com/graphql/graphql-js/blob/47bd8c8897c72d3efc17ecb1599a95cee6bac5e8/src/type/introspection.ts and https://github.com/graphql/graphql-js/blob/29b811fca5f726c9a3aa1d979c70ecbced8b4ec8/src/utilities/getIntrospectionQuery.ts
> Support new introspection fields

- lib/graphql/types/relay/connection_behaviors.rb
- spec/graphql/types/relay/base_connection_spec.rb
> Handle base connections that implement interfaces

- guides/fields/introduction.md
- lib/graphql/schema/field.rb
- spec/graphql/schema/field_spec.rb
closes https://github.com/rmosolgo/graphql-ruby/issues/3855
> Support nested keys as alternative to hash_key for fields

- lib/graphql.rb
- lib/graphql/dataloader/source.rb
- lib/graphql/schema.rb
- lib/graphql/schema/field.rb
- spec/graphql/schema/field_spec.rb
Fixes #3867
There _are_ more invariants in the code where this error could be raised, but I want to wait to roll this out until 2.0-dev is on master, otherwise, I'm going to create a lot of conflicts 😅
> Add GraphQL::InvariantError, use it for Field#owner_type

- guides/fields/arguments.md
- lib/graphql/schema/argument.rb
- spec/graphql/schema/argument_spec.rb
> Add replace_null_with_default: true

- guides/queries/complexity_and_depth.md
`GraphQL::Schema::Field#calculate_complexity`
> docs: fix typo for Complexity & Depth guide

- lib/graphql/schema/directive.rb
- spec/graphql/schema/build_from_definition_spec.rb
> [1.12] SDL: Fix having two directives on the same type

- lib/graphql/schema/directive.rb
- spec/graphql/schema/build_from_definition_spec.rb
backporting https://github.com/rmosolgo/graphql-ruby/pull/3884
> [1.13] SDL: Fix having two directives on the same type

- lib/graphql/schema/field.rb
- spec/graphql/analysis/ast/query_complexity_spec.rb
> Handle validation errors on connection complexity

- guides/_layouts/guide.html
- guides/_plugins/api_doc.rb
- guides/css/main.scss
- guides/operation_store/redis_backend.md
Trying to make it easier to navigate from guide to guide. I'm inspired by Rails's huge pop-over:
But I'm not sure how to implement it, and besides, I've already got these breadcrumbs. So now they're drop-downs that navigate when you select something new: 
There's still room to add a huge pop-over like rails has, but this seems like a nice improvement in the same direction for now.
> Make breadcrumbs into dropdowns that navigate

- lib/graphql/schema/field.rb
These are already no-ops, but I forgot to remove them in 2.0.0
> Remove deprecated field options field:, function:, resolve:

- lib/graphql/relay/connection_type.rb
- spec/integration/rails/graphql/relay/connection_type_spec.rb
> [1.13] Warn if GraphQL::Relay::ConnectionType settings are set

- guides/type_definitions/enums.md
Added missing extension to file name on base enum definition
> Update enum.md missing extension on enum base class definition

- lib/graphql/schema/resolver/has_payload_type.rb
- spec/graphql/schema/mutation_spec.rb
Fixes #3963. 
It seems like I commented out this `alias ...` in a previous recent PR. Not sure why, but evidently it wasn't tested properly 😖
> Fix mutation type(...) config

- Rakefile
- benchmark/run.rb
Here's what it looks like:
```
Result         Depth
---------------------
Eager          201
Lazy           79
Very Lazy      49
```
> Add a benchmark for stack trace depth

- Rakefile
- benchmark/run.rb
- lib/graphql/execution/errors.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/query.rb
- lib/graphql/query/null_context.rb
- lib/graphql/schema.rb
- lib/graphql/schema/argument.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/object.rb
- lib/graphql/schema/scalar.rb
TODO: 
- Gather some before benchmarks on memory consumed during runtime (not just limits, but also how much is GC'ed) and stack trace size at certain points 
- See if this improves either measure
- The real work is in runtime.rb -- reducing recursive calls and nesting.
> Try reducing stack trace size during queries

- lib/graphql/schema/member/relay_shortcuts.rb
- spec/graphql/schema/member/relay_shortcuts_spec.rb
> Fix edge/connection class lookup when Node is included in another module

- lib/graphql/schema/addition.rb
- spec/graphql/schema/build_from_definition_spec.rb
> Fix indirect interface implementation from SDL

- guides/pro/encoders.md
Fixes https://github.com/rmosolgo/graphql-ruby/issues/3991
> Update pro encoding documentation to use class based definition

- spec/graphql/subscriptions_spec.rb
> Add a test for complexity errors on subscriptions

- lib/graphql/relay/range_add.rb
- spec/integration/rails/graphql/relay/range_add_spec.rb
> [1.13] Warn when range add context is missing

- lib/graphql/schema/field.rb
- spec/graphql/schema/field_spec.rb
> Allow field null: to override resolver config

- guides/pro/encoders.md
These need to be class methods.
> Fix object id method definition

- lib/graphql/types/iso_8601_date.rb
- spec/graphql/types/iso_8601_date_spec.rb
> Fix unexpected DateEncodingError when passing nil to optional ISO8601Date argument

- lib/graphql/types/relay/base_connection.rb
> Updated implementation example for BaseConnection

- guides/javascript_client/relay_subscriptions.md
Spent a bit of time figuring this out myself from the source code
> Simplify docs ActionCable config

- lib/graphql/execution/interpreter/resolve.rb
- spec/graphql/dataloader_spec.rb
> Fix lazy auth with dataloaded value

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/execution/errors_spec.rb
> Rescue errors raised by calling .each on list values

- spec/graphql/schema/introspection_system_spec.rb
I modified indent because rubocop formatted funny.
> modify indent

- lib/graphql/schema/field.rb
Resolves https://github.com/rmosolgo/graphql-ruby/issues/4101
> `Schema::Field`: add `#relay_nodes_field` attr reader

- lib/graphql/schema/addition.rb
- spec/graphql/schema/addition_spec.rb
> Fix #add_type for duplicate types with cyclical references

- guides/javascript_client/urql_subscriptions.md
- javascript_client/package.json
- javascript_client/src/subscriptions/SubscriptionExchange.ts
- javascript_client/src/subscriptions/__tests__/SubscriptionExchangeTest.ts
> Add Urql support for pusher subscriptions

- guides/type_definitions/input_objects.md
Fixes a link that goes to the wrong page.
> link to the correct documentation

- lib/graphql/schema/field.rb
- spec/graphql/schema/field_spec.rb
Hi! I stumbled upon an issue after upgrading to the latest version. I added tests that reproduce the actual issue. ~~Will try to provide a fix for that later.~~ Added fix.
> Fix boolean fields with hash_key and false value provided

- lib/graphql/schema/argument.rb
- spec/graphql/schema/argument_spec.rb
> Add methods to configure argument default_value and prepare

- guides/javascript_client/sync.md
- javascript_client/src/__tests__/cliTest.ts
- javascript_client/src/__tests__/syncTest.ts
- javascript_client/src/cli.ts
- javascript_client/src/sync/generateClient.ts
- javascript_client/src/sync/index.ts
- javascript_client/src/sync/sendPayload.ts
> Add --header option to js client

- lib/generators/graphql/templates/schema.erb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
Suggest a default max errors of 100 for new schemas 
Fixes #4154
> Generate schemas with a max validation errors of 100

- guides/dataloader/sources.md
- lib/graphql/dataloader/source.rb
- spec/graphql/dataloader_spec.rb
As suggested in https://github.com/rmosolgo/graphql-ruby/issues/4075#issuecomment-1237508780
> Add .merge for pre-filling dataloader caches

- lib/graphql/execution/lookahead.rb
> Lookahead: don't coerce symbol to string if a match can be made with the symbol

- lib/graphql/schema/field.rb
- spec/graphql/schema/field_spec.rb
> Fix: prioritize local config over resolver for connection detection

- lib/graphql/execution/lookahead.rb
- spec/graphql/execution/lookahead_spec.rb
> Add selected_type: to Lookahead#selects?

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/schema/enum_spec.rb
> Add error handling to enum result coercion

- lib/graphql/schema/build_from_definition.rb
- spec/graphql/schema/directive_spec.rb
> Fix parsing repeatable directives in schemas

- lib/graphql/query/context.rb
Oops, this could be done better to avoid an allocation along the way. 
From `rake bench:profile_large_result`: 
```diff
1.000  i/100ms
-                         4.491  (± 0.0%) i/s -     23.000  in   5.122639s
+                         4.481  (± 0.0%) i/s -     23.000  in   5.134446s
... 
allocated objects by location
62000  /Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:784
20002  /Users/rmosolgo/code/graphql-ruby/lib/graphql/execution/interpreter/runtime.rb:414
-      12003  /Users/rmosolgo/code/graphql-ruby/lib/graphql/query/context.rb:155
11008 …
```
> Refactor scoped context lookup to avoid allocations

- lib/graphql/schema/field.rb
- spec/graphql/analysis/ast/query_complexity_spec.rb
> Backport complexity fix

- lib/graphql/query/context.rb
- spec/graphql/query/context_spec.rb
> Fix: digging into current arguments from context

- guides/related_projects.md
I have sadly decided to sunset the Hubburu project (I am the founder)
> Removes hubburu project

- Gemfile
- benchmark/run.rb
- lib/graphql/schema/member/has_fields.rb
- lib/graphql/schema/member/has_interfaces.rb
- lib/graphql/schema/warden.rb
> Improve interface tms 2.0

- Rakefile
- benchmark/run.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/introspection/directive_type.rb
- lib/graphql/introspection/field_type.rb
- lib/graphql/introspection/schema_type.rb
- lib/graphql/introspection/type_type.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/schema/warden.rb
Carrying some PRs into 1.13.x into 2.0.x:
> Forward port perf

- lib/graphql/static_validation/literal_validator.rb
- spec/graphql/schema/build_from_definition_spec.rb
Fixes #4307 
Oops, this probably should have been updated back when `null` was added to GraphQL, but it never was. 
When queries are running, this is handled by: https://github.com/rmosolgo/graphql-ruby/blob/4712a3d4c71ac7a36181a1a5da0d972b634137fe/lib/graphql/execution/interpreter/arguments_cache.rb#L96-L97
But during validation, we may not have a query running.
> Don't pass NullValue to literal validation

- lib/graphql/static_validation/literal_validator.rb
- spec/graphql/schema/build_from_definition_spec.rb
Derp, another try at fixing #4307
> Fix nils in JSON Type hash values

- .github/workflows/ci.yaml
> Adds Ruby 3.2 to CI

- lib/graphql/schema.rb
- spec/graphql/schema/argument_spec.rb
Fixes issue described in https://github.com/rmosolgo/graphql-ruby/issues/4334
> Fix handle_or_reraise with arguments validation

- javascript_client/src/__tests__/__snapshots__/syncTest.ts.snap
- javascript_client/src/__tests__/cliTest.ts
- javascript_client/src/__tests__/syncTest.ts
- javascript_client/src/cli.ts
- javascript_client/src/sync/__tests__/sendPayloadTest.ts
- javascript_client/src/sync/index.ts
- javascript_client/src/sync/sendPayload.ts
> JS: fix typo for changeset-version, more logging

- lib/graphql/schema/member/has_deprecation_reason.rb
> Add special deprecation_reason handling for faster introspection

- CHANGELOG.md
> fix wrong year

- lib/graphql/types/relay/base_connection.rb
Small typo fix in documentation
> Fixed typo in documentation

- lib/graphql/schema.rb
- spec/graphql/schema_spec.rb
- spec/graphql/tracing/legacy_trace_spec.rb
> Fix tracers on parent schema classes

- lib/graphql/tracing/appsignal_trace.rb
- spec/graphql/tracing/appsignal_trace_spec.rb
> Fix AppsignalTrace

- graphql-c_parser/ext/graphql_c_parser_ext/graphql_c_parser_ext.c
- graphql-c_parser/ext/graphql_c_parser_ext/lexer.c
- graphql-c_parser/ext/graphql_c_parser_ext/lexer.rl
- graphql-c_parser/ext/graphql_c_parser_ext/parser.c
- graphql-c_parser/ext/graphql_c_parser_ext/parser.h
- graphql-c_parser/ext/graphql_c_parser_ext/parser.y
- graphql-c_parser/lib/graphql/c_parser.rb
- lib/graphql.rb
- lib/graphql/language/nodes.rb
- lib/graphql/language/parser.rb
- lib/graphql/language/parser.y
- spec/graphql/language/definition_slice_spec.rb
- spec/graphql/language/equality_spec.rb
- spec/graphql/language/printer_spec.rb
- spec/graphql/query_spec.rb
- spec/graphql/schema/build_from_definition_spec.rb
> Clean up pluggable parser API

- lib/graphql/tracing/appsignal_trace.rb
- spec/graphql/tracing/appsignal_trace_spec.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/4387#issuecomment-1495580233
> Fix resolve_type instrumentation for resolve_type

- lib/graphql/language/document_from_schema_definition.rb
- spec/graphql/schema/input_object_spec.rb
> print @oneOf definition in SDL when it's used

- lib/graphql/filter.rb
- lib/graphql/language/document_from_schema_definition.rb
- lib/graphql/query/null_context.rb
- lib/graphql/schema.rb
It will be removed in #4325 v2.1.0
> Add deprecation warning to GraphQL::Filter

- lib/graphql/schema/member/has_fields.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/4420
> Avoid needless type checks at runtime in `get_field`

- lib/graphql/static_validation/rules/fields_have_appropriate_selections.rb
- spec/graphql/static_validation/rules/fields_have_appropriate_selections_spec.rb
> Fix crash when selections and inline fragments are made on scalars

- lib/graphql.rb
- lib/graphql/execution/interpreter.rb
- lib/graphql/execution/interpreter/arguments.rb
- lib/graphql/execution/interpreter/arguments_cache.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/language/nodes.rb
- lib/graphql/pagination/connection.rb
- lib/graphql/query.rb
- lib/graphql/query/context.rb
- lib/graphql/schema/argument.rb
- lib/graphql/schema/build_from_definition.rb
- lib/graphql/schema/enum_value.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/field_extension.rb
- lib/graphql/schema/find_inherited_value.rb
- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/schema/member/has_directives.rb
- lib/graphql/schema/member/has_validators.rb
- lib/graphql/schema/resolver.rb
- lib/graphql/schema/validator.rb
- lib/graphql/static_validation/rules/fields_will_merge.rb
> Consolidate empty value constants

- lib/graphql/backtrace.rb
- lib/graphql/backtrace/trace.rb
- lib/graphql/query.rb
- lib/graphql/schema.rb
- lib/graphql/tracing.rb
- lib/graphql/tracing/legacy_trace.rb
- lib/graphql/tracing/trace.rb
- spec/graphql/backtrace_spec.rb
- spec/graphql/schema_spec.rb
- spec/graphql/tracing/legacy_trace_spec.rb
> Make GraphQL::Backtrace work with module traces

- lib/graphql/execution/interpreter.rb
- lib/graphql/execution/interpreter/runtime.rb
Oops, #4450 went into a dead-end branch, not master.
> Memoize Query#current_trace

- lib/graphql/query/context.rb
- spec/graphql/query/context_spec.rb
> Fix Context#dig with only one key

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/dataloader_spec.rb
> Fix sequential mutations with Dataloader

- guides/type_definitions/interfaces.md
Use a more relevant type for orphan_types example
> Update orphan_type example in interfaces.md

- lib/graphql/backtrace.rb
- lib/graphql/schema.rb
- spec/graphql/backtrace_spec.rb
> Fix backtrace: true with other trace modules

- lib/graphql/schema/timeout.rb
> Document that Timeout can handle Floats

- lib/generators/graphql/mutation_delete_generator.rb
- lib/generators/graphql/mutation_update_generator.rb
Updated the lib/generators/graphql/mutation_delete_generator.rb AND lib/generators/graphql/mutation_update_generator.rb document/comment to reflect the actual operation
> doc: Updated mutation delete/update documentation

- lib/graphql/language/visitor.rb
Two small things that were missed in the big removal
> Remove more deprecated Visitor code

- gemfiles/rails_7.0.gemfile
- lib/generators/graphql/relay.rb
- spec/integration/rails/generators/graphql/install_generator_spec.rb
- spec/integration/rails/generators/graphql/relay_generator_spec.rb
> Update generator to use generated node type

- lib/graphql/schema/validator.rb
- spec/graphql/schema/validator/length_validator_spec.rb
- spec/graphql/schema/validator/required_validator_spec.rb
> Support %{value} in validator messages

- guides/queries/executing_queries.md
- lib/graphql/query/context.rb
- lib/graphql/query/context/scoped_context.rb
- spec/graphql/query/context/scoped_context_spec.rb
> Add context.scoped for setting scoped context inside promises

- graphql-c_parser/ext/graphql_c_parser_ext/parser.c
- graphql-c_parser/ext/graphql_c_parser_ext/parser.y
> GraphQL::CParser: remove dependency on Nodes::NONE

- guides/queries/executing_queries.md
fixes #4609 . Is it right like that?
> Update executing_queries.md to show nested scoped_context

- lib/graphql/language/sanitized_printer.rb
- spec/graphql/language/sanitized_printer_spec.rb
> Fix enum variable default values in sanitized_query_string

- guides/queries/complexity_and_depth.md
- lib/graphql/analysis/ast/query_depth.rb
- lib/graphql/schema.rb
- spec/graphql/analysis/ast/max_query_depth_spec.rb
Addressing issues as mentioned in #2437 and #3061
> Add max_depth ... count_introspection_fields: false

- guides/mutations/mutation_classes.md
- lib/graphql/load_application_object_failed_error.rb
- lib/graphql/schema/member/has_arguments.rb
- spec/graphql/schema/resolver_spec.rb
> Load application object failed improvements

- lib/graphql/query/null_context.rb
- lib/graphql/schema.rb
- lib/graphql/schema/directive.rb
- lib/graphql/schema/enum.rb
- lib/graphql/schema/has_single_input_argument.rb
- lib/graphql/schema/member/has_arguments.rb
- lib/graphql/schema/member/has_fields.rb
- lib/graphql/schema/member/has_interfaces.rb
- lib/graphql/schema/member/validates_input.rb
- lib/graphql/schema/resolver.rb
- lib/graphql/schema/union.rb
- lib/graphql/subscriptions.rb
- lib/graphql/subscriptions/event.rb
- spec/graphql/query/null_context_spec.rb
- spec/graphql/schema/enum_spec.rb
- spec/graphql/schema/input_object_spec.rb
- spec/graphql/schema/scalar_spec.rb
- spec/integration/rails/graphql/input_object_spec.rb
- spec/integration/rails/graphql/schema_spec.rb
> Migrate NullContext to use Singleton

- lib/graphql/pagination/mongoid_relation_connection.rb
> Don't load all records in Mongoid hasNextPage

- lib/graphql/subscriptions.rb
- spec/graphql/subscriptions_spec.rb
> Fix ParseError in Subscriptions#trigger

- lib/graphql/schema/field/scope_extension.rb
- spec/graphql/schema/member/scoped_spec.rb
> Fix ScopeExtension outside of execution

- lib/graphql/execution/interpreter.rb
- lib/graphql/schema.rb
- lib/graphql/subscriptions.rb
- spec/graphql/schema_spec.rb
> Support a custom Schema.query_class

- lib/graphql/query/null_context.rb
I'm not sure if this will "just work" or not -- but it's worth a try.
> Make NullContext inherit from Context; fixes #4709

- lib/graphql/dataloader.rb
Some fixes I noticed working on #4727
> Dataloader improvements

- lib/graphql/dataloader/async_dataloader.rb
- spec/graphql/dataloader_spec.rb
> Re-raise errors from Async::Tasks in AsyncDataloader

- lib/graphql/analysis/ast/query_complexity.rb
Gives some love to the object-heavy complexity costing algorithm to make it a bit lighter and cleaner. It’s a heavy hitter on our p99 analysis times. This is a 1:1 refactor that provides some reduction to object allocations; taking the [first three specs](https://github.com/rmosolgo/graphql-ruby/blob/master/spec/graphql/analysis/ast/query_complexity_spec.rb#L22-L149) as examples:
- **Spec 1:** objects before 82, after 62, -24.4%
- **Spec 2:** objects before 101, after 77, -23.7%
- **Spec 3:** objects before 134, after 113, -15.6%
These reductions scale linearly with request size, so larger requests (with more object scopes) should see larger gains, thus primarily benefiting p99. Major changes:
1. `ScopedTypeComplexity` inherits from `Hash` and eliminates `scoped_children`. Before, every …
> Optimize QueryComplexity algorithm

- lib/graphql/dataloader.rb
Backporting #4743 since these issues were introduced in 2.1.8
> [2.1.x] Fix dataloader for hanging fibers

- lib/graphql/dataloader.rb
- lib/graphql/dataloader/source.rb
- spec/graphql/dataloader_spec.rb
> [2.1] remove Fiber#transfer support

- lib/graphql/dataloader/async_dataloader.rb
- spec/graphql/dataloader_spec.rb
This addresses those dangling `suspended` Fibers, eg https://github.com/rmosolgo/graphql-ruby/issues/4739
> AsyncDataloader: Use .yield instead of async { ... }.wait to give tasks a chance to run

- guides/getting_started.md
- lib/generators/graphql/install_generator.rb
- lib/generators/graphql/templates/base_resolver.erb
FIx About this issue [uninitialized constant Types::Resolvers::BaseResolver (NameError) #4750](https://github.com/rmosolgo/graphql-ruby/issues/4750)
> fix getting start base resolver file name error

- guides/related_projects.md
Just noticed this helpful directory... Adding the stitching gem, and clarifying what the Apollo federation gem specifically does.
> Add GraphQL Stitching to related projects guide

- .github/workflows/ci.yaml
- gemfiles/rails_7.0.gemfile
- gemfiles/rails_7.1.gemfile
- guides/dataloader/async_dataloader.md
- guides/dataloader/overview.md
- guides/dataloader/parallelism.md
- guides/dataloader/sources.md
- spec/graphql/pagination/active_record_relation_connection_spec.rb
- spec/integration/rails/graphql/dataloader_spec.rb
- spec/support/active_record_setup.rb
Fixes #4766 
Also: 
- Add a Ruby 3.3 test 
- Add a Rails 7.1 test (I think the Rails 7.0 test may have actually been running on 7.1 -- but now it runs 7.0) 
- Remove Rails 5.2 test
> Document and test ActiveRecord::Promise usage

- guides/schema/definition.md
- lib/graphql/introspection/entry_points.rb
- lib/graphql/introspection/schema_type.rb
- lib/graphql/language/document_from_schema_definition.rb
- lib/graphql/schema.rb
- spec/graphql/schema/introspection_system_spec.rb
- spec/graphql/schema/printer_spec.rb
- spec/graphql/schema_spec.rb
- spec/support/jazz.rb
> Add Schema.extra_types for documentation-only types

- lib/graphql/query/variables.rb
- spec/graphql/query_spec.rb
> Fix for when variables are defined as object types

- guides/_layouts/default.html
- guides/css/main.scss
- guides/dataloader/overview.md
- guides/index.html
I can't promise it's pretty, but I think it _will_ be easier on the eyes, if you're used to dark mode. I'd love contributions or improvements if anyone wants to offer any!
> Website: add a dark theme 

- guides/dataloader/testing.md
Update example per https://github.com/rmosolgo/graphql-ruby/pull/4795/files#r1462039017
> Fix Dataloader testing examples

- CHANGELOG.md
- lib/graphql/analysis/ast/field_usage.rb
- spec/graphql/analysis/ast/field_usage_spec.rb
- spec/support/dummy/schema.rb
Hi, @rmosolgo! What do you think about this change? Thank you!
> Allow GraphQL::Analysis::AST::FieldUsage to detect use of deprecated enum value as argument

- graphql.gemspec
- lib/graphql.rb
- spec/graphql/static_validation/validator_spec.rb
> Remove unused racc dependency; deprecate parse_with_racc

- lib/graphql/testing/helpers.rb
> Reorganize modules to work with RDoc

- lib/graphql/execution/interpreter.rb
- spec/graphql/execution/interpreter_spec.rb
- spec/graphql/execution/multiplex_spec.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/4822
Turns out my first instinct was right, and this was pretty easy once I was looking in the right spot 🤦 
Thanks for the pointer @rmosolgo
> Reorder errors before data in the response

- javascript_client/package.json
> Fix JavaScript CI

- lib/graphql/schema/resolver.rb
- spec/graphql/schema/resolver_spec.rb
> Properly handle Resolver arguments that return false for authorized?

- lib/graphql/schema/field.rb
- spec/graphql/analysis/ast/query_complexity_spec.rb
Oops, this previously used a hard-coded `1` for connection fields, ignoring any other configuration. Fixes #4838
> Apply configured complexity to connection fields

- guides/authorization/authorization.md
- guides/mutations/mutation_authorization.md
Mention both  `#authorized?` methods of Mutations. The instance method lacks explanation, but at least its mentioned now.
> Update authorization.md to include mutation#authorized?

- lib/graphql/schema/member/has_arguments.rb
- spec/graphql/schema/dynamic_members_spec.rb
> Pass context when fetching argument for loads

- lib/graphql/analysis/ast.rb
- lib/graphql/schema/field.rb
- spec/graphql/analysis/ast/max_query_complexity_spec.rb
> Handle unauthorized argument errors properly during complexity analysis

- guides/testing/schema_structure.md
The validate method returns array.
> fix: update testing/schema_structure.md

- lib/graphql/language/lexer.rb
- lib/graphql/language/parser.rb
- spec/graphql/language/parser_spec.rb
> Handle stray hyphens in Ruby parser

- lib/graphql/backtrace/inspect_result.rb
- lib/graphql/language/document_from_schema_definition.rb
- lib/graphql/query.rb
- lib/graphql/query/context.rb
- spec/graphql/query/context_spec.rb
- spec/graphql/schema/warden_spec.rb
There's some code structure here left from old `FieldResolutionContext` classes, it's all unused.
> Remove old Context structure

- lib/graphql/schema/mutation.rb
- lib/graphql/schema/resolver.rb
- spec/graphql/schema/mutation_spec.rb
> Mutation: clear dataloader cache right before resolving

- spec/graphql/execution/interpreter_spec.rb
- spec/graphql/schema/input_object_spec.rb
- spec/graphql/schema/loader_spec.rb
- spec/graphql/schema/member/has_arguments_spec.rb
- spec/graphql/schema/resolver_spec.rb
- spec/graphql/schema/validator/allow_blank_validator_spec.rb
- spec/graphql/schema/validator/allow_null_validator_spec.rb
- spec/graphql/schema/validator/length_validator_spec.rb
- spec/graphql/schema_spec.rb
- spec/graphql/subscriptions_spec.rb
- spec/graphql/types/big_int_spec.rb
- spec/integration/rails/graphql/query/variables_spec.rb
- spec/integration/rails/graphql/types/iso_8601_duration_spec.rb
Addressing warnings from minitest
> Update specs to use assert_nil

- guides/queries/complexity_and_depth.md
- lib/graphql/analysis/ast/query_complexity.rb
- lib/graphql/schema.rb
- spec/graphql/analysis/ast/max_query_complexity_spec.rb
Support `max_complexity ..., count_introspection_fields: false` 
Fixes #4873
> Complexity count introspection option

- .github/workflows/ci.yaml
- javascript_client/package-lock.json
- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/schema/directive/feature_spec.rb
> Fix use of directives in nested fragments

- .github/workflows/ci.yaml
- javascript_client/package-lock.json
- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/schema/directive/feature_spec.rb
> 2.2.x nested fragments

- .github/workflows/ci.yaml
- javascript_client/src/subscriptions/createAblyHandler.ts
- spec/integration/rails/graphql/dataloader/async_dataloader_spec.rb
Oops, I merged #4944 without activating this test. Also adding a new fiber-isolated test.
> Rails async dataloader test

- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/execution/interpreter/runtime/graphql_result.rb
I'm poking around here, trying to refactor, and finding ways that things can be simplified...
> Consolidate more runtime state

- Rakefile
- lib/graphql/language/nodes.rb
- lib/graphql/schema/input_object.rb
- lib/graphql/schema/member/has_arguments.rb
- spec/graphql/schema/resolver_spec.rb
- spec/graphql/tracing/appoptics_trace_spec.rb
- spec/graphql/tracing/appoptics_tracing_spec.rb
- spec/integration/rails/data.rb
- spec/integration/rails/generators/base_generator_test.rb
It's really time to pay down this tech debt -- and stay on top of issues like #4976 and #4977 
TODO:
> Re-enable warnings in test suite (also remove default load_* implementations in arguments)

- lib/graphql/schema.rb
- lib/graphql/schema/addition.rb
- lib/graphql/schema/has_single_input_argument.rb
- lib/graphql/schema/introspection_system.rb
- spec/graphql/schema_spec.rb
- spec/support/dummy/schema.rb
> Improve structure of possible_types and references_to

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/schema/directive/feature_spec.rb
Backporting #4959 as requested in https://github.com/rmosolgo/graphql-ruby/issues/4953#issuecomment-2163816554
> [2.0.x] Fix use of directives in nested fragments

- lib/graphql/dataloader/async_dataloader.rb
- spec/graphql/dataloader/async_dataloader_spec.rb
> Copy Fiber-local variables over to sources when using AsyncDataloader

- lib/graphql/schema/directive.rb
- lib/graphql/schema/field.rb
- lib/graphql/schema/resolver.rb
- spec/graphql/schema/resolver_spec.rb
> Support directives on Resolver classes

- lib/graphql/schema/field.rb
- spec/graphql/schema/resolver_spec.rb
> Merge field directives and resolver directives

- guides/javascript_client/graphiql_subscriptions.md
Fix reference to the wrong adapter + minor and mostly cosmetic cleanups to the GraphiQL ActionCable documentation
> Clean up GraphiQL Subscription examples

- guides/subscriptions/broadcast.md
- lib/graphql/subscriptions/broadcast_analyzer.rb
- lib/graphql/types/relay/connection_behaviors.rb
- lib/graphql/types/relay/edge_behaviors.rb
- lib/graphql/types/relay/page_info_behaviors.rb
- spec/graphql/subscriptions/broadcast_analyzer_spec.rb
Also, add debug logging to BroadcastAnalyzer
Fixes #5006
> Make it possible to broadcast nodes field

- lib/graphql/dataloader/source.rb
- spec/graphql/execution_error_spec.rb
This PR attempts to include the fix for #5020 merged to master into the 2.1.x branch
Related PR: https://github.com/rmosolgo/graphql-ruby/pull/5021
> Backport fix to Issue #5020 to 2.1.x

- lib/graphql/dataloader/source.rb
- spec/graphql/execution_error_spec.rb
This PR attempts to include the fix for #5020 merged to master into the 2.2.x branch
Related PR: https://github.com/rmosolgo/graphql-ruby/pull/5021
> Backport fix to Issue #5020 to 2.2.x

- lib/graphql/schema/member/has_unresolved_type_error.rb
- spec/graphql/schema/member/has_unresolved_type_error_spec.rb
> Use GraphQL::UnresolvedTypeError for anonymous unions and interfaces

- lib/graphql/execution/interpreter/arguments_cache.rb
- lib/graphql/execution/interpreter/runtime.rb
- lib/graphql/schema.rb
- lib/graphql/schema/introspection_system.rb
- lib/graphql/schema/warden.rb
> Clean up compare-by-identity usage

- lib/graphql/language/nodes.rb
- spec/graphql/language/nodes_spec.rb
> Fix Node#line and Node#col when it's not provided and no parser is present

- .github/workflows/ci.yaml
- graphql.gemspec
- lib/graphql.rb
> Add fiber-storage dependency

- guides/authorization/authorization.md
- lib/graphql.rb
- lib/graphql/schema/enum.rb
- lib/graphql/unauthorized_enum_value_error.rb
- spec/graphql/authorization_spec.rb
- spec/graphql/cop/root_types_in_block_spec.rb
> Call .authorized? on incoming and outgoing enum values

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/schema/mutation_spec.rb
Using `@dataloader.run` here wasn't sufficient because if a fiber yielded, then Dataloader could transfer to a different fiber. The code assumed that no other fibers would have been enqueued in this case, which held true for single mutations. But with multiplex, each running query may have appended a job (to a Dataloader instance shared by all queries in the multiplex). 
Using `run_isolated` makes sure that only the given job runs. 
Fixes #5046
> Fix dataloader fiber switching in Mutations

- lib/graphql/schema.rb
- spec/graphql/tracing/trace_modes_spec.rb
> Fix default traces added to parent classes after default traces added to child class

- lib/graphql/language/document_from_schema_definition.rb
- spec/graphql/schema/printer_spec.rb
Fixes #5076 
Because of how possible types are (aren't?) filtered, you have to also pass them to `extra_types` for them to show up.
> fix printing union possible types when the union is an extra type

- lib/graphql/language/lexer.rb
- spec/graphql/language/parser_spec.rb
> Handle minus followed by identifier

- lib/graphql/testing/helpers.rb
- spec/graphql/testing/helpers_spec.rb
To make this match execution more closely
> Set context[:current_field] in testing helpers

- lib/graphql/rubocop/graphql/field_type_in_block.rb
- spec/fixtures/cop/.rubocop.yml
- spec/fixtures/cop/field_type_array_corrected.rb
- spec/graphql/cop/default_null_true_spec.rb
- spec/graphql/cop/field_type_in_block_spec.rb
- spec/support/rubocop_test_helpers.rb
> Fix FieldTypeInBlock for list types

- lib/graphql/rubocop/graphql/field_type_in_block.rb
- spec/fixtures/cop/.rubocop.yml
- spec/fixtures/cop/field_type_interface.rb
- spec/fixtures/cop/field_type_interface_corrected.rb
- spec/graphql/cop/field_type_in_block_spec.rb
- spec/support/rubocop_test_helpers.rb
> Fix types-in-block cop for Interface types

- lib/graphql/subscriptions.rb
- spec/graphql/subscriptions_spec.rb
> subscription triggering with nested input object occurred error

- .gitignore
- guides/javascript_client/sync.md
- javascript_client/src/__tests__/cliTest.ts
- javascript_client/src/cli.ts
- javascript_client/src/sync/__tests__/__snapshots__/dumpPayloadTest.ts.snap
- javascript_client/src/sync/__tests__/dumpPayloadTest.ts
- javascript_client/src/sync/dumpPayload.ts
- javascript_client/src/sync/index.ts
> Add sync --dump-payload option

- graphql.gemspec
Apparently this issue was addressed upstream but the author doesn't want to release a new version 😖 
https://github.com/nahi/httpclient/issues/458
> Fix mutex_m error

- lib/graphql/schema/loader.rb
- spec/graphql/schema/enum_spec.rb
- spec/graphql/schema/loader_spec.rb
Fixes https://github.com/rmosolgo/graphql-ruby/issues/5223
> Check the new class instead of its superclass to see if it responds to the value method

- lib/graphql/static_validation/rules/fields_will_merge.rb
- spec/graphql/static_validation/rules/fields_will_merge_spec.rb
> Lookup the right field in FieldsWillMerge

- lib/graphql/schema/input_object.rb
> [2.1] fix bad merge

- lib/graphql/static_validation/rules/fields_will_merge.rb
- spec/graphql/static_validation/rules/fields_will_merge_spec.rb
> [2.3] Lookup the right field in FieldsWillMerge

- lib/graphql/backtrace/table.rb
- spec/graphql/backtrace_spec.rb
When GraphQL::Backtrace is enabled and an exception occurs during execution of a query with inline fragments, the backtrace system itself throws an error:
```
NoMethodError: undefined method 'alias' for an instance of GraphQL::Language::Nodes::InlineFragment
lib/graphql/backtrace/table.rb:83:in 'block in GraphQL::Backtrace::Table#rows'
lib/graphql/backtrace/table.rb:83:in 'Array#each'
lib/graphql/backtrace/table.rb:83:in 'Enumerable#find'
lib/graphql/backtrace/table.rb:83:in 'GraphQL::Backtrace::Table#rows'
lib/graphql/backtrace/table.rb:29:in 'GraphQL::Backtrace::Table#to_backtrace'
lib/graphql/backtrace.rb:38:in 'GraphQL::Backtrace#to_a'
lib/graphql/backtrace/traced_error.rb:31:in 'GraphQL::Backtrace::TracedError#initialize'
lib/graphql/schema.rb:1131:in 'Class#new' …
```
> Fix GraphQL backtrace handling for inline fragments

- lib/graphql/schema/argument.rb
- lib/graphql/schema/input_object.rb
- spec/graphql/schema/input_object_spec.rb
- spec/graphql/schema/validator/validator_helpers.rb
> InputObject: validate even when prepare is overridden

- lib/graphql/execution/interpreter/runtime.rb
- spec/graphql/execution_error_spec.rb
Without `GraphQL::Dataloader` installed, the error is handled by graphql-ruby but the `location` and `path` of the error is not set.
With `GraphQL::Dataloader` installed, the error is not handled by graphql-ruby
As I am not familiar with this codebase, this PR based on the assumption that `continue_value` will handle `GraphQL::ExecutionError` and `GraphQL::UnauthorizedError` value.
> Handle error in resolve_type

- .rubocop.yml
- cop/development/trace_methods_cop.rb
- lib/graphql/execution/interpreter.rb
- lib/graphql/query.rb
- lib/graphql/tracing.rb
- lib/graphql/tracing/active_support_notifications_trace.rb
- lib/graphql/tracing/data_dog_trace.rb
- lib/graphql/tracing/monitor_trace.rb
- lib/graphql/tracing/new_relic_trace.rb
- lib/graphql/tracing/notifications_trace.rb
- lib/graphql/tracing/perfetto_trace.rb
- lib/graphql/tracing/sentry_trace.rb
- lib/graphql/tracing/trace.rb
- spec/graphql/autoload_spec.rb
- spec/graphql/tracing/active_support_notifications_trace_spec.rb
- spec/graphql/tracing/appsignal_trace_spec.rb
- spec/graphql/tracing/data_dog_trace_spec.rb
- spec/graphql/tracing/data_dog_tracing_spec.rb
- spec/graphql/tracing/new_relic_trace_spec.rb
- spec/graphql/tracing/notifications_trace_spec.rb
- spec/graphql/tracing/sentry_trace_spec.rb
- spec/support/datadog.rb
- spec/support/new_relic.rb
- spec/support/sentry.rb
> Update Tracers to handle Fiber starts/stops

- .github/workflows/ci.yaml
- gemfiles/rails_master.gemfile
- lib/graphql/dashboard.rb
- lib/graphql/dashboard/operation_store.rb
- lib/graphql/dashboard/statics/dashboard.css
- lib/graphql/dashboard/statics/dashboard.js
- lib/graphql/dashboard/views/graphql/dashboard/operation_store/clients/_form.html.erb
- lib/graphql/dashboard/views/graphql/dashboard/operation_store/clients/edit.html.erb
- lib/graphql/dashboard/views/graphql/dashboard/operation_store/clients/index.html.erb
- lib/graphql/dashboard/views/graphql/dashboard/operation_store/clients/new.html.erb
- lib/graphql/dashboard/views/graphql/dashboard/operation_store/index_entries/index.html.erb
- lib/graphql/dashboard/views/graphql/dashboard/operation_store/index_entries/show.html.erb
- lib/graphql/dashboard/views/graphql/dashboard/operation_store/not_installed.html.erb
- lib/graphql/dashboard/views/graphql/dashboard/operation_store/operations/index.html.erb
- lib/graphql/dashboard/views/graphql/dashboard/operation_store/operations/show.html.erb
- lib/graphql/dashboard/views/layouts/graphql/dashboard/application.html.erb
- lib/graphql/execution/interpreter.rb
- lib/graphql/execution/multiplex.rb
- lib/graphql/query.rb
- lib/graphql/tracing/perfetto_trace.rb
- spec/dummy/app/graphql/dummy_schema.rb
- spec/dummy/config/environments/development.rb
- spec/dummy/config/environments/test.rb
- spec/dummy/test/controllers/dashboard/operation_store/clients_controller_test.rb
- spec/dummy/test/controllers/dashboard/operation_store/index_entries_controller_test.rb
- spec/dummy/test/controllers/dashboard/operation_store/operations_controller_test.rb
I'm reimplementing some code from GraphQL-Pro here, but on a Rails engine.
> Add OperationStore UI to GraphQL::Dashboard

- lib/graphql/dashboard.rb
- lib/graphql/dashboard/installable.rb
- lib/graphql/dashboard/operation_store.rb
- lib/graphql/dashboard/subscriptions.rb
- lib/graphql/dashboard/views/graphql/dashboard/subscriptions/not_installed.html.erb
- lib/graphql/dashboard/views/graphql/dashboard/subscriptions/subscriptions/show.html.erb
- lib/graphql/dashboard/views/graphql/dashboard/subscriptions/topics/index.html.erb
- lib/graphql/dashboard/views/graphql/dashboard/subscriptions/topics/show.html.erb
- lib/graphql/dashboard/views/layouts/graphql/dashboard/application.html.erb
- spec/dummy/app/graphql/dummy_schema.rb
- spec/dummy/app/graphql/mock_pusher.rb
- spec/dummy/config/environments/test.rb
- spec/dummy/test/controllers/dashboard/subscriptions/topics_controller_test.rb
Moving these views from GraphQL-Pro to here to use the new dashboard.
> GraphQL::Dashboard - add subscription views

- lib/graphql/schema/visibility.rb
- spec/graphql_spec.rb
> Fix when Rails doesn't have .env

- lib/graphql/query/partial.rb
- spec/graphql/query/partial_spec.rb
Fixes `GraphQL::Current.operation_name` with Query::Partial
> Add Partial#selected_operation_name

- lib/graphql/schema/validator/required_validator.rb
> Fix typo in RequiredValidator method name

- javascript_client/src/subscriptions/AblyLink.ts
- javascript_client/src/subscriptions/__tests__/AblyLinkTest.ts
- address missing feature https://github.com/rmosolgo/graphql-ruby/issues/5371
- props to @erickreutz
> Support .unsubscribe in AblyLink

- lib/graphql/schema/visibility.rb
- lib/graphql/schema/visibility/migration.rb
- lib/graphql/schema/visibility/profile.rb
- spec/graphql/schema/visibility_spec.rb
> Fix inheriting visibility with preload: true

- guides/type_definitions/input_objects.md
`@oneOf` was adopted to the September 2025 GraphQL Spec.
> Update input_objects.md for new Specification

- lib/graphql/testing/helpers.rb
- spec/graphql/testing/helpers_spec.rb
> Support visibility_profile: ... in testing helpers
